### ISSUE TITLE
InputStream MPEG DASH: Could not open / parse mpdURL - Amazon 0.2.7

### ISSUE THREAD

**Issue by chuber1986** [Sandmann79/xbmc#10]
Hi!

My problem is that AmazonVOD does not start playing any videos.
It seams that for some reason the ImputStream plugin can't open the links.

I use Kodi 17 beta3 on a Raspberry3, the the widevine library should be up-to-date and I already tried updating to Amazon 0.2.7.

Is it a known issue or have I done somthing wrong?
I couldn't find an appropriate report here at github.

[kodi_amazon_error.txt](https://github.com/Sandmann79/xbmc/files/409608/kodi_amazon_error.txt)

BG Christian

ps: very nice project! ;)

**Comment by chuber1986** [comment]
Hi again,

since I updated Kodi to the lastest Beta, the problem also occures on my Windows System.

BG Christian

**Comment by Sandmann79** [comment]
This is a common Inputstream error, mostly due a wrong combination of inputstream addon, kodi or decrypter version.

For more information, please refer to this thread: [http://www.kodinerds.net/index.php/Thread/51486-Kodi-17-Inputstream-AddOns-fuer-den-Kodi-17-VideoPlayer-aktuelle-Git-builds-Upda/](url)

**Comment by chuber1986** [comment]
You're right, thanks! :)
