### ISSUE TITLE
Videos not playing on Amazon VOD plugin for Raspberry Pi 3 (KODI LEIA #310)

### ISSUE THREAD

**Issue by HpNoTiQ56** [Sandmann79/xbmc#100]
Hi,
Yesterady, I've updated to Kodi LibreElec Leia Test build#310 on my RPI3 to try Amazon VOD plugin.
I can't play any video using Amazon prime.
Have seen #62 #90 #99 but should be fixed using last build.

**Comment by Varstahl** [comment]
Without logs we can't really help, do you know what the problem is?

**Comment by HpNoTiQ56** [comment]
Updated to version #312 which is working fine with series . No I've got another problem (getting films)
`21:56:00.639 T:1668375424  NOTICE: [Amazon VOD] Version: 0.5.3
21:56:00.640 T:1668375424  NOTICE: [Amazon VOD] Unicode filename support: False
21:56:00.640 T:1668375424  NOTICE: [Amazon VOD] Locale: en-gb / Language: fr
21:56:58.035 T:1527788416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 3248, in <module>
                                                PrimeVideo_Browse(None if 'path' not in args else args['path'])
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 458, in PrimeVideo_Browse
                                                PrimeVideo_LazyLoad(node, nodeName)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 693, in PrimeVideo_LazyLoad
                                                meta['asin'] = re.search(r'"asin":"([^"]*)"', cnt, flags=re.DOTALL).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
21:56:58.225 T:1940853264   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2f%2f-Films
21:56:58.225 T:1940853264   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2f%2f-Films) failed`

**Comment by Varstahl** [comment]
Ah yes, its has been reported today in #101, it's already fixed, you can update the `/storage/.kodi/addons/plugin.video.amazon-test/default.py` with the version [from the repository](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/default.py).
