### ISSUE TITLE
NullPointerException when selecting 'Movies' menu item

### ISSUE THREAD

**Issue by kapcake** [Sandmann79/xbmc#101]
Hi,
I'm new to Kodi and when trying out this addon, I stumbled upon a NullPointer when selecting the Movies menu item. TV Shows works perfectly fine and loads all the series, but when selecting the Movies folder, the addon starts searching for movies, finds some (as shown in the overlay notification) and then throws an exception in the log. I would try and find the source of the error myself, but I never used Python before.

I'm on OSMC 2018.02-1, Kodi 18 Alpha build 17.8-192, 12 March 2018 on my RPi3

The log: https://pastebin.com/GsBXKyxN

**Comment by Varstahl** [comment]
Hmm, that is most troubling and quite unexpected. Apparently there is an unplayable movie, it never happened in all my tests. What country are you in and/or what section are you browsing when it crashes? Immediately after selecting Movies?

**Comment by Varstahl** [comment]
Nevermind, the exact same problem is currently happening on my end too, amazon messed it up on their end, the addon wasn't prepared for that. I'll issue a fix immediately.

**Comment by Varstahl** [comment]
The fix has been issued. While waiting for the update to be distributed through Kodi you can manually overwrite your `/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py` with the content of the [most recent one on the repository](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/default.py).

**Comment by kapcake** [comment]
Well, that was fast😅 thank you, I’ll do so.
