### ISSUE TITLE
Mark videos included in Prime

### ISSUE THREAD

**Issue by basxto** [Sandmann79/xbmc#106]
It would be helpful to mark which videos are included in prime.
I have not tried what happens when you try to play a video, you would need to buy first.

Especially filtering out non-prime videos in your watchlist, like amazon’s web interface does, would be great.

**Comment by basxto** [comment]
I first tried the „Amazon“ addon, but „Amazon VOD“ does it great with coloring it orange.
The option for hiding paid content does not appear to work for my watchlist.
When I activate season bundeling, I get showed serials with no seasons, because then it gets filtered.
Maybe mark serials orange, when all seasons are paid, and yellow, when some seasons are paid?

**Comment by Sandmann79** [comment]
The paid content filter is not active for Watchlist and Library, so that you be able to see the complete list. 
This filter hides or color all content, that's by default not included for free in Prime Video membership.
Purchased content are available at Library section in Add-on.

**Comment by basxto** [comment]
With the option that shows serials instead of seasons in our watchlist, all paid seasons are filtered out.

**Comment by Sandmann79** [comment]
You're right - it's only displayed at top level of watchlist menu.
But you can access it via Library section at home menu.
Maybe I enable this feature for watchlist too, but I need to find a better solution to display not all available content for all users.

**Comment by basxto** [comment]
It also exports all seasons, not just the available ones.

**Comment by lroeser** [comment]
i am using the amazon add-on (german version) and i dont see any coloring or filtering options for prime-included movies :-(

**Comment by thk12** [comment]
i'am using the latest 0.7.7 amazon VOD and coloring is enabled. using german version too

**Comment by lroeser** [comment]
i was using the Amazon add-on (german version), but I understand that amazon VOD works with german accounts as well.
Thanks for the info, i will give it a try!
