### ISSUE TITLE
Remove exported movies

### ISSUE THREAD

**Issue by basxto** [Sandmann79/xbmc#107]
Despite deleting folders in `.kodi/userdata/addon_data/plugin.video.amazon-test/Movies`, I don’t see a way to remove exported movies within kodi.
If I remove them from the library they just reappear after the next scan.

**Comment by Sandmann79** [comment]
Enable at Settings / Media / General / Allow file renaming and deletion. You have to switch at least to advanced mode to see this option.
After that you can easily remove unwanted titles at Videos / File section.
