### ISSUE TITLE
Watchlist item not present

### ISSUE THREAD

**Issue by m0uthless** [Sandmann79/xbmc#110]
Hi, in my amazon vod plugin the item watchlist is not present. On primevideo i try to add 3 tvshow on watchlist but in addon watchlist is not present. I tried version 0.5.3 and 0.5.4 bet from github.
Watchlist is the only item can be user for export library?

Thx

**Comment by Sandmann79** [comment]
Like already written in readme.md are watchlist and library functionality currently not available for primevideo members.
