### ISSUE TITLE
Connection between stream and library items

### ISSUE THREAD

**Issue by basxto** [Sandmann79/xbmc#111]
When I watch an exported episode, it…
* isn’t marked as seen.
* doesn't trigger `Netxup Service Notification`.

This looks to me like kodi does not realize, that the stream belongs to the exported library item.

*On Kodi 18 pre release with inputstream.*

**Comment by Sandmann79** [comment]
This is a common issue how Kodi is handling this exported strm files. 
Strm files are threaded as playlist files and there is no support for this functionalities.
