### ISSUE TITLE
Another thank you  :-)

### ISSUE THREAD

**Issue by RobbesU** [Sandmann79/xbmc#119]
Hi Sandmann,
Just a quick one to once again say Thank You for your fabulous work.
After allowing the Widevine library to update this morning (having ignored the request for a week) it stopped playing.  
Updating both LibreELEC and your Prime Addon to latest fixed it immediately.

_Thank you_
Robbes
https://robbesshed.blogspot.co.uk/2017/12/watching-amazon-prime-using-raspberry.html

**Comment by Varstahl** [comment]
Sandmann's been off for a while now, don't get mad if he doesn't answer right away :)
I'll keep this open in the meanwhile.
