### ISSUE TITLE
Video startet nicht

### ISSUE THREAD

**Issue by assgex** [Sandmann79/xbmc#12]
In unregelmäßigen Abständen startet das Video einfach nicht. Wie viele Zeilen Log brauchst du zur Analyse? Hab mal 50 raus gelassen: [http://pastebin.com/BNJTyZKG](http://pastebin.com/BNJTyZKG)

**Comment by Sandmann79** [comment]
In letzter Zeit gibt es häufiger Probleme mit dem Cloudfront Server. Am besten in den Addon-Einstellungen einen anderen Hoster auswählen oder die Einstellung auf Auto belassen.

**Comment by nbittmann** [comment]
Spot on das war genau das Problem auf meinem Media center!

Wenn man tail auf den logs laufen laesst sieht man einen error wie z.b.

`ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403`

Habe nun auf einen anderen host gewechselt von dem Auto setting und alles läuft wieder!

**Comment by FreddyDummy** [comment]
Hallo,
ich nutze seit Juni das addon für den Rhaspi, also mit dem Input Stream.
Seit gut zwei Wochen funktioniert das Abspielen der Videos nicht mehr, ohne dass ich etwas geändert hätte. Die Anmeldung und das Listing der Filme funktioniert aber. Auch eine Neuinstallation mit der neuesten LibreElec-Version hat nichts gebracht.

**Comment by nbittmann** [comment]
Wie gesagt bei mir hat es funktioniert nachdem ich von AUTO auf AKAMEI gestellt hab. Wuerde vorschlagen das einmal zu versuchen alternativ die log files anhaengen

**Comment by FreddyDummy** [comment]
Hallo
Danke, aber Adam hat leider auch nicht funktioniert.




Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: Nils Bittmann <notifications@github.com> 
Datum:24.08.2016  23:40  (GMT+01:00) 
An: Sandmann79/xbmc <xbmc@noreply.github.com> 
Cc: FreddyDummy <freddy_dummy@arcor.de>,Comment <comment@noreply.github.com> 
Betreff: Re: [Sandmann79/xbmc] Video startet nicht (#12) 

Wie gesagt bei mir hat es funktioniert nachdem ich von AUTO auf AKAMEI gestellt hab. Wuerde vorschlagen das einmal zu versuchen alternativ die log files anhaengen

**Comment by FreddyDummy** [comment]
Akamai,  wenn die automatische Korrektur nicht dazwischen kommt. 
Auch die Einstellungen auf Cloudfront funktioniert nicht.




Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: Nils Bittmann <notifications@github.com> 
Datum:24.08.2016  23:40  (GMT+01:00) 
An: Sandmann79/xbmc <xbmc@noreply.github.com> 
Cc: FreddyDummy <freddy_dummy@arcor.de>,Comment <comment@noreply.github.com> 
Betreff: Re: [Sandmann79/xbmc] Video startet nicht (#12) 

Wie gesagt bei mir hat es funktioniert nachdem ich von AUTO auf AKAMEI gestellt hab. Wuerde vorschlagen das einmal zu versuchen alternativ die log files anhaengen

**Comment by Sandmann79** [comment]
Möglicherweise stimmt auch die Inputstream Version mit der des Decrypters nicht überein. Am besten die aktuellen Versionen aus diesem Thread verwenden: [http://www.kodinerds.net/index.php/Thread/51486-Kodi-17-Inputstream-AddOns-fuer-den-Kodi-17-VideoPlayer-aktuelle-Git-builds-Upda/](http://www.kodinerds.net/index.php/Thread/51486-Kodi-17-Inputstream-AddOns-fuer-den-Kodi-17-VideoPlayer-aktuelle-Git-builds-Upda/).

**Comment by FreddyDummy** [comment]
Danke,
das scheint geholfen zu haben.
Es funktioniert wieder !
Regards
Freddy

**Comment by Sandmann79** [comment]
@assgex ist das Problem bei dir noch vorhanden?

**Comment by assgex** [comment]
Kann ich nicht sagen, bin wegen mehrerer Probleme wieder zurück zum
FireTV..

Am 14.09.2016 07:07 schrieb "Sandmann79" <notifications@github.com>:

**Comment by Sandmann79** [comment]
Okay dann mach ich erst einmal zu hier.
Kannst ja das Issue später erneut öffnen oder eine neues zu aufmachen.

**Comment by FreddyDummy** [comment]
Hallo,

nein, das Problem ist momentan nicht mehr vorhanden.
Nachdem ich die genannten Patches eingespielt habe, funktionierte Amaon wieder.

Best Regards
Freddy  


----- Original Nachricht ----
Von:     Sandmann79 <notifications@github.com>
An:      Sandmann79/xbmc <xbmc@noreply.github.com>
Datum:   14.09.2016 07:07
Betreff: Re: [Sandmann79/xbmc] Video startet nicht (#12)
