### ISSUE TITLE
Spanish from Spain does not appear in the audio list in amazon vod add on

### ISSUE THREAD

**Issue by peterman65** [Sandmann79/xbmc#124]
Hi all, 

first, thanks for your great work.

I have installed the add on amazon vod and I cannot select the Spanish from Spain language when I play a video from amazon, it provides six languages: German,French,Portuguese,Italian, Spanish and English and the Spanish language corresponds to the Latin version.  When I play it in the firefox browser or in a little tv box based on android I have  8 or 9 languages including Latin Spanish and Spain Spanish. 

Could someone tell me how to do in order to have the Spanish Spain language??

Thanks in advance

Pedro

**Comment by Varstahl** [comment]
Can you send me a link to the video you're trying to watch? It's not supposed to happen, I have to look into that.

**Comment by peterman65** [comment]
Thanks for your fast answer,

it happens with all the films and series in my Amazon Premium subscription.

**Comment by Varstahl** [comment]
You're partly correct, partly wrong. The spanish version is in both the movies and series, but there's no differentiation between the two. That has nothing to do with the addon, is managed by Kodi + InputStream.Adaptive, I can't really help you there. I just tried with the first movie I found, and there are both the spanish and latino america languages, but they're both listed under "spanish".

**Comment by peterman65** [comment]
Varstahl, I do not understand your answer (my English is very bad). Are you  saying that it is a kodi and/or inputStream.Adaptive problem? Then should I revise the configuration of inputStream.Adaptive??? 

Thanks again

Pedro

**Comment by Varstahl** [comment]
When you look at audio language inside a movie, IS.A takes the language name and gives it to Kodi, and Kodi changes them again. You can't do anything I think. Maybe submit a bug report to Kodi or IS.A, I don't know which causes the problem.
