### ISSUE TITLE
Force Refresh Watchlist

### ISSUE THREAD

**Issue by PatelTilak** [Sandmann79/xbmc#125]
Is it possible to refresh Watchlist manually ?

Consider a scenario where I added a movie to watchlist from Mobile app & want to view on Kodi in TV

**Comment by Varstahl** [comment]
It's planned but not fully implemented yet, the only way to manually force a refresh is to remove the catalog, deleting `%AppData%\userdata\addon_data\plugin.video.amazon-test\PVCatalog<MarketPlaceID>.pvcp` or the *nix `~/.kodi/userdata/addon_data/plugin.video.amazon-test/PVCatalog<MarketPlaceID>.pvcp`.

**Comment by PatelTilak** [comment]
You can add option in Addon settings to set cache expiration time. It will add 2 features in one change.

1. Setting custom expiration time ( Default is 11 hours I think. Saw somewhere in code)
2. Setting it to 0 will force refresh content everytime.

**Comment by Varstahl** [comment]
Resetting the content every time will actually break even basic functionalities. It's the first on the todo list, as soon as the GDPR fever is contained.
