### ISSUE TITLE
Not working on ShieldTV - > different Amazon App

### ISSUE THREAD

**Issue by Animizio** [Sandmann79/xbmc#126]
Hey,
Amazon is Not working on kodi17 with the Android Option.
On my Smartphone it work, on my shieldtv is doesn't.
I guess because IT uses a different Amazon Video App.

This should be the apk.. u can install it on any Android Device. Maybe you can solve it better on this way. 
Thank you! I love it and would like to use this on my shield :)

https://drive.google.com/file/d/18eWwZjfW9aPSixQeajXmgrkqHnZsWizj/view?usp=drivesdk

**Comment by Sandmann79** [comment]
This app doesn't provide any activity to start the video directly. 
There's only one activity to launch the app.
In this case it isn't possible to use this app with the android option at Addon.

Alternatively you can install Kodi 18 and use Inputstream as playback method.
