### ISSUE TITLE
Want to include your Amazon addon

### ISSUE THREAD

**Issue by Animizio** [Sandmann79/xbmc#128]
Hey, I would like to include your Amazon Addon into a search Addon. Thats ok for you?
Means.. You search a title and if its found on Amazon, you can click it and it will open your Addon and play IT directly.
But to include it, I need the call for your Addon.
For Amazon Devices and the wrapper Methode its working fine. For other Devices Not yet. Maybe you Got an idea or can help me to get it working? Great Addon bzw :)

**Comment by Varstahl** [comment]
Hmm. I can only speak for the PrimeVideo portion for the amazon-test, as that's the portion I built. I'm assuming that by the way you describe it, the user must have configured the addon before, right? If so — and if I correctly understood that you have some kind of wrapping method intercepting the ListItem additions — you can call the function PV_Search [found here on line 437](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/default.py#L437). A call akin to `plugin://plugin.video.amazon-test/?mode=PrimeVideo_Search`, although it doesn't support external queries at the moment.

I don't think we have a platform agnostic unified query system yet.

**Comment by Animizio** [comment]
Okay thanks for your answer.
But to clear it up a bit more:
We have an Addon, to search for Movies and series in different addons, to play them after.
We already know the title of the files, so the search in your Addon is not needed. We only need the "play" call, to get a direct play. Thats possible? :)

**Comment by Varstahl** [comment]
If you have a unique identifier, as in product id (i.e. [B0766H2WVH](https://www.amazon.de/dp/B0766H2WVH/) or [0N4N45OGQW9DPZ4NQN78H2BZA5](https://www.primevideo.com/detail/0N4N45OGQW9DPZ4NQN78H2BZA5/)) or most importantly the unique amazon identifier (`amzn1.dv.gti.86acfadf-0720-7e5e-c904-74f7f07bed5d`), I could possibly make it happen.

The problem with amazon is that there are several marketplaces with different IDs and video offers, so it's not going to be extremely simple. I (very roughly) translated parts of what you wrote in german, so if you have the exact stream already, it could be way easier to implement.

**Comment by Sandmann79** [comment]
@Varstahl that's almost the same as in english, they're using trackt.tv as information provider.
@Animizio like @Varstahl already wrote, only the video title is not enough. If you don't have any additional infos, we can only add an search function, that starts the first found video. This could work for movies, but for episodes, I don't know... 
Btw, how do you call the video on Amazon Devices?

**Comment by Philps** [comment]
let me go more into detail:

we basically return the Amazon ASIN. Its working quite well for the external Video Wrapper on Amazon FireTv Devices. 

However, it makes more sense, to make an external call to your AmazonVOD AddonON, passing on the Amazon ASIN to play the Item and return whhen existing.

Something Like this:
'plugin://plugin.video.vimeo/?path=/root/explore/hd&action=play_video&videoid='+vid_id

The question would be:
- what routine to call in the AmazonVOD AddOn
- and also, if the routine already got the config settings such as LogIn Details, Device Playback ( InputStream, Android, BrowserFallback etc.) as the calling Addon provides ASIN only.

**Comment by Sandmann79** [comment]
Okay that's the info we need to play it directly.
Use the following call:
`plugin://plugin.video.amazon-test/?mode=PlayVideo&name=%s&asin=%s&adult=%s&trailer=%s`

At the moment three parameters (name, asin, adult) mandatory, but you can leave it empty (except asin)
If you want to play the trailer set param `trailer=1`

But I don't know, if this works for primevideo.com members (every country outside US, UK, Germany and Japan)
Maybe there are some little code adjustments necessary.

**Comment by Varstahl** [comment]
> But I don't know, if this works for primevideo.com

It should, I used existing functions where possible. After the browsing the PV code calls PlayVideo as well, with title and asin, so yeah, no problem there.

**Comment by Sandmann79** [comment]
@Varstahl this supposition is related to the asin, which you're not using on PV. You're using only the titleId or i am wrong?.

**Comment by Philps** [comment]
thx. supporting amazonVOD plugin only, with german merketplace id. seems to work quite nice. will perform some more testing

call implemented: 
xbmc.executebuiltin('RunPlugin("plugin://plugin.video.amazon-test/?mode=PlayVideo&asin=%s")' % ASIN)

**Comment by Philps** [comment]
it seems that Kodi18 and inputstream isnt working well, withi this external call. the Amazon VOD standalone PlugIn works on the same system though

Debug Log:

20:19:48.597 T:522987762928   DEBUG: print AMA PlayVideo amazonUrl
20:19:48.597 T:522987762928   DEBUG: https://www.amazon.de/dp/B01MRCF2Y0
20:19:48.598 T:522987762928   DEBUG: [Amazon VOD] External Call
20:19:48.598 T:522987762928   DEBUG: print AMA methodINputstream start
20:19:48.598 T:522987762928   DEBUG: print IStreamPlayback asin
20:19:48.598 T:522987762928   DEBUG: B01MRCF2Y0
20:19:54.147 T:522987762928  NOTICE: [Amazon VOD] Using Host: Cloudfront
20:19:54.149 T:522987762928  NOTICE: [Amazon VOD] checkURL: https://d1l0nb3g075aoz.cloudfront.net/dm/2$6BJKsZ54Gexh0EdtXZCzEAxiCYo~/c1d5/10bd/cc48/4704-9704-62cedafb73cd/3b30a667-8de7-4e29-b64d-ac978796bfb2_corrected.mpd
20:19:55.135 T:522987762928   DEBUG: print AMA inputstream drm_check
20:19:55.136 T:522987762928  NOTICE: [Amazon VOD] getURL: https://d1l0nb3g075aoz.cloudfront.net/dm/2$6BJKsZ54Gexh0EdtXZCzEAxiCYo/c1d5/10bd/cc48/4704-9704-62cedafb73cd/3b30a667-8de7-4e29-b64d-ac978796bfb2_corrected.mpd
20:19:56.631 T:522987762928   DEBUG: [Amazon VOD] https://d1l0nb3g075aoz.cloudfront.net/dm/2$6BJKsZ54Gexh0EdtXZCzEAxiCYo~/c1d5/10bd/cc48/4704-9704-62cedafb73cd/3b30a667-8de7-4e29-b64d-ac978796bfb2_corrected.mpd
20:19:56.632 T:522987762928  NOTICE: [Amazon VOD] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/GetASINDetails?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=f0e1060e6f96047dc5a04e45ac55e4d5febe1797b972a53efce8618f&format=json&version=2&formatVersion=3&marketplaceId=A1PA6795UKMFR9&IncludeAll=T&AID=1&ASINList=B01MRCF2Y0
20:19:56.787 T:522987762928  NOTICE: [Amazon VOD] Using inputstream.adaptive Version:2.1.13
20:19:56.788 T:522987762928 WARNING: Attempt to use invalid handle -1  <---- PROBLEM ???
20:19:56.789 T:522987762928  NOTICE: [Amazon VOD] Checking AudioTrack

**Comment by Animizio** [comment]
The kodi.log and tries are with the default inputstream settings.

**Comment by Sandmann79** [comment]
Just checked this and it's strange - if you call the add-on from an exported title or widget it works (they using the same call), but from another add-on it doesn't work. For this reason we will use player.play() for external calls - this works.

**Comment by Philps** [comment]
great. is this already implemented into a test buildor any PR. otherwise i would be more than happy if you post/send the required changes, so that we can start testing. much appreciated

**Comment by Philps** [comment]
@Sandmann79: could it be that you need to set the item properties palyable = true

see --> https://forum.kodi.tv/showthread.php?tid=173986

I coulnd find this item property in  def IStreamPlayback()

**Comment by Sandmann79** [comment]
Unfortunately this doesn't work, i also tried the isfolder false property, but i had no success with that.

The changes will be uploaded tonight.

**Comment by Varstahl** [comment]
> Just checked this and it's strange - if you call the add-on from an exported title or widget it works (they using the same call), but from another add-on it doesn't work

Since it happened to me while coding the PV support, I'll go on a limb: in order for the call to work (more or less) as intended, the list item, in this case provided by the other addon, must have the `IsPlayable` flag set – `item.setProperty('IsPlayable', 'true')`. Since it doesn't have that, Kodi treats it as a regular non playable file, and that's why you get the -1 invalid handle when the player gets the item and thinks "actually I don't have to play that".

Before discovering that I had a perfectly valid video list that just wouldn't play, and it took me several hours of wall headbashing to figure that out.

**Comment by Sandmann79** [comment]
@Philps i tried to implement it on yesterday, but the player call doesn't work on exported titles or widgets. In this cases Kodi crashes on my machine, so i went back to the setresolvedurl call.
But @Varstahl solution works perfect - tested it yesterday. Don't forget to set `listitem.setInfo` or you get an error.

**Comment by Philps** [comment]
def IStream()
...
` listitem.setProperty('IsPlayable','true')
    listimetm.setInfo('video',infoLabels=getInfolabels(infoLabels)))
    xbmcplugin.setResolvedUrl(pluginhandle, True, listitem=listitem)`

**Comment by Sandmann79** [comment]
yes

**Comment by Philps** [comment]
@Varstahl : did you come up with a solution?

**Comment by Sandmann79** [comment]
@Philps i don't understand your problem at the moment. 
At this point where you create the video listing on your addon, you should add `listitem.setProperty('IsPlayable','true')`.

Short example:
`pluginhandle = int(sys.argv[1])`
`url = 'plugin://plugin.video.amazon-test/?mode=PlayVideo&asin=B071FQY73H'`
`item = xbmcgui.ListItem('Baywatch', thumbnailImage=thumb.jpg)`
`item.setProperty('IsPlayable','true') `
`item.setInfo(type='Video', infoLabels={'title': 'Baywatch'})`
`xbmcplugin.addDirectoryItem(pluginhandle, url, item, isFolder=False)`
`xbmcplugin.endOfDirectory(pluginhandle, updateListing=False)`

**Comment by Philps** [comment]
thought you guys wanted to implement this into the official VOD Addon. I'll feedback the results. thx

**Comment by Philps** [comment]
i misread the answers and understood the item.setpropery is playable need to be added to the Amazon VOD code when it acutally need to be the list item of the 3rd party plugin calling the amazonVod plugin.
