### ISSUE TITLE
primevideo error

### ISSUE THREAD

**Issue by Badmongo88** [Sandmann79/xbmc#129]
unable to find main primevideo.com or something similar

have added kodi log.

i used two step verification as i was not receiving the one time verification codes and thought that's why i was getting an error. i got a please input two step verification and i did that. still got the error afterwards.

i used only one user it came up successfully logged in and then error (before two step)

I used multi user (before two step) logged in and then trying to open application i got the error

inputstream installed and selected

logged in through multiuser, cookies and not stored crededntials
 
[kodi.old.log](https://github.com/Sandmann79/xbmc/files/2066630/kodi.old.log)

**Comment by Varstahl** [comment]
Sorry for the late reply. I see a lot of errors:
```
CAddonSettings[service.vpn.manager]: failed to find definition for setting label1226. Creating a setting on-the-fly...
ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings InsecureRequestWarning)
ERROR: [Amazon VOD] Unable to find the main primevideo.com navigation section
```
So you basically have VPN problems causing a lot of issues, and SSL verification is disabled for whatever reason while it shouldn't. Then there's the "can't fetch catalog", but at this point I don't know if there's a problem with the addon, PrimeVideo or your environment. I'll provide a list of steps to potentially solve the problem or get more information in the process:
1. shut down or reconfigure properly the service.vpn.manager
2. if you disabled SSL verification in the Amazon VOD addon, re-enable it. If SSL verification is disabled by other addons, find the culprit and fix the problem
3. if everything else fails, go to [https://www.primevideo.com/](https://www.primevideo.com/), download the main page html, and give me a link where I can grab it to inspect it.

So far, every time such a problem arisen in the past, it was 99.95% of the time connection/vpn/configuration problems.

**Comment by Varstahl** [comment]
I'm closing this for lack of feedback.
