### ISSUE TITLE
Amazon Video Plugin 0.2.7 doesn't work

### ISSUE THREAD

**Issue by zioalex** [Sandmann79/xbmc#13]
Hi ,
I was just using the Amazon video plugin and it worked just few weeks ago but now nothing. I was using the version 0.2.5. Now I update to the 0.2.7 but still it doesn't work.
I got the follow error in the log:
`
00:19:28 496.324219 T:1672475552  NOTICE: [Amazon VOD] [('cat', 'Browse'), ('mode', 'listContent'), ('opt', 'listcat'), ('page', '1'), ('url', 'ContentType=Movie&OrderBy=Rating&Preorder=F&MinAmazonRatingCount=30&amp;Preorder=F')]
00:19:28 496.328552 T:1672475552  NOTICE: [Amazon VOD] getURL: https://atv-eu.amazon.com/cdp/catalog/Browse?firmware=XXXXXXXXX
00:19:32 500.388428 T:1447941024  NOTICE: [Amazon VOD] [('mode', 'checkMissing')]
00:19:32 500.388885 T:1447941024  NOTICE: [Amazon VOD] Starting Fanart Update
00:19:32 500.389435 T:1447941024  NOTICE: [Amazon VOD] searching fanart for LOOP FITNESSBAND WORKOUT: ABNEHMEN & FIT WERDEN: 6 EFFEKTIVE WORKOUTS at tmdb.com
00:19:32 500.392883 T:1447941024  NOTICE: [Amazon VOD] getURL: http://api.themoviedb.org/3/search/movie?api_key=XXXXXXXXX
00:19:33 500.654266 T:1447941024  NOTICE: [Amazon VOD] getURL: http://api.themoviedb.org/3/search/movie?api_key=&language=de&query=loop+fitnessband+workout%3A+abnehmen+%26+fit+werden%3A+6+effektive+workouts
00:19:33 500.889404 T:1447941024  NOTICE: [Amazon VOD] getURL: http://api.themoviedb.org/3/search/movie?api_key=&language=de&query=loop+fitnessband+workout&year=2016
00:19:33 501.130768 T:1447941024  NOTICE: [Amazon VOD] getURL: http://api.themoviedb.org/3/search/movie?api_key=&language=de&query=loop+fitnessband+workout
00:19:34 501.423920 T:1447941024  NOTICE: [Amazon VOD] Finished Fanart Update
00:19:38 505.947845 T:1447941024  NOTICE: [Amazon VOD] [('asin', 'XXXXXXXXX'), ('mode', 'PlayVideo'), ('name', '[COLOR FFE95E01]Billy Elliot The Musical: Live [OV][/COLOR]'), ('adult', '0'), ('trailer', '0'), ('selbitrate', '0')]
00:19:38 505.951996 T:1447941024  NOTICE: [Amazon VOD] Login
00:19:38 506.033600 T:1447941024   ERROR: /storage/.kodi/addons/plugin.video.amazon-test/default.py:1453: UserWarning: gzip transfer encoding is experimental!
                                              br.set_handle_gzip(True)
00:19:41 508.890533 T:1447941024  NOTICE: [Amazon VOD] getURL: https://www.amazon.de/gp/deal/ajax/getNotifierResources.html
00:19:41 509.160889 T:1447941024  NOTICE: [Amazon VOD] getURL: https://www.amazon.de/gp/video/streaming/player-token.json?callback=onWebToken_126
00:19:42 509.433868 T:1447941024  NOTICE: [Amazon VOD] getURL: https://atv-eu.amazon.com/cdp/catalog/GetPlaybackResources?asin=XXXXXXXXX
00:19:42 509.789398 T:1447941024   ERROR: [Amazon VOD] Cannot complete request. (prs.norights.notowned)
00:19:42 509.789825 T:1447941024  NOTICE: [Amazon VOD] False
00:19:42 509.847565 T:1962971136  NOTICE: VideoPlayer: Opening:
00:19:42 509.847687 T:1962971136 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
00:19:42 509.848175 T:1489884064  NOTICE: Creating InputStream
00:19:42 509.848969 T:1489884064   ERROR: Unable to load /usr/lib/kodi/system/players/VideoPlayer/libdvdnav-arm.so, reason: /usr/lib/kodi/system/players/VideoPlayer/libdvdnav-arm.so: cannot open shared object file: No such file or directory
00:19:42 509.849030 T:1489884064   ERROR: CVideoPlayer::OpenInputStream - error opening []
00:19:42 509.849060 T:1489884064  NOTICE: CVideoPlayer::OnExit()
00:19:42 509.849518 T:1962971136   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.amazon-test/?asin=XXXXXXXXX
00:19:42 509.857758 T:1962971136  NOTICE: CVideoPlayer::CloseFile()
00:19:42 509.857880 T:1962971136  NOTICE: VideoPlayer: waiting for threads to exit
00:19:42 509.857941 T:1962971136  NOTICE: VideoPlayer: finished waiting
00:19:42 509.858002 T:1962971136  NOTICE: CVideoPlayer::CloseFile()
00:19:42 509.858032 T:1962971136  NOTICE: VideoPlayer: waiting for threads to exit
00:19:42 509.858063 T:1962971136  NOTICE: VideoPlayer: finished waiting

I can see the film list and also try to play it but then nothing happen.

`I see an error searching for libdvdnav-arm.so. Not sure if it is an hard dependency because I think I never had that one.
Thanks
Alex

**Comment by Sandmann79** [comment]
Maybe a hoster problem. In the past the Cloudfront server often causes problems. 
Try to switch the hoster in addon settings -> connection.

**Comment by FreddyDummy** [comment]
Hello Sandmann,

without any changes on my Kodi (I switched off automatic update) and your plug-in I encountered yesterday, that the Amazone Prime Video does not start. It seems to be the same as I had two month ago.
Are there any changes on Amazone site which could cause this problem?

Regards
Freddy

**Comment by Sandmann79** [comment]
@FreddyDummy is the problem still present?

**Comment by Sandmann79** [comment]
Due a lack of feedback, i close this issue.
If the problem persists just reopen it.

**Comment by FreddyDummy** [comment]
Hello,

sorry for not giving feedback.
It is working.

Best Regards
Freddy

**Comment by FreddyDummy** [comment]
Hello,

there is a new problem with the Amazon Video.
It seems that Amazone changed something with DRM encryption.
It has been working until Thursday/Friday this week.

Now there is an error message saying that imput stream is not working.

Could you check this aut!?

Best Regards
Freddy

**Comment by FreddyDummy** [comment]
Hallo
This is noch the error message i get since Friday. 
Regards Freddy




Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: Sandmann79 <notifications@github.com> 
Datum:14.03.2017  6:30  (GMT+01:00) 
An: Sandmann79/xbmc <xbmc@noreply.github.com> 
Cc: FreddyDummy <freddy_dummy@arcor.de>,Mention <mention@noreply.github.com> 
Betreff: Re: [Sandmann79/xbmc] Amazon Video Plugin 0.2.7 doesn't work (#13) 

Due a lack of feedback, i close this issue.
If the problem persists just reopen it.

**Comment by Sandmann79** [comment]
Tested it and found no error. What is the complete error message? Or upload kodi.log.

**Comment by FreddyDummy** [comment]
Hello,

do you still need the log-file or was the picture sufficient.

Regards
Freddy

**Comment by Sandmann79** [comment]
Which picture you mean? There is no picture in your posts.

**Comment by FreddyDummy** [comment]
..oh, I added a screenshot of my Kodi when trying to start an Amozone Video.
I will try to get the log data

**Comment by Sandmann79** [comment]
You don't mean this message here?
English: Due changes at Amazon's  encryption...
German: Wegen Änderung von Amazon's DRM Verschlüsselung...

Because this error is already known and talked at the other issues #19, #21
