### ISSUE TITLE
Trojan Detected

### ISSUE THREAD

**Issue by SlydePhaeder** [Sandmann79/xbmc#132]
Windows Defender detects Trojan:Win32/Occamy.C
in files: tools\userinput.exe

Affected items:
xbmc\packages\plugin.video.amazon-test\plugin.video.amazon-test-0.5.4.zip
xbmc\packages\plugin.video.amazon\plugin.video.amazon-1.9.5.zip

**Comment by Varstahl** [comment]
False positive, as discussed in #61 and simplified in this [FAQ right here](https://github.com/Varstahl/xbmc/wiki#a-virus).

**Comment by SlydePhaeder** [comment]
Sixty-two Antivirus engines at VirusTotal.com confirm that the zip files are safe, but the false-positive detection by Windows Defender means that real-time protection must be switched off in a Windows 10 PC or the download from GitHub in a browser will be blocked. 

Thanks for the speedy reply.
