### ISSUE TITLE
Initial configuration of Kodi and Amazon VOD

### ISSUE THREAD

**Issue by Jacky2493** [Sandmann79/xbmc#135]
Hello i am from India.I am using Kodi 18 and i am new in this thing please help me i want to play Amazon prime videos in my android tv box.I have installed amazon vod as said but dont know what to do further.Please help me if u can.

**Comment by Jacky2493** [comment]
Do i need any another app for running prime video?

**Comment by Varstahl** [comment]
No, just Kodi 18 & Amazon VOD.

**Comment by Jacky2493** [comment]
Thank you so much i have generic android tv i hope this will work.I am in India no issues? https://m.gearbest.com/tv-box/pp_1801338.html?wid=1433363

**Comment by Varstahl** [comment]
I don't know about the hardware, if it's not powerful enough you might be stuck to 720p or less.

> I am in India no issues? 

As far as I know, PrimeVideo is working fine in India with AmazonVOD.

**Comment by Jacky2493** [comment]
Hello there is something going on amazonvod plugin demo is going on i cancelled directly gone to movies but there is http error

**Comment by Jacky2493** [comment]
Thank you for your help.Still i have problem i cant see any kids content nor tv shows and all movies are not synced.

**Comment by Varstahl** [comment]
It might not be powerful enough. There are options in the InputStream.Adaptive plugin settings (also accessible from the AmazonVOD settings), try to reduce the maximum resolution and see if it makes things better (480p for example). As long as the videos start and the content works, that's a Kodi/IS.A/hardware problem, I can't help you with that.

**Comment by Jacky2493** [comment]
Content works best in 1080p no problem with that.No buffering and resolution will you please help me with that where can i change that?

**Comment by Varstahl** [comment]
All TV series by default run in 1080p. If the machine is too weak to decode the Widevine DRM for higher resolutions (as happens with the Raspberry) you won't be able to playback at those res. For every other manual selection of resolution, go to the InputStream.Addon and fiddle with that.

**Comment by Jacky2493** [comment]
thank you.

**Comment by Jacky2493** [comment]
can i download the movie in amazon vod?

**Comment by Varstahl** [comment]
No, streaming only.
