### ISSUE TITLE
Most Amazon Prime Videos: Green output

### ISSUE THREAD

**Issue by yogi81** [Sandmann79/xbmc#136]
Hello, since recently (started to be the case one month ago) most of the videos I play are green.

Only 1% of amazon prime videos can be properly decoded. Green screen output is similar as when the DRM decoding is not working.

**Comment by xergo** [comment]
Same here. I have all videos grey or white, most of them without sound. Using Kodi17.6 and 0.5.4 of Amazon VOD

**Comment by xergo** [comment]
@yogi81, could you please name one of the 1% Amazon prime video? Would like to try if it works by me. Thanks!

**Comment by Varstahl** [comment]
I can confirm the issue. I've tried to load up my Kodi installation, I was greeted by a Widevine CDM update, followed by `Unable to load widevine shared library`. I'm not sure of the cause yet, doesn't seem to be addon related, but it definitely stopped working alright.

**Comment by Varstahl** [comment]
Both Kodi & InputStream.Adaptive have been heavily updated, the issue is no longer present.
