### ISSUE TITLE
Can't export content to Kodi library

### ISSUE THREAD

**Issue by rusterboy77** [Sandmann79/xbmc#137]
Hi, 

I try to add content to my Kodi library by long press the video and export but context menu don't show me this option. Just show play, play here and add to fav options. I'm in Spain (maybe country matters) and I've tested on Shield and my phone both Kodi Leia (Eminence/Estuary) with same results. 

Maybe offtopic but also tried with Library integration tool and AddToLib addons. They make they work and add content to my library perfectly but I get an error when try to play from library (not from Amazon addon). 

Thank you Sandman79 for this great addon

**Comment by Varstahl** [comment]
The PrimeVideo portion I developed for Amazon VOD is not exactly feature complete. Adaptive caching, contextual menus, export functionalities are all missing. They will come, eventually, it's just not there yet.

**Comment by rusterboy77** [comment]
I was going crazy with this ;)  I hope this feature will be avaliable soon in next updates. Thank you for your quick response and your amazing job with this addon.
