### ISSUE TITLE
Addon broken in latest Leia Alpha

### ISSUE THREAD

**Issue by Blackclaws** [Sandmann79/xbmc#138]
Ok so I've been trying to debug this problem for a while now. There seems to be some sort of breaking change in the way plugins are handled that makes this one malfunction. I'm not quite sure what exactly happened yet but the problems are along these lines:

01:36:32.701 T:139934724022720   DEBUG: ------ Window Init (DialogBusy.xml) ------
01:36:32.841 T:139932018120448   DEBUG: CPythonInvoker(3, /home/kodi/.kodi/addons/plugin.video.amazon/default.py): entering source directory /home/kodi/.kodi/addons/plugin.video.amazon
01:36:32.841 T:139932018120448   DEBUG: CPythonInvoker(3, /home/kodi/.kodi/addons/plugin.video.amazon/default.py): instantiating addon using automatically obtained id of "plugin.video.amazon" dependent on version 2.24.0 of the xbmc.python api
01:36:32.841 T:139932018120448   DEBUG: ['plugin://plugin.video.amazon/', '1', '?mode=appfeed&name=Library&opt&page=1&sitemode=ListMenu&url=video-library', 'resume:false']
01:36:32.841 T:139932018120448   DEBUG: {}
01:36:32.842 T:139932018120448   DEBUG: These are the voyages
01:36:32.842 T:139932018120448   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named None
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.amazon/default.py", line 54, in <module>
                                                modes()
                                              File "/home/kodi/.kodi/addons/plugin.video.amazon/default.py", line 50, in modes
                                                exec 'import resources.lib.%s as sitemodule' % args.get('mode')
                                              File "<string>", line 1, in <module>
                                            ImportError: No module named None
                                            -->End of Python script error report<--
01:36:32.842 T:139932018120448   DEBUG: onExecutionDone(3, /home/kodi/.kodi/addons/plugin.video.amazon/default.py)

Where the three DEBUG outputs before the exception are in order:

print(sys.argv)
print(args)
print("These are the voyages") 

Apparently the args array does no longer get filled correctly with the contents of the query string. However this does not ALWAYS happen.

01:36:55.678 T:139932018120448   DEBUG: ['plugin://plugin.video.amazon/', '2', '?mode=appfeed&name=Library&opt&page=1&sitemode=ListMenu&url=video-library', 'resume:false']
01:36:55.678 T:139932018120448   DEBUG: A mother is a friend indeed
01:36:55.679 T:139932018120448   DEBUG: ?mode=appfeed&name=Library&opt&page=1&sitemode=ListMenu&url=video-library
01:36:55.679 T:139932018120448  NOTICE: [Amazon] Args: {'url': 'video-library', 'page': '1', 'sitemode': 'ListMenu', 'mode': 'appfeed', 'name': 'Library'}
01:36:55.683 T:139932018120448   DEBUG: ['plugin://plugin.video.amazon/', '2', '?mode=appfeed&name=Library&opt&page=1&sitemode=ListMenu&url=video-library', 'resume:false']
01:36:55.683 T:139932018120448   DEBUG: {'url': 'video-library', 'page': '1', 'sitemode': 'ListMenu', 'mode': 'appfeed', 'name': 'Library'}
01:36:55.683 T:139932018120448   DEBUG: These are the voyages

In this case "A mother is a friend indeed" marked a section from resources/lib/common.py.

Curiously resources/lib/common.py was NOT called in the first example. Apparently a thread was reused in that case as well.

01:36:32.603 T:139932026513152   DEBUG: GetLanguageInvoker - Reusing LanguageInvokerThread 3 for script /home/kodi/.kodi/addons/plugin.video.amazon/default.py

Which might explain why the import statement was NOT executed a second time, hence args was never updated, and remains empty. 

This is actually proven by the fact that moving the parsing code for the args variable into the block in default.py removes the exception. There have been other changes it seems however that also lead to errors. For example its impossible to get to the inputstream addon settings the error is "Invalid Handle 14". Also every single show is empty. This might have to do with a change in how files are handled by kodi.

I'd be happy to help debug this further. This has taken quite some time this evening to narrow down completely, and also forced me to roll back to an earlier git version of kodi itself.

I can confirm that kodi git version 759b5e46eb is still working. So the breaking changes were introduced after that.

**Comment by Blackclaws** [comment]
Seem to have found the culprit: See message #10 in this thread.

https://forum.kodi.tv/showthread.php?tid=303073

**Comment by Blackclaws** [comment]
Partial fix in #139

**Comment by Varstahl** [comment]
Thanks for the heads up, I'll work on this asap.

**Comment by Varstahl** [comment]
Contrary to what I expected, re-tested today with the latest Kodi & IS.A builds, and everything is working as intended.
