### ISSUE TITLE
Vieles von Amazon Prime US funktioniert nicht mehr

### ISSUE THREAD

**Issue by The6thDay** [Sandmann79/xbmc#14]
Hi,

Amazon US hat offenbar etwas an der Verschlüsselung geändert, immer mehr Filme/Serien funktionieren nicht mehr(Amazon DE scheint davon noch nicht betroffen zu sein, wird aber bestimmt bald nachfolgen).

Beispiel: 

Interstellar geht ohne Probleme: 
https://www.amazon.com/gp/product/B00TU9UO1W
Log: http://pastebin.com/aRRbQnHV

Mission Impossible Rouge Nation geht nicht:
https://www.amazon.com/gp/product/B012PJVQ7Y/
Log: http://pastebin.com/hVLkGLMy

**Comment by Sandmann79** [comment]
Servus, 

du hast das ja bereits im Kodinerds Forum angebracht und es hat ja auch nichts mit dem Addon direkt zutun - von daher mach ich hier zu.
