### ISSUE TITLE
Login not working - Possible CAPTCHA

### ISSUE THREAD

**Issue by guaycuru** [Sandmann79/xbmc#140]
I'm trying to login to my amazon account in the addon, but keep getting the message: "Unknown Error, please enable advanced debugging in settings and check avod-login.log/avod-login-si.log/avod-login-mfa.log".
So I enabled verbose logging and the only file I could find was avod-login.log which seems to be the HTML response from amazon. Looking through it, I noticed what seems to be a CAPTCHA challenge.
Has anyone seem this before? Is there any way to get around it?

```
    <label for="auth-captcha-guess" class="a-form-label">
      Digite os caracteres
    </label>



    <input type="text" id="auth-captcha-guess" autocomplete="off" name="guess" tabindex="3" class="a-input-text a-span12 auth-required-field">





<div id="auth-guess-missing-alert" class="a-box a-alert-inline a-alert-inline-error auth-inlined-error-message a-spacing-top-mini"><div class="a-box-inner a-alert-container"><i class="a-icon a-icon-alert"></i><div class="a-alert-content">
  Insira os caracteres ▒|  medida que eles aparecem na imagem.
</div></div></div>

  </div>

  <div class="a-section a-text-center">


    <a class="a-link-normal" href="/gp/help/customer/account-issues/ref=is_auth_captcha_fp?ie=UTF8">
      Com problemas ou visão prejudicada?
    </a>
  </div>

```

**Comment by Sandmann79** [comment]
This Captcha check is already included at addon. 
Can you provide the full file, to see whats changed?

**Comment by guaycuru** [comment]
Sure, here it is: https://drive.google.com/file/d/1q5qx-uOQv1EFSovKF45vXvQlFayU5klP/view?usp=sharing

Thank you for looking at this!

**Comment by Varstahl** [comment]
This should be fixed as of @Sandmann79's 9f03818e424106c932c068b2a5c3ed069158aecb, if you want to test it.

**Comment by guaycuru** [comment]
Cool, I'll test it and report back! Thanks!

**Comment by guaycuru** [comment]
It worked, thanks!
