### ISSUE TITLE
Fixes and enhancements for the ReusePythonInvoker

### ISSUE THREAD

**Issue by Varstahl** [Sandmann79/xbmc#143]
@peak3d was gracious enough to submit #142, fast fixes to support ReuseInvoker. I temporarily merged into [enh-reuseinvoker](https://github.com/Sandmann79/xbmc/tree/enh-reuseinvoker), where we can test and further improve it.

@Sandmann79 it requires testing on your part, in the meanwhile I'll propagate the changes to AmazonVOD.

**Comment by Sandmann79** [comment]
@Varstahl the AmazonVOD doesn't need to be updated, this changes affects only addons with submodules, like the Amazon (plugin.video.amazon) one. 
If i understand this right, the python files defined at addon.xml are permanently "refreshed", while the other ones only at addon init, not while browsing thru the directories.

**Comment by Varstahl** [comment]
I think you're right in that regard, but a bit of future proofing won't harm, I think. I also wanted to check if I could restructure things a bit to support plugin routing for example, and this might be a good way to hit two birds with one stone.

Besides, although it's outside the scope of the issue, the Amazon VOD has seen some pretty serious work, and I was considering the possibility to take the 3.5k lines monolith default.py and split it into more meaningful and manageable modules.

What do you think?

**Comment by Sandmann79** [comment]
I've considered that possibility, but too lazy too realize that :wink:.

In this case we can initialize all variables at default.py and using a similar structure, like in the other Amazon addon. (common.py play.py primevideo.py ...)

**Comment by Varstahl** [comment]
Merged to main in 40a709f897f1ad575872da44eec360b1aa489081.
