### ISSUE TITLE
Unable to add/remove videos from Watch List

### ISSUE THREAD

**Issue by knappster1** [Sandmann79/xbmc#147]
I am using Amazon VOD 0.5.4 on Kodi 18 alpha 2.  It is installed in an arch-based 64-bit linux.  Video playback works great, but I am unable to add or remove videos from the Watch list.  I have a similar issue in the Netflix addon, so I wonder if they might be related.

Here is a pastebin of everything subsequent to the URL including the csrf token.  I'm not sure how sensitive that is and thought it's best not to post it publicly.
https://pastebin.com/L4DvwGsi

**Comment by Sandmann79** [comment]
It's have been already fixed with 1cf32e538273c66912d6ab0c2071225da0739f9e at git, but not published yet.

**Comment by knappster1** [comment]
@Sandmann79 thanks for the response.  Would you like me to try that commit and report back?  Or am I better off waiting for the next release?

**Comment by Varstahl** [comment]
@knappster1 you can download [`default.py`](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/default.py) and overwrite the one on your machine (`~/.kodi/addons/plugin.video.amazon-test/default.py`).

**Comment by knappster1** [comment]
@Varstahl that did it.  I'm  closing the issue now.  Thanks!
