### ISSUE TITLE
Amazon VOD only playing audio and no video

### ISSUE THREAD

**Issue by Haroon89** [Sandmann79/xbmc#15]
Hardware: Pi 3B
Software: 7.0.2 -> Updated with Krypton build #1008

Hello

first I want to say, that I love the addon, it work well. I have a issue with a few titles though, i.e. John Wick it only plays audio and no video starts. Is this issue known and is there a fix?

Regards

**Comment by Sandmann79** [comment]
Hi, 

that's a known issue, because Amazon changed their DRM encryption security level.
The devs working on it and found a solution, but it needs some time to implement it.

**Comment by Haroon89** [comment]
Hi,

that's very nice to hear.
Thanks for the reply.

**Comment by Tihmann** [comment]
Hi 

Any News on this issue?

**Comment by DarkLevi** [comment]
Got the same Issue but only on first Episode of every Season =D
I very confused cause Episode 2 and so on works like a charm. Only every 1 Episode won't work.

But plugin himself is very great work and i love it. Many thanks for developing this great Plugin.

Looking forward for a solution of this issue.

Thx

**Comment by htrampe** [comment]
THX for the great plugin. Change in 0.2.9 is only an errormessage for the drm issue. What about the drm-issue-stat - when it will be done? Great work so far so keep it on! Maybe u have enough time for netflix, too :)

**Comment by Sandmann79** [comment]
There are no news at the moment. 

The last info i got, is that kodi needs yuv decoding, wich it dosn't support at the moment.

@htrampe: if you're not on Raspi, you can setup an fallback playback method in settings, like browser or script.

**Comment by Sandmann79** [comment]
Same as #19
