### ISSUE TITLE
Export not available for PrimeVideo

### ISSUE THREAD

**Issue by DanySK** [Sandmann79/xbmc#150]
To the best of my understanding, in order for the library integration to work I need to export the titles I want to integrate, then point my library to the generated files. This can be done by using the contextual menu on seasons (series?) and movies. However, such submenu does not appear:
* in case of series and seasons, only "Add to favourites" is displayed after a right click
* in case of movies, the options are: "Play", "Information", "Mark as watched", "Play from here", and "Add to favourites"

Am I not understanding correctly how the export system is supposed to work?

Thanks

**Comment by Varstahl** [comment]
The export feature for PrimeVideo.com videos is not implemented yet. I started working on the addon way later than the time the addon was originally created, so a lot of features that are fully functional for the amazon.com/co.uk/de/jp are not completely developed. Another example is the Watchlist, where at the moment it can be updated and set from the website, but not from inside the addon.

They will come sooner or later, I just don't have any ETAs for the moment.

**Comment by DanySK** [comment]
Thanks for the clarification, and for your work.
You might want not to close the issue now but treat it as a feature request.

**Comment by jokerigno** [comment]
> They will come sooner or later, I just don't have any ETAs for the moment.

Hi, any update on this? It is still in the road map?

**Comment by Zuikkis** [comment]
Thumbs up for this feature! :)
