### ISSUE TITLE
cant play video on rpi2

### ISSUE THREAD

**Issue by eerozeteen** [Sandmann79/xbmc#151]
Hi,

Im trying to watch amazon on my rpi2 with newest osmc. 
I saw old issues with my problem, and tries tips which i found there.
 
Sandmann79's tip dont work for me: https://github.com/Sandmann79/xbmc/issues/90#issuecomment-366874966

Script download widevine but still have info in log about no finding license.

> 22:10:35.390 T:1181516544   ERROR: AddOnLog: InputStream Adaptive: Unable to find license;hdcpEnforcementResolutionPixels in JSON string
> 22:10:35.390 T:1181516544   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
> 22:10:35.391 T:1181516544   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)

what should i do ?

**Comment by Varstahl** [comment]
I'm not sure if it's the same problem, but the addon won't probably work anymore unless you have the latest version of InputStream.Adaptive (2.2.4 iirc, or something like that) and one of the latest nightly builds of Kodi (Alpha3). I'm not sure if the Widevine in RPi are up to date like the rest, but after the latest Widevine update at least all PC versions stopped working.

**Comment by eerozeteen** [comment]
My  InputStream.Adaptive is 2.0.20, Kodi 17.6 (probably to old) OSMC build 2018.06-1. I think that kodi can be too old (i read about v18 to work with plugin)

**Comment by Varstahl** [comment]
Yup, it's way too old to support InputStream.Adaptive & Widevine. You can maybe install Chrome and use the external browser method, if you don't want to update.

**Comment by eerozeteen** [comment]
thank you for answer and tip. i will try install chromium and use it.

**Comment by eerozeteen** [comment]
Just inform. I install beta repo of osmc witch v18 and all works ok. Thanks @Varstahl again for show me the proper way ;)

**Comment by Varstahl** [comment]
Awesome, glad it works :D
