### ISSUE TITLE
Videos buffer a lot depending on server

### ISSUE THREAD

**Issue by Blackclaws** [Sandmann79/xbmc#154]
So I originally had the host selection set to auto. This worked fine for a while until it started buffering heavily one day after working fine for other videos. I manually selected a host and that seemed to fix it for that time. However that host also appears to have issues from time to time making it necessary to host hop.

I was wondering whether there was any way to improve the auto feature (I'd be willing to help with this) or to adaptively switch to different hosts depending on stream performance. 

It also appears as though there isn't a very large buffer for the amazon videos. Is this something that can be configured? I do have Kodi set to buffer as much as possible for any type of media, however I do not know how it handles these DRM protected streams.

**Comment by Varstahl** [comment]
Sometimes wit happens, sort of regardless of what you select, and it's pretty evident from the beginning of the video. The only "workaround" I found that works for me, is top stop the episode and restart from the beginnings. 80% of the times the buffering problem goes away by itself, sometimes it takes a couple tries.

Testing all the available CDNs for speed or reliability before automatically selecting one could be a good idea, we could maybe ping them all once and calculate the response times (if they actually support ICMPs, which I'm not sure about).

I'll leave this issue open while I think about it.

**Comment by Blackclaws** [comment]
I have had similar experiences. However there has to be a way to reliably get rid of this problem as I never experienced anything similar using the amazon web player. 

Pinging them might be a good first step, however even if they all respond to ping (which they should) then that only gives you a latency and no information on throughput. I'm also not sure whether this couldn't still be solved by buffering further ahead if that's possible in any way. Or is this something that would have to be handled by inputstream adaptive? 

The interesting part is that sometimes it appears to buffer for quite a while once it hits a stop and then runs fine again for another 5 minutes until the next breakdown. Is there any way we could do a quick failover in the background when we notice one source becoming slow? Or is that something that is again prevented by the way we rely on inputstream adaptive to actually do the decoding etc.? I.e. do we even have any information about the video once its been started?

**Comment by Varstahl** [comment]
Closing this as the relevant information are now inside the [FAQ](https://github.com/Sandmann79/xbmc/wiki/FAQ#my-video-is-buffering-a-lot--my-video-takes-a-long-time-to-start-playback-and-interrupts-every-few-seconds).
