### ISSUE TITLE
Wiedergabe nicht möglich - Mindestens eine Datei konnte nicht abgespielt werden.

### ISSUE THREAD

**Issue by tb1rd** [Sandmann79/xbmc#158]
Hi,
ich habe die neuste Kodi und Libreelecversion in der Alphaphase. Bei mir kommt jedoch diese Meldung, wenn ich einen Film abspielen möchte. Inputstream.adaptive ist ebenfalls installiert. Wo finde ich die log-Datei für Amazon VOD? Vielleicht könnte das weiterhelfen.
Vielen Dank 
:)

**Comment by Varstahl** [comment]
My german is terrible so I won't even try. The logs for LibreElec should be under `/storage/.kodi/temp/kodi.log`.

**Comment by tb1rd** [comment]
Hi,
thank you for your fast answer. Here is the log file.
The problem is that the plugin is loading - but the movie does not start.
Do you have any solution?

`21:01:01.393 T:1609679728  NOTICE: [Amazon VOD] Starting Playback: 0.0/0.0
21:01:01.394 T:1609679728  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.amazon.de/cdp/usage/UpdateStream?asin=B0766FMZMB&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=bef2180b74cff7a426a50c145b6a1a106bfd6ed52b3044d12ead586c&marketpl$
21:01:05.777 T:1566376816   ERROR: AddOnLog: InputStream Adaptive: Unable to find license;hdcpEnforcementResolutionPixels in JSON string
21:01:05.777 T:1566376816   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
21:01:05.777 T:1566376816   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
21:01:05.780 T:1566376816   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.amazon-test/?asin=B0766FMZMB&mode=PlayVideo&adult=0&name=%5BCOLOR+FFE95E01%5DBlade+Runner+2049%5B%2FCOLOR%5D&trailer=0&selbitrate=0]
21:01:05.780 T:1566376816  NOTICE: CVideoPlayer::OnExit()
21:01:05.827 T:1940750352 WARNING: OnMessage: Suspiciously long time to handle GUI_MSG_PLAYBACK_STARTED (4.59s)
21:08:46.094 T:1609679728  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.amazon.de/cdp/catalog/GetPlaybackResources?asin=B01D0IFJOK&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=bef2180b74cff7a426a50c145b6a1a106bfd6ed52b3044d12ead586$
21:08:46.420 T:1609679728  NOTICE: [Amazon VOD] Using Host: Cloudfront
21:08:46.420 T:1609679728  NOTICE: [Amazon VOD] checkURL: https://d1l0nb3g075aoz.cloudfront.net/dm/2$DeR7Gg2C1X-JPcdDa7jdWBOsFTM~/445d/4db1/05d2/4ba7-9c72-59b5c4a99791/157bd742-e69a-4ac2-ad54-1997be90565e_corrected.mpd
21:08:47.780 T:1609679728  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 999.2.2.16
21:08:47.905 T:1940750352  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B01D0IFJOK&mode=PlayVideo&adult=0&name=%5BCOLOR+FFE95E01%5DAuferstanden%5B%2FCOLOR%5D&trailer=0&selbitrate=0
21:08:47.907 T:1794081648  NOTICE: Creating InputStream
21:08:48.086 T:1609679728  NOTICE: [Amazon VOD] Starting Playback: 0.0/0.0
21:08:48.087 T:1609679728  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.amazon.de/cdp/usage/UpdateStream?asin=B01D0IFJOK&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=bef2180b74cff7a426a50c145b6a1a106bfd6ed52b3044d12ead586c&marketpl$
21:08:51.878 T:1794081648   ERROR: AddOnLog: InputStream Adaptive: Unable to find license;hdcpEnforcementResolutionPixels in JSON string
21:08:51.878 T:1794081648   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
21:08:51.879 T:1794081648   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
21:08:51.881 T:1794081648   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.amazon-test/?asin=B01D0IFJOK&mode=PlayVideo&adult=0&name=%5BCOLOR+FFE95E01%5DAuferstanden%5B%2FCOLOR%5D&trailer=0&selbitrate=0]
21:08:51.881 T:1794081648  NOTICE: CVideoPlayer::OnExit()
21:08:51.982 T:1940750352 WARNING: OnMessage: Suspiciously long time to handle GUI_MSG_PLAYBACK_STARTED (4.06s)
`
Thank you

**Comment by Varstahl** [comment]
It looks like a problem with the Widevine CDM, you need to update it if possible. I'm unsure of the specific procedure, but you can find more information in issues #90 and #62. Closing the issue as duplicate.
