### ISSUE TITLE
Error Contents: local variable 'Info' referenced before assignment

### ISSUE THREAD

**Issue by d3m10n** [Sandmann79/xbmc#160]
I'm a new user. kodi 18 beta2 30082018 - windows 10 build 17962
After 2-3 hours of using/testing and viewing a film i can't open the film overview within the addon and in the log i got 

19:58:54.732 T:12716   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'Info' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\x\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py", line 5, in <module>
                                                EntryPoint()
                                              File "C:\Users\x\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\startup.py", line 83, in EntryPoint
                                                g.pv.Browse(None if 'path' not in args else args['path'])
                                              File "C:\Users\x\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 173, in Browse
                                                PlayVideo(self._videodata[nodeName]['metadata']['video'], self._videodata[nodeName]['metadata']['asin'], '', 0)
                                              File "C:\Users\x\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\playback.py", line 579, in PlayVideo
                                                playable = _IStreamPlayback(asin, name, trailer, isAdult, extern)
                                              File "C:\Users\x\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\playback.py", line 527, in _IStreamPlayback
                                                listitem.setInfo('video', getInfolabels(Info))
                                            UnboundLocalError: local variable 'Info' referenced before assignment
                                            -->End of Python script error report<--

19:58:54.891 T:12716 WARNING: CPythonInvoker(5, C:\Users\x\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py): the python script "C:\Users\x\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon,class XBMCAddon::xbmcgui::Dialog

19:59:05.743 T:7924  NOTICE: [Amazon VOD] {'path': 'root-//-Films-//-Films populaires-//-0NHFMLVGW1K38SOTPAT8RRFSDL', 'mode': 'PrimeVideo_Browse'}

19:59:06.323 T:7924  NOTICE: [Amazon VOD] External Call

19:59:06.373 T:7924  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.primevideo.com/cdp/catalog/GetPlaybackResources?asin=amzn1.dv.gti.8cad7ed1-4091-e52e-011a-59a233124469&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=4c855f08b1e92c37ab4d4873dcef021a893322e46a3cdc2a8605cf0e&marketplaceID=A3K6Y4MI8GDYMT&format=json&version=1&gascEnabled=true&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProtocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&videoMaterialType=Feature&desiredResources=PlaybackUrls,SubtitleUrls,ForcedNarratives&supportedDRMKeyScheme=DUAL_KEY

19:59:08.076 T:7924  NOTICE: [Amazon VOD] Using Host: Cloudfront

**Comment by Varstahl** [comment]
I'm sorry for the delay, but I'm unable to reproduce the issue. A few questions:
* What version of Kodi are you using?
* What version of Amazon VOD are you using?
* What did you exactly do that caused the issue?

**Comment by ammgws** [comment]
Is it possible to get to [line 527](https://github.com/Sandmann79/xbmc/blob/fcc56d64853222aca125033397879dac29f0f6b3/plugin.video.amazon-test/resources/lib/playback.py#L527) in `_IStreamPlayback` without the `Info` var being set? g.UsePrimeVideo = true, extern = true, trailer=false seems like a combination that would cause that.

**Comment by Varstahl** [comment]
Sure seems so. Bug introduced with 0773beede1a33c20a23d5f93d91d9bcb7ec8d578, 8 months ago. I'm quite unsure how to fix it though, will have to look at the flow.
