### ISSUE TITLE
Inputstream version issue

### ISSUE THREAD

**Issue by mrbell321** [Sandmann79/xbmc#162]
I’m fairly certain this is a setup issue on my end but I can log in and get the list of my videos, but when I go to play, I get this:
`
19:25:02.831 T:1253639024  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.2.25.0
19:25:02.992 T:1939700384  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B015LLS4NW&mode=PlayVideo&adult=0&name=The+Man+in+the+High+Castle+-+Official+Trailer&trailer=0&selbitrate=0
19:25:02.999 T:1278817136  NOTICE: Creating InputStream
19:25:03.001 T:1278817136   ERROR: ADDON: Could not locate inputstream.adaptive.so.2.0.20
`
This is libreelec alpha and I have inputstream.adaptive version 2.2.25.0.
Not sure where the 2.0.20 reference is coming from. Ideas?

**Comment by Varstahl** [comment]
I'm honestly not too sure, and I can't really find much on the subject either. It seems like the videoplayer is linked to and old version of InputStream or something. [For a similar problem](https://github.com/peak3d/inputstream.adaptive/issues/88) that happened in the past, the only fix was rebuilding the package. So it's probably some corrupted alpha build from LibreElec that needs fixing.

**Comment by CGarces** [comment]
@mrbell321 try to update your libreELEC build, see https://github.com/LibreELEC/LibreELEC.tv/pull/2960

**Comment by mrbell321** [comment]
Ah, interesting. Thanks. Looks like not an xbmc issue so closing this
