### ISSUE TITLE
Malware contaminated xbmc-master.zip !?

### ISSUE THREAD

**Issue by RobbesU** [Sandmann79/xbmc#166]
Hi Sandmann79,

After updating the Widevine last night, kodi stopped playback so I wanted to update to the latest (my install is from just after you updated to the automatic Widevine extraction :-) ).

**However**, just tried downloading your latest zip, and my virus scanner threw up an alarm!

![image](https://user-images.githubusercontent.com/33870532/45766715-26310900-bc30-11e8-97b7-773acecbd715.png)

Scanning the file with BitDefender states infection with "Trojan.GenericKD.30576130".

![image](https://user-images.githubusercontent.com/33870532/45766892-a6f00500-bc30-11e8-998f-c555f6a88eed.png)

**Comment by RobbesU** [comment]
FWIW:  I managed to remove the virus with BitDefender (but you might still want to see if it is in the source file).
PS: After install and update the player works again. Top !

**Comment by RobbesU** [comment]
Sorry. shouldn't have closed as virus risk in source not closed.

**Comment by Varstahl** [comment]
False alarm, contains an AutoHotKey script executable for windows which you can safely remove. If you want to check it you should see that it's `tools/userinput.exe`.

**Comment by RobbesU** [comment]
Top. Thank you.



Sent from my phone.
(apologies for odd swipe/spelling errors)
