### ISSUE TITLE
ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)

### ISSUE THREAD

**Issue by haggaie** [Sandmann79/xbmc#167]
Not sure if this is the right place to post this, but I am trying to use your plugin on LibreELEC 8.90.004, and I'm getting the following errors when trying to play a video on Amazon Prime:

```
21:18:44.435 T:1394598768   ERROR: AddOnLog: InputStream Adaptive: Unable to find license;hdcpEnforcementResolutionPixels in JSON string
21:18:44.435 T:1394598768   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
21:18:44.436 T:1394598768   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
21:18:44.446 T:1394598768   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=search-%2F%2F-amzn1.dv.gti.6ead
db64-c06e-2c7e-ccf7-30218311ca8d-%2F%2F-0I1CWVRUIFHRR47BBZXEGCSZL5-//-0TITTM94ZQ0IWAUSEBNA2O97F5]

```

Any idea what might cause that?

**Comment by Varstahl** [comment]
Yup, you must update lib widevine. More information on #62 and #99.

**Comment by haggaie** [comment]
Thank you @Varstahl. I've tried following [this](https://github.com/Sandmann79/xbmc/issues/90#issuecomment-366874966) solution in #90 and [this](https://github.com/Sandmann79/xbmc/issues/62#issuecomment-358640313) solution in #62 to try and update widevine. Both resulted in the same error. Do you know any other solution that can help?

**Comment by Varstahl** [comment]
I'm afraid I can't really help you as I never had a LibreElec installation. This problem pops up every once in a while, but there's not much to do other than updating LibreElec, Kodi and the InputStream.Adaptive,

**Comment by haggaie** [comment]
Thanks. pgrading to ULibreELEC 8.90.005 did the trick.

**Comment by fatg3erman** [comment]
I'm getting this on a RPi 3B+ running Raspbian. I've applied all updates, deleted libwidevine and the inpustream helper folder to force an update of libwidevine - which was successful, still getting this error. Anything else I can try?

```
2019-04-07 07:31:20.770 T:1103106800   ERROR: AddOnLog: InputStream Adaptive: Unable to find license;hdcpEnforcementResolutionPixels in JSON string
2019-04-07 07:31:20.770 T:1103106800   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)

```

```
bob@raspberrypi:~/.kodi/cdm $ ls -l
total 20
-rw-r--r-- 1 bob bob 1805 Apr  7 07:31 EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED.challenge
-rw-r--r-- 1 bob bob   89 Apr  7 07:31 EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED.init
-rw-r--r-- 1 bob bob  625 Apr  7 07:31 EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED.response
lrwxrwxrwx 1 bob bob   89 Apr  6 21:09 libwidevinecdm.so -> /home/bob/.kodi/userdata/addon_data/script.module.inputstreamhelper/cdm/libwidevinecdm.so
drwxr-xr-x 5 bob bob 4096 Mar 30 21:13 widevine

```

```
bob@raspberrypi:~/.kodi/userdata/addon_data/script.module.inputstreamhelper/cdm $ ls -l
total 6796
-rwxr--r-- 1 bob bob 6821832 Apr  6 21:09 libwidevinecdm.so
-rw-r--r-- 1 bob bob  132303 Apr  6 21:09 widevine_config.json

```

**Comment by Varstahl** [comment]
[Read this and apply the fix](https://github.com/Sandmann79/xbmc/issues/293#issuecomment-479945580).

**Comment by fatg3erman** [comment]
Thanks, working at 720p now.
