### ISSUE TITLE
Add Amazon US live channels and can't play hd

### ISSUE THREAD

**Issue by esaigio** [Sandmann79/xbmc#168]
Hello it is possible to add the amazon hd live channels like hbo cinemax starz I have the addons and will like to watch those channels in kodi also I have a problem everytime I try to choice the quality to hd the video got frozen audio keeps playing but when I back to a sd resolution the video play fine again is there any setting I'm missing or amazon can't play in hd in kodi?

thanks in advance!

**Comment by Varstahl** [comment]
> Hello it is possible to add the amazon hd live channels like hbo cinemax starz

While I originally wanted to provide a way to automatically enable those channels I never got around to it. We'd have to ask @Sandmann79, as I have no idea what that entails at the moment.

> I try to choice the quality to hd the video got frozen audio keeps playing but when I back to a sd resolution the video play fine again

TV series should play fine at any resolution, movies won't play HD. Amazon's movies 720p or higher are encoded with a different Widevine standard, which causes players to fail decrypting the stream. There are no current solutions known for this problem.
