### ISSUE TITLE
Can not sign in, Continuously have a Captcha

### ISSUE THREAD

**Issue by damgot** [Sandmann79/xbmc#169]
Hello,
I've an issue with Amazon VOD.
When I try to sign in (in the addon settings), I enter my email, then my password, then it ask to reenter my password with a Captcha (for security reason).

I enter my password and the captcha, everything is good but 10 secondes later, the captcha appears again and I have to reenter my password with the captcha. Finally, I'm not able to connect at all.

I've tried to enter a wrong password, and I have a clear error message "Wrong password". So password and captcha are good.

Log doesn't say a lot of things : 
01:23:41.500 T:2616943344 WARNING: CPythonInvoker(4, /home/osmc/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE
01:24:31.533 T:2616943344  NOTICE: [Amazon VOD] {'mode': 'LogIn'}
01:24:31.701 T:2616943344  NOTICE: [Amazon VOD] Retrieve territoral config
01:24:31.772 T:2616943344  NOTICE: [Amazon VOD] getURL: https://na.api.amazonvideo.com/cdp/usage/v2/GetAppStartupConfig?deviceTypeID=*********&deviceID=************&firmware=1&version=1&format=json
01:25:01.626 T:2616943344   ERROR: /home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py:418: UserWarning: gzip transfer encoding is experimental!
                                              br.set_handle_gzip(True)
01:25:01.641 T:2616943344  NOTICE: [Amazon VOD] Connect to SignIn Page 5 attempts left
01:27:11.907 T:2616943344  NOTICE: [Amazon VOD] MFA, DCQ or Captcha form

**Comment by Varstahl** [comment]
@Sandmann79 as @damgot said in #170, and I quote: 

> So it was just a wrong password. But in the returned error message, "wrong code" message is only for bad captcha. For a wrong password, there is no special indication.

Is this a limitation on Amazon's server or do we just return a general error when we have 2FA? Does Amazon provide different error codes, even with 2FA enabled?

**Comment by damgot** [comment]
I didn't have 2FA enabled, but in my case, as my first autentification try failed, it ask me a captcha. But it never says that the password is wrong. It's just something like "for security reason please type your password again and fill the captcha" (not exactly but it's the idea).

**Comment by Varstahl** [comment]
Ah yeah, sorry, my bad.

**Comment by Varstahl** [comment]
Fair enough
