### ISSUE TITLE
Videos Not playing on Amazon VOD

### ISSUE THREAD

**Issue by pfugazzi** [Sandmann79/xbmc#175]
Hi, even if the installation seems ok and imputstream enabled when starting a Video after a while noting happen.  System is Libreelec with KODI18.
Here the log

10:09:39.658 T:1471148912  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.primevideo.com/cdp/catalog/GetPlaybackResources?asin=amzn1.dv.gti.4eaeab88-cf4d-71e6-65c4-d3b14b19eb6b&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=5ba1d9bb8d385cbd35bd04f52291c2122a5e8ed1960860489b72d0a4&marketplaceID=A3K6Y4MI8GDYMT&format=json&version=1&gascEnabled=true&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProtocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&videoMaterialType=Feature&desiredResources=PlaybackUrls,SubtitleUrls,ForcedNarratives&supportedDRMKeyScheme=DUAL_KEY
10:09:40.528 T:1471148912  NOTICE: [Amazon VOD] Using Host: Cloudfront
10:09:40.530 T:1471148912  NOTICE: [Amazon VOD] checkURL: https://s3-dub.cf.dash.row.aiv-cdn.net/dm/2$yZzGjtJbMIIZTQz5gnOSwIv-gQI~/4828/ab82/6ca2/4d3f-96e0-31cd38311151/7ae60e00-a5c6-4484-a44a-8b968c49ac74_corrected.mpd
10:09:43.662 T:1471148912  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.2.27.0
10:09:43.702 T:1938973472  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2F%2F-Film-%2F%2F-Continua+a+guardare%3A+film-//-0JTAY3JTO3YDULJWPI5YPOG297
10:09:43.704 T:1550824304  NOTICE: Creating InputStream
10:09:43.705 T:1550824304   ERROR: ADDON: Could not locate inputstream.adaptive.so.2.0.20
10:09:43.705 T:1550824304   ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
10:09:43.705 T:1550824304   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2F%2F-Film-%2F%2F-Continua+a+guardare%3A+film-//-0JTAY3JTO3YDULJWPI5YPOG297]
10:09:43.705 T:1550824304  NOTICE: CVideoPlayer::OnExit()
10:09:43.812 T:1695892336   ERROR: EXCEPTION: XBMC is not playing any media file
10:09:43.813 T:1695892336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XBMC is not playing any media file
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/player.py", line 74, in onPlayBackStarted
                                                self.current_video_total_time = self.getTotalTime()
                                            RuntimeError: XBMC is not playing any media file
                                            -->End of Python script error report<--
10:09:43.966 T:1471148912  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.primevideo.com/cdp/usage/UpdateStream?asin=amzn1.dv.gti.4eaeab88-cf4d-71e6-65c4-d3b14b19eb6b&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=5ba1d9bb8d385cbd35bd04f52291c2122a5e8ed1960860489b72d0a4&marketplaceID=A3K6Y4MI8GDYMT&format=json&version=1&gascEnabled=true&event=STOP&timecode=0
10:09:44.017 T:1784640368  NOTICE: Previous line repeats 1 times.
10:09:44.018 T:1784640368  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.primevideo.com/cdp/usage/UpdateStream?asin=amzn1.dv.gti.d6abfc03-6bda-3a07-15dc-903337574cb4&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=5ba1d9bb8d385cbd35bd04f52291c2122a5e8ed1960860489b72d0a4&marketplaceID=A3K6Y4MI8GDYMT&format=json&version=1&gascEnabled=true&event=STOP&timecode=0
10:09:44.349 T:1938973472 WARNING: CGUIMediaWindow::OnMessage - updating in progress

**Comment by Varstahl** [comment]
There's a problem with your installation:

```
NOTICE: Creating InputStream
ERROR: ADDON: Could not locate inputstream.adaptive.so.2.0.20
ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
```

I believe you might need to update LibreElec and/or Kodi. It's not a problem with the addon, it just can't load InputStream.Adaptive. Also, the addon as it is released in the wild won't work with the new amazon changes, you will need to wait for version 0.5.8 to work correctly with last night's changes. But yeah, even 0.5.8 won't help with a broken installation.

**Comment by StefanHirche** [comment]
Hi,
I know this tocket is closed, but as I have the same issue...
On pfugazzi and my system inputstream.adaptive in version 2.2.27 is installed:

`NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.2.27.0`

I can't see how an update of kodi or libreelec might help, as I'm running current beta/alpha of those.

I tried to install version 2.0.20, but this yields the error

`ERROR: Unable to resolve exports from dll /storage/.kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.0.20`
`ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation`

**Comment by Varstahl** [comment]
> `ERROR: Unable to resolve exports from dll […]/inputstream.adaptive.so.2.0.20`

This is a linking error, which happens when the main software application is linked against a different dynamic library. InputStream.Adaptive and Kodi must be built/upgraded together, otherwise you won't be able to load the necessary executable files for InputStream.Adaptive, resulting in an error. So if you're reverting IS.A you need to revert Kodi as well.

I'm not sure about the details and the reason why there are problems, but in any case it's strictly a problem between Kodi and IS.A, we can't help.

**Comment by dagwieers** [comment]
Related to https://github.com/xbmc/inputstream.adaptive/issues/454
