### ISSUE TITLE
Kodi 18 librelec v8.90.005 ALPHA Amazon prime France not working

### ISSUE THREAD

**Issue by adruet29** [Sandmann79/xbmc#176]
After successfully getting the netflix plugin working great on libreelec on my raspberry pi 3 B+ I tried your amazon prime addon.
The plugin installs correctly, it tells me I am connected sucessfully but I am unable to browse the content.

In the logs I get this error:

19:38:14.634 T:1570763632  NOTICE: [Amazon VOD] Login
19:38:14.699 T:1570763632  NOTICE: [Amazon VOD] Connect to SignIn Page 5 attempts left
19:38:26.185 T:1570763632   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 83, in EntryPoint
                                                g.pv.Browse(None if 'path' not in args else args['path'])
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 177, in Browse
                                                self._LazyLoad(node, nodeName)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 441, in _LazyLoad
                                                results = re.search(r'<section\s+[^>]*class="[^"]*av-detail-section[^"]*"[^>]*>\s*(.*?)\s*</section>', cnt, flags       =re.DOTALL).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
19:38:26.526 T:1570763632 WARNING: CPythonInvoker(101, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugi       n.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcg       ui6DialogE
19:38:26.544 T:1335096176   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2f%2f-Enfants-%2f%2f-S%c3%a9       ries%20Amazon%20Original
19:38:26.548 T:1938539296   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2f%2f-Enfants-%2f%2f-S%c3%a       9ries%20Amazon%20Original) failed

Please let me know if I can help you out in anyway to correct this.

**Comment by Varstahl** [comment]
Duplicate #170 

> After successfully getting the netflix plugin working great on libreelec on my raspberry pi 3 B+ I tried your amazon prime addon

Just to clear this ahead of time: Netflix and Amazon have nothing in relation to each other. Both use Widevine DRM, but different types, so one working doesn't mean the other will. In case of Amazon, movies with a resolution higher than 720+ won't decrypt correctly, while TV series give no such problems.

> The plugin installs correctly, it tells me I am connected sucessfully but I am unable to browse the content.

The current stable version (0.5.7) isn't working due to some changes in Amazon frontend that happened between last friday and monday evening. You can bypass these problems by replacing the `primevideo.py` in your installation with the one from the [master branch](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/resources/lib/primevideo.py).

I'm waiting a couple days to see if more UI change on PrimeVideo.
