### ISSUE TITLE
7z issue, unable to package

### ISSUE THREAD

**Issue by Varstahl** [Sandmann79/xbmc#178]
The version of 7z currently shipped in the tools has its relative missing DLL, and therefore is unable to archive anything, making the building script provided useless.

```
> tools\7z.exe a <name>.zip <target> -tzip

7-Zip [64] 9.34 alpha  Copyright (c) 1999-2014 Igor Pavlov  2014-06-22

Error:
7-Zip cannot find the code that works with archives.
```

Since it's a fairly old build I dare not touch anything, but if you can you should upload the relative dynamic library, otherwise it makes no sense shipping the `7z.exe` in the tools.

**Comment by Sandmann79** [comment]
You're absolutely right. 7z.exe has been replaced with current 7za.exe (standalone version) at 178bce9478581a026a47b35c42f34e0e62b053f6.
