### ISSUE TITLE
After upgrade to 0.5.8 cannot sign to Amazon site

### ISSUE THREAD

**Issue by pfugazzi** [Sandmann79/xbmc#179]
after upgrade trying to sign in nothing happen

Here the log

15:57:26.868 T:1705767680   ERROR: GetDirectory - Error getting
15:57:53.476 T:1472197376   ERROR: Previous line repeats 2 times.
15:57:53.476 T:1472197376  NOTICE: [Amazon VOD] Switching UserAgent
15:57:53.477 T:1472197376  NOTICE: [Amazon VOD] Loading list of common UserAgents
15:57:53.482 T:1472197376  NOTICE: [Amazon VOD] getURL: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
15:57:54.964 T:1472197376  NOTICE: [Amazon VOD] Error 500
15:57:54.964 T:1472197376   ERROR: [Amazon VOD] Error reason: 429 (HTTPError)
15:58:04.965 T:1472197376  NOTICE: [Amazon VOD] Attempt #2. Too many requests - Pause 10 sec
15:58:04.966 T:1472197376  NOTICE: [Amazon VOD] getURL: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
15:58:05.586 T:1472197376  NOTICE: [Amazon VOD] Error 500
15:58:05.586 T:1472197376   ERROR: [Amazon VOD] Error reason: 429 (HTTPError)
15:58:15.587 T:1472197376  NOTICE: [Amazon VOD] Attempt #3. Too many requests - Pause 10 sec
15:58:15.588 T:1472197376  NOTICE: [Amazon VOD] getURL: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
15:58:15.969 T:1472197376  NOTICE: [Amazon VOD] Error 500
15:58:15.970 T:1472197376   ERROR: [Amazon VOD] Error reason: 429 (HTTPError)
15:58:15.980 T:1472197376   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'string'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 38, in EntryPoint
                                                getUA()
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 66, in getUA
                                                UAlist = text.string.split('\n')
                                            AttributeError: 'NoneType' object has no attribute 'string'
                                            -->End of Python script error report<--
15:58:16.156 T:1472197376 WARNING: CPythonInvoker(4, /home/osmc/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE

**Comment by pfugazzi** [comment]
forcing use of Python 3.7 I've the same behaviour but a bit different log
16:25:03.066 T:1905259264  NOTICE: [Amazon VOD] Switching UserAgent
16:25:03.067 T:1905259264  NOTICE: [Amazon VOD] Loading list of common UserAgents
16:25:03.073 T:1905259264  NOTICE: [Amazon VOD] getURL: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
16:25:04.177 T:1905259264  NOTICE: [Amazon VOD] Error 500
16:25:04.178 T:1905259264   ERROR: [Amazon VOD] Error reason: 429 (HTTPError)
16:25:14.178 T:1905259264  NOTICE: [Amazon VOD] Attempt #2. Too many requests - Pause 10 sec
16:25:14.179 T:1905259264  NOTICE: [Amazon VOD] getURL: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
16:25:14.798 T:1905259264  NOTICE: [Amazon VOD] Error 500
16:25:14.798 T:1905259264   ERROR: [Amazon VOD] Error reason: 429 (HTTPError)
16:25:24.799 T:1905259264  NOTICE: [Amazon VOD] Attempt #3. Too many requests - Pause 10 sec
16:25:24.799 T:1905259264  NOTICE: [Amazon VOD] getURL: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
16:25:25.433 T:1905259264  NOTICE: [Amazon VOD] Error 500
16:25:25.433 T:1905259264   ERROR: [Amazon VOD] Error reason: 429 (HTTPError)
16:25:25.436 T:1905259264   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'string'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 38, in EntryPoint
                                                getUA()
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 66, in getUA
                                                UAlist = text.string.split('\n')
                                            AttributeError: 'NoneType' object has no attribute 'string'
                                            -->End of Python script error report<--
16:25:25.607 T:1905259264 WARNING: CPythonInvoker(8, /home/osmc/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE

**Comment by Varstahl** [comment]
Thanks for the information, it's the first time this ever happened. I uploaded a quick fix a couple minutes ago, could you please download the [network.py](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/resources/lib/network.py), replace the one found in your installation at `/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py`, and confirm that everything is working correctly?

**Comment by mo123** [comment]
All the tv show and movie lists are empty, but the login problem is solved.

**Comment by Varstahl** [comment]
hmmm… wait, what? Have you tried clearing the cache after the error? Delete `/home/osmc/.kodi/userdata/addon_data/plugin.video.amazon-test/PVCatalog[ID].pvcp` after closing Kodi, and try again.

**Comment by Varstahl** [comment]
Thank you for the feedback, will push an update asap.

**Comment by Varstahl** [comment]
Fix deployed with 38f314db034a2759f133a4d41ce7e3c87035acdf. Thanks again, everyone.

**Comment by ameetmd** [comment]
Have deleted /home/osmc/.kodi/userdata/addon_data/plugin.video.amazon-test/PVCatalog[ID].pvcp as suggested however tv show and movie lists are still empty, This is on RPi3B+ with OSMC

[Err20181005.txt](https://github.com/Sandmann79/xbmc/files/2450202/Err20181005.txt)

**Comment by Varstahl** [comment]
In your case, you need to also delete `PVVideoData<id>.pvdp`.

**Comment by ameetmd** [comment]
Apologies.
