### ISSUE TITLE
Unable to play / Browser or script missing

### ISSUE THREAD

**Issue by nidico100** [Sandmann79/xbmc#18]
muss ich noch etwas weiteres installieren vorher? wo krieg ich die browser her? bsp chrome?

**Comment by Sandmann79** [comment]
Das kommt auf dein System drauf an, beim Raspi zum Beispiel steht nur Inputstream zur Verfügung.
Bei allen anderen kann der Browser über die Paketquellen bzw. das Internet bezogen werden.

**Comment by nidico100** [comment]
achsoo okee, danke
