### ISSUE TITLE
Changing default playback method

### ISSUE THREAD

**Issue by Varstahl** [Sandmann79/xbmc#182]
@Sandmann79 after erasing my settings several times tonight while trying to debug #180, I found myself constantly resetting the playback method from Browser to InputStream.

Given the fact that most of the distros and platform with Kodi are by now all running IS.A, wouldn't it be more sensible to change in the settings the default value to IS.A?

**Comment by Sandmann79** [comment]
Since inputstream runs stable over several months, we should do this.

**Comment by Sandmann79** [comment]
Modified with 0ac6212e0cfc6994b76a174a941e9246986dcab3
