### ISSUE TITLE
Change in the single movie/TV series UI broke the addon

### ISSUE THREAD

**Issue by JohnnyPicnic** [Sandmann79/xbmc#185]
Followed the url posted which lead to "The Man In the High Castle" Season 1 Episode 1.

[URL](https://www.primevideo.com/gp/video/detail/0TA9YAO0SCEV5SDZE4O2K123DG/)

**Comment by Varstahl** [comment]
I don't need the URL, I need a content dump. The same URL changes content based on a number of factors: location, users, language preferences and so on. I can tell you that *my* MitHC works perfectly fine, but you have problems, so:
* open the URL in your browser
* CTRL+U or View source or whatever it is in the browser you're using
* copy all the HTML code and post it somewhere (like pastebin for example)
* then provide me the link to the HTML content

**Comment by JohnnyPicnic** [comment]
I hope i've got it right this time. 
https://pastebin.com/V5Vhvss5

**Comment by Varstahl** [comment]
Yup, seems okay, I'll analyse it as soon as I get the chance.

**Comment by Varstahl** [comment]
UGH, they changed the UI again, I start to hate them…

**Comment by JohnnyPicnic** [comment]
Here is my log after using the latest changes from the master.
I thought it was working as Kodi was taking a while to load "TV Shows" as usual but after opening "TV Shows" there were no shows in any of the genres.
https://paste.kodi.tv/sikudekeqe.kodi

**Comment by Varstahl** [comment]
This looks like a corrupt data file due to the bug caused by the UI change. You probably need to delete both cache files (*.pvcp, *.pvdp) and try again, then it should work.

**Comment by Varstahl** [comment]
@JohnnyPicnic any update on the issue?

**Comment by JohnnyPicnic** [comment]
Still having the same issue. Tried the current master and when first opened it takes a while to load TV Shows but after opening a genre the list is empty. Will post a log shortly. Will also try a completely fresh install.

**Comment by Varstahl** [comment]
@JohnnyPicnic the logs are cut early, there's nothing to be seen.

**Comment by JohnnyPicnic** [comment]
it just repeats the urls after that
[Amazon VOD] postURL: https://atv-ps.primevideo.com.....

**Comment by JohnnyPicnic** [comment]
Another verbose log.
https://paste.kodi.tv/vilobileru.kodi

**Comment by Varstahl** [comment]
The pagination is broken somehow. I need to port the old queries to the new addon system, that should fix a lot of troubles we're currently having, but it's going to take a while.

**Comment by Varstahl** [comment]
@JohnnyPicnic

I need a favour if I am to get to the bottom of this. I need the following HTML file contents from these pages:
* [PrimeVideo homepage](https://www.primevideo.com/)
* [Series page](https://www.primevideo.com/storefront/tv/)
* [Expanded category page](https://www.primevideo.com/search/ref=atv_tv_hom_c_fsjguc_3_seemre?query=p_n_entity_type%3DTV%20Show%26search-alias%3Dinstant-video%26index%3Deu-amazon-video-euro%26adult-product%3D0%26bq%3D(and%20sort:'featured-rank'%20(and%20studio:'amazon%20studios'%20(and%20(not%20(or%20av_primary_genre:'children'%20av_primary_genre:'family'))%20(not%20(or%20av_secondary_genre:'children'%20av_secondary_genre:'family')))))%26av_offered_in_territory%3DIT%26qs-av_request_type%3D4%26qs-is-prime-customer%3D2&ie=UTF8)
* Any season page, [like this](https://www.primevideo.com/detail/0T1R1MXA75ZCR0C3247CHPIS3X/) for example, but from your own listings.

There are many differences across the listings that I can't get to the bottom of if I don't have your versions of the pages.

**Comment by Drahas** [comment]
https://www.dropbox.com/s/1movlpda9dxqloj/PrimeVideo.zip?dl=0

Thank you very much for your worrk :)

**Comment by Varstahl** [comment]
Thanks @Drahas, looking at this as we speak, and I realized I missed the [Watchlist page](https://www.primevideo.com/watchlist/) from my list of needed pages, do you think you can hook me up with that too?

**Comment by Drahas** [comment]
@Varstahl :  https://pastebin.com/6an7jtpv

**Comment by Drahas** [comment]
@Varstahl  Yeah I don't use Amazon Prime yet.
I add something in my watchlist
https://pastebin.com/hnw3EkqL

**Comment by Drahas** [comment]
For me it's better, I can access to the movies / tv shows list.
But now when I try to play something in the list I get an error
Sorry the log export does'nt work

**Comment by Varstahl** [comment]
> But now when I try to play something in the list I get an error

Meh. Could you manually provide the logs? You can find them in `~/.kodi/temp/kodi.log` or `%AppData%\Kodi\kodi.log`, depending on the OS.

**Comment by Drahas** [comment]
Ok it's work manually :)
https://pastebin.com/Luy7HK3L

**Comment by Varstahl** [comment]
Not entirely sure but seems like a cache problem. Have you tried to shut down kodi and delete the *.pvcp and *.pvdp inside `~/.kodi/userdata/addon_data/plugin.video.amazon-test/`?

**Comment by Drahas** [comment]
I retried to clean cache and reboot but I can't read anything :(

**Comment by Varstahl** [comment]
Don't know, the logs show that it can't find `root > Films > Films – Comédie`. Maybe an encoding error? Have you tried other categories and/or TV series results? Does it stop working when it gets into the movie/series list, when it get into the season with the episode list, or when you try to playback? I didn't see any playback try in the logs you provided.

**Comment by Drahas** [comment]
I tried other movies or tv show and the playback never display anything.
When I launch the playbackI have the waiting symbols for few minutes and after an error message

**Comment by JohnnyPicnic** [comment]
I didn't delete any cache file. Just used the latest master and replaced with the primevideo.py file in this thread.
All is working! Thanks for your work on this.
