### ISSUE TITLE
Amazon VOD error only for TV Show list

### ISSUE THREAD

**Issue by ameetmd** [Sandmann79/xbmc#186]
As suggested, opening a new issue on Amazon VOD error appearing for TV Show listing only. Tested using RPi3B+ running OSMC with Kodi 18.0-BETA2 having Amazon VOD v0.5.9 add-on from India location. 

Post reading other issues on this subject, following has been already tried with no success -
1. Exited Kodi. Cleared catalog & videodata file from /.kodi/userdata/addon_data/plugin.video.amazon-test/. Rebooted and added the Amazon account till it confirmed I was logged in. 
2. TV Show list give Amazon VOD Error; kodi.log for TV show listing error is as attached. [TV Shows Log.txt](https://github.com/Sandmann79/xbmc/files/2464492/TV.Shows.Log.txt)
3. Basis https://github.com/Sandmann79/xbmc/issues/180#issuecomment-427647401 discussion, copied <domain>/catalog/GetPlaybackResources?<query> into the browser however the connection times out. FYI, <domain>/catalog/GetPlaybackResources? for Movie & TV Show list is the same & only the query string is different. Pasting both links in the browser eventually results in time out. 

To reiterate, movie list takes some time to display the first time, thereafter, they appear & play normally. Any assistance on getting TV Show listing to work will be helpful. Thanks in advance.

**Comment by Varstahl** [comment]
The problem is that it must work. If that doesn't work, then the entire plugin would result empty. Are you sure you copy pasted the URL correctly? It must include all parameters found in the GET query.

Also, pay attention because the log you provided has portions missing, for example the URL is cut at a certain length.

**Comment by ameetmd** [comment]
Yes, the attached logs may have been incomplete but i got it while diagnosing. Refer below 

1. TV List URL - https://atv-ps-eu.primevideo.com/cdp/catalog/GetPlaybackResources?asin=amzn1.dv.gti.5aac37fb-9be0-bd23-94ac-dc557388b134&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=79f6be88f753ba56fc9db36a6fc7a1319becf21e74c9524c10480a33&marketplaceID=A2MFUE2XK8ZSSY&format=json&version=1&gascEnabled=true&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProtocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&videoMaterialType=Feature&desiredResources=CatalogMetadata&titleDecorationScheme=primary-content

2. Movie URL - https://atv-ps-eu.primevideo.com/cdp/catalog/GetPlaybackResources?asin=amzn1.dv.gti.86b2b69c-7ec3-edda-384c-df56d5d48190&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=79f6be88f753ba56fc9db36a6fc7a1319becf21e74c9524c10480a33&marketplaceID=A2MFUE2XK8ZSSY&format=json&version=1&gascEnabled=true&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProtocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&videoMaterialType=Feature&desiredResources=CatalogMetadata&titleDecorationScheme=primary-content

As you can see the domains are identical & only query varies. Being the noob here & agreeing to your statement that it should work; I will carry out a fresh install on an SD card & revert with my observations shortly. Thank you

**Comment by Varstahl** [comment]
If the TV list URL is the one **immediately** before the crash in the logs, open it in a browser, and copy the JSON somewhere. Since it's geo/location based, I can't access the version you see just as you can't access the version I see. If I don't have your version of the data, I can't understand where's the problem.

**Comment by Varstahl** [comment]
Also, note, that the current version of PrimeVideo changed and broke again, you need to update primevideo.py with the one in the master.

**Comment by L0r3n20** [comment]
Same issue in Italy. I reversed Amazon VOD to 0.5.7 as instructed. Now movie list is populated and playable while I get an error opening TV shows list. My log is similar to the ones already posted.

**Comment by Varstahl** [comment]
@L0r3n20 I'm not going to support 0.5.7, but if you're experiencing similar problems with 0.5.9, feel free to follow the instructions I gave to @ameetmd and provide the necessary JSON I asked for.

**Comment by M0RN3S1** [comment]
I have a similar problem where I get an Amazon VOD error appearing for TV Show listings only. The Movie listing works fine though, and the search function works as a workaround to get to the TV Show you want to watch. I am in South Africa BTW. I have already cleared the Cache. It did not resolve the problem though. BTW, I am a newby when it comes to anything Linux and Kodi.
[kodi.log](https://github.com/Sandmann79/xbmc/files/2479300/kodi.log)

**Comment by Varstahl** [comment]
@M0RN3S1 completely different problem, and no error on your end. Try reverting to 0.5.7, [instructions here](https://github.com/Sandmann79/xbmc/issues/176#issuecomment-426745485).

**Comment by M0RN3S1** [comment]
> @M0RN3S1 completely different problem, and no error on your end. Try reverting to 0.5.7, [instructions here](https://github.com/Sandmann79/xbmc/issues/176#issuecomment-426745485).

Thank you! That seems to have fixed the issue. Thanks for all your good work.

**Comment by Varstahl** [comment]
Glad it worked :)
