### ISSUE TITLE
due changes at amazon's drm encryption ...

### ISSUE THREAD

**Issue by mkleiber** [Sandmann79/xbmc#19]
Hallo,
KODI gibt mir seit kurzem die Meldung "due changes at amazon's drm encryption, it's not possible to use inputstream for this video. please configure the fallback." bei manchen (neueren) Filmen von Amazon Prime.
Gibt es dafür eine Lösung? Einen möglichen Fallback gibt es auf dem Raspi ja nicht.
VG, Micha

**Comment by Sandmann79** [comment]
Aktuell noch nicht.

Mein letzter Stand ist, das im Kodi die YUV Dekodierung implementiert werden muss - was wohl nicht ganz trivial ist.

**Comment by Hagenzone** [comment]
Hallo Sandmann79,
erstmal Danke für das tolle Add-On. Das DRM-Problem besteht leider noch immer.
Gibt es mittlerweile Neuigkeiten zum Sachverhalt?
LG

**Comment by FreddyDummy** [comment]
Hallo,
mittlerweile scheint das Amazon auf alle Videos ausgeweitet zu haben, bei mir geht seit letztem Freitag gar keines mehr.
Regards
Freddy

**Comment by Sandmann79** [comment]
Mittlerweile gibt es auch die ersten Lösungen, dabei muss man sich aber den Kodi selbst kompilieren.
Auf RasPi's läuft es wohl auch noch nicht.
Hier gibt es mehr Infos: https://www.kodinerds.net/index.php/Thread/44211-Release-Amazon-Prime-Instant-Video/?postID=366963#post366963

**Comment by FreddyDummy** [comment]
Hallo,
OK, dann warten wir mal ab.....
Regards Freddy

**Comment by mfarley281** [comment]
Can anyone share the status of this issues for U.S. Prime accounts? Is the DRM working on the latest Kodi and latest version of this plugin? (Unfortunately, I can't read German :()

**Comment by Hagenzone** [comment]
As far as I see there have been no changes since 2 months. I suppose from today, solving the drm-issue is more than just installing / updating the plugin.

**Comment by Sandmann79** [comment]
The drm issue is not addon related, it's caused by the inputstream addon, which the addon is using for video playback.

There is a solution out there, but you have to compile kodi by yourself: https://github.com/Sandmann79/xbmc/issues/22#issuecomment-285946443

**Comment by mfarley281** [comment]
Any idea when the updated Kodi DRM code (Agile branch?) will make it into core main stream Kodi?

**Comment by timbru31** [comment]
@mfarley281 The Milhouse testbuild 628 is working again, since the agile changes are merged back to regular xbmc/xbmc repo - go grab it from here: https://forum.kodi.tv/showthread.php?tid=298461
You need to patch the addon, by removing these lines though: https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/default.py#L1119-L1124

**Comment by stevenleadbeater** [comment]
@timbru31 those lines would break the plugin if they were commented out. There would be an elif with no starting if so it would be a syntax error. I checked the file at the point of commit the day before your comment too and it was the same. can you elaborate please?

**Comment by Sandmann79** [comment]
@stevenleadbeater You don't need to patch the default.py anymore. The patch provided by @timbru31 is for an older version of addon. Inputsteam adaptive v2.0 is now fully supported by the addon..

**Comment by Sandmann79** [comment]
I think that issue can be closed, because its fixed since July at Kodi 18 alpha and Libreelec 9.

**Comment by electronicSteam** [comment]
ich habe bereits die neuste imputstream und amazon vod versoin und bei mir kommt immernoch der gleiche drm fehler

**Comment by Sandmann79** [comment]
@electronicSteam Kodi 18 alpha bzw. LibreElec 9 installiert?
