### ISSUE TITLE
Impossible to add credentials

### ISSUE THREAD

**Issue by rotdrop** [Sandmann79/xbmc#190]
Well, this is for Leia. Installed the thing. Then the following issues pop up:

- plugin disabled: I cannot add credentials
- plugin enabled: the beast reminds me every 5 seconds or so that I should add my credentials. I try. But before I have finished the reminder pops up again AND VOIDS MY CREDENTIALS. The effect is that this is totally unusable, because I am not able to give it my Amazon credentials, because the reminder pops up, reminding me, that I should, I try, the reminder pops up again, I try, I'm interrupted again ...

Thanks for your work, of course, I know that it is a spare-time activity. 

IMHO, there should either be the possibility to configure the beast offline before the plugin is enabled. Otherwise those reminders shoudl be disabled while the credential-input-dialog is active.

**Comment by rotdrop** [comment]
Can't there please be a less sophisticated method to enter the Amazon credentials? It is a real nightmare the way it is. Please provide a means to edit the credentials directly into the config files. Perhaps one could use htpasswd to secure the credentials a little bit. I'm still stuck filling in my credentials ...

**Comment by rotdrop** [comment]
Can't there please be a short-circuit I-add-my-credentials-via-my-favourite-edtor?

I have now tried for three (3!) hours to add my login credentials. Every something is wrong the entire inputs are voided and I have to start over again. Sorry, but in the current state the plugin is totally useless. Can be that by a chance -- investing 5 hours more or so -- I eventually arrive at a state which is accepted by your plugin. But that just cannot "be it". 

Still I appreciate your work, know that it is your spare-time work, so please just interpret this posting as a hint, and keep up your good work. Thanks.

**Comment by rotdrop** [comment]
Oops. Ok. please forgive me and let's start over again.

**Comment by Sandmann79** [comment]
This bug has been fixed some years ago with 2040b926a4dad6569e4488cd775d1e3546ad92db,
but removed for some reason with commit 955bdd599b0c1629328a7680c0e0c55379c19fd0.
Have to look into this.
