### ISSUE TITLE
Can't load movies / tv show list

### ISSUE THREAD

**Issue by Drahas** [Sandmann79/xbmc#192]
I tried to use your plugin because I think it could be really nice :)
So when I want to load tv shows or movies, the list can't be loaded and I have an error. I retrieve the categories  folder (in french) but I can't navigate into.
http://paste.debian.net/1048403/

My configuration :
OSMC on Rasberry PI
French amazon prime user
No VPN
Addons Amazon VOD installed and I just configure the credentials

Hope you can help me or fix something :)

**Comment by Drahas** [comment]
I tried to revert the primevideo.py file and I still get the same error.
I'm not really sure I did it well, I copy by ftp the new primevideo.py in /home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib

http://paste.debian.net/1048418/

**Comment by Varstahl** [comment]
Ah yes, of course, I forgot to tell you you need to delete the *.pvcp and *.pvdp cache files in `/home/osmc/.kodi/userdata/addon_data/plugin.video.amazon-test/`.

**Comment by Drahas** [comment]
I tried to delete the *.pvcp and *.pvdp cache file, clear credential, reboot, set credential and launch the addon and I still get an error
http://paste.debian.net/1048531/

**Comment by Varstahl** [comment]
> I tried to delete the *.pvcp and *.pvdp cache file, clear credential, reboot, set credential and launch the addon and I still get an error

What the hell… you're sure you reverted to 0.5.7 correctly? Could you please open a browser on [this page](https://www.primevideo.com/detail/0TEJURB40RR9O77D1OHY14JUO5/) and post its content somewhere?

> Same symptoms here (breaks upon loading series list)

Have you tried reverting to 0.5.7 as well?

**Comment by Varstahl** [comment]
> I tried to delete the *.pvcp and *.pvdp cache file, clear credential, reboot, set credential and launch the addon and I still get an error

Are you sure you reverted to 0.5.7 correctly? Could you open [this page](https://www.primevideo.com/detail/0TEJURB40RR9O77D1OHY14JUO5/) in your browser, and post the content somewhere?

> Same symptoms here (breaks upon loading series list)

Did you revert to 0.5.7 as well?

**Comment by Drahas** [comment]
Sorry I dont know how to revert to 0.5.7
https://ibb.co/i0EqtA

**Comment by santinod** [comment]
> > Same symptoms here (breaks upon loading series list)
> 
> Did you revert to 0.5.7 as well?

Just tried copying primevideo.py from commit 6a0d6c5 (Jul 30), which I assume is 0.5.7, and removed a .pvcp file.
Things got a bit better: now I can get past the first menu (series / film / etc.), but when I try to open e.g. the "Comedy" list, the "Amazon VOD Error" shows up again.
Kodi log: https://pastebin.com/bpuYzmTL

**Comment by Varstahl** [comment]
This is becoming a fucking nightmare :D

Sooo… you have a mix of the old catalogs with the new series page. I need to look back and try to support both, somehow.

**Comment by Varstahl** [comment]
@Drahas, @santinod

I need a favour if I am to get to the bottom of this. I need the following HTML file contents from these pages:
* [PrimeVideo homepage](https://www.primevideo.com/)
* [Series page](https://www.primevideo.com/storefront/tv/)
* [Expanded category page](https://www.primevideo.com/search/ref=atv_tv_hom_c_fsjguc_3_seemre?query=p_n_entity_type%3DTV%20Show%26search-alias%3Dinstant-video%26index%3Deu-amazon-video-euro%26adult-product%3D0%26bq%3D(and%20sort:'featured-rank'%20(and%20studio:'amazon%20studios'%20(and%20(not%20(or%20av_primary_genre:'children'%20av_primary_genre:'family'))%20(not%20(or%20av_secondary_genre:'children'%20av_secondary_genre:'family')))))%26av_offered_in_territory%3DIT%26qs-av_request_type%3D4%26qs-is-prime-customer%3D2&ie=UTF8)
* Any season page, [like this](https://www.primevideo.com/detail/0T1R1MXA75ZCR0C3247CHPIS3X/) for example, but from your own listings.

There are many differences across the listings that I can't get to the bottom of if I don't have your versions of the pages.

**Comment by Varstahl** [comment]
Whops, I forgot to post the update here. @santinod there is a beta update: can you test if [this version of primevideo.py](https://raw.githubusercontent.com/Varstahl/xbmc/master/plugin.video.amazon-test/resources/lib/primevideo.py) fixes all of your problems? Wiping the cache data should not be necessary, but won't hurt.

> I tried other movies or tv show and the playback never display anything.
> When I launch the playbackI have the waiting symbols for few minutes and after an error message

@Drahas do you mind if we keep talking here about your issue? The threads are starting to mix up and I'm losing my mind. To recap:
* are you using an account with a valid prime subscription? Note that linked accounts might not work.
* from an SSH connection, can you `systemctl stop kodi`, delete the cache files, then issue a `systemctl start kodi`? Does it fix the problem?
* did you replace the primevideo.py in `~/.kodi/addons/plugin.video.amazon-test/resources/lib` with the one I linked?

**Comment by santinod** [comment]
The primevideo.py you linked properly downloads all lists (thought you might be interested in this piece of news even though the issue is now closed). Thank you!
However, even though I am now able to select e.g. a series episode, I am unable to play it ("One or more items could not be played"). Log [here](https://github.com/Sandmann79/xbmc/files/2520380/kodi.log).

**Comment by Varstahl** [comment]
I hope to god it's a cache issue, although it might not be. There is a full fledged update out (0.6.1), could you install that, delete the *.pvcp and *.pvdp cache files, and try again?
