### ISSUE TITLE
amozon-test plugin, everything is sorted "by date"

### ISSUE THREAD

**Issue by rotdrop** [Sandmann79/xbmc#196]
Hi,
again thank you for your work!

I have a slight issue with the amazon-test plugin, everything is just sorted by date without having the possibility to change this. I am aware of the possibility to set the sort-method in the addon-settings page. However, this does not have any effect.

I comparison with the non-test amazon pluing: the non-test version does sort by name (only that I cannot play any video), see the previous issue)

This is with the current Leia branch.

Best

Claus

**Comment by Varstahl** [comment]
1 year inactivity on both ends, have no idea if this still applies, closing this for the moment.
