### ISSUE TITLE
Export movies and shows with original title

### ISSUE THREAD

**Issue by padok** [Sandmann79/xbmc#197]
In order to include the exported movies and series in the Kodi library and make them easier for the scraper to find, it would be nice to have the possibility to name the file names as original titles.
As good as the Amazon information is, it is unfortunately incomplete and does not support e.g. the summary in film collections.

**Comment by Sandmann79** [comment]
Normally that would not be a problem, but the response from Amazon servers doesn't provide this information.

**Comment by padok** [comment]
Is there alternatively a good scraper that can also match German titles? I haven't had any success with the officials yet.

**Comment by Sandmann79** [comment]
The default scrapper returns good results for me. 
Don't forget to set the language at scrapper settings.

**Comment by padok** [comment]
I had set the language but I'm still not successful, what exactly is your setup?
For Example the Harry Potter Movies from Amazon aren't grouped like the ones from my hard disk.
![screenshot from 2018-11-12 12-54-04](https://user-images.githubusercontent.com/32652531/48346478-8fa32600-e67b-11e8-86a9-7e954c4abde7.png)
