### ISSUE TITLE
Couple of questions and a suggestion

### ISSUE THREAD

**Issue by axlt2002** [Sandmann79/xbmc#198]
First of all I would like to thank the developers; it was a while that I was far from this add-on and quite surprised about the new features that have been added.

I have a couple of questions related to amazon-test:
- I saw that there is the possibility to export the video contents to be integrated in the Kodi library; I guess that this would save some .strm files in the add-on folder or a personal one...but I don't see anything like that. Is there something that I should do in order to proceed with the exportation?
- I have installed the add-on on both Kodi 17.6 and Kodi 18 and noticed that videos are not played over Kodi 17.6...is this a known issue?

And just a suggestion:
- In Kodi 18, the Inputstream add-on is no more installed by default and the user should install it by himself. I saw that in case this add-on is missing, amazon-test notifies this with a popup window. I would suggest that, after that popoup, it would be nice also to procceed with the installation using the built-in function provided by Kodi:

`InstallAddon(Inputstream.adaptive)`

Have a great day!

Alex

**Comment by Varstahl** [comment]
> I saw that there is the possibility to export the video contents to be integrated in the Kodi library; I guess that this would save some .strm files in the add-on folder or a personal one...but I don't see anything like that. Is there something that I should do in order to proceed with the exportation?

Still haven't touched it for PrimeVideo. It's in the ToDo list.

> I have installed the add-on on both Kodi 17.6 and Kodi 18 and noticed that videos are not played over Kodi 17.6...is this a known issue?

Kodi 17 can't handle stream decryption, some of the functions needed to decrypt Widevine have been implemented on 18+.

> In Kodi 18, the Inputstream add-on is no more installed by default and the user should install it by himself

Are you sure? IS.A is hard linked to Kodi, you can't just update it without updating Kodi too. Unless they changed the linking of course, I'll take a look into it. Thanks for the info :)

**Comment by axlt2002** [comment]
> > InstallAddon(Inputstream.adaptive)
> 
> It doesn't work, IS.A is not in Kodi's repository. This is getting complicated, will need to check what are they planning to do.
> 
> On a funny note, in order to test/work around this, I currently broke my local installation, can't do anything anymore without IS.A. 🎉

Hi Varstahl,

Are you sure about that? I've exactly downloaded Inputstream adaptive from the Kodi repository...version 2.3.7 by peak3d. You can find it under Kodi Add-on repository -> VideoPlayer InputStream.

Alex

**Comment by Varstahl** [comment]
I've just reinstalled from the latest nightly and it doesn't appear in the repo. Might be a cache issue, I'm investigating.

**Comment by axlt2002** [comment]
Ok...

My version is 20181105-1af2f2ee66.

**Comment by Varstahl** [comment]
I kind of worked around the problem, and I've managed to set everything up. The code is working correctly, checks for IS.A, then Widevine, and everything is installed as it should. The problem is, that NOTHING works. Does the plugin work for you?

With the Widevine CDM installed on a brand new installation, everything fails :|

**Comment by axlt2002** [comment]
Thanks for the enhancement!

May be you can add a popup window that tells to the user to restart Kodi, just to avoid false alarms.

Have a nice evening!
