### ISSUE TITLE
Cannot play video on Raspberry Pi 3 model B+

### ISSUE THREAD

**Issue by queendevelopers** [Sandmann79/xbmc#199]
I am using raspberry Pi 3 model b+ and firstly I faced a no video player issue on Input Stream and I tried changing the settings and none of them work. The only way was Installing Chrome OS 1.9 GB . After Install I try to play the video I get other issue. I have seen the Post #100  issue, the logs are same but  I am using an latest version of Amazon VOD from sandmann79 repo and  just update the Kodi to latest version using command  sudo apt-get  update && sudo apt-get dist-upgrade but still the same issue. 

When I play the video, the timer 00:00 appears at the top right screen then suddenly error dialog with message check log for detail. You can check errors here : http://paste.osmc.tv/ebihukadub

**Comment by Varstahl** [comment]
First of all, playback won't work without Kodi 18, then:

```
 NOTICE: VideoPlayer: Opening: https://a311avoddashs3ww-a.akamaihd.net/d/2$iNwzq5tCod9FMohIof_apWpkz3E/ondemand/dub-dub-iad/a2c6/0f4e/701b/428d-ae2f-aef2c7d74096/3774e258-c5d4-42e2-b2a1-f988875da81d_corrected.mpd
WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
 NOTICE: Creating InputStream
  ERROR: AddOnLog: InputStream Adaptive: Unable to find license;hdcpEnforcementResolutionPixels in JSON string
  ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
15:32:14.283 T:1447031552   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
```

To solve this, refer to #62.

You can also check information on how to upgrade OSMC on its discourse, [here](https://discourse.osmc.tv/t/testing-kodi-18-leia-builds-for-raspberry-pi/20631).
