### ISSUE TITLE
plugin.program.browser.launcher: Site hinzufügen geht nicht

### ISSUE THREAD

**Issue by getriebesand** [Sandmann79/xbmc#2]
es kommt nur eine Fehlermeldung. 
Das scheint an der default.py Zeile 116 zu liegen. thumb wird garnicht abgefragt und existiert nicht.
Und custBrowser scheint nicht optional zu sein. Ist etwas verwirrend

**Comment by Sandmann79** [comment]
Da haben sich so einige Fehler in dem Zusammenhang eingeschlichen. Danke für's Melden.
Wurde in Commit c8ccb2e5eb79e579959a365def39d12bf00dcea4 gefixt.
