### ISSUE TITLE
Export Watchlist automatically

### ISSUE THREAD

**Issue by kenodai** [Sandmann79/xbmc#20]
I've been playing around with the VOD Addon lately and really enjoy the export functionality to have my favourite shows added to the Kodi Database.
I was thinking if it is possible to have e.g. a Service running which is regularly fetching the Amazon Watchlist and export newly added episodes, so Kodi will pick them up automatically.

Do you see the option to add this kind of funcitonality? I might be able to implement this as well, but you are way more familiar with your codebase.

**Comment by Sandmann79** [comment]
Hi you can try [Osmosis](http://www.kodinerds.net/index.php/Thread/53307-Beta-Version-OSMOSIS-Streams-zur-DB-hinzuf%C3%BCgen/?pageNo=1&s=5e683f04c16582336f3b1316b1deffd0b5ace7dd) ([Github](https://github.com/stereodruid/plugin.video.osmosis)).
With this addon you can add any categories of any addon to kodi library.

**Comment by Sandmann79** [comment]
I close this here, cause of missing feedback
