### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by daschaffert** [Sandmann79/xbmc#200]
Hi i have done a fresh installation of libreelec and of amazon vod today.
But its not possible to log in to amazon I`m getting this erromessage " unknown error please enable advanced logging..."

I have done this, but the only File I can find is this

./storage/.kodi/avod-login-si.log

https://pastebin.com/pUJYXh3u

Pluginversion is 0.6.1

any suggestions are welcome
THX in advance

Btw. my region is germany if that is of matter

**Comment by Sandmann79** [comment]
This bug has been already fixed with 18fb6982b62e11ea8a3a546035ff4fa4b3ef1d42, but not released to public yet. 
If you don't want to wait till the updated is published, you can replace `plugin.video.amazon-test/resources/lib/network.py` with this one [network.py](https://raw.githubusercontent.com/Sandmann79/xbmc/master/plugin.video.amazon-test/resources/lib/network.py).

**Comment by daschaffert** [comment]
Thank you! The login is working now... but for what ever reason the all the movilists are empty ...
no movie and no series are shown ...

**Comment by Sandmann79** [comment]
That's the reason why the update isn't published yet. 
See #201 .

**Comment by cherowley** [comment]
Hi,

I replaced the file as suggested and now get the following errors:
09:30:54.306 T:140353239750400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: (unicode error) 'utf8' codec can't decode byte 0x85 in position 0: invalid start byte (network.py, line 331)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 3, in <module>
                                                from resources.lib.startup import EntryPoint
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 6, in <module>
                                                from .network import *
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 331
                                                wnd = _Captcha((getString(30008).split(' ')[0]), soup, email)
                                            SyntaxError: (unicode error) 'utf8' codec can't decode byte 0x85 in position 0: invalid start byte
                                            -->End of Python script error report<--

Any ideas?

Cheers :)

**Comment by Sandmann79** [comment]
@cherowley can you test it with the recently released v0.6.2?

**Comment by cherowley** [comment]
Hi Sandmann79,

Many thanks - success! Credentials ok, also lists and streaming ok :)

Now to find out why playback is choppy on x86 libreelec but only for this and only when there isn't an overlay :)

Cheers!

**Comment by oAltxF4o** [comment]
Hmmm... I am still having login issues with the Amazon VOD addon in the US region. I even did a fresh install of Libreelec with the most recent Milhouse build on a RBpi 3. Using the Amazon VOD v0.6.2 release. I will post a link to the pastebin with my log in a little bit.

**Comment by Sandmann79** [comment]
@oAltxF4o maybe the last update regarding to this here fixes your login issue. Just replace your network.py with this one: [network.py](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/resources/lib/network.py). 
Please don't replace the file contents, this would break the encoding. It's better to use right click and save link as...

**Comment by mase76** [comment]
I still cannot log in, even with this fix or the new release.

**Comment by mase76** [comment]
After I changed the region from Auto to Germany, I can log in again.

**Comment by V-Modder** [comment]
Same here on fresh Libreelec x64 installation, addon version 0.7.1. Replacing the netwrok.py or changing the region didn't help.
Some kodi logs [here](https://pastebin.com/3tGsUCFj "Pastebin")

**Comment by Varstahl** [comment]
> V-Modder

There's a change in the login page with 2FA, apparently.
