### ISSUE TITLE
Movie and TVShows categories are empty

### ISSUE THREAD

**Issue by Sandmann79** [Sandmann79/xbmc#201]
Due some changes at Amazon's side, the movie and tvshows categories are empty at the moment.
Watchlist, Library and Search are still working.

We're working on this but its can take some time to fix it.

Meanwhile you can add shows or movies with Amazon app or via web to your Watchlist and play them within the Addon.

**Comment by Varstahl** [comment]
Hmm, interesting. May have they standardised it with the PrimeVideo portion of their business? I went through the very same headache recently, if they were uniforming the platforms we might already have the code available (hopeless dream).

**Comment by Sandmann79** [comment]
They redesigned it for all, but it's doesn't work with your primevideo code, but I didn't look further in it.

The Android Api should work for us all, but it isn't possible for me to sniff the login process. 
But i think the token is bound to an Android DevicetypeId and with this, there is no playback possible.

Anyway, for some reason it does work again, maybe a temporary server failure.

**Comment by Varstahl** [comment]
Possible. I'm still quite hell bent on trying to reverse engineer the app provided with the samsung 4k TVs though, but the set up process is so tedious/complicated I still haven't tried. At the very least it should be able to provide good information.

**Comment by Marcocham** [comment]
Hello !
Have you some news on this bug and the way to connect to Amazon ?
Even if you add a serie or a film to the watch list (from web interface or mobile application), you won't recover the serie in the list from the interface
Thank you for your help
Best regards

**Comment by Varstahl** [comment]
This particular issue is long gone. If you have a specific problem open a new issue and provide the [logs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi).
