### ISSUE TITLE
download subtitles problem 

### ISSUE THREAD

**Issue by gergeo86** [Sandmann79/xbmc#203]
can someone help me with subtitles ?sometimes not showing anything from opensubtitles,other times showing other names and when shows correct subs cant find subs that are sync with the serie.please help!

**Comment by gergeo86** [comment]
i want greek subs.i find subs but because the name is not good(not clear like realdebrid) for example dont know if have to download 720p bluray,72op webrip etc.you know which subs work with all amazon sites ?

**Comment by Varstahl** [comment]
If I had to guess, I'd go with the webrip subs. But again, they're rips, so they're bound to offset some way or another when encoded. Some imperfections are expected.

**Comment by gergeo86** [comment]
ok thanks!
