### ISSUE TITLE
Python 3 support for Kodi 18 & 19

### ISSUE THREAD

**Issue by Varstahl** [Sandmann79/xbmc#207]
As notified with #206, Kodi, [moving forward](https://kodi.tv/article/kodi-v18-leia-rc1-new-hope), will only support Python 3 in the long run starting from v19, and addons capable of running under both Python 2 and 3 in v18.

`Mechanize` is one such library which will break py3 compatibility, but surely `urllib` will break just as well. While, technically, we're not in the official repository, we might start considering what code needs refactoring moving on, if we don't want to be caught off guard. Kodi 18 will still support py2.7, so we're in no need to rush out immediately, but still…

**Comment by ammgws** [comment]
Regarding `urllib` it seems only `quote_plus` and `urlencode` are being used, so just updating the imports should from `urllib` to `urllib.parse` should be enough unless there's bytestrings involved.

**Comment by Varstahl** [comment]
I was waiting for py3 Kodi builds, but last I checked it crashed and burned.

**Comment by ammgws** [comment]
True, it seems you have to compile the `feature_python3` branch yourself for now. If I get some time I'll check it out.

**Comment by Varstahl** [comment]
Well, yup, `mechanize` surely broke everything. This will go far less smoothly than anticipated.
