### ISSUE TITLE
Eurosport live channels missing

### ISSUE THREAD

**Issue by Cyrus51** [Sandmann79/xbmc#208]
Hello,
The live channels Eurosport 1 HD & Eurosport 2 HD are up and working, but the Eurosport 360 HD 1-16 channels are not showing up. Can you please add these channels as well?

**Comment by Cyrus51** [comment]
Here are the Channel IDs:

Eurosport 360° HD 1  amzn1.dv.lcid.422d3469-015a-4fe8-b18c-3cb871a12e24
Eurosport 360° HD 2  amzn1.dv.lcid.45a16875-1d4b-4d33-bea4-8e94c19785a5
Eurosport 360° HD 3  amzn1.dv.lcid.071873cc-1bcc-41bb-b829-1eea5ebcc332
Eurosport 360° HD 4  amzn1.dv.lcid.cbe6abf4-2c9f-45af-a886-381d28bc28e1
Eurosport 360° HD 5  amzn1.dv.lcid.16be3e6b-8e6a-4aa6-91d5-fda2a2f6f939
Eurosport 360° HD 6  amzn1.dv.lcid.a59cfee6-04b9-47e5-9c36-9838097e11d4
Eurosport 360° HD 7  amzn1.dv.lcid.d4a02bec-86a4-4c41-b420-eeda0452aca5
Eurosport 360° HD 8  amzn1.dv.lcid.9bd3cae7-077e-412f-91d9-c7be9faf2fb5
Eurosport 360° HD 9  amzn1.dv.lcid.45a39ee9-0bd9-4c24-ad17-9239a1b386a3
Eurosport 360° HD 10 amzn1.dv.lcid.149eedaa-946e-46b4-925b-f1a71ba5109f
Eurosport 360° HD 11 amzn1.dv.lcid.5559a2f8-62fb-46fd-83c4-a73c25dfd2c8
Eurosport 360° HD 12 amzn1.dv.lcid.3b2e610d-fc0d-44a9-b531-fd2dcdb8183b
Eurosport 360° HD 13 amzn1.dv.lcid.2954d6a0-660a-42bc-8cc5-ef5e93a15e70
Eurosport 360° HD 14 amzn1.dv.lcid.1af34746-e2f2-48a2-91eb-f6aa828a2291
Eurosport 360° HD 15 amzn1.dv.lcid.11969a9c-b0ce-4bc2-a6c1-47ebfed4e74a
Eurosport 360° HD 16 amzn1.dv.lcid.6f854d32-255a-4280-88b0-a4266555b519

**Comment by Sandmann79** [comment]
Thanks for the title ids, channels added with cde0897dfb00547d98e6c8d5c936ede53901b542.
Should be available within the next 8 hours.

**Comment by Cyrus51** [comment]
Thank you very much
