### ISSUE TITLE
Amazon VOD 0.3.0 spielt keine Videos ab

### ISSUE THREAD

**Issue by crstmkt** [Sandmann79/xbmc#21]
Ich nutze das Amazon VOD Addon in Verbindung mit LibreELEC (v7.90.009)auf einem Raspberry Pi 2. Wenn ich nun ein Video zum Abspielen auswähle zeigt sich kurz der Ladekringel und dann passiert nichts weiter.

Bis vor wenigen Wochen (ca. Ende November) hat das ganze funktioniert. Leider kann ich keinen genauen Zeitpunkt nennen. Ich habe zwischenzeitlich einige Updates durchgeführt (LibreELEC und das VOD Addon)

[01_KODI.log.txt](https://github.com/Sandmann79/xbmc/files/644417/01_KODI.log.txt)
[02_System.log.txt](https://github.com/Sandmann79/xbmc/files/644418/02_System.log.txt)
[03_Hardware.log.txt](https://github.com/Sandmann79/xbmc/files/644419/03_Hardware.log.txt)
[04_Audio.log.txt](https://github.com/Sandmann79/xbmc/files/644420/04_Audio.log.txt)
[05_Network.log.txt](https://github.com/Sandmann79/xbmc/files/644421/05_Network.log.txt)
[06_varlog.log.txt](https://github.com/Sandmann79/xbmc/files/644422/06_varlog.log.txt)

**Comment by Sandmann79** [comment]
Warscheinlich muss wegen der Umstellung auf inputstream.adaptive, der Decrypter (libssd_wv.so) wieder aktualisiert werden.
Dazu am besten das inputstream.adaptive Addon aus der Kodinerds Repo installieren - dort ist der aktuelle Decrypter bereits enthalten und den Decrypter von /storage/.kodi/cdm/libssd_wv.so nach /storage/.kodi/addons/inputstream.adaptive/lib/libssd_wv.so verlinken.

**Comment by crstmkt** [comment]
Das Addon inputstream.adaptive aus dem Kodinerds Repo ist bereits installiert (v1.0.4). Wie kann ich die Verlinkung vornehmen?

**Comment by Sandmann79** [comment]
Das geht ganz einfach mittels:
`ln -s ~/.kodi/addons/inputstream.adaptive/lib/libssd_wv.so ~/.kodi/cdm/`

Die komplette Anleitung gibt es auch hier:
http://www.kodinerds.net/index.php/Thread/51486-Kodi-17-Inputstream-AddOns-f%C3%BCr-Kodi-17-Beta-6-aktuelle-Git-builds-Update-10-12-2/?postID=333953#post333953

**Comment by crstmkt** [comment]
Danke! Funktioniert wieder. Bei manchen Filmen oder Serien bekomme ich allerdings die Meldung, dass "Aufgrund einer Änderung in Amazons DRM Verschlüsselung kann die Datei nicht wiedergegeben werden."

**Comment by Sandmann79** [comment]
Ist bekannt.

Siehe #15 #19
