### ISSUE TITLE
Can't get past CAPTCHA

### ISSUE THREAD

**Issue by arpruss** [Sandmann79/xbmc#210]
When I try to get past the CAPTCHA on login, I always get an error about no control matching u'guess'.
Here's my log file: https://pastebin.com/eMzftG9C

This is with Kodi 18 RC1, both on an RPI3 and on a GalliumOS laptop.

**Comment by arpruss** [comment]
Figured it out. In network.py, in _MFACheck(), just before setting br['email'], br['password'] and br['guess'], the line br.select_form(nr=0) should be replaced with br.select_form("signIn") to get past the CAPTCHA.

**Comment by Sandmann79** [comment]
Thanks for the hint, but it has already fixed with 3a9acf82e222af7fe442ed80b75f71de922c12db.
But not published yet.

**Comment by arpruss** [comment]
Thanks!

**Comment by uSpike** [comment]
@Sandmann79 any idea when this fix will be published?  It's currently preventing me from logging in.  Is there a workaround I can use in the short term?
Thanks!

**Comment by arpruss** [comment]
You could just edit the file manually.

**Comment by Sandmann79** [comment]
@uSpike I think it should be done within these day
