### ISSUE TITLE
Ampersand in TV Shows and Movies sections

### ISSUE THREAD

**Issue by stargriv** [Sandmann79/xbmc#211]
Opening a new issue for Amazon VOD, error appearing for TV Shows and Movies sections when I'm trying to play any title from menu which has ampersand in its name (Action & Adventure Movies, Kids & Family Movies, Action & Adventure TV, Kids & Family TV). Tested using RPi3B running OSMC with Kodi 18.0 17.8-345 having Amazon VOD v0.6.2 add-on from Czech Republic.

How-to reproduce:
1. Remove cache files from /home/osmc/.kodi/userdata/addon_data/plugin.video.amazon-test/PV*A2MFUE2XK8ZSSY.pv?p
2. Restart RPI
3. Open Amazon VOD, navigate to Movies or TV Shows section and wait when cache will be filled again.
4. Try to play any item from Action & Adventure Movies, Kids & Family Movies, Action & Adventure TV, Kids & Family TV

In Kodi log I have error telling that it can't find proper name in pickled dictionary for 'Kids ' because in dictionary we have 'ssVKids & Family Movies'

```
13:26:37.841 T:1498407664   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'Kids '
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 83, in EntryPoint
                                                g.pv.Browse(None if 'path' not in args else args['path'])
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 182, in Browse
                                                node = node[n]
                                            KeyError: u'Kids '
                                            -->End of Python script error report<--

```

**Comment by Varstahl** [comment]
Hmm… That would explain why "Kids " and "Action ". The question would now be wth is wrong with that, got to check.

**Comment by Varstahl** [comment]
The problem lies in your installation of Kodi 17. I've tested the latest Amazon VOD version in some Kodi 18 builds, on Windows, Debian and LibreElec, and they all work correctly. I have no plans to support Kodi 17, but your problems should fix themselves once you upgrade.
