### ISSUE TITLE
Choosing Art for Video Files with embedded Covert Art causes Kodi to crash

### ISSUE THREAD

**Issue by ScubyUK** [Sandmann79/xbmc#213]
Windows 7 fully patched
Issue occurs with Leia RC1, RC2 and Nightlies up to the 10th

If mp4 and mkv files contain embedded artwork, Kodi will not display a poster for that title upon after scan.
When you try to choose artwork for that title Kodi will stop responding and crash within 20 seconds or so.
Using a tag editor to remove the embedded artwork resolves the issue.

**Comment by ScubyUK** [comment]
[kodi_crashlog-18.0-RC1 Git_20181121-314c302559-20181210-213508.zip](https://github.com/Sandmann79/xbmc/files/2665731/kodi_crashlog-18.0-RC1.Git_20181121-314c302559-20181210-213508.zip)

Attached are copies of crash dumps in case they help.

**Comment by Sandmann79** [comment]
Here is not the official xbmc/kodi repository. You can find it here:
https://github.com/xbmc/xbmc
