### ISSUE TITLE
Watchlist Serien not working

### ISSUE THREAD

**Issue by ChristophGoth** [Sandmann79/xbmc#215]
The Serien-Watchlist doesn't open:

09:10:16.043 T:140671844898560  NOTICE: [Amazon] getURL: https://www.amazon.de/gp/video/watchlist/tv/?ie=UTF8&sort=DATE_ADDED_DESC
09:10:16.634 T:140671844898560   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'split'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon/default.py", line 52, in <module>
                                                modes()
                                              File "/storage/.kodi/addons/plugin.video.amazon/default.py", line 49, in modes
                                                exec 'sitemodule.%s()' % var.args.get('sitemode')
                                              File "<string>", line 1, in <module>
                                              File "/storage/.kodi/addons/plugin.video.amazon/resources/lib/appfeed.py", line 175, in ListCont
                                                for asin in tv.lookupTVdb(value, tbl='shows', rvalue='asin').split(','):
                                            AttributeError: 'NoneType' object has no attribute 'split'
                                            -->End of Python script error report<--
09:10:16.756 T:140671805232896   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon/?mode=appfeed&name=Serien&opt&page=1&sitemode=ListCont&url=%2fgp%2fvideo%2fwatchlist%2ftv%2f
09:10:16.765 T:140674545499456   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon/?mode=appfeed&name=Serien&opt&page=1&sitemode=ListCont&url=%2fgp%2fvideo%2fwatchlist%2ftv%2f) failed

Just updated to 2.0.0 Beta, still happening.

Movies is working as expected.

**Comment by Sandmann79** [comment]
This error should never occur, if the database update has correctly finished. 
Just update the database again and it should be gone.

**Comment by Varstahl** [comment]
@ChristophGoth any update on the issue?

**Comment by gint0nic** [comment]
> 
> 
> This error should never occur, if the database update has correctly finished.
> Just update the database again and it should be gone.

Hi Sandmann,

thx for your reply (an you great work on this addon), got the same problem here (kodi 18 arm64 release jan 28th, android 7.1, rep 1.0.2, addon 0.6.6 (german 2.x never worked)). for 3 days now, i'm not able to see the watchlist for series an can't play movies. i' can't see an option  for "update database" in the settings, could you enlight me where i can find it?

greetings
g1n

**Comment by gint0nic** [comment]
Hej there,

now i‘d tried again by uninstalling amazon vod (with all settings and dependencies) and switched to german amazon addon. still the same problem: nothing‘s to see in the addon, doesn‘t matter if i‘m looking in watchlist or anything else, even the search show absolutly nothing. manual db sync (which is now available) doesn‘t change an thing. :(

**Comment by Varstahl** [comment]
As far as I know, the manual db sync takes a few hours, just let it run in the background.

**Comment by gint0nic** [comment]
Hej Varstahl,

did not helped :( I‘d had to completly remove kodi and reinstall it, fortunetly i‘m only using 3 addons with kodi, a complete resetup is done in 20mins. now it works so far, i‘m able to see content but it only plays in 920x540 or something like that. i‘d tested some settings like „minimum bitrate“ set to 80mbps to force FHD, did‘nt worked :( any ideas? 

greetings

**Comment by Varstahl** [comment]
On PC and other open devices 720p and 1080p movies are protected with HDCP, not currently supported by Kodi/IS.A afaik, so the highest possible resolution is 1088x464. You should test some TV series, they generally support full 1080p.

**Comment by gint0nic** [comment]
Sorry, forgot to mention, I‘m only watching serie. So the problem i‘m trying to solve affects Amazon series ;)

**Comment by Varstahl** [comment]
Waaait, you mentioned some arm-based shenanigans. Are you using a RPi or similar gear? Are you **sure** you are able to watch 1080p videos to begin with? (And by that I mean enough power to download the stream, decrypt it, decode it, and watch it without stutters)

Hardware like Raspberry-Pis are well known for not supporting full HD due to a lack of raw power.

**Comment by gint0nic** [comment]
it‘s a h96 pro+ with a amlogic 912. 4k with 80mbps streams very smooth from my plex ;) and amazon series in 1080p ran very well till mid december ;/

**Comment by Varstahl** [comment]
Yeah, exactly, when they started fiddling with codecs, bandwidth and what have you. Maybe they changed something else, I don't know. If you select manual stream selection in IS.A what is the highest resolution you see, and what is the higher resolution you can play?

**Comment by gint0nic** [comment]
i‘d tested it before, same result, 920x540 or 940x520... something like that.

seems like amazon changed something ... are youusing a specific content provider? akamai or level3 or so?

**Comment by Varstahl** [comment]
> i‘d tested it before, same result, 920x540 or 940x520... something like that.

Seen in the list or playable? If you go in the list of video streams available is there some 720p or 1080p, regardless of if they playback or not? The only fix we made recently was because Amazon blocked several streams from appearing to people, specifically on linux distros. We bypassed that and forced their backend to return proper results, maybe the changed it again.

**Comment by gint0nic** [comment]
it‘s the highest available resolution, not even a sign of 720p or 1080p :( ther‘re a lot streams from 240p to 540p available, but no HD or FHD

**Comment by Varstahl** [comment]
Closing this thread for inactivity. Also, @gint0nic, we inadvertently hijacked the issue, and that's a no-no.

In any case:

> it‘s the highest available resolution

Then that's limited by Amazon, there's nothing I can do. The original discussion is here at #218, however if you feel your hardware's different open a new issue so we can investigate this deeper.
