### ISSUE TITLE
Amazon plugin suddenly play with very low framerate (16fps)

### ISSUE THREAD

**Issue by Steph71** [Sandmann79/xbmc#216]
Hi, 

I am using the Amazon addon since a while an it worked like charm. Then an OS/Kodi update from Corelec (8.95.6) came along and suddenly video is only played with very low framerate (16fps) and audio/video get out of sync.

In thee logfile I see some warnings like:

WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
or
DEBUG: ActiveAE::SyncStream - average error 28.084332, last average error: 873.468805
or 
DEBUG: ActiveAE::SyncStream - average error of -15.104814, start adjusting

But unfortunately tehy do not tell me alot.

Anybody here an Idea what I could try to solve that ?

[01_KODI.log](https://github.com/Sandmann79/xbmc/files/2681594/01_KODI.log)

Best Regards
Steph

**Comment by Steph71** [comment]
short update on that:

I rolled back the version to 8.95.5 (fresh install) but the problem persists … probably it is related to an update of the videwine library, which happend close after the coreelec update …

still any hints appreciated.

Best Regards
Steph

**Comment by Varstahl** [comment]
I'm sorry if I didn't answer earlier but I'm not really familiar with CoreElec, I've only tested LibreElec. In the logs I see quite a few frame skips recurring often, so that means you probably are trying to decode a video which is too large for the processor (maybe lower the resolution?).

As for Widevine, you can probably backup/remove the entire CDM folder `/storage/.kodi/cdm`. That would help reset the CDM if it was tied to the CoreElec distribution.

**Comment by Varstahl** [comment]
Any updates on the issue?

**Comment by Steph71** [comment]
Hi,

I was not on the topic for a while, as I moved my old x86 platform back to the living room. 

However I'd love to get this solved ... actually I can exclude, that the the stream is to heavy for the processor, as it is the same for very small resolutions and processor usage is very liitle .. like 30 % or so ...

Actually I have seen the same effect on my X86 pattform, but it magically disapeared and the plugin plays fine there for weeks now.

But on the amlogic s905 platform I still see the low framerates. Also reinstalling videvine lib did'nt help

**Comment by Varstahl** [comment]
Hmm, but the video decryption (at least) should be processed by the GPU. Not that I'm well versed in embedded, but I found a few of the s905 coupled with Mali gpus. And your machine could also be android based, which would open a new whole can of worms.

I highly doubt we can do anything about it but I'll leave the issue open, in case someone can shed some light on the problem.

**Comment by trosenda** [comment]
Hi,

little different setup :coreelec 8.95.7 on a S912.
I see Sky streaming perfectly fine while Amazon is unwatchable.
Shall I create some logs ? Attach here or open a new issue?

thanks

**Comment by Varstahl** [comment]
If the addon is not the problem I just can't help you guys. Feel free to attach the logs, but if the problem is between CoreElec/Kodi/IS.A/RPi, there's nothing I can do. Every information you need to provide logs, debug mode etc. is in the [FAQ](https://github.com/Sandmann79/xbmc/wiki/FAQ).

**Comment by trosenda** [comment]
I'm not sure where the problem is. Could be the addon as the sky addon is working....could be missing hw-accel because of different codecs....
maybe this gets us closer :  http://ix.io/1xUS

**Comment by Varstahl** [comment]
Nah, it's not the addon: `[swscaler] No accelerated colorspace conversion found from yuv420p to bgra`. As for the other issue, there are a number of things that could go wrong, but as soon as the video plays it's not the addon, and I can't help.

**Comment by Steph71** [comment]
just for the record:

I have documented some new findings here:

- Problem can be fixed by reboot
- Problem is triggered by specific streams

https://discourse.coreelec.org/t/s905x-amazon-vod-addon-broken/2680/4?u=x96core

Best Regards
Stephan
