### ISSUE TITLE
The HD resolutions have disappeared in my nvidia shield tv

### ISSUE THREAD

**Issue by Paco8** [Sandmann79/xbmc#218]
I installed Kodi 18 and the Amazon VOD addon on a nvidia shield a couple of weeks ago. It worked fine, I could play movies and shows up to 1080p. But now suddenly the HD resolutions are gone, I can only play at 384p or 576p. Even the movies and shows that I could previously play at 1080p now play with those low resolutions.

What happened? Is it a bug?

The log:
https://justpaste.it/6l8i3

**Comment by Varstahl** [comment]
FHD for movies never worked, causes unknown, see also #51

720p/1080p only works for tv series.

**Comment by Paco8** [comment]
But how come I could watch a movie in 1080p a few days ago? Now the same movie plays at 384p.
I can't even play tv series in HD, they are at 576p at most (previously 1080p).

If I enable manual streams in the Inputstream preferences, I can see some resolutions but none of them are HD. Previously there were up to 1080p.

I guess maybe amazon changed something and now the plugin can't find the HD streams.

**Comment by Varstahl** [comment]
That's possible, amazon's been doing weird things with various devices, included shield. Changed bitstreams, then removed some formats, God only knows. If you're actually saying that there are entire streams missing, then it's something they're doing on their backends.

**Comment by Jibbonator** [comment]
Hey there,
I've noticed the same Problem on my nvidia ShieldTV. Could this be a Problem due to an Kodiupdate?
All other addons that use inputstream aka Netflix, works fine.

**Comment by Varstahl** [comment]
> Could this be a Problem due to an Kodiupdate?

I tend to believe it's not. Had another user with similar issues on a different device, that were not solved upon rollback. I'm more keen to believe Amazon being Amazon.

> All other addons that use inputstream aka Netflix, works fine.

They use different codec/encryptions, so Kodi working with Netflix usually means nothing when it comes to Amazon.

**Comment by Krzmbrzl** [comment]
I have installed the plugin on a Raspberry Pi 3 (runnung LibreElec) and I also have at most 500-600p resolution. I thought this was due to some different encoding of the higher resolution streams.

I checked the same movies and series on the Amazon FireStick and there they had 1080p resolution. So I'm guessing Amazon is hiding those streams somehow...

**Comment by Paco8** [comment]
It works!!!!
The HD resolutions are back:
https://imgur.com/a/vRjhppV

However I noticed that sometimes the movie freezes at the beginning or plays without video, and I have to restart kodi to fix it.

**Comment by semool** [comment]
@Varstahl 
Thanks you. On Nvidia Shield 1080p Streams are working again.

**Comment by Varstahl** [comment]
Very, very interesting. Will investigate further. Glad it works, closing the issue for the moment.

**Comment by satmandu** [comment]
> It works!!!!
> The HD resolutions are back:
> https://imgur.com/a/vRjhppV
> 
> However I noticed that sometimes the movie freezes at the beginning or plays without video, and I have to restart kodi to fix it.
> 


For what it is worth I noticed a video freeze when playing using google chrome from my kodi box the other day, so the freezes may not be related to the plugin, but just to amazon's servers being overwhelmed by people hooking up new equipment over the holidays.
