### ISSUE TITLE
Crash when using Amzon Prime plugin

### ISSUE THREAD

**Issue by Krzmbrzl** [Sandmann79/xbmc#220]
When using the Amazon plugin intended for germans (so not the VOD-version) I get a crash when trying to put in my login-credentials. I am using this on a Raspberry Pi 3 with LibreElec as my OS.

This is the observed behavior:

1. Download + install the plugin
2. The settings open asking to login
3. Nothing happens after having put in the credentials (User is not logged in afterwards either)
4. Open settings
5. Click on Log In
6. UI changes back to home screen - no login-window appearing

Log: http://ix.io/1wzp

Relevant part (I think):
```
14:51:06.544 T:1499460512  NOTICE: [Amazon] Login
14:51:49.697 T:1558180768  NOTICE: Previous line repeats 1 times.
14:51:49.697 T:1558180768   ERROR: /storage/.kodi/addons/plugin.video.amazon/resources/lib/common.py:470: UserWarning: gzip transfer encoding is experimental!
                                              br.set_handle_gzip(True)
14:51:49.697 T:1558180768  NOTICE: [Amazon] Connect to SignIn Page 5 attempts left
14:51:51.335 T:1558180768  NOTICE: [Amazon] MFA, DCQ or Captcha form
14:51:51.840 T:1558180768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'contents'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon/default.py", line 52, in <module>
                                                modes()
                                              File "/storage/.kodi/addons/plugin.video.amazon/default.py", line 49, in modes
                                                exec 'sitemodule.%s()' % var.args.get('sitemode')
                                              File "<string>", line 1, in <module>
                                              File "/storage/.kodi/addons/plugin.video.amazon/resources/lib/common.py", line 439, in MechanizeLogin
                                                res = LogIn(ask)
                                              File "/storage/.kodi/addons/plugin.video.amazon/resources/lib/common.py", line 506, in LogIn
                                                br = MFACheck(br, email, soup)
                                              File "/storage/.kodi/addons/plugin.video.amazon/resources/lib/common.py", line 713, in MFACheck
                                                msg = soup.find('div', attrs={'class': 'a-row a-spacing-micro cvf-widget-input-code-label'}).contents[0].strip()
                                            AttributeError: 'NoneType' object has no attribute 'contents'
                                            -->End of Python script error report<--
```
It crashes exactly [here](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon/resources/lib/common.py#L713)

**Comment by Sandmann79** [comment]
The addon crashes at some user verification step at login.

Please enable verbose logging at miscellaneous settings.
Login again. 
After that you'll be find amazon-login.log located at /storage/.kodi/temp.
This file contains the login html response, so you have to remove your username/email from it.
Upload it somewhere.

**Comment by leppa** [comment]
I have exactly the same issue. It looks like Amazon is asking for CAPTCHA. Here's my [Amazon-login.log](https://olse.me/wLW).

**Comment by Krzmbrzl** [comment]
I loaded the HTML and viewed it in the browser. That's what it looks like:
![amazonlogin](https://user-images.githubusercontent.com/12751591/50538334-35e4b580-0b6e-11e9-9ed7-4d77f936c316.png)

I want to try it out on my machine as well in order to confirm this but I assume that it will be the same (in fact I'd be very suprised if not)...

**Comment by Krzmbrzl** [comment]
Okay I just tested it on my Raspberry and I am getting the same captcha-problem (as expected) which indicates that it is indeed the root of this crash.

Log: [Amazon-login.log](https://github.com/Sandmann79/xbmc/files/2716514/Amazon-login.log)
And this is the rendered page:
![amazonlogin](https://user-images.githubusercontent.com/12751591/50540002-0f347800-0b8a-11e9-8bb3-7ed25fdd4fd1.png)

**Comment by Varstahl** [comment]
I took a look at the problem, and I initially didn't see any problem with it, 'cause I was looking at Amazon VOD code (d'oh!). At a second glance at the proper code, it's easy enough to see that the Amazon addon is missing some of the Captcha features that @Sandmann79 implemented inside Amazon VOD.

I can try to patch it and make it work if you want, but I can't test it, so I'd need your help.

**Comment by Krzmbrzl** [comment]
Sure - I can be your guinea pig :)

Though I realised that I can't use my RPi for streaming anyways (not powerful enough to decode HD Streams). So I personally don't need that fix anymore.
If you still want to patch the code I'd be happy to help :+1:

**Comment by Varstahl** [comment]
You can find the (hopefully) fixed version of [`common.py` right here](https://github.com/Varstahl/xbmc/blob/d1551bf2940b555c14011363996fc3b480362c3e/plugin.video.amazon/resources/lib/common.py). With it you can overwrite `/storage/.kodi/addons/plugin.video.amazon/resources/lib/common.py`.

Everything should work fine. _Should_, being the keyword :D

**Comment by Krzmbrzl** [comment]
> Strange, reportedly heard people streaming 1080p with RPis. Guess it might depend on the version.
Dunno - for me it stutters and according to what I found online the RPi isn't powerful enough to decode widevine 1920x1080p streams as it can't use hardware acceleration for it...

The provided file doesn't seem to fix the error. I still have the same result. Here's the log: http://ix.io/1xva

I can't find the previous error in the log though so at least _something_ changed :)

I guess this is the relevant part:
```
16:56:08.079 T:1707008880  NOTICE: [Amazon] AmazonDB: Service Start
16:56:08.348 T:1707008880  NOTICE: [Amazon] AmazonDB: Starting DBUpdate (1970-01-01 00:00:00 / 2019-01-04 16:56:08.305875)
16:56:09.444 T:1715401584  NOTICE: [Amazon] Args: {'sitemode': 'updateAll', 'mode': 'appfeed'}
16:56:09.622 T:1715401584  NOTICE: [Amazon] Login
16:56:29.322 T:1571148656   ERROR: GetDirectory - Error getting
16:56:30.401 T:1562755952   ERROR: Previous line repeats 6 times.
16:56:30.401 T:1562755952  NOTICE: [Amazon] Args: {}
16:56:30.605 T:1562755952  NOTICE: [Amazon] Version: 2.0.0
16:56:30.605 T:1562755952  NOTICE: [Amazon] Unicode filename support: False
16:56:35.890 T:1562755952  NOTICE: [Amazon] Login
16:57:00.503 T:1937181072   ERROR: Window Translator: Can't find window videolibrary
16:57:00.504 T:1937181072 WARNING: Label Formating: $VAR[GlobalFanartVar] is not defined
16:57:00.562 T:1937181072   ERROR: Control 1000 in window 13001 has been asked to focus, but it can't
16:57:00.565 T:1937181072 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
16:57:00.565 T:1937181072  NOTICE: LoadJpeg: unable to load /usr/share/kodi/addons/service.libreelec.settings/resources/skins/Default/media/default/bg.jpg
16:57:03.505 T:1937181072   ERROR: Control 1200 in window 13001 has been asked to focus, but it can't
16:57:08.349 T:1707008880  NOTICE: [Amazon] AmazonDB: Starting DBUpdate (1970-01-01 00:00:00 / 2019-01-04 16:57:08.347905)
16:57:09.530 T:1549792112  NOTICE: [Amazon] Args: {'sitemode': 'updateAll', 'mode': 'appfeed'}
16:57:09.672 T:1549792112  NOTICE: [Amazon] Login
```

**Comment by Varstahl** [comment]
I don't see anything wrong with the logs, other that the fact that the RPi got broken again

```
NOTICE: LoadJpeg: unable to load /usr/share/kodi/addons/service.libreelec.settings/resources/skins/Default/media/default/bg.jpg
```

Can you maybe enable debug logs and see if it's doing something? In theory it's updating the DB so it should be working correctly, although I only develop for Amazon VOD, so I have no idea how it's supposed to behave.

If it's asking for the captcha during login, then I guess that's fixed. @leppa could you maybe test it too?

**Comment by leppa** [comment]
@Varstahl, I've commented on your pull request: it works when I change `_Captcha` back to `Captcha` on line 136. Else, I'm getting "NameError: global name 'Captcha' is not defined" error.

**Comment by Varstahl** [comment]
:O must have typo'd, thanks for the notification
