### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by dryerflyer** [Sandmann79/xbmc#222]
I didn't see one specified anywhere and didn't know if that was intentional or not.

https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by Sandmann79** [comment]
Every addon has its own license, you can find it inside addon.xml.
But you're right the whole project has no license.

Changing this soon.

**Comment by Varstahl** [comment]
Btw, if you want to just include a common license (like addon's GPL2), you can do it [straight from GitHub](https://github.com/Sandmann79/xbmc/community/license/new?branch=master), without the need to create files manually.

**Comment by Sandmann79** [comment]
It's done with 2852eb1a294dc0de0109a0b7dda2c90b1757e5b5
