### ISSUE TITLE
Spurious timeouts on server error

### ISSUE THREAD

**Issue by ebswift** [Sandmann79/xbmc#228]
V0.6.3
Win10
Kodi 18.0 RC3

Paging is completely ignored on both my Win10 machines.  The result is that everything tries to get loaded at once for the menu you click on, for example a movie genre.  This takes a long time and often times out causing the list to end up being unplayable because of missing information.  Page size was set at the default 40 but ultimately it is loading up a single page of potentially hundreds of items.

I see others have this working, could it be that Amazon is ignoring NumberOfResults in the URL call in the AU region perhaps?   This is the only real clue I could find reading amazontld.py though could be barking up the wrong tree:

url = '%s&NumberOfResults=%s&StartIndex=%s&Detailed=T&mobileClient=true' % (url, ResPage, (page - 1) * ResPage)

**Comment by Varstahl** [comment]
If you're using PrimeVideo then yes, I completely ignore paging. The first time you're scraping the catalog it takes an enormous amount of time, but it shouldn't time out at all. It is an annoyance at times, but it's absolutely temporary, from the second time you load the same section it will load much, much faster.

I had to make a decision when managing those kind of things, either do it the Amazon way, getting results   in a semi random way, or get _everything_ and sort it out properly. My method offers the benefit especially when it comes to TV series, when instead of going through 3, 10, or 40 pages of results to check, when you step into a series you always have all the available ones right there.

So this begs the question: are you concerned about loading times, or about having less results in every page?

**Comment by ebswift** [comment]
Thanks for the reply, I can understand your approach there, I wasn't sure whether this was just an issue at my end.  As for your question, if I enter a movie genre that has many videos then I get too many requests errors which corrupts the cached data so a no matching key error occurs if I try to play one of these titles.

https://paste.kodi.tv/ifuxihapuk.kodi

Sometimes a longer list will load, but most often it will ultimately fail with too many requests.

**Comment by Varstahl** [comment]
Nah, it's okay, I can just re-title. I see how that can be a problem, although at the moment I can't quite picture a solution. Could you do a test for me? Just close Kodi, delete the `%AppData%\Kodi\userdata\addon_data\plugin.video.amazon-test\PVCatalog*.pvcp`, then reload Kodi and go back following the same path you did previously. Does all content load properly, the second time? (Don't worry, the second pass should be a lot faster, most of the data should be already stored in the *.pvdp)

**Comment by ebswift** [comment]
Righto, I tried a few times, before the final attempt I left it for 4-5 hours to see if the attempts might reset but it didn't work.  All subsequent attempts were much faster, though it did fail at exactly the same spot each time.  For this test I used Movies->Comedy which seems to have a lot of titles under it.

```
15:01:02.087 T:2856  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/search/ref=atv_sr_pg_46?phrase&query=av_offered_in_territory%3DAU%26index%3Dfe-amazon-video%26p_n_entity_type%3DMovie%26adult-product%3D0%26search-alias%3Dinstant-video%26bq%3D%28and%20sort:%27featured-rank%27%20%28and%20av_primary_genre:%27av_genre_comedy%27%20%28not%20av_secondary_genre:%27av_subgenre_international_india%27%29%29%29&from=900&ie=UTF8
15:01:03.002 T:2856  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/detail/0JP2CG751OBOP1EDL53GKMC36M/ref=sr_hom_c_unkc_1_10?sr=1-910&qid=1546146062
15:01:03.545 T:2856  NOTICE: [Amazon VOD] Error 404
15:01:03.546 T:2856   ERROR: [Amazon VOD] Error reason: 429 (HTTPError)
15:01:13.547 T:2856  NOTICE: [Amazon VOD] Attempt #2. Too many requests - Pause 10 sec

```
I think although the data is cached it might still be touching the Amazon URL which adds to the request count.  Maybe a workaround could be if the request count reset time can be established then the 10 second wait could be increased to that and the loop can continue on from where it left off from rather than trying to start again on subsequent attempts.

**Comment by Varstahl** [comment]
What you mean at the same point? The second attempt should have 2 or 3 times less queries than the first, if it fails, so it should absolutely not stop there. Also, that's a 404 not found right there. Something's fishy.

Can you open [this url](https://www.primevideo.com/detail/0JP2CG751OBOP1EDL53GKMC36M/) fine from a browser?

I was checking the code and I think the 429 is spurious, injected just to keep retrying. But a 404 can't really give a different output. Can you confirm that url doesn't work for you?

**Comment by ebswift** [comment]
By at the same point I mean that same line just before the 404 is the same URL each time.  The URL link does come up with a "it's not here" on Amazon so that would be the cause of the 404.  Let me know if there's anything else I can try for you.

**Comment by Varstahl** [comment]
The problems should be fixed, but I need you to do a test for me: replace the `network.py` and `primevideo.py` in your installation with the files you find [here](https://github.com/Varstahl/xbmc/tree/df076bf5cc699ee9ec941ba7c39abd1776a79783/plugin.video.amazon-test/resources/lib), and report back if everything works.

You'll probably see a couple error notifications every time you'll update the catalog list (until amazon fixes their servers), but everything else should work correctly.

**Comment by ebswift** [comment]
I replaced the files, deleted the vcp and proceeded to the same movies->comedy path.  The error flashed up, this time it kept going until completion.  I checked the log and it's the same URL it failed on last time (before continuing successfully):

```
08:04:18.969 T:21432  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/detail/0JP2CG751OBOP1EDL53GKMC36M/ref=sr_hom_c_unkc_1_6?sr=1-746&qid=1546293854
08:04:19.574 T:21432   ERROR: [Amazon VOD] Error reason: 404 error (NoRetries)
08:04:19.574 T:21432   ERROR: [Amazon VOD] Unable to fetch the url: https://www.primevideo.com/detail/0JP2CG751OBOP1EDL53GKMC36M/ref=sr_hom_c_unkc_1_6?sr=1-746&qid=1546293854
08:04:19.581 T:21432  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/detail/0HSUXSQQIKTPEKVFVNGO9HP4N4/ref=sr_hom_c_unkc_1_12?sr=1-752&qid=1546293854
```

The only other observations is that even newer movies don't have a 1080p stream option, the ones I sampled were pretty low quality (this is probably from the Amazon end).  TV shows do play in 1080p.  Also, the odd movie shows as a folder, for example Movies->Comedy->Classic All-Star Commercials.

So the fix is clearly working, thank you and have a happy new year!

**Comment by Varstahl** [comment]
> even newer movies don't have a 1080p stream option

Due to some DRM problems, movies with a horizontal resolution greater than 1440 pixels don't work. There's some light investigation on the problem, including trying to bring 4k to the platform, but it's going nowhere yet.

> Also, the odd movie shows as a folder

Mea culpa, I forgot to remove the problematic item from the catalog. Will fix it before pushing the update, thanks for the report.

> thank you and have a happy new year!

You too :)

**Comment by Varstahl** [comment]
Can I ask you to send me your .pvcp after you loaded the section with the movie that doesn't work? I can't address it the way I originally anticipated, so I may find another way if I take a look at the problem with your catalog data. You can attach it in a reply to this issue.

**Comment by Varstahl** [comment]
I might also need your .pvdp if you don't mind.

**Comment by ebswift** [comment]
I've attached the files, which should include pretty much all activity since I ran troubleshooting with the add-on.  If you like I can wipe everything and run from scratch on the folder of your choosing.

[plugin.video.amazon-test.zip](https://github.com/Sandmann79/xbmc/files/2723388/plugin.video.amazon-test.zip)

**Comment by Varstahl** [comment]
Nah, as long as there's the problematic part it should be ok, I'll take a look at it shortly.

**Comment by Varstahl** [comment]
Thank you so much, your feedback has been very useful. Every problem should now be fixed, and will go public asap.
