### ISSUE TITLE
Script for chromium

### ISSUE THREAD

**Issue by xxcuratorxx** [Sandmann79/xbmc#23]
Hi,

due to some problems with the DRM of prime, I was trying to use the add in and show the video in the chromium browser. 

So watching videos is possible and the usage of the add in is working to.

But now I need a script to open chromium from the addin.

My script passes only the file {u} and starts chromium like
chromium-browser $1

The problem is, Kodi is not running in a X Window, so chromium cannot start. When connected via VNC, however, chromium is started on the VNC Window and is not visible on the TV (where kodi is shown)

Any ideas, how to overcome this?

**Comment by zioalex** [comment]
You can try to run the browser in docker as outlined here:
https://forum.libreelec.tv/thread-234-page-2.html

https://github.com/awiouy/chromium-elec

I tried to run chromium and worked but I don't know if you can use Amazon
Video with it.

Cheers
Alessandro

**Comment by Sandmann79** [comment]
@xxcuratorxx is the problem still present? Or works the solution provided by @zioalex?

**Comment by Sandmann79** [comment]
Due a lack of feedback, i close this issue.
If the problem persists, just reopen it.
