### ISSUE TITLE
Amazon credentials

### ISSUE THREAD

**Issue by spaniardguy** [Sandmann79/xbmc#232]
Is completely secure adding Amazon credentials to this add-on? Sorry to ask, just trying to stay on the safe side.

**Comment by Varstahl** [comment]
As safe as any other uncompromised endpoint. Unless you specifically choose to store your credentials, once logged in they're forgotten and only the session cookies are set, just like any browser. If your machine _is_ compromised, then the addon is just as vulnerable as any other browser or application.

If you want to check yourself, here's the [`LogIn`](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/resources/lib/network.py#L286) segment of the code, where user/pass are asked and used.

**Comment by spaniardguy** [comment]
Thanks for your quick and good response. I do not have deep knowledge on this topic but the code has been useful. I was worried because Amazon credentials are sensible information but the code is neat :)

**Comment by Varstahl** [comment]
Closing this as the relevant information are now inside the [FAQ](https://github.com/Sandmann79/xbmc/wiki/FAQ#can-i-trust-this-addon-with-the-amazon-credentials).

Also, as a side note, thanks for raising the issue in the first place, transparency is always preferable to security through obscurity :)
