### ISSUE TITLE
Some movies takes forever to play and then only play for a few seconds

### ISSUE THREAD

**Issue by Paco8** [Sandmann79/xbmc#234]
I noticed that I couldn't play certain movies, the movies take a lot of time to begin to play, and when they finally do they play for a few seconds and then freeze.

After trying several options I think I found a way to fix it: in the addon preferences I changed the preferred host from auto to akamai. According to the kodi log, the Amazon VOD addon is using the Level3 host for this movie when the option is set to auto. I guess maybe that server is very slow.

If someone else is having this problem, you can try to change that setting.

**Comment by Varstahl** [comment]
The addon chooses nothing, CDNs are usually selected randomly, round robin, or judging by the lowest ping. Different videos have also different CDN priorities, so depending on the movie IS.A might pick up the first from the list, which might differ from movie to movie.

But yeah, there is the option to pre-select the CDN you'd like your content to be served from, so you can select it. Note though that sometimes, regardless of which CDN you selected, some videos might still get choppy. I usually stop the video and restart the playback, and (again, _usually_) IS.A picks another CDN from the list and the problem goes away.

**Comment by Varstahl** [comment]
Closing this as the relevant information are now inside the [FAQ](https://github.com/Sandmann79/xbmc/wiki/FAQ#my-video-is-buffering-a-lot--my-video-takes-a-long-time-to-start-playback-and-interrupts-every-few-seconds).
