### ISSUE TITLE
Not all season folders showing up

### ISSUE THREAD

**Issue by JohnnyPicnic** [Sandmann79/xbmc#238]
In particular for "The Man In The High Castle" only season 1 is showing. It is in my watchlist so i'm not sure if that is causing an issue.

**Comment by JohnnyPicnic** [comment]
So I removed the shows I had in my watchlist, deleted the two cache files in addon data and now all season folders are showing up.

**Comment by Varstahl** [comment]
Depending on when/how it was scanned, it's possible that only the first season was valid, so the second is hidden. I've since added the refresh function, so it should be possible, from the list of TV series, to hit refresh on a selected show and repopulate the series with both seasons.
