### ISSUE TITLE
Add support for india

### ISSUE THREAD

**Issue by vinodsr** [Sandmann79/xbmc#24]
As amazon prime is available in India. Please add support. Thanks

**Comment by vasundhar** [comment]
Content as such is not dependent on the country,
primevideo.com remains same for India or USA.

**Comment by Sandmann79** [comment]
@vasundhar Can you access your watchlist or library?

**Comment by ninjagoat** [comment]
@Sandmann79 ok so I was able to sign in by selecting USA.
Can access library. But not watchlist.
Also, unable to play anything from the library. It just says not available in your country. I even tried to play the ones which are actually listed on primevideo.com (when accessed from here) but no luck.
(None of the local Indian content available either)

Let me know if you need any more information

**Comment by ninjagoat** [comment]
@vasundhar you said that the content is not dependent on the country. But were you able to access Indian videos by signing in through US? Nothing came up in search when I did.

**Comment by Sandmann79** [comment]
Same as #22. Please comment on this issue.

**Comment by bhatsu** [comment]
can @vasundhar @ninjagoat @vinodsr you guys confirm that it is now working in India. When I try to use it on my raspberry pi, I get this. 
**Login Error: 
Captcha Request, please change IP or try again later**

Also I am not able to see India in the country list.

**Comment by vasundhar** [comment]
No It is not working, I think I will find some time and see where it is pointing. 
Even with the InputStream, it is listing some programs but not Indian.
