### ISSUE TITLE
Retain watched status / resume position

### ISSUE THREAD

**Issue by bdominguez** [Sandmann79/xbmc#241]
It doesn't seem to mark as watched a video when you have watched it  I mean in the Android app for example the green circle is not there.

**Comment by bdominguez** [comment]
1. Leia RC1. I haven't changed anything theme related, it has the default one.
2. Amazon VOD.
3. Latest version (I have with auto update).

I use it in a Raspberry Pi 3b+

My "mark as watched" problem occurs in the two environments:
1. In Kodi if I close it and open it again it loses the "ticks" that determines if it's already watched or not.
2. In Amazon Prime Video app in Android it doesn't mark the video as watched neither as I said.

**Comment by Varstahl** [comment]
Sorry for the late reply. I don't have an android Kodi available, but I can't reproduce the issue you're describing.

In Kodi I start to play a video, I go to the end, I let it complete (watched status has always been a bit finicky with Kodi), and after I see the video being "ticked", I close everything, delete the *.pvcp, re-obtain the catalog from online resources, and the tick is still there.

If you go from two different paths though, that doesn't work (for example, `TV Series > Anime > Episode` and `Watchlist > Anime > Episode` are treated as different). If this is your problem, there is currently no solution, a fix is planned but not implemented yet.

I'll leave this open as a reminder for the enhancement, if you have further trouble feel free to reply.

**Comment by bdominguez** [comment]
Regarding Kodi yes, you are right that my problem was with two different paths.

Regarding Amazon I still have the same problem, it seems that it isn't aware of the episode "being watched" because in the official website or app I don't see that being correctly marked as watched.

**Comment by Varstahl** [comment]
As far as I know, there are a few signals that helps Amazon update the series with the next episode in line. For example if you watch via browser an episode, if you refresh the season page the default play button will indicate that it would start as the next episode.

I'm not sure if there's a way for cross compatibility in that manner. I don't know/remember if Amazon keeps track of the watchcount, so to speak, so each installation will act differently, except for the "keep watching" and the like.

As for the single Kodi installation, something can be done but not yet scheduled. For multiple Kodi installations, you could probably use a syncher across multiple platforms.
