### ISSUE TITLE
new error since today (raspbian stretch)

### ISSUE THREAD

**Issue by janvangent** [Sandmann79/xbmc#242]
The past days/weeks the plugin worked great on my RPi 3 running raspbian stretch.
However, since of today I'm getting this error.
Any ideas?

`14:01:15.481 T:1780892400  NOTICE: Running database version MyMusic72
14:01:15.581 T:1780892400  NOTICE: Running database version MyVideos113
14:01:15.598 T:1780892400  NOTICE: Running database version TV32
14:01:15.609 T:1780892400  NOTICE: Running database version Epg12
14:01:15.610 T:1900002960  NOTICE: start dvd mediatype detection
14:01:15.821 T:1900002960  NOTICE:   load skin from: /usr/share/kodi/addons/skin.estuary (version: 2.0.17)
14:01:18.370 T:1900002960 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
14:01:18.508 T:1900002960  NOTICE: Register - new keyboard device registered on application->keyboard: Toetsenbord (0000:0000)
14:01:18.563 T:1900002960  NOTICE: Register - new mouse device registered on application->mouse: Muis (0000:0000)
14:01:18.576 T:1900002960  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
14:01:18.580 T:1900002960  NOTICE: Loaded playercorefactory configuration
14:01:18.581 T:1900002960  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
14:01:18.581 T:1900002960  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
14:01:18.642 T:1900002960  NOTICE: initialize done
14:01:18.642 T:1900002960  NOTICE: Running the application...
14:01:18.658 T:1900002960  NOTICE: starting zeroconf publishing
14:01:18.666 T:1659892464  NOTICE: ES: Starting UDP Event server on port 9777
14:01:18.668 T:1659892464  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
14:01:18.696 T:1900002960  NOTICE: VideoPlayer::OpenFile: /var/run/lirc/lircd
14:01:18.698 T:1623192304  NOTICE: Creating InputStream
14:01:18.702 T:1623192304   ERROR: CVideoPlayer::OpenInputStream - error opening [/var/run/lirc/lircd]
14:01:18.702 T:1623192304  NOTICE: CVideoPlayer::OnExit()
14:01:18.819 T:1729094384  NOTICE: Register - new cec device registered on cec->RPI: CEC Adapter (2708:1001)
14:01:19.484 T:1900002960  NOTICE: CVideoPlayer::CloseFile()
14:01:19.484 T:1900002960  NOTICE: VideoPlayer: waiting for threads to exit
14:01:19.484 T:1900002960  NOTICE: VideoPlayer: finished waiting
14:01:19.558 T:1900002960 WARNING: OnMessage: Suspiciously long time to handle GUI_MSG_PLAYBACK_STARTED (0.28s)
14:01:21.482 T:1676669680  NOTICE: [Amazon VOD] Service: Start
14:01:21.498 T:1676669680  NOTICE: [Amazon VOD] Service: End
14:01:21.543 T:1676669680 WARNING: CPythonInvoker(2, /home/pi/.kodi/addons/plugin.video.amazon-test/service.py): the python script "/home/pi/.kodi/addons/plugin.video.amazon-test/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE
14:02:23.044 T:1763500784   ERROR: GetDirectory - Error getting
14:02:27.333 T:1595929328   ERROR: Previous line repeats 6 times.
14:02:27.333 T:1595929328   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.EOFError'>
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/pi/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 48, in EntryPoint
                                                loadUser('atvurl', cachedUsers=users), loadUser('pv', cachedUsers=users))
                                              File "/home/pi/.kodi/addons/plugin.video.amazon-test/resources/lib/common.py", line 120, in InitialiseProvider
                                                self._globals['pv'] = PrimeVideo(self, Settings())
                                              File "/home/pi/.kodi/addons/plugin.video.amazon-test/resources/lib/singleton.py", line 14, in __call__
                                                cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 95, in __init__
                                                self._LoadCache()
                                              File "/home/pi/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 120, in _LoadCache
                                                cached = pickle.load(fp)

 File "/usr/lib/python2.7/pickle.py", line 1384, in load
                                                return Unpickler(file).load()
                                              File "/usr/lib/python2.7/pickle.py", line 864, in load
                                                dispatch[key](self)
                                              File "/usr/lib/python2.7/pickle.py", line 886, in load_eof
                                                raise EOFError
                                            EOFError
                                            -->End of Python script error report<--
14:02:27.415 T:1595929328 WARNING: CPythonInvoker(3, /home/pi/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/pi/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
14:02:27.422 T:1676669680   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/
14:02:27.423 T:1900002960   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/) failed
14:02:50.745 T:1900002960  NOTICE: stop player
14:02:50.746 T:1900002960  NOTICE: Storing total System Uptime
14:02:50.746 T:1900002960  NOTICE: Saving settings
14:02:50.764 T:1900002960  NOTICE: Saving skin settings
14:02:50.768 T:1900002960  NOTICE: stop all
14:02:50.770 T:1900002960  NOTICE: ES: Stopping event server
14:02:50.770 T:1900002960  NOTICE: stopping zeroconf publishing
14:02:51.085 T:1659892464  NOTICE: ES: UDP Event server stopped
14:02:51.085 T:1900002960  NOTICE: stop dvd detect media
14:02:51.155 T:1900002960  NOTICE: stopped
14:02:51.355 T:1900002960  NOTICE: destroy
14:02:51.824 T:1900002960  NOTICE: unload skin
14:02:51.964 T:1900002960  NOTICE: unload sections
14:02:52.200 T:1900002960  NOTICE: application stopped...`

**Comment by Varstahl** [comment]
It seems that the `PVCatalog*.pvcp` got corrupted while being saved to disk last time, maybe due to a power loss. It's no big deal, you can remove it manually [following the FAQ](https://github.com/Sandmann79/xbmc/wiki/FAQ#where-are-kodis-logs--where-are-the-addons-cache-files), and it should regenerate itself quickly.
