### ISSUE TITLE
Amazon prime Video not playiing due to defaults.py error

### ISSUE THREAD

**Issue by senorping** [Sandmann79/xbmc#245]
Dear Contributors,

I still have an issue with german Add-On of Prime Video! I tried manually updating the shared library object. Literally, I tried every proposed solution I found here. So far everything didn't work. However, I attached the full log file to this comment. I am not sure whether this is the right thread. However, when I search for "Amazon" in the log file, it points out that there are errors after calling a function in defaults.py
Help is much appreciated. If it's the wrong thread, plase point me to right one.

Sicerly Hannes aka senorping

16:00:07.739 T:1511265024 NOTICE: [Amazon] ASINS to Remove: [u'B077XNS6X5,B077XL2DPN,B077XPV2L4,B078CY5RG2']
16:00:17.662 T:1511265024 NOTICE: [Amazon] TV Shows Update:
4 Shows added
5 Seasons added, 1 Removed
100 Episodes added, 19 Removed
16:01:55.854 T:1511265024 NOTICE: [Amazon] getURL: https://www.amazon.de/gp/video/video-library/tv/?ie=UTF8&sort=DATE_ADDED_DESC
16:01:56.759 T:1511265024 NOTICE: [Amazon] ASINS to Remove: [u'B01M0K6K7P,B01LXB2T9R,B01M1751KJ,B01M0VJHXJ', u'B00ERNKF2O,B00ERNKFVA,B00ERNKG1O,B00ERNKG4Q', u'B0791LPNPP,B0791L3HXY,B0791LP6JR,B0791LVMJY', u'B0791L42RP,B0791LGKD4,B0791M92W6,B0791M9CGJ', u'B00ERL7NHG,B00ERL7O9S,B00ERL7P9C,B00ERL7Q32']
16:02:01.409 T:1511265024 NOTICE: [Amazon] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=34a47c216cfc53d398feaabce7089abfb6073d22b9735568e1786440&format=json&StartIndex=0&NumberOfResults=140&ContentType=TVEpisode&RollUpToSeason=T&OrderBy=Title&SeasonASIN=B0776TXQTC,&IncludeBlackList=T&HideNum=T&AID=1&IncludeNonWeb=T&IncludeAll=T&version=2
16:02:02.088 T:1511265024 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.IndexError'>
Error Contents: list index out of range
Traceback (most recent call last):
File "/home/osmc/.kodi/addons/plugin.video.amazon/default.py", line 52, in 
modes()
File "/home/osmc/.kodi/addons/plugin.video.amazon/default.py", line 49, in modes
exec 'sitemodule.%s()' % var.args.get('sitemode')
File "", line 1, in 
File "/home/osmc/.kodi/addons/plugin.video.amazon/resources/lib/appfeed.py", line 352, in updateAll
tvresult = tv.addTVdb(False, cj=cj)
File "/home/osmc/.kodi/addons/plugin.video.amazon/resources/lib/tv.py", line 420, in addTVdb
addTVdb(False, 'full', cj)
File "/home/osmc/.kodi/addons/plugin.video.amazon/resources/lib/tv.py", line 352, in addTVdb
season_size = int(title['childTitles'][0]['size'])
IndexError: list index out of range
-->End of Python script error report<--
16:11:21.891 T:1528296192 NOTICE: ES: Client from ::ffff:192.168.178.28 timed out
16:15:26.394 T:1925843456 ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://freidis-macbook.fritz.box/'
unix_err:'1' error : 'Operation not permitted'
16:15:28.840 T:1925843456 ERROR: GetDirectory - Error getting smb://freidis-macbook.fritz.box/
16:15:42.115 T:1486099200 ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://freidis-macbook.fritz.box/'
unix_err:'1' error : 'Operation not permitted'
16:15:43.588 T:1925843456 ERROR: GetDirectory - Error getting smb://freidis-macbook.fritz.box/
16:15:43.588 T:1925843456 ERROR: CGUIDialogFileBrowser::GetDirectory(smb://freidis-macbook.fritz.box/) failed
16:16:03.503 T:1486099200 ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://FREIDIS-MACBOOK/'
unix_err:'1' error : 'Operation not permitted'
16:16:05.744 T:1925843456 ERROR: GetDirectory - Error getting smb://FREIDIS-MACBOOK/
16:16:05.744 T:1925843456 ERROR: CGUIDialogFileBrowser::GetDirectory(smb://FREIDIS-MACBOOK/) failed
16:16:55.113 T:1486099200 ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://FREIDIS-MACBOOK/'
unix_err:'1' error : 'Operation not permitted'
16:16:57.078 T:1925843456 ERROR: GetDirectory - Error getting smb://FREIDIS-MACBOOK/
16:16:57.078 T:1925843456 ERROR: CGUIDialogFileBrowser::GetDirectory(smb://FREIDIS-MACBOOK/) failed
16:18:20.966 T:1925843456 ERROR: Control 18 in window 10129 has been asked to focus, but it can't
16:19:46.285 T:1905259264 ERROR: GetDirectory - Error getting
16:19:49.729 T:1696854784 ERROR: Previous line repeats 6 times.
16:19:49.729 T:1696854784 NOTICE: [Amazon] Args: {}
16:19:49.936 T:1696854784 NOTICE: [Amazon] Version: 2.0.1
16:19:49.936 T:1696854784 NOTICE: [Amazon] Unicode filename support: False
16:19:56.642 T:1477710592 NOTICE: [Amazon] Args: {'url': 'watchlist', 'page': '1', 'sitemode': 'ListMenu', 'mode': 'appfeed', 'name': 'Watchlist'}
16:20:02.117 T:1469321984 NOTICE: [Amazon] Args: {'url': '/gp/video/watchlist/movie/', 'page': '1', 'sitemode': 'ListCont', 'mode': 'appfeed', 'name': 'Movies'}
16:20:03.297 T:1469321984 NOTICE: [Amazon] getURL: https://www.amazon.de/gp/video/watchlist/movie/?ie=UTF8&sort=DATE_ADDED_DESC
16:20:07.180 T:1494487808 ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://s3.amazonaws.com/sgp-catalog-images/region_DE/tobis-tobis0050201-Full-Image_GalleryBackground-de-DE-1472678653453._V1_.jpg
16:20:10.989 T:1469321984 NOTICE: [Amazon] Args: {'asin': 'B00FYUJN9U', 'sitemode': 'PLAYVIDEO', 'name': 'Robin Hood', 'mode': 'play', 'trailer': '0', 'adult': '0'}
16:20:33.979 T:1469321984 NOTICE: [Amazon] No Inputstream Addon found or activated
16:20:34.178 T:1925843456 ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.amazon/?asin=B00FYUJN9U&sitemode=PLAYVIDEO&mode=play&adult=0&name=Robin+Hood&trailer=0]
16:20:51.217 T:1925843456 NOTICE: stop all
[Logs2019-01-27.txt](https://github.com/Sandmann79/xbmc/files/2800249/Logs2019-01-27.txt)

**Comment by Varstahl** [comment]
I'm sorry for the long time without an answer, but the dev responsible for that addon is currently inactive.

As far as I can see, there are both problems with a Show having no seasons — `int(title['childTitles'][0]['size'])` IndexError: list index out of range — and with unavailable content — 403 on the requested image —. Something's wrong alright, but I'm afraid I can't help you with this.

**Comment by Varstahl** [comment]
Could/should be fixed with the new version we just released, closing this.
