### ISSUE TITLE
Correct Icons and and Fanart 

### ISSUE THREAD

**Issue by ians325** [Sandmann79/xbmc#246]
![next](https://user-images.githubusercontent.com/5463802/51941861-82414080-240d-11e9-8e90-a762371dca66.png)
![home](https://user-images.githubusercontent.com/5463802/51941874-88cfb800-240d-11e9-8017-fce8a707c7d2.png)
![icon](https://user-images.githubusercontent.com/5463802/51941885-8d946c00-240d-11e9-9018-70cf74675622.png)
![fanart](https://user-images.githubusercontent.com/5463802/51941892-91c08980-240d-11e9-88b0-05a521343cab.jpg)

**Comment by Varstahl** [comment]
Thanks for the thought, although most of them aren't applicable to the addon. Also, isn't the play icon optically skewed towards the left?
