### ISSUE TITLE
New TV episodes and Watchlist not updating

### ISSUE THREAD

**Issue by mattiep12** [Sandmann79/xbmc#250]
Addon version 0.6.6
LibreELEC-Generic x86_64 9.0-Milhouse 20190129212017-0129
Kodi Leia 18.1-RC1

When new episodes are released into TV show seasons, the addon is not updating the list.

I disabled and enabled the addon, rebooted, searched specifically for the episode name and other tricks to trigger a cache refresh, but I am still not seeing new episodes.

**Comment by Varstahl** [comment]
Go into the TV show, select the season and hit "Refresh".

**Comment by mattiep12** [comment]
Forgive a possibly silly question, but where is the refresh option? I can't see it in the context menu, nor in the options menu (when I hit 'left' on the remote).  I have a Kodi remote app on my phone and searching through the functions, I can't find a 'refresh' call available for me to assign to a key either.

**Comment by Varstahl** [comment]
It should be in the context menu. It doesn't apply to every item, I don't remember off the top of my head if it can be used from the show name, or the season number, but it definitely should be there.

**Comment by ezu64** [comment]
I've the same problem. I've solved with uninstall and reinstall addon. Now I try refresh option

**Comment by mattiep12** [comment]
Interesting, because I've looked at everything from the category level, down through, show and season and there's definitely not a refresh option.

I'm going away for work for a week now. Maybe I'll try this again when I get back.

**Comment by ezu64** [comment]
I did not find the refresh option in any category or level . If I uninstalling and erasing all settings and I reinstall addon It can update new season and other category JUST ONCE

**Comment by Varstahl** [comment]
> Interesting, because I've looked at everything from the category level, down through show and season and there's definitely not a refresh option.

That sounds like a problem alright, I'll have to look into it if that's the case. I'm a bit behind schedule 'cause I'm in the middle of an office relocation, I'll try to look into it as soon as I can.

> I've the same problem. I've solved with uninstalling and reinstalling addon. Now I try refresh option.

That is not necessary. If the refresh option isn't working anymore you can just delete the *.pvcp file, [explained in the FAQ](https://github.com/Sandmann79/xbmc/wiki/FAQ#where-are-kodis-logs--where-are-the-addons-cache-files).

**Comment by ezu64** [comment]
Thanks a lot Varstahl

**Comment by ezu64** [comment]
I would like create a script to delete file .pvcp at startup but libreelec is no-modify os

**Comment by ezu64** [comment]
maybe it depends on whether I use a cec remote control on RPI2

**Comment by Varstahl** [comment]
Pretty sure it doesn't, I used it all the time with a remote. Can't tell for RPi though. Can you both actually check if the option is there?

**Comment by ezu64** [comment]
I'll check it as soon as possible.

**Comment by ezu64** [comment]
no way. to update the last episode of "the grand tour" I had to delete * .pvcp * .pdcp as soon as I can send .log

**Comment by Varstahl** [comment]
Ok, we need to establish a baseline here: do you see **and** are you able to click the refresh button? When you do, what happens?

If you're not able to proc the contextual menu from your remote, you need to reconfigure it.

**Comment by ezu64** [comment]
the "refresh" button is the 0 key when I try on "third season" of "the grand tour" I can see the central update logo that works but nothing happens. if I try with "search" the new title "urus ......." the search sends me to the "third season" where inside there is not the new episode It seems "to know" that there is but it fails to display it

**Comment by mattiep12** [comment]
Hi Varstahl, Sorry this reply has taken some time, I only just got back after a week away for work.

I definitely do not have the refresh option in my context menu. I've walked through the steps this morning, and here is how the process looks on my Kodi box. You will see that I only have "Add to favourites" as an option in my context menu.

Notes for context:
Kodi is running as Libreelec on a Dell E7330 Laptop (would libreelec be a factor?)
My remote is an old HP HTPC remote, and I lost what I was using as the context menu button when the PVR functions were added to Kodi. I have not yet remapped it. The 'zero' key is actually zero on this remote.
I use an app called Sybu for access to the context menu and some other functions

Here are photos (sorry, screen captures are not working) of my walk through from the main menu.

Main menu
![image](https://user-images.githubusercontent.com/37614466/52506969-4c3d6100-2c44-11e9-9de6-b673900a566a.png)

Amazon VOD addon, select TV Shows
![image](https://user-images.githubusercontent.com/37614466/52506992-5f503100-2c44-11e9-9ff2-2fb4e961f89d.png)

Select Prime Original Series
![image](https://user-images.githubusercontent.com/37614466/52507025-798a0f00-2c44-11e9-898b-913639588f55.png)

Select The Grand Tour
![image](https://user-images.githubusercontent.com/37614466/52507037-8444a400-2c44-11e9-891d-f8554df81773.png)

Select Season 3
![image](https://user-images.githubusercontent.com/37614466/52507048-8eff3900-2c44-11e9-8ef7-714a752dde2e.png)

Context Menu
![image](https://user-images.githubusercontent.com/37614466/52507060-96bedd80-2c44-11e9-86ae-7b59746c0f55.png)

**Comment by Varstahl** [comment]
I just got curious and reloaded. Refresh is there for Season 1 and Season 2 of Grand Tour on my box, but not Season 3. I'll have to look into this tomorrow, it's pretty strange, I never see it happen anywhere else. Can you confirm that refresh actually appears on Season 2, just to be on the same page?

**Comment by mattiep12** [comment]
No, definitely no refresh option on any of the seasons. I've also checked 3 or 4 other TV Shows and they don't have the refresh option in the context menu either.

PS: I love your issue with refresh missing only on season 3. That would do my head in. Thanks so much for your support!!

**Comment by Varstahl** [comment]
> No, definitely no refresh option on any of the seasons. I've also checked 3 or 4 other TV Shows and they don't have the refresh option in the context menu either.
> 
> PS: I love your issue with refresh missing only on season 3. That would do my head in. Thanks so much for your support!!

You tell me. It must be something completely stupid, but I have no idea what. I had plans to look into this today, but I had some carpentry to do for my office. On the plus side, I'm now back on a gigabit line :D

**Comment by ezu64** [comment]
I ask you both to try "option" with the title of the last episode of "the grand tour" ex "urus”. I have a weird result. perhaps the update is not the issue

**Comment by brunosaragiotto** [comment]
Hello, I have the same problem, in comedy series show only the first season of The Office, and if I search I don't find the Office. I already try to refresh but with the office won't appear the button. Sorry for my bad English.

**Comment by Varstahl** [comment]
The search option is broken for a couple reasons. The fix is already in the master branch, but even that won't  help with refreshing series.

I know it's a bug and this has my priority, but I have other matters to attend to that are taking all my free time. So, as per usual, the fix will come in "hawaiian time".

**Comment by mattiep12** [comment]
Thanks so much for the support @Varstahl, I can deal with deleting the pvcp & pdcp files and rebooting weekly to force a series refresh for the time being.

**Comment by ezu64** [comment]
a pretty hint to solve a the issue. activate cron as follow "systemctl enable cron.service". Create a script with editor as notepad or that you want. here the text
"#!/bin/bash
rm -f "/storage/.kodi/userdata/addon_data/plugin.video.amazon-test/*.pvdp
rm -f /storage/.kodi/userdata/addon_data/plugin.video.amazon-test/*.pvcp
exit"
Save as delete.sh in this path "/storage/backup"
Open crontab -e add or create a job as follow "*/1 * * * * /storage/backup/delete.sh" .
Check with crontab -l . Every time you start/reboot the script will delete files .pvpd .pvcp and amazon vod will can update . Have a nice vision

**Comment by ezu64** [comment]
A pretty hint to solve issue at moment. Activate cron as follow "systemctl enable cron.service" Create a script with your text editor (for ex notepad) : here the text 
"#!/bin/bash
  rm -f /storage/.kodi/userdata/addon_data/plugin.video.amazon-test/*.pvdp
  rm -f /storage/.kodi/userdata/addon_data/plugin.video.amazon-test/*.pvcp
  exit"
Save in the follow path : "/storage/backup" as "delete.sh"
Edit crontab with crontab -e ( use nano commands) . Add the follow job:
"*/1 * * * * /storage/backup/delete.sh"
Everytime startup/reboot your device .*pvdp and *.pvcp will be deleted and Amazon Vod will be updated.
Have a nice vision

**Comment by Varstahl** [comment]
@ezu64 that doesn't work though, does it? Doesn't that delete cache every minute?

Besides, I'm working on it, I should have everything fixed in a few hours. There's a few outstanding problems I'm facing, but most of it is done.

**Comment by ezu64** [comment]
I’ve tested yesterday and it works. But I can cancel my post immediately . maybe the attempt is a little rough😉

**Comment by Varstahl** [comment]
We have a new and improved refresh. Can you replace the `primevideo.py` in your installation with the one from the [master branch](https://raw.githubusercontent.com/Sandmann79/xbmc/master/plugin.video.amazon-test/resources/lib/primevideo.py) if everything's working as it should?

**Comment by ezu64** [comment]
I'm testing and it's seems all right

Il giorno lun 18 feb 2019 alle ore 19:10 Bruno Passeri <
notifications@github.com> ha scritto:

**Comment by ezu64** [comment]
Great work👏👏

Il giorno lun 18 feb 2019 alle ore 19:54 Paolo Iannone <
paolo.iann64@gmail.com> ha scritto:
