### ISSUE TITLE
No video but audio playback

### ISSUE THREAD

**Issue by similicious** [Sandmann79/xbmc#251]
Hey there, thanks a lot for everyones work on this plugin.

I just tried to set up the Amazon Video VOD plugin with the latest Kodi v18 stable.
Unfortunatly, I don't see any video, but there is audio playing.

I took a look into the log and it says:

`18:25:03.078 T:9812   DEBUG: CWinRenderer::SelectRenderMethod: selected render method 1: Pixel Shaders
18:25:03.078 T:9812   DEBUG: CWinRenderer::SelectRenderMethod: selected buffer format 8
18:25:03.079 T:9812   ERROR: CD3DTexture::Create: failed to create texture.
18:25:03.079 T:9812   ERROR: CWinRenderer::CreateRenderBuffer: unable to create video buffer 0
18:25:03.079 T:9812   ERROR: CD3DTexture::Create: failed to create texture.
18:25:03.079 T:9812   ERROR: CWinRenderer::CreateRenderBuffer: unable to create video buffer 1
18:25:03.079 T:9812   ERROR: CD3DTexture::Create: failed to create texture.
18:25:03.079 T:9812   ERROR: CWinRenderer::CreateRenderBuffer: unable to create video buffer 2
18:25:03.079 T:9812   ERROR: CD3DTexture::Create: failed to create texture.
18:25:03.079 T:9812   ERROR: CWinRenderer::CreateRenderBuffer: unable to create video buffer 3
18:25:03.080 T:9812   ERROR: CD3DTexture::Create: failed to create texture.
18:25:03.080 T:9812   ERROR: CWinRenderer::CreateRenderBuffer: unable to create video buffer 4
18:25:03.080 T:9812   ERROR: CD3DTexture::Create: failed to create texture.
18:25:03.080 T:9812   ERROR: CWinRenderer::CreateRenderBuffer: unable to create video buffer 5
18:25:03.080 T:9812   DEBUG: CRenderManager::Configure - 6`

You can find the full (debug mode enabled log) here https://pastebin.com/ut9r6SmF

I reinstalled Kodi (deleting all leftover files in Program Files and AppData/Romaing) but no success. Also, I played a bit with the rendering options in the settings. Still no video.

Anyone else encounters this problem?

Best Regards,
Simon

**Comment by Paco8** [comment]
I have the same problem on Windows 10 if I try to play a movie in HD, there's audio but not video (TV shows work fine).

I have to enable manual streams in the Inputstream preferences, and then select a video stream which is not HD.

**Comment by the-dreamer** [comment]
You have to disable override HDCP then input stream is not trying to start hdcp secured streams and automatic stream selection is working always then.

**Comment by similicious** [comment]
Sorry to have bothered you. This was not a plugin issue but a Kodi issue. I noticed, that a I also couldn't play some local files encoded with mpeg4. Additionally, I missed to disable the option "Allow harder acceleration - dxva2".

I could now resolve the issue by choosing Software as a render method and disallowing hardware accelleration. Thanks for your help.

**Comment by Paco8** [comment]
This doesn't work for me. I tried disabling "override HDCP", disabling DXVA2, and enabling Software render mode, and I still don't have video when using HD resolutions in movies. SD resolutions work fine.
Using kodi 18 64 bit on Windows 10.

**Comment by Varstahl** [comment]
@Paco8, on PrimeVideo HD movies require HDCP which at the moment Kodi/IS.A/we are not able to provide. What @the-dreamer meant is that if you disable "Override HDCP" in IS.A and enable automatic stream selection, IS.A will pick the highest available without the need for you to manually select a working stream.

@similicious that's also true in your case. FYI series work fine at 1080p, while movies can't go 720p or higher.
