### ISSUE TITLE
[Amazon VOD 0.6.6] Linux 1080p fine for TV Shows, but Movie decoding fails

### ISSUE THREAD

**Issue by AnonTester** [Sandmann79/xbmc#252]
Hi. First of all, thanks very much for your plugin!

There appears to be a problem with this patch https://github.com/Sandmann79/xbmc/pull/224 .
With this applied as in v0.6.6 of Amazon VOD, TV shows work fine on 1080p, however, Movies only play audio while video doesn't start and leaves the kodi interface visible in a somewhat frozen state. Logs refer to decryption kNoKey for key.

When removing these two lines from plugin.video.amazon-test/resources/lib/network.py , Movies play fine at 720p, however, TV Shows max out at 720p now as well.

This is on nightly Kodi (18.1-RC1 Git:20190201-c734016). Platform: Linux x86 64-bit
ADDON: plugin.video.amazon-test v0.6.6 installed
Linux kernel 4.15.0-45
Ubuntu Server 18.04.1 LTS / bionic
United Kingdom

Probably unrelated, but I see errors like this one quite a lot:
00:16:10.268 T:140586133911296 WARNING: CPythonInvoker(345, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/kodi/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE

Log:
00:15:52.800 T:140586133911296  NOTICE: [Amazon VOD] {'asin': 'B0791Z3S86', 'name': 'The Commuter', 'mode': 'PlayVideo', 'selbitrate': '0', 'trailer': '0', 'adult': '0'}
00:15:52.808 T:140586185602816  NOTICE: [Amazon VOD] Starting Fanart Update
00:15:54.058 T:140586133911296  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.amazon.co.uk/cdp/catalog/GetPlaybackResources?asin=B0791Z3S86&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=3218e290b76980dd1ac2e4279f4a67aee92c56f356f71d776
bc1f2a9&marketplaceID=A1F83G8C2ARO7P&format=json&version=1&gascEnabled=false&operatingSystemName=Windows&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProt
ocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&videoMaterialType=Feature&desiredResources=PlaybackUrls,SubtitleUrls,ForcedNarratives&supportedDRMKeyScheme=DUAL_KEY
00:15:54.133 T:140586185602816  NOTICE: [Amazon VOD] Finished Fanart Update
00:15:54.743 T:140586185602816 WARNING: CPythonInvoker(344, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/kodi/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory t
hat we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE
00:15:54.827 T:140586133911296  NOTICE: [Amazon VOD] Using Host: Cloudfront
00:15:54.828 T:140586133911296  NOTICE: [Amazon VOD] checkURL: https://s3-dub-2.cf.dash.row.aiv-cdn.net/dm/2$Xwwz3STsTVCYUkY0x6KXS6tabtI~/4504/0d0d/2b39/4ade-87f7-abef5a5def6c/e4b71f24-6b41-4eb3-b468-981519ac3404_corrected.mpd
00:15:55.287 T:140586133911296  NOTICE: [Amazon VOD] https://s3-dub-2.cf.dash.row.aiv-cdn.net/dm/2$Xwwz3STsTVCYUkY0x6KXS6tabtI/4504/0d0d/2b39/4ade-87f7-abef5a5def6c/e4b71f24-6b41-4eb3-b468-981519ac3404_corrected.mpd
00:15:55.328 T:140586133911296  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.3.13
00:15:55.433 T:140589894112192  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B0791Z3S86&mode=PlayVideo&adult=0&name=The+Commuter&trailer=0&selbitrate=0
00:15:55.435 T:140588667561728  NOTICE: Creating InputStream
00:15:56.494 T:140589295195904   ERROR: CAESinkALSA - snd_pcm_writei(-32) Broken pipe - trying to recover
00:15:57.156 T:140588667561728  NOTICE: Creating Demuxer
00:15:57.159 T:140588667561728  NOTICE: Opening stream: 1 source: 256
00:15:57.257 T:140588667561728  NOTICE: Display resolution ADJUST : DP-1: 3840x2160 @ 24.00Hz (19) (weight: 0.000)
00:15:57.286 T:140589894112192  NOTICE: CWinSystemX11::SetFullScreen - calling xrandr
00:15:57.354 T:140589894112192  NOTICE: VideoPlayer: OnLostDisplay received
00:15:57.354 T:140589894112192 WARNING: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
00:15:57.354 T:140589894112192 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
00:15:57.797 T:140588667561728  NOTICE: Creating video codec with codec id: 27
00:15:57.800 T:140588667561728  NOTICE: Creating video thread
00:15:57.800 T:140585998468864  NOTICE: running thread: video_thread
00:15:58.020 T:140588667561728  NOTICE: Opening stream: 4 source: 256
00:15:58.123 T:140589894112192  NOTICE: VideoPlayer: OnLostDisplay received
00:15:58.123 T:140589894112192 WARNING: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
00:15:58.178 T:140588667561728  NOTICE: Finding audio codec for: 86056
00:15:58.179 T:140588667561728  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder eac3
00:15:58.179 T:140588667561728  NOTICE: Creating audio thread
00:15:58.180 T:140585990076160  NOTICE: running thread: CVideoPlayerAudio::Process()
00:15:58.214 T:140589894112192  NOTICE: VideoPlayer: OnResetDisplay received
00:15:58.276 T:140586133911296  NOTICE: [Amazon VOD] Starting Playback: 0.0/6268.00048828
00:15:58.281 T:140586133911296  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.amazon.co.uk/cdp/usage/UpdateStream?asin=B0791Z3S86&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=3218e290b76980dd1ac2e4279f4a67aee92c56f356f71d776bc1f2a9&marketplaceID=A1F83G8C2ARO7P&format=json&version=1&gascEnabled=false&event=START&timecode=0.0
00:15:58.707 T:140585998468864   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 3D92DBFBED6D46149643222AD2ABA591
00:15:58.717 T:140585990076160  NOTICE: Creating audio stream (codec id: 86056, channels: 6, sample rate: 48000, no pass-through)
00:15:58.718 T:140585998468864   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 3D92DBFBED6D46149643222AD2ABA591
00:16:00.769 T:140589894112192   ERROR: Previous line repeats 201 times.
00:16:00.769 T:140589894112192  NOTICE: Display resolution ADJUST : DP-1: 3840x2160 @ 24.00Hz (19) (weight: 0.000)
00:16:00.773 T:140585998468864   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 3D92DBFBED6D46149643222AD2ABA591
00:16:01.510 T:140589295195904   ERROR: Previous line repeats 18 times.
00:16:01.510 T:140589295195904   ERROR: CAESinkALSA - snd_pcm_writei(-32) Broken pipe - trying to recover
00:16:01.532 T:140585998468864   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 3D92DBFBED6D46149643222AD2ABA591
00:16:01.938 T:140585956505344   ERROR: Previous line repeats 11 times.
00:16:01.969 T:140585998468864   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 3D92DBFBED6D46149643222AD2ABA591
00:16:05.663 T:140589894112192   ERROR: Previous line repeats 88 times.
00:16:05.663 T:140589894112192  NOTICE: CVideoPlayer::CloseFile()
00:16:05.663 T:140589894112192  NOTICE: VideoPlayer: waiting for threads to exit
00:16:05.673 T:140588667561728  NOTICE: CVideoPlayer::OnExit()
00:16:05.673 T:140588667561728  NOTICE: Closing stream player 1
00:16:05.674 T:140588667561728  NOTICE: Waiting for audio thread to exit
00:16:05.675 T:140585990076160  NOTICE: thread end: CVideoPlayerAudio::OnExit()
00:16:05.675 T:140588667561728  NOTICE: Closing audio device
00:16:05.695 T:140588667561728  NOTICE: Deleting audio codec
00:16:05.695 T:140588667561728  NOTICE: Closing stream player 2
00:16:05.696 T:140588667561728  NOTICE: waiting for video thread to exit
00:16:05.696 T:140585998468864   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
00:16:05.696 T:140585998468864  NOTICE: thread end: video_thread
00:16:05.696 T:140588667561728  NOTICE: deleting video codec
00:16:05.719 T:140589894112192  NOTICE: VideoPlayer: finished waiting
00:16:05.719 T:140589894112192  NOTICE: CVideoPlayer::CloseFile()
00:16:05.719 T:140589894112192  NOTICE: VideoPlayer: waiting for threads to exit
00:16:05.719 T:140589894112192  NOTICE: VideoPlayer: finished waiting
00:16:05.766 T:140589894112192  NOTICE: CWinSystemX11::SetFullScreen - calling xrandr
00:16:06.307 T:140589894112192   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
00:16:07.807 T:140586133911296  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.amazon.co.uk/cdp/usage/UpdateStream?asin=B0791Z3S86&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=3218e290b76980dd1ac2e4279f4a67aee92c56f356f71d776bc1f2a9&marketplaceID=A1F83G8C2ARO7P&format=json&version=1&gascEnabled=false&event=STOP&timecode=3.99100017548
00:16:09.357 T:140589295195904  NOTICE: Previous line repeats 1 times.
00:16:09.357 T:140589295195904   ERROR: CAESinkALSA - snd_pcm_writei(-32) Broken pipe - trying to recover
00:16:10.268 T:140586133911296 WARNING: CPythonInvoker(345, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/kodi/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE

**Comment by Varstahl** [comment]
Movies will never play HD or FHD due to HDCP. TV series *should* work at 1080p, unless Amazon changed something. In order to watch the content at the highest quality possible, you must configure IS.A to allow high quality streams, enable auto stream selection (not manual selection), and you must also disable `HDCP override` from the IS.A settings. I can investigate this tomorrow at the earliest, I'll let you know.

**Comment by AnonTester** [comment]
The HDCP override setting in the inputstream adaptive plugin seems to have been the issue. I disabled it and movies are playing properly at ~720p ish now and tv shows still work fine at 1080p. Thanks very much.

This hasn't had any effect on these errors though:
12:14:53.530 T:140585971054336 WARNING: CPythonInvoker(410, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/kodi/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE

12:14:54.978 T:140586004625152 WARNING: CPythonInvoker(414, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/kodi/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE

**Comment by Varstahl** [comment]
Glad it works.

> This hasn't had any effect on these errors though

Nah, that's something different for optimisations and stuff, not related.

> movies are playing properly at ~576p

1088x464, a little below the maximum 520.000 pixel resolution allowed without HDCP.
