### ISSUE TITLE
Raspberry Pi 3. Amazon VOD cannot access Amazon content after Widevine update

### ISSUE THREAD

**Issue by cliverlong** [Sandmann79/xbmc#253]
Hi

Note: I do not have any technical depth in RPi/Kodi/ Linux etc. etc.

Raspberry Pi 3 running latest OSMC / Kodi.

Kodi Debug Log files: http://paste.osmc.tv/onahujaqul

Symptom: I can navigate and see list of films and TV programs in AMazon. When I select any content to watch, within a few seconds the UI displays the message "Http error". This happens for any Amazon content. I can successfully use and access content on the  Youtube and BBC Iplayer add-ons on the same Rpi3 machine.

Before the error, and before upgrading widevine, I have been successfully using the Amazon VOD add-on under RPi3 Kodi to access Amazon video content , having configured my Amazon userid and password in Kodi

The problem started after I accepted a widevine update .

A few lines extracted from the log file that may be relevant follow:

14:51:19.661 T:1391457008   DEBUG: [script.module.inputstreamhelper-0.3.3]: Widevine update check was made on 2019-02-02T22:51:10
14:51:19.673 T:1391457008  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.amazon.co.uk/cdp/catalog/GetPlaybackResources?asin=B07G1Z7SWZ&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=a4a5676906fe007365b93a2cdb2d34379a5ad1356e6f4ab9bd70d19e&marketplaceID=A1F83G8C2ARO7P&format=json&version=1&gascEnabled=false&operatingSystemName=Windows&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProtocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&videoMaterialType=Feature&desiredResources=PlaybackUrls,SubtitleUrls,ForcedNarratives&supportedDRMKeyScheme=DUAL_KEY
14:51:19.729 T:1391457008   ERROR: [Amazon VOD] Error reason: 403 error (NoRetries)
14:51:19.735 T:1391457008   DEBUG: [Amazon VOD] Playing Dummy Video
14:51:19.748 T:1918152704   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
14:51:19.748 T:1332736752   DEBUG: Thread scriptobs 1332736752 terminating
14:51:19.766 T:1918152704   DEBUG: CPlayerCoreFactory::GetPlayers(/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/dummy.avi)

**Comment by cliverlong** [comment]
Turned out to be out-of-date password in my add-on configuration.

**Comment by qpaz** [comment]
@cliverlong 
I get nearly the same issue and configuration here. you only updated your password in your configuration?
