### ISSUE TITLE
Different paths on resume playback crash the addon

### ISSUE THREAD

**Issue by MrMilk23** [Sandmann79/xbmc#254]
Nothing is being played anymore
https://pastebin.com/TAuBhJEH

**Comment by Varstahl** [comment]
Off the top of my head, try to delete `%AppData%\Kodi\userdata\addon_data\plugin.video.amazon-test\resume.db`, and see if the problem persists.

**Comment by Varstahl** [comment]
On top of that problem, we no longer should have it, after the recent changes. Whatever caused the issue, it doesn't anymore.

**Comment by Varstahl** [comment]
Fixed last month in 226457de3b3001788c0a0f8e50c745296f160f76.
