### ISSUE TITLE
Movies not playing video, only sound (even on low video stream)

### ISSUE THREAD

**Issue by Bombest** [Sandmann79/xbmc#258]
Hello, first of all thank you for taking the time to create this plugin. I merely would like for it to be better.

So, i've researched enough around and understand that higher movie resolution is not supported yet in the plugin. So far TV shows work perfectly across all stream resolutions. However, movies play only as sound even when i manually switch to the lowest possible video stream (such as 416x224).

Here is a bit of the log concerning playing and switching streams:
[VOD.log](https://github.com/Sandmann79/xbmc/files/2856702/VOD.log)

**Comment by Varstahl** [comment]
```
ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key <KEY>
```

Either wrong options or change in Amazon's back end. In IS.A settings select "automatic selection" and disable "HDCP Override". If TV series work but the movie(s) you selected don't, it means that HDCP enforcement might be stricter, so there's nothing we can do about it.

**Comment by Bombest** [comment]
IS.A options are set to default, and even when "automatic selection" is chosen it's the same result.
Just reporting what's happening in case someone else is running into the same problem.

**Comment by Varstahl** [comment]
Given what happens it requires HDCP, but it's not currently supported by Kodi/IS.A afaik. Try some different movies, maybe.

What region btw?

**Comment by Bombest** [comment]
Tried a number of movies to no avail.
Region is "Other parts of the world" that's the only option i get since my region is not listed, but it streams normally through chrome regardless.

**Comment by Varstahl** [comment]
Browsers have no trouble with HDCP. The only suggestion I can give you is to not use IS.A and use external browser method with Amazon VOD. Very inconvenient but unless HDCP is supported there's not much else to do.

**Comment by Bombest** [comment]
I'll take that recommendation, hopefully the addon gets some updates soon. Thanks.

**Comment by Varstahl** [comment]
Sadly that has nothing to do with the addon, it's quite literally out of our hands.
