### ISSUE TITLE
Inputstream not supported

### ISSUE THREAD

**Issue by 86Atlas** [Sandmann79/xbmc#259]
Hi!

Installed OSMC on RPI 3b+, both Amazon plugins (to test) and widevine. Setup everything accordingly and tried to play a video. Got a message that due to DRM, InputStream is not supported and i have to declare a fallback option.

I am sure, last week i watched (on the new Kodi Leia 18 LibreElec build) videos with the same plugins and setup.

Is this a known thing, is there a solution?

Best regards

**Comment by Varstahl** [comment]
This is the first I've heard of this. Maybe the RPi board revision is not yet supported?

**Comment by 86Atlas** [comment]
Although it did work with LibreElec a week prior?
Addition: I switched to OSMC to see if the error (http error message in LibreElec) was still here in OSMC.

**Comment by Varstahl** [comment]
Honestly I don't know. Generally speaking, on the same hardware, LibreElec seems to be the one that works for most people, while OSMC/OpenElec tend to give problems. I use a PC for my HT needs, so I'm not too familiar with these issues. In any case if it's an IS.A problem, it's between the OS, Kodi and IS.A, the addon has nothing to do with it, so I can't do much.

**Comment by 86Atlas** [comment]
Oki, thank you very much for the answers. I will try again with LibreElec and report back.
