### ISSUE TITLE
Unable to install on OpenELEC

### ISSUE THREAD

**Issue by ninjagoat** [Sandmann79/xbmc#26]
I have already installed Beautifulsoup and Mechanize but it still says dependencies not met. Could you please tell me what else is required?

**Comment by Sandmann79** [comment]
Maybe pydes or pyxbmct? 
Just look into your kodi.log or post it here.

**Comment by ninjagoat** [comment]
pydes and pyxbmct didn't help either. So here is the log. Thank you!

[kodi.txt](https://github.com/Sandmann79/xbmc/files/669154/kodi.txt)

**Comment by Sandmann79** [comment]
You are using an outdated Kodi version (15.2). The addons needs at least v16 or newer.

**Comment by ninjagoat** [comment]
Strange. Before fetching that log, I also tried with OpenELEC 7.0 Beta 3 (which has Kodi 16.1) and it wasn't working with that either. But today, I tried with a clean install of Open and Libre ELEC and it works fine now. Thanks
