### ISSUE TITLE
Kodi freezes when trying to play unauthorized subscription content.

### ISSUE THREAD

**Issue by satmandu** [Sandmann79/xbmc#260]
I am running kodi 18 final from the team-xbmc ppa on ubuntu/cosmic.

I have been able to play many videos through this amazon plugin using my Prime account.

However, some videos do not play due to a permissions error from not having the appropriate subscription. (Example: https://www.amazon.com/Poldark-Season-4/dp/B07HFMBT27 ) 

When I try to play these videos, kodi appears to hang. The debug log shows it is receiving ​​​​​​​inputs from my CEC remote, but the screen is frozen, and I can only get kodi back via ```sudo systemctl restart kodi```.  I can use the remote to turn off the tv, and turn it back on, but kodi stays frozen.

Ideally Kodi shouldn't hang when this happens. I guess this plugin is blocking, but is there any way to get kodi to force the plugin to quit aside from having to restart the entire kodi process?

Here's the debug log:

http://paste.ubuntu.com/p/bxGYJcKv65/

**Comment by satmandu** [comment]
Also mentioning this here: https://forum.kodi.tv/showthread.php?tid=340810

**Comment by Varstahl** [comment]
>  I guess this plugin is blocking

Since it's not PrimeVideo related I won't put my life at stake, but I believe you're wrong:

```
10:42:05.306   ERROR: [Amazon VOD] Cannot complete request. (prs.norights.notowned)
10:42:05.308   DEBUG: [Amazon VOD] Playing Dummy Video
10:42:05.330  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B07HFMBT27&mode=PlayVideo&adult=0&name=%5BCOLOR+FFE95E01%5D3+-+Episode+3%5B%2FCOLOR%5D&trailer=0&selbitrate=0
10:42:05.330   DEBUG: OnPlayBackStarted: CApplication::OnPlayBackStarted
10:42:05.335   DEBUG: Open - av_find_stream_info finished
10:42:05.335    INFO: ffmpeg[7F2ACF7E9700]: Input #0, avi, from '/home/kodi/.kodi/addons/plugin.video.amazon-test/resources/dummy.avi':
10:42:05.335    INFO: ffmpeg[7F2ACF7E9700]:   Metadata:
10:42:05.335    INFO: ffmpeg[7F2ACF7E9700]:     encoder         : VirtualDubMod 1.5.10.2 (build 2542/release)
10:42:05.335    INFO: ffmpeg[7F2ACF7E9700]:   Duration: N/A, start: 0.000000, bitrate: N/A
10:42:05.336    INFO: ffmpeg[7F2ACF7E9700]:     Stream #0:0: Video: rawvideo, bgr24, 640x352, 25 fps, 25 tbr, 25 tbn, 25 tbc
10:42:05.451  NOTICE: CVideoPlayer::CloseFile()
10:42:05.451  NOTICE: VideoPlayer: waiting for threads to exit
```

Everything's working as intended on our end.

**Comment by satmandu** [comment]
For completeness I'm including a full debug log as I was [told on the kodi forums](https://forum.kodi.tv/showthread.php?tid=340810&pid=2822052#pid2822052) that the previous log I attached was incomplete:

http://paste.ubuntu.com/p/5RkbDBHD6Y/

So waiting to hear what they say.

FYI subscribing to the content on Amazon lets the content play just fine! This new debug log is with different content which I don't have a subscription to. (Outlander on Starz)

**Comment by Varstahl** [comment]
Well, it doesn't seem like it's anything new https://www.reddit.com/r/kodi/comments/9tekrr/kodi_hangs_while_waiting_for_video_thread_to_exit/

**Comment by satmandu** [comment]
I just realized I posted this same issue last month here: https://github.com/Sandmann79/xbmc/issues/226#issue-394755950 . 
Sorry about that.

I wonder if there might be an issue with playing the dummy.avi file in Leia?

**Comment by satmandu** [comment]
Moving dummy.avi in .kodi/addons/plugin.video.amazon-test/resources out of the way keeps kodi from freezing up, and I even get the error now about item not being purchased.

So this does maybe look like a kodi issue with not playing that file.

**Comment by Varstahl** [comment]
Weird. Granted, I didn't touch any of it, but Kodi freezing for that is plain silly. Besides, only on RPi? Something's fishy.

**Comment by satmandu** [comment]
For the record, I'm running Kodi on an amd64 Skylake system, not on RPi.
