### ISSUE TITLE
[Request]: Fixing the text direction in the Arabic subtitles

### ISSUE THREAD

**Issue by Essam315** [Sandmann79/xbmc#261]
The text direction in the Arabic subtitles are not displayed right (and the question mark and the comma in some subtitles), to fix this problem in "playback.py" i replaced 

`                            text = tt[2]`

with

import unicodedata

                            text = tt[2]
                            text = re.sub('^', unicodedata.lookup('RIGHT-TO-LEFT EMBEDDING'), text, flags=re.MULTILINE)						
                            text = text.replace('?', '؟').replace(',', '،')

It will be great if you could add this to the add-on, and make it applied only for the Arabic subtitles, thanks.

It looks like this

![1](https://user-images.githubusercontent.com/42877866/52895843-b4ea8780-31c8-11e9-861e-8f8e13763f4a.jpg)

when it should look like this

![2](https://user-images.githubusercontent.com/42877866/52895849-bd42c280-31c8-11e9-9ab3-ccabcd9bc27a.jpg)

**Comment by Varstahl** [comment]
Pardon if I'm wrong, but isn't this `re.sub('^', unicodedata.lookup('RIGHT-TO-LEFT EMBEDDING'), text, flags=re.MULTILINE)` just prepending RTL to the string? Like `text = unicodedata.lookup('RIGHT-TO-LEFT EMBEDDING') + text`?

In any case I should be able to implement it shortly.

**Comment by Essam315** [comment]
Thank you, please before implementing the changes, it would be great if you could upload the modified files, so i can test them, to make sure everything is working right and no other subtitle languages affected by the changes, i tested "text = unicodedata.lookup('RIGHT-TO-LEFT EMBEDDING') + text" and it did not give the same result, it only add RTL to one line of the subtitles in case of using multi lines at the same time, like the one in the photos.

**Comment by Varstahl** [comment]
Ah, makes perfect sense, I didn't pay attention to the multiline.

**Comment by Varstahl** [comment]
Can you replace the `playback.py` in your installation with the one in the [master branch](https://raw.githubusercontent.com/Sandmann79/xbmc/master/plugin.video.amazon-test/resources/lib/playback.py), and tell me if everything's working on your end? I've tested it, so it should, but just to be on the safe side.

**Comment by Essam315** [comment]
Thank you so much, everything is working fine.

**Comment by Essam-315** [comment]
@Varstahl I found that Amazon already fixed the Arabic subtitles direction in some subtitles, could you please do this replacement in "proxy.py"? Thanks.

                    from unicodedata import lookup
                    text = re.sub('^', lookup('RIGHT-TO-LEFT EMBEDDING'), text, flags=re.MULTILINE)

with

`                    text = re.sub('^(?!\u202b|\u200f)', '\u202b', text, flags=re.MULTILINE)`

**Comment by Varstahl** [comment]
Easy enough.

**Comment by Varstahl** [comment]
https://raw.githubusercontent.com/Sandmann79/xbmc/master/plugin.video.amazon-test/resources/lib/proxy.py

**Comment by Essam-315** [comment]
Thank you so much, worked perfectly.
