### ISSUE TITLE
UHD listning 

### ISSUE THREAD

**Issue by ghoshben** [Sandmann79/xbmc#263]
Does anybody discovered how to get uhd mpd listing?  Before some dayes deviceVideoQualityOverride=UHD & deviceHdrFormatsOverride=Hdr10 was listning 4k UHD. But it is giving only 1080p now

**Comment by Varstahl** [comment]
Amazon now uses the platform portion of things to limit streams availability. We've been investigating the issue in #51, with no success.

https://www.primevideo.com/help/?nodeId=202065160
