### ISSUE TITLE
Audio track - No dolby digital plus 6 channel

### ISSUE THREAD

**Issue by azmann75** [Sandmann79/xbmc#269]
I'm succesfull install and run this add-on version 0.6.8. I get full hd for most all video, but audio track only 2 channel. No 6 channel (dolby digital plus 5.1). Hope you can fixed audio channel. If i used netflix add-on, i can choose 6 channel audio track.

**Comment by Varstahl** [comment]
Not every video has DD+, there are plenty of movies and TV series with no surround. That's also more true for several countries, in which the dubs are done stereo only, like Poland. Are you sure what you're trying to watch, actually has it to begin with?

**Comment by Varstahl** [comment]
A couple band-aids while I'm testing things out.

---

To disable MPD parsing (for missing surround audio tracks), change [line 165](https://github.com/Sandmann79/xbmc/blob/1c2f16e3bc6ffdf3dfb3ddaf8e9b04beece617be/plugin.video.amazon-test/resources/lib/playback.py#L165) of playback.py with:
```python
                return (urlset['url'], subUrls) if retmpd else (True, _extrFr(data))
```

To disable GPR parsing, change [line 235](https://github.com/Sandmann79/xbmc/blob/1c2f16e3bc6ffdf3dfb3ddaf8e9b04beece617be/plugin.video.amazon-test/resources/lib/network.py#L235) of network.py with:
```python
    data = getURL(url, useCookie=useCookie, postdata='')
```

**Comment by Varstahl** [comment]
@aers @peak3d Does any of you guys know if MPDs have some sort of content protection on a URL/URI level, or anything similar?

More specifically to the point, do you have any idea why proxying an amazon MPD, even if unaltered, results in half the audio tracks disappearing? If it goes straight from the domain to IS.A, some 50+ DD+ tracks appear, although the `Representation` nodes are **not** in the MPD, but if I pass it through a proxy they vanish.
