### ISSUE TITLE
Script when launching and ending browser

### ISSUE THREAD

**Issue by mase76** [Sandmann79/xbmc#27]
Hi!
Please let amazon video execute a custom script when launching and ending the browser.
So it would be possible to disable the remote control in kodi and configure a remote to
control firefox. Otherwise all lirc commands are catched up by kodi in the background.

**Comment by Sandmann79** [comment]
There is no need for that. 
You can create one script, that executes some commands, than starts the browser and executes some commands afterwards.

As example:
#!/bin/sh
(Commands)
/usr/bin/google-chrome --kiosk $1
(Commands)

**Comment by mase76** [comment]
Got it, but I cannot disable / enable the remote via script. Kodi also catches all lirc commands in the background.

**Comment by mase76** [comment]
I only want to disable LIRC temporarely during the browser is open.
I did not find a way to do this from outside of kodi.
Maybe you could use parts from here:
https://github.com/AddonScriptorDE/plugin.program.chrome.launcher/pull/4/files?diff=split

**Comment by Sandmann79** [comment]
You can disable lirc outside from kodi with folling command:
/usr/bin/kodi-send -a "LIRC.Stop"
and enable with
/usr/bin/kodi-send -a "LIRC.Start"

**Comment by mase76** [comment]
Got it! I had to build a small C++ program. The shipped python program disabled lirc, but enabling was not possible.

Am 13. März 2017 06:40:59 MEZ schrieb Sandmann79 <notifications@github.com>:
>You can disable lirc outside from kodi with folling command:
>/usr/bin/kodi-send -a "LIRC.Stop"
>and enable with
>/usr/bin/kodi-send -a "LIRC.Start"

-- 
gpg-id: 383107c4
https://setho.org/people

**Comment by Sandmann79** [comment]
The commands above doesn't work?

**Comment by mase76** [comment]
I have built Kodi from source on Debian Jessie. The command you mean is a small python
program. LIRC.stop disabled the remote, but LIRC.Start did not enable it again. There was
no error, neither in the commandline, not in the log.
A small C++ program linked against xbmcclient did the job. Maybe a bug in the python module?
My Kodi works as expected now. So if you don't want to build in LIRC disable / enable, you can
close this issue.
Here is the piece of code I wrote. ou can use it like the python program.
`#include "xbmcclient.h"
#include <stdio.h>
#include <string.h>
#include <sys/socket.h>

int main(int argc, char **argv)
{
  /* connect to localhost, port 9777 using a UDP socket
     this only needs to be done once.
     by default this is where XBMC will be listening for incoming
     connections. */
  CAddress my_addr; // Address => localhost on 9777
  int sockfd = socket(AF_INET, SOCK_DGRAM, 0);
  if (sockfd < 0)
  {
    printf("Error creating socket\n");
    return -1;
  }

  my_addr.Bind(sockfd);

  CXBMCClient Client;
  Client.SendACTION(argv[1]);

  CPacketBYE bye;
  bye.Send(sockfd, my_addr);
}`

**Comment by Sandmann79** [comment]
Thanks for explaining that, i didn't know that's a python app.
But it's strange that is not working, because it does the same like your program.

However, i close this issue.
