### ISSUE TITLE
individual series episodes not being listed

### ISSUE THREAD

**Issue by iamogopogo** [Sandmann79/xbmc#270]
Currently when selecting a series, it only loads the first episode of that season, such as 'Pilot'. I posted the issue on the Kodi forum, and Varstahl asked for html dumps for Homepage, Movie list, Series list, Series page, and Search. Unfortunately pastebin won't allow me to upload anything larger than 512kb with a free account, and the pages are 1.2mb's. The individual series episode page only came to 216kb though, and that's the only thing not working anyway, so I posted that by itself. If you still need the other pages, just let me know an easier way of posting them. Cheers.

https://pastebin.com/tXNbN0Zy

**Comment by iamogopogo** [comment]
Seems it was a cache issue...everything's working as it should be now, please disregard.

**Comment by Varstahl** [comment]
The amazing thing is that until you closed the issue I wasn't notified and it didn't show up in the list with the others. Wth? :D

**Comment by iamogopogo** [comment]
My account was flagged so I was muted. I received an email saying the flagging was a mistake by the automated process, so I'm no longer muted. :)

**Comment by Paco8** [comment]
I have the same problem, when I go to watchlist, shows, instead of the list of shows it displays the first episode of each show. Deleting the cache didn't fix the problem.
I guess amazon changed something in the html.

**Comment by Varstahl** [comment]
I thought about this and it kind of makes sense. Basically, instead of detecting them as series it thinks they're movies. I'll have to look into it.

**Comment by Varstahl** [comment]
Yup, there's a new format alright. Why keep things the same when you can change it up for no reason and break everything, amirite? :D

**Comment by Varstahl** [comment]
So: the fix for the episodes list is pretty simple, everything else not so much. They re-re-re-fucked everything up for the sake of it, which now leaves me with the hard task of interpolating 3 or 4 of their fucking revisions in order for the service to work, and I'm currently not in the mood for parameter intersection, so it's going to take a while.

In order to do this properly btw, I also need the HTML from a movie page.

**Comment by iamogopogo** [comment]
[movies.txt](https://github.com/Sandmann79/xbmc/files/2915915/movies.txt)

**Comment by Varstahl** [comment]
Nope, wrong one. Could still be useful, but I need a single movie page, like [this](https://www.primevideo.com/detail/0RMOCK9IWIURYT1CAPEQS8F9PD/) for example, but one that you can watch.

**Comment by Paco8** [comment]
[movie_page.zip](https://github.com/Sandmann79/xbmc/files/2920812/movie_page.zip)

**Comment by iamogopogo** [comment]
[single movie.txt](https://github.com/Sandmann79/xbmc/files/2921357/single.movie.txt)

**Comment by iamogopogo** [comment]
[single season.txt](https://github.com/Sandmann79/xbmc/files/2921380/single.season.txt)

Just in case.

**Comment by Varstahl** [comment]
Thank you for the data, this should prove useful. I'm going against my better judgement to get this fixed over the weekend, send t&p. And booze. Lots of booze :p

**Comment by Varstahl** [comment]
I'm almost done, but I need another favour: can you provide me a season page of a tv show with a single season available? The HTML changed in all revisions, so I got the multi one but not the single. Something like [this](https://www.primevideo.com/detail/0FSEQSGZ99PFA5DL5OH8X0S30J/).

**Comment by Paco8** [comment]
[html.zip](https://github.com/Sandmann79/xbmc/files/2922415/html.zip)

**Comment by Varstahl** [comment]
Replace primevideo.py with [this one](https://raw.githubusercontent.com/Sandmann79/xbmc/0a2f4ad2c780ca9cf9fab9916f0976e7dc37e590/plugin.video.amazon-test/resources/lib/primevideo.py) and tell me if everything is working. I half expect stuff to blow up tbh. More specifically:

1. Are directors/actors in the video information?
2. Are age ratings correctly displayed in each episode? (provided they have a rating on primevideo.com)
3. Do episodes have the correct premiere air date?
4. Are all the synopsis for episodes and seasons correct, including thumbnails and background art?
5. Do movies still retain correct information after the update? (Year, actors, directors, synopsis, run time, etc.)

If something blows up, I've added a few logging info, so enable Kodi's debug logging and provide it.

**Comment by Paco8** [comment]
The movies seem to work fine, the list of shows fail to load:

```
22:46:24.430 T:612  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/watchlist/tv/ref=atv_wtlp_tv?page=1&amp;sort=DATE_ADDED_DESC
22:46:25.101 T:612  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/detail/0PYXVINS8OWR1YHXPQ4M2Y1ZR7/ref=atv_wtlp_wtl_0
22:46:25.999 T:612   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py", line 5, in <module>
                                                EntryPoint()
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\startup.py", line 83, in EntryPoint
                                                g.pv.Browse(None if 'path' not in args else args['path'])
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 225, in Browse
                                                self._LazyLoad(node[n], nodeName)
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 757, in _LazyLoad
                                                'premiered': r'<div[^>]*>\s*<div[^>]*>\s*' + self._dateFinder + r'\s*</div>',  # Original air date
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 516, in MultiRegexParsing
                                                o[i] = DelocalizeDate(amzLang, o[i])
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 468, in DelocalizeDate
                                                p = re.search(self._dateParserData[lang]['deconstruct'], datestr)
                                              File "C:\Program Files\Kodi\system\python\Lib\re.py", line 146, in search
                                                return _compile(pattern, flags).search(string)
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--
```

**Comment by iamogopogo** [comment]
Yeah, clicking a season just errors out. The log Paco8 posted should have more errors beneath, saying it couldn't load a plugin, as well as "plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up."

[kodi.log](https://github.com/Sandmann79/xbmc/files/2922583/kodi.log)

**Comment by Varstahl** [comment]
Made an oopsie with a regex. Let's hope that's all, here's the [correct version](https://raw.githubusercontent.com/Sandmann79/xbmc/master/plugin.video.amazon-test/resources/lib/primevideo.py).

**Comment by Paco8** [comment]
It seems to work now, thank you.
I found a small problem, the synopsis of the episodes is not correct, it shows instead the synopsis of the season for all episodes.

**Comment by Varstahl** [comment]
It doesn't make much sense though. Could you clear both cache files and try with a different series/season? (Or maybe just try with a refresh)

**Comment by Varstahl** [comment]
[New version](https://github.com/Sandmann79/xbmc/blob/a9f2ca4bd715a8fb94c8d3474b283411d73c7a6e/plugin.video.amazon-test/resources/lib/primevideo.py). Hope it's working. If it isn't, *lie to me*.

**Comment by Paco8** [comment]
Yes, it's fixed :)
Thank you very much.

**Comment by iamogopogo** [comment]
Thanks Varstahl!! You are a god. :)

**Comment by Paco8** [comment]
Maybe the issue is not completely fixed, I experienced several corruptions of the cache in the few past days.

Taking a look at the network traffic with firefox from the primevideo website, I noticed it's possible to get listings in json format, for example this returns the watchlist:

`https://www.primevideo.com/api/watchlist/?myStuffTreatment=false&contentType=ALL&sort=DATE_ADDED_DESC&primeOnly=false&startIndex=0
`

And this the contents of the main page:

`https://www.primevideo.com/api/storefront/?startIndex=0&pageSize=14&contentType=home&pageNumber=1&contentID=home`

Would it be possible to use that instead of parsing the html pages?
I guess it would be easier and less error prone to get the contents that way.

**Comment by Varstahl** [comment]
> Maybe the issue is not completely fixed, I experienced several corruptions of the cache in the few past days.

There have been some problems and some changes on their end after I submitted the updates, so it's possible that some form of corruption might have happened. You should still be able to use the Refresh functionality to fix it without wiping the data though.

> Taking a look at the network traffic with firefox from the primevideo website, I noticed it's possible to get listings in json format, for example this returns the watchlist:

Well, about fucking time. "Back in my days" we had to make do with HTML and Amazon-JSON-UI, which wasn't particularly brilliant.

As far as I can't see it's not a 1:1 replacement, we might still need to parse HTML if they didn't provide everything through API (and if the past is any proof, they didn't). Since everything is working now I won't rush this just to be fucked the same way as last time, where they took away the API endpoints and I had to re-code everything to parse HTML. I'll open a new enhancement issue with the API endpoints, and see where it leads us, with all due caution.
