### ISSUE TITLE
Playback issue with R.I.P.D

### ISSUE THREAD

**Issue by debutanker** [Sandmann79/xbmc#272]
Hi @varstahl,
first of all many thanks for keepin the amazon stuff still up to date!
For me everythings workin fine with recent Milhouse x86 build and amazon vod 0.6.9 except one movie: R.I.P.D - Rest in Peace Department.
No playback possible with this movie - maybe my log shows some helpful information....
http://ix.io/1C6K

**Comment by Varstahl** [comment]
That's a bug in the new parser, thanks for reporting. Should be pretty easy to fix, I've never seen that type of parameter-less `<Period>`. If you want to try to fix it yourself while you wait for the update, find [row 233](https://github.com/Sandmann79/xbmc/blob/1bbf9ddc645bff256aa1d73d151720527cb0aaed/plugin.video.amazon-test/resources/lib/proxy.py#L233) in the proxy.py file, and replace the space after `Period`, like so:
```
header, sets, footer = re.search(r'^(.*<Period[^>]*>\s*)(.*)(\s*</Period>.*)$', content, flags=re.DOTALL).groups()
```

**Comment by debutanker** [comment]
Workin fine - many thanks!
