### ISSUE TITLE
Unable to browse/play Tv series

### ISSUE THREAD

**Issue by ezu64** [Sandmann79/xbmc#278]
I've a strange issue as you can see in attached file. I believe is
 due a new change in path structure. All folders are empty. Raspberry pi 3+
![img_4253](https://user-images.githubusercontent.com/44585218/54027415-c01a4d00-41a1-11e9-884a-3adccfc0e409.JPG)

LOG

12:33:11.706 T:1937694240   DEBUG:   ParentPath = [plugin://plugin.video.amazon-test/pv/browse/root/Serie+TV/Serie+TV+aggiunte+di+recente]
12:33:11.707 T:1804092272   DEBUG: Thread waiting start, auto delete: false
12:33:11.719 T:1816114032   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.amazon-test] took 13 ms
12:33:11.719 T:1804092272   DEBUG: StartScript - calling plugin Amazon VOD('plugin://plugin.video.amazon-test/pv/browse/root/Serie+TV/Serie+TV+aggiunte+di+recente/amzn1.dv.gti.3aac2306-9e57-93d2-e254-e52c2bcf48f8','1','','resume:false')
12:33:11.719 T:1804092272   DEBUG: GetLanguageInvoker - Reusing LanguageInvokerThread 5 for script /storage/.kodi/addons/plugin.video.amazon-test/default.py
12:33:11.719 T:1548739440    INFO: initializing python engine.
12:33:11.720 T:1548739440   DEBUG: CPythonInvoker(5, /storage/.kodi/addons/plugin.video.amazon-test/default.py): start processing
12:33:11.720 T:1548739440   DEBUG: CPythonInvoker(5, /storage/.kodi/addons/plugin.video.amazon-test/default.py): entering source directory /storage/.kodi/addons/plugin.video.amazon-test
12:33:11.720 T:1548739440   DEBUG: CPythonInvoker(5, /storage/.kodi/addons/plugin.video.amazon-test/default.py): instantiating addon using automatically obtained id of "plugin.video.amazon-test" dependent on version 2.24.0 of the xbmc.python api
12:33:11.721 T:1548739440   DEBUG: [Amazon VOD] Requested /pv/browse/root/Serie+TV/Serie+TV+aggiunte+di+recente/amzn1.dv.gti.3aac2306-9e57-93d2-e254-e52c2bcf48f8
12:33:11.749 T:1548739440  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/detail/0STATSUKBRZ2SFUYITDMVNBPBK/ref=br_def_r_br_c_5yuTIXnul_1_1
12:33:11.807 T:1937694240   DEBUG: ------ Window Init (DialogBusy.xml) ------
12:33:12.052 T:1647506288   DEBUG: PushCecKeypress - received key  b duration 384 (rep:0 size:0)
12:33:12.052 T:1647506288   DEBUG: PushCecKeypress - ignored key  b
12:33:12.616 T:1548739440   DEBUG: [Amazon VOD] Movie/series list or search results
12:33:12.664 T:1548739440   DEBUG: [Amazon VOD] Encoded PrimeVideo URL: plugin://plugin.video.amazon-test/pv/browse/root/Serie+TV/Serie+TV+aggiunte+di+recente/amzn1.dv.gti.3aac2306-9e57-93d2-e254-e52c2bcf48f8/0STATSUKBRZ2SFUYITDMVNBPBK
12:33:12.664 T:1548739440   DEBUG: [Amazon VOD] Encoded PrimeVideo refresh URL: pv/refresh/root/Serie+TV/Serie+TV+aggiunte+di+recente/amzn1.dv.gti.3aac2306-9e57-93d2-e254-e52c2bcf48f8/0STATSUKBRZ2SFUYITDMVNBPBK
12:33:12.685 T:1548739440   DEBUG: [Amazon VOD] Encoded PrimeVideo URL: plugin://plugin.video.amazon-test/pv/browse/root/Serie+TV/Serie+TV+aggiunte+di+recente/amzn1.dv.gti.3aac2306-9e57-93d2-e254-e52c2bcf48f8/0STATSUKBRZ2SFUYITDMVNBPBK
12:33:12.685 T:1548739440   DEBUG: [Amazon VOD] Encoded PrimeVideo refresh URL: pv/refresh/root/Serie+TV/Serie+TV+aggiunte+di+recente/amzn1.dv.gti.3aac2306-9e57-93d2-e254-e52c2bcf48f8/0STATSUKBRZ2SFUYITDMVNBPBK
12:33:12.686 T:1548739440    INFO: CPythonInvoker(5, /storage/.kodi/addons/plugin.video.amazon-test/default.py): script successfully run
12:33:12.686 T:1804092272   DEBUG: Thread waiting 1804092272 terminating
12:33:12.692 T:1937694240   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
12:33:12.699 T:1804092272   DEBUG: Thread BackgroundLoader start, auto delete: false
12:33:12.711 T:1804092272   DEBUG: Thread BackgroundLoader 1804092272 terminating
12:33:41.719 T:1557132144   DEBUG: Thread JobWorker 1557132144 terminating (autodelete)
12:33:41.719 T:1570780016   DEBUG: Thread JobWorker 1570780016 terminating (autodelete)
12:33:41.719 T:1816114032   DEBUG: Thread JobWorker 1816114032 terminating (autodelete)
                                                                         12:34:22.011 T:1908810608   DEBUG: CAESinkPi:Deinitialize
12:34:22.012 T:1908810608   DEBUG: CAESinkPi:SetAudioProps hdmi_stream_channels 0 hdmi_channel_map 00000000
12:34:22.025 T:1908810608   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.audio_render handle 0x701030b8
12:36:12.048 T:1937679216   DEBUG: CAnnouncementManager - Announcement: OnScreensaverActivated from xbmc
12:36:12.048 T:1937679216   DEBUG: GOT ANNOUNCEMENT, type: 4, from xbmc, message OnScreensaverActivated
12:36:12.065 T:1937694240   DEBUG: CAddonSettings[screensaver.xbmc.builtin.dim]: loading setting definitions
12:36:12.065 T:1937694240   DEBUG: CAddonSettings[screensaver.xbmc.builtin.dim]: trying to load setting definitions from old format...

**Comment by Varstahl** [comment]
I noticed this yesterday, some of the series stopped working last night. I thought it was due to the typo I had in it, but it must have been something else. I'll have to check.

**Comment by Varstahl** [comment]
Everything went to shit, including searching for movies. I swear to God…

**Comment by ezu64** [comment]
congratulations for your patience

**Comment by ezu64** [comment]
Everything seems ok now😉😉

Il giorno ven 8 mar 2019 alle ore 16:58 Bruno Passeri <
notifications@github.com> ha scritto:

**Comment by Varstahl** [comment]
Give it another 12-ish hours, I'm sure something new will pop up from their backend…

**Comment by ezu64** [comment]
😂😂😂

Inviato da iPhone
