### ISSUE TITLE
Amazon Prime fallback remote control (Ubuntu 16.04.1)

### ISSUE THREAD

**Issue by audimax85** [Sandmann79/xbmc#28]
Hallo,
danke für das geniale addon!

Problembeschreibung auf Englisch:
I have a problem controlling the playback in chrome. The xdotool seems to be executed only after chrome is closed (killed via console).
I played around without any real knowledge in python and found that if i comment out line 89 (result = process.communicate()[0])  and 90 (Log(result)) everything works fine. I'm not really sure what those lines are supposed to do, but i think those a for diagnostic purposes only and the first one doesn't seem to return until chrome is closed.
Environment:
x86_64 bit Ubuntu 16.04.1
Google Chrome 55.0.2883.87
Kodi 17.0RC1
Amazon 1.7.6

Thank you very much.
Gruß
max

**Comment by Sandmann79** [comment]
Thanks for reporting. 
I forgot to add an exclusion for Libreelec, should be fixed with commit 85f8976efdaebbe13e80d6a4cb7256dcbb0d0ba3.

**Comment by Sandmann79** [comment]
Due a lack of feedback, i close this issue.
If the problem persists just reopen it.
