### ISSUE TITLE
Kodi no longer plays series or movies

### ISSUE THREAD

**Issue by MrMilk23** [Sandmann79/xbmc#283]
Kodi does not play any more videos since yesterday for me
.When I pick something out and want to start it loads a moment and then it breaks off.

Log https://pastebin.com/uuc1HJnx
Debug https://pastebin.com/NxGB3rsv

**Comment by Varstahl** [comment]
```
ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (C:\Users\W10\AppData\Roaming\Kodi\cdm\widevinecdm.dll)
ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
```

Problems between Windows 10, Kodi, InputStream.Adaptive, Widevine or any combination of those. Check if the cdm dll is still there, in case try to remove the cdm directory with all the files in it. It doesn't seem like anything I can help you with, specifically.
