### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by Varstahl** [Sandmann79/xbmc#288]
Some people are getting confused between the amazon and the amazon-test addons. Somewhere along the updates the information regarding plugin.video.amazon being DE only must have been lost. It's a good time to check if some information need updates too.

**Comment by GIPeon** [comment]
Hey there!  
Just a suggestion to warn users that on first run the system could take quite some time to cache the catalogue entries as noted in #281, I got quite confused the first time and thought something was plain wrong with the continuous flow of "Found: something" notifications and the endless spinner.

I take the chance to thank you for your great work and effort in this, I'm using your addon on LibreELEC with newly released 9.0.1 and 18.1 Kodi, it's working pretty well with no issues until now! :crossed_fingers: 

Cheers! :beers:
