### ISSUE TITLE
TV shows not loading

### ISSUE THREAD

**Issue by harikt** [Sandmann79/xbmc#289]
Hi, 

I noticed in the search, only movies are loaded, TV shows are shown, when you dive deeper into seasons, there is none in the list to play.

What should I provide to debug for more details ?

**Comment by Varstahl** [comment]
A [debug log](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi) would be really useful. Does any error appear, or it's just empty?

**Comment by harikt** [comment]
No error is shown on the screen. Just empty for all.

**Comment by harikt** [comment]
Here is the log [kodi.log](https://github.com/Sandmann79/xbmc/files/2986749/kodi.log)

**Comment by Varstahl** [comment]
This is getting weirder by the minute, there are no errors whatsoever. What happens if you right click on one of those series and hit Refresh?

**Comment by harikt** [comment]
I don't know how to refresh. There is no option shown to refresh. @santhoshnsscoe mentions about the same.. But couldn't figure out where it is.

**Comment by Varstahl** [comment]
You can do it even with keyboard alone. Find the TV Show/Season you want to refresh, then right click on it with the mouse or select it with the arrow keys and then press the contextual menu button (usually to the right of the spacebar after the Alt and sometimes the Win flag). That should open the contextual menu which shows the Refresh menu item. Select refresh and it should reload content for a few seconds, then you can walk into it and see if there's anything in there.

**Comment by harikt** [comment]
@Varstahl thanks. I tried, it is loading information. I can see on the top right of screen. But when you enter into the directory, there is nothing shown.

**Comment by Varstahl** [comment]
Seems the same as #285. I have no clue.

**Comment by harikt** [comment]
Yes, do we want to close this issue and continue on #285 ?

**Comment by Varstahl** [comment]
Sure, I'll mark this as dupe.
