### ISSUE TITLE
unable to install video Add-on in OSX - Kodi V17 Krypton

### ISSUE THREAD

**Issue by muteddaemon** [Sandmann79/xbmc#29]
Got the repository added , showing two addons, Amazon and Amazon VOD..
tried installing both video add-on(s) , but clicking on "install" button doesn't do anything.

**Comment by Sandmann79** [comment]
Sometimes the Beautiful Soup and Mechanize Addons are not automatically installed.
You can download it here: https://github.com/Sandmann79/xbmc/tree/master/packages

Check your kodi.log, if this doesn't fix your problem.

**Comment by muteddaemon** [comment]
that works. Thanks a lot
