### ISSUE TITLE
The Amazon VOD doesn't realize when a unavailable movie is available again

### ISSUE THREAD

**Issue by Paco8** [Sandmann79/xbmc#291]
I've just found this problem.
I had a movie in my watchlist which amazon removed some time ago, but I didn't remove it from my watchlist. But now the movie is available again, so I wanted to watch it. However the addon doesn't show this movie in the list.
I tried the refresh option, but it still doesn't show.
I tried to search for the movie, I saw in the popup notification that it found the movie, but however the movie is not shown in the search results.
I guess the addon marked the movie in the past as unavailable and now it doesn't check if the movie is available.

Finally I removed the cache files and the movie finally showed in the list.

**Comment by Varstahl** [comment]
Sounds like the "unavailable flag" (which I thought I removed?) didn't get reset. Either case this is a bug, I'll try to hunt it down as soon as I find the time, thanks for the report.

**Comment by benhammer2002** [comment]
I've the same problem. But it's not resolved. I still have the problem after cleaning the cache. Now I have nothing in the Amazon library, even after a refresh.

**Comment by Varstahl** [comment]
That's hardly the same problem, sounds like Amazon changed their backend again. Totally possible.

**Comment by Varstahl** [comment]
This issue just deprecated itself with the new system.
