### ISSUE TITLE
Amazon VOD playback freezes with 720p

### ISSUE THREAD

**Issue by rytecbe** [Sandmann79/xbmc#292]
Hi guys,

I have reduced the input stream from 1080p to 720p on advice from another user here and it went better but when playing a tv show for example it often stands still and buffers.
I already have put it on 720p and I'm using a fast internet connection.
Maybe someone can tell me what to try next or should I test something?

Thank you
Ryan

**Comment by Varstahl** [comment]
It might be a problem of bandwidth. For each resolution there are several bandwidths available, with increasing size increases the decoding needs as well. You might try to enable manual stream selection with InputStream.Adaptive, and check which maximum bandwidth runs smooth.

**Comment by Varstahl** [comment]
Deprecated issue.
