### ISSUE TITLE
Amazon Prime Flemish Menu ?

### ISSUE THREAD

**Issue by DavGoodvibes** [Sandmann79/xbmc#296]
I have a Prime France Subscription.
When I try to use Amazon VOD, all the menu are in ... FLEMISH !
How can I change that ? Thank you.
![VOD](https://user-images.githubusercontent.com/33485002/55667122-8d26b000-5858-11e9-98f7-2ac5da76a486.jpg)

**Comment by Varstahl** [comment]
All the languages are handled by Amazon. Log in primevideo.com, go to [language settings](https://www.primevideo.com/settings/language/ref=atv_set_language) and select french.

**Comment by DavGoodvibes** [comment]
Sorry to say the settings was already in french, but the menu still in flemish.
This is really strange. Any other tips to fix this ? Thanks.
![VOD2](https://user-images.githubusercontent.com/33485002/55681760-69339f00-592a-11e9-9363-39b287b19507.jpg)

**Comment by Varstahl** [comment]
Are you using a VPN/proxy perchance? I really don't know, the addon does nothing but parse primevideo.com, it's completely language/locale agnostic.

**Comment by DavGoodvibes** [comment]
Nope, no VPN at all. 
I checked again the link provided it open with "french" language.
Just to test I pressed "SAVE" ...  just in case and now everything is okay.
This issue can be closed. Thanks for your help ;-)

Kind regards !
