### ISSUE TITLE
packages/addons.xml.md5 is wrong

### ISSUE THREAD

**Issue by Rocka84** [Sandmann79/xbmc#30]
packages/addons.xml.md5 does not contain the proper checksum for packages/addons.xml

**Comment by Rocka84** [comment]
Pull Request coming soon...

**Comment by Rocka84** [comment]
From http://kodi.wiki/view/Add-on_repositories
> Note: for historical reason it is called "checksum", but it is not verified and not required to be a checksum as long as it is changed whenever addons.xml has changed.

Sorry I didn't check this beforehand. Closing.

**Comment by Sandmann79** [comment]
Thanks for reporting.
I think this is a result of Windows <-> Linux line ending converting, done by the github tool.
