### ISSUE TITLE
PyDes Installation failed on Kodi 18

### ISSUE THREAD

**Issue by julianCast** [Sandmann79/xbmc#300]
Kodi 18 RC-2
Raspberry 3
OSMC

One dependency fail when try to install the amazon vod, "PyDes", the other ones are succesfully installed.

![photo5906865215520222981](https://user-images.githubusercontent.com/559677/56595169-702b0480-65ee-11e9-844b-5fba1f82daf7.jpg)

**Comment by Varstahl** [comment]
Hmm, strange, it might be a fluke. Have you tried reinstalling it again? If it doesn't work, can you provide the [debug logs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi)?

**Comment by julianCast** [comment]
Resolved by installing the dependency via a different repo.
