### ISSUE TITLE
Black screen after play video

### ISSUE THREAD

**Issue by julianCast** [Sandmann79/xbmc#302]
Osmc, raspberry 3,kodi 18.
After hitting play the screen turns blackthe video is playing because , my leds are grabbing the colors I can see them changing. I have enabled and disabled check DRM, with no luck.
Widevine was installed when I was asked in a prompt dialog after hitting play the first time.

**Comment by Varstahl** [comment]
Sometimes after installing Widevine on some O/S you actually need to reboot/restart Kodi for the CDM to work correctly. In any case are you still experiencing problems? Could you provide [the logs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi)?

**Comment by julianCast** [comment]
Still happening after rebooting.

Here my log after press PLAY.
https://pastebin.com/acsbACkf

And a video to show what I see randomly:
https://photos.app.goo.gl/adeKvfzyZtmru9ve6

**Comment by Varstahl** [comment]
It seems fine on the addon side. I see a lot of buffer underruns, some weird stuff from the skin that could be interfering (additional caching?), but aside from that everything seems fairly normal.

As tentative tests:
* Go to the InputStream.Adaptive settings and limit the maximum resolution/bandwidth heavily, like 240p/360p/480p. If they work at some lower resolution but not higher, than it's a processing power problem.
* If you intend to mostly/solely use Kodi on it, you could try replacing OSMC with LibreELEC.

I don't know the reasons why, but over the last couple-ish years, several users reported problems with OSMC that they solved moving to LibreELEC. I don't have a RPi myself so I never tried, but I'm just reporting it to you as additional information.

**Comment by julianCast** [comment]
That's interesting, thank you I'll try that and I'll let you know.
I didn't want to change to librelec because all the hyperion leds config and stuff is a pain to re do it.

**Comment by Varstahl** [comment]
Take it with a grain of salt, it's just what I gathered by people talking. Generally when somethings changes I mostly hear complaints coming from OSMC, rarely from LibreELEC.

And, btw, I guess you could just dump the SD and restore it later, should it fail.

**Comment by julianCast** [comment]
Confirmed. On libreElec no problems. On OSMC blinking. Thank you!

**Comment by Varstahl** [comment]
Glad it works :)
