### ISSUE TITLE
Request: Amazon Channel RTL Living

### ISSUE THREAD

**Issue by 86Atlas** [Sandmann79/xbmc#305]
Hi!

Would it be possible to add RTL Living to the channel list?

Best regards

**Comment by Varstahl** [comment]
Since I'm not the dev for that portion of code, I need more info:

1. us/de/uk/jp?
2. URL of the channel

Not sure if I can help, but maybe I can give it a look.

**Comment by 86Atlas** [comment]
Hi!

I live in Austria, RTL Living is a german channel i believe (you can switch most of it to english though)
URL is (at least thats what it shows in my browser) https://www.amazon.de/Instant-Video/b/ref=sxts_spkl_1_1_5c0805e1-2c57-4941-901b-c5151821e4e8?benefitId=livingrtl&node=3010075031&pd_rd_w=LgFsT&pf_rd_p=5c0805e1-2c57-4941-901b-c5151821e4e8&pf_rd_r=H8FJMJFNTE0C1Y2J7V10&pd_rd_r=af415b0f-5ab9-4b8b-9006-e9fb8a2dd754&pd_rd_wg=qcGAy&qid=1558540811

Best regards

**Comment by 86Atlas** [comment]
Hey!

I wanted to ask if there was any chance this helped you?
Can i do something else that might shed some light on this request?

Best regards
Atlas

**Comment by Sandmann79** [comment]
Channels updated with commit b9ae41518ed9ff1071c8abcbaf1c5a0362331140, including RTL Living. 
You have to wait for the next addon release to be able to play it.

**Comment by 86Atlas** [comment]
Thank you so much!!!

Tue Oct 01 21:03:04 GMT+02:00 2019 Sandmann79 <notifications@github.com>:
