### ISSUE TITLE
Unable to login into JP account

### ISSUE THREAD

**Issue by JohnnyZB** [Sandmann79/xbmc#307]
Using the latest version of Kodi (18.2) and the latest version of the plugin (0.7.2-bis) on Windows, after changing the region to Japan, I'm unable to login after entering my credentials. I can do it on my other account with US region being set, but JP throws an error before reaching the captcha. 

Clearing cookies and complete fresh reinstalling of everything didn't help.

[Log](https://pastebin.com/PJvbK3sg)

**Comment by Varstahl** [comment]
Looks like an encoding error, might be a change on their backend or something weird happening somewhere. I'm not the maintainer of that code portion but I'll take a look if I can. In the meanwhile:

* enable verbose logging (miscellaneous settings)
* Login again
* After that you'll find `amazon-login.log` located at %AppData%\Kodi. This file contains the login html response, so you have to remove your username/email from it
* Upload it somewhere

If it's a change in locales on JP servers or login page format, that could be useful.

**Comment by JohnnyZB** [comment]
Thank you. I have uploaded the log file [here](https://www.dropbox.com/s/sz4z0vok2vo3ahz/avod-login.log?dl=0).

**Comment by yuhirok** [comment]
I got the same problem using Kodi (18.2) and the plugin (0.7.3) on Raspbian. It seems like the system locale is not utf-8, but my system was set to `LANG=C.UTF-8`. So, I tried setting the environment variable to `PYTHONENCODING=utf-8`, and I succeeded to login my JP account.

**Comment by SasakiSadako** [comment]
im using Kodi on a fresh installed osmc on the Rasperry Pi 3 and im struggling too with the login.

im living in japan, so i tried to use my amazon jp account for login
i only get an error message with this entry in the logs:
`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe3 in position 0: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 89, in EntryPoint
                                                exec '%s()' % mode
                                              File "<string>", line 1, in <module>
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 486, in LogIn
                                                br = _MFACheck(br, email, soup)
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 348, in _MFACheck
                                                wnd = _Captcha((getString(30008).split('…')[0]), soup, email)
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 568, in __init__
                                                self.head = head.p.renderContents().strip().encode('utf-8')
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 0: ordinal not in range(128)
                                            -->End of Python script error report<--
2019-10-06 05:40:55.341 T:1529869024 WARNING: CPythonInvoker(8, /home/osmc/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory t$
2019-10-06 05:40:55.353 T:1790964448   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/
2019-10-06 05:40:55.357 T:1916065328   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/) failed
`

I tried to change my locale, or add more utf locales, i used GE utf8 before, but i add some US and GB too.
there is no PYTHONENCODING=utf-8 when i reconfigure the locales

**Comment by Varstahl** [comment]
This might be late for a lot of you, but I just pushed out v0.7.5, which brings a change in the browser automation, string encoding/decoding and new login processing. Now that things settled down, if you're still experiencing login problems I'd love to hear it.

**Comment by SasakiSadako** [comment]
I Updated yesterday to the newest version and for me it stopped working.
I uninstalled and reinstalled the addon with all settings new, but i cannot login anymore. I checkout the network.py for the changes before, but the necessary row is not in it anymore - maybe because of the changes. the funny thing is, even with verbose logs enabled, i get no logs anymore.

**Comment by Sandmann79** [comment]
Strange last time i checked, it worked. Now i get an error, too.
Maybe they changed something. 
Looking into it.

**Comment by Sandmann79** [comment]
@SasakiSadako can you check, if commit 2eed01985dfcc995528b74bed0c268e558598cad solve this issue for you? I'm not able to test it completely, because my account doesn't work on JP site.

**Comment by SasakiSadako** [comment]
> @SasakiSadako can you check, if commit [2eed019](https://github.com/Sandmann79/xbmc/commit/2eed01985dfcc995528b74bed0c268e558598cad) solve this issue for you? I'm not able to test it completely, because my account doesn't work on JP site.

I will try it when im at home.
But I have the same issues with my Amazon us login. Because I use an amazon.com account with my VPN (Which I use on my notebook with a regular Browser for Amazon Prime too)

**Comment by SasakiSadako** [comment]
With the newest update i can finally login again with my us account and the videos are running. i will checkout the multi login with my japanese too. i hope it will work now :)

thank you for the hard work

**Comment by Sandmann79** [comment]
No response since tree month. Closing.
