### ISSUE TITLE
Failed to install addon from ZIP file

### ISSUE THREAD

**Issue by darrenclimienewman** [Sandmann79/xbmc#31]
Hi Sandmann

Ive just tried to install this addon, and i get the error in the title.

Is there a known issue/fix for this problem?

Thanks

**Comment by Sandmann79** [comment]
Did you installed the addon from the repo (https://github.com/Sandmann79/xbmc/blob/master/packages/repository.sandmann79.plugins/repository.sandmann79.plugins-1.0.2.zip)? 
If not, install the repo and after that the addon, in order that all dependencies are installed.

**Comment by darrenclimienewman** [comment]
I installed the Addon from the Zip from Github, installed now and logged in! Thanks!

Lastly, I'd like to use inputstream, but when I download the inputstream.adaptive from Github, I get the same install error. 

I've installed the Kodinerds repository as I believe that's where it's located, in case it didn't have the dependencies like the APIV addon, but still get the error. 

What's the best way to get an input addon installed?

Thanks mate!

**Comment by darrenclimienewman** [comment]
Update:

All sorted! When DRM video files can't be run through inputstream, and it falls back to Browser  (chrome in my case), I've set to full screen kiosk mode, when you exit the video playing (X top right corner) it goes back to the browser window in kiosk mode, which is a pain to get out of and back to Kodi. Is there way of exiting the playing video in the browser, back in to Kodi?

**Comment by Sandmann79** [comment]
This depends on your system, on windows you can close the browser with all+f4, on Linux with alt+x. There are many tools out there, where you can assign this keys to an ir remote button.  You can also use kore or yatse on your mobile with this addon, just enable web remote support in addon settings.

**Comment by Sandmann79** [comment]
The issue itself is resolved, closing
