### ISSUE TITLE
The addon doesn't report correctly the stop time to the amazon server

### ISSUE THREAD

**Issue by Paco8** [Sandmann79/xbmc#311]
I noticed that when I play a video with the amazon VOD addon, the primevideo apps know that I started to play the video but they don't know if I watched the video entirely or the point where I left it.

The function updateStream in playback.py should report the current position but I noticed that most of the times the timecode is 0.

I think the problem is actually in this part of the code:

```
        while not xbmc.abortRequested and player.running:
            if player.isPlayingVideo():
                player.video_lastpos = player.getTime()
                if time.time() > starttime + player.interval:
                    starttime = time.time()
                    player.updateStream('PLAY')
            sleep(1)
```

That loop is never run, because for some reason xbmc.abortRequested is true, so player.video_lastpos is never updated.

**Comment by Varstahl** [comment]
That would explain… quite a lot, actually. I didn't manage that portion of the code, but nice finding. I'll look into it hawaiian time.

**Comment by Paco8** [comment]
I read that xbmc.abortRequested is deprecated. Maybe it could be fixed this way?

```
--- playback-orig.py	2019-06-26 19:27:32.314635330 +0200
+++ playback.py	2019-06-26 19:27:57.399171329 +0200
@@ -430,13 +430,13 @@
         player.resolve(listitem)
         starttime = time.time()
 
-        while not xbmc.abortRequested and player.running:
+        while not xbmc.Monitor().abortRequested() and player.running:
             if player.isPlayingVideo():
                 player.video_lastpos = player.getTime()
                 if time.time() > starttime + player.interval:
                     starttime = time.time()
                     player.updateStream('PLAY')
-            sleep(1)
+            xbmc.Monitor().waitForAbort(1)
         player.finished()
         del player
         return True

```
It's working for me fine.

**Comment by Varstahl** [comment]
Makes sense, but we should have a static object. Thanks for the research, I should be able to test and edit this soon.

**Comment by Varstahl** [comment]
The update just went live. Even though it takes me an ungodly amount of time to even merge in your fixes, I just wanted to thank you once again for fixing the problem and reporting, really helped updating both Amazon and Amazon VOD.
