### ISSUE TITLE
Amazon Vod 0.7.4 - can't export in Kodi video library but in favorites only

### ISSUE THREAD

**Issue by Fabio8G2** [Sandmann79/xbmc#313]
Regarding Amazon vod version 0.7.4 on Kodi 18.3 installed on android it is impossible to export movies or TV series in the relative Kodi video libraries but only in favorites.  Once the amazon vod add-on is opened -> my videos -> series -> the context menu contains only refresh and add to favorites.

**Comment by Varstahl** [comment]
As stated in the readme:

> * access and edit Amazons Watchlist and Video Library (currently not available for primevideo)

As a workaround I'm well aware of the fact that certain addons exist, that allow you to export to library for addons that don't have the functionality yet, like [Library Integration Tool](https://forum.kodi.tv/showthread.php?tid=327514). There are others, but I don't remember the names.
