### ISSUE TITLE
White noise screen coming out of Amazon Vod plugin

### ISSUE THREAD

**Issue by Tuk72** [Sandmann79/xbmc#316]
Hi, I installed the Amazon Vod plugin recently, it seems to work perfectly until I stop playing, because after a few seconds if I don't start another file, I get a white noise screen!

This is a video of the problem:
https://youtu.be/-xM0_D1NpIE

This is the log file:
https://pastebin.com/gUG9BdzG

**Comment by Varstahl** [comment]
Delete `%AppData%\Kodi\userdata\addon_data\plugin.video.amazon-test\resume.db`, as there's a problem with that. As for the white noise that's something insane, looks like you maybe got some weird addon or something, nothing should work like that so I just don't know.

**Comment by Tuk72** [comment]
Ok, I deleted "resume.db" and I absolutely agree that there is something insane! The problem only occurs a few seconds after stopping the plugin, even if I come out of Kodi! It seems to be an error related to VGA or its driver, probably something unstable used by the plugin. If I connect remotely to the computer I see the screen perfectly ... I will try to play with Amazon Vod settings and if I do not resolve to reinstall it.

**Comment by Varstahl** [comment]
The plugin literally uses nothing, it's controlled by Kodi. The plugin only tells Kodi "here you can find the video", past that it's all on Kodi/IS.A. Did you enable "Override HDCP" in IS.A. settings by any chance?

**Comment by Tuk72** [comment]
I made an attempt with "Override HDCP" and every other plugin setting without getting any results. I closed Kodi and tried to play a movie on "Prime Video" with Firefox and Edge, I discovered that the problem is related exclusively to the reproduction of the movies on "Prime Video", I can reproduce anything else online and offline without problems! Mystery...

**Comment by Varstahl** [comment]
So you got the same issue even on browsers? That's one weird issue. Have you tried another device? Smart TV, mobile, whatever…

You might also try to contact Amazon support, though I don't have a quick link at hand.

**Comment by Tuk72** [comment]
Mystery solved, the problem occurs when the Widevine DRM module is unloaded from memory. I'll try to fix it in Firefox before trying again in kodi.

**Comment by Varstahl** [comment]
Ok, seems to be a system related issue. Closing this.
