### ISSUE TITLE
Failed login probably due to missing verification code

### ISSUE THREAD

**Issue by pank** [Sandmann79/xbmc#32]
Hi,

Recently `amazon.de` seems to require a "verification code" whenever I log in.  This code is sent to my email (I have not enabled 2 way authentication on Amazon).

When I try to log in in your amazon video plugin it fails now.  At the same time, I can see that I receive verification codes on my email.

I looked for ways to verify the box on my amazon account via a normal PC, but did not find a way.

Would it be possible to supply a verification code during the login procedure?

Thanks,

**Comment by johnygeorge** [comment]
I also have the same issue ?? Is there any fix for it ???

**Comment by Sandmann79** [comment]
To get rid of this message, you have to configure Two Step Verification at Amazon Webpage > Your Account › Login & security › Advanced Security Settings. 
After you have done this, you can safely disable Two Step Verification, if you don't want to use it.

**Comment by Sandmann79** [comment]
This issue should be completed with d4b42484484b0cc542094702accae631a9493bd9
