### ISSUE TITLE
The sections movies, shows and kids show no results

### ISSUE THREAD

**Issue by Paco8** [Sandmann79/xbmc#322]
I guess Amazon changed again the html. The watchlist and the search function still work, but I noticed that when I try to browse the other sections (movies, shows and kids) it displays an empty list. 
There's no error in the log.

**Comment by Varstahl** [comment]
Probable, which is why we're moving away from it. I'm just not done with it though.

**Comment by Paco8** [comment]
I fixed it partially with this patch:
```
--- primevideo-orig.py	2019-07-31 22:13:40.175048136 +0200
+++ primevideo.py	2019-07-31 22:14:00.402793839 +0200
@@ -609,7 +609,7 @@
 
             for t in [('\\\\n', '\n'), ('\\n', '\n'), ('\\\\"', '"'), (r'^\s+', '')]:
                 cnt = re.sub(t[0], t[1], cnt, flags=re.DOTALL)
-            if None is not re.search('<div id="Storefront">', cnt):
+            if None is not re.search('<div\s+class="DVWebNode-storefront-wrapper|<div id="Storefront">', cnt):
                 ''' Categories list '''
                 Log('Storefront page', Log.DEBUG)
                 from BeautifulSoup import BeautifulSoup
@@ -648,7 +648,8 @@
                             else:
                                 # Widow carousel with movies/TV series. Most information has been stripped away from
                                 # the carousel, so we can't do more than just forwarding a request
-                                requestURLs.append((link, o[title], ExtractURN(link), True))
+                                if None is re.search(r'/search/', link):
+                                    requestURLs.append((link, o[title], ExtractURN(link), True))
                     else:
                         ''' The carousel has explore link '''
                         NotifyUser(getString(30253).format(title))
```

I didn't fix the "Genres/Categories" links.

I also noticed another problem, the addon crashes when scanning shows with a single season. This is because amazon changed **class="_2XnrBy"** with **class="_3yWnmV _2XnrBy"**.

I fixed it by replacing "_2XnrBy" with ".*?_2XnrBy"

**Comment by sheldonmaschmeyer** [comment]
How do you install and use patch? I also have movies, shows and kids show no results. When typing in Star Trek, it says in the top right corner that it found Into Darkness but, does not appear in results list.

**Comment by sanangel** [comment]
@Paco8 
How and where do you put your patches?
Gracias.

**Comment by Paco8** [comment]
I attach the patched primevideo.py:

[primevideo.zip](https://github.com/Sandmann79/xbmc/files/3491343/primevideo.zip)

**Comment by sanangel** [comment]
Thanks @Paco8 working perfecto.
Gracias!!!!

**Comment by Surajpd** [comment]
Hi @Paco8,
Thanks for the updated Amazon VOD repository. This refreshes all movie contents flawlessly.
However while playing movies, I find that no Video is displayed. Instead the screen is filled with colours with some static disturbance at the top. I tried to toggle with the video settings to no avail. Audio works pefectly. Will be grateful if you have any suggestion for this. I am accessing from India. Thanks in advance.

**Comment by rytecbe** [comment]
> 
> 
> I attach the patched primevideo.py:
> 
> [primevideo.zip](https://github.com/Sandmann79/xbmc/files/3491343/primevideo.zip)
> 
> I also have this repo with my modifications:
> https://github.com/Paco8/kodi-repo/tree/master/packages

Hello Paco8, how to install the patches please? With FTP and which folders?

Thank you.

**Comment by Paco8** [comment]
Extract primevideo.py from primevideo.zip, and copy it to plugin.video.amazon-test/resources/lib/ replacing the original one.

**Comment by sanangel** [comment]
@Paco8 I have put a link to this topic in the kodi forum. I hope that doesn't create any problem ...
https://forum.kodi.tv/showthread.php?tid=331136&pid=2877470#pid2877470

**Comment by Crancker969** [comment]
> I attach the patched primevideo.py:
> 
> [primevideo.zip](https://github.com/Sandmann79/xbmc/files/3491343/primevideo.zip)
> 
> I also have this repo with my modifications:
> https://github.com/Paco8/kodi-repo/tree/master/packages

Thanks @Paco8 working perfecto.
Gracias!!!! eres un fenomeno

**Comment by Fabrizio-93** [comment]
how do i install on kodi? You can help me?

**Comment by Paco8** [comment]
I guess you can install this package:
https://github.com/Paco8/kodi-repo/raw/master/packages/plugin.video.amazon-test/plugin.video.amazon-test-0.7.4%7Ebeta-20190912.zip

**Comment by Paco8** [comment]
By the way, it seems amazon made changes again and I think the code which gets the season number from the episode list is broken again.

I made a patch which gets the season number from the json data in case the regular expressions above fail. I attach the patch and the modified primevideo.py

[primevideo-fix.zip](https://github.com/Sandmann79/xbmc/files/3637389/primevideo-fix.zip)

**Comment by Markef80** [comment]
Hi all

I had installed the path of August and it worked.
After an absence, I had another mistake.
So I installed the patch of September.
I have no more error but the directory is empty ...
Thanks for your help.
