### ISSUE TITLE
AmazonVOD Still Green

### ISSUE THREAD

**Issue by katjap** [Sandmann79/xbmc#323]
This is probably related to issue #136 
I just installed the AmazonVOD plug-in for the first time today on a Pi 3B+. Any DRM-protected videos playback as a chunky green screen. Audio and subtitles play ok. Stream selection is set to auto. Tried max resolution of Auto, 720p, and 480p. 
![IMG_20190804_135935088](https://user-images.githubusercontent.com/3036629/62429259-7044a100-b6c1-11e9-85a1-5058cf8fae3e.jpg)
Debug Log:
[kodi.log](https://github.com/Sandmann79/xbmc/files/3465324/kodi.log)

**Comment by Varstahl** [comment]
The addon's working as intended. It seems to be identical to last year's problem, so it will probably need a binary update for either Kodi, IS.A or video libraries on the RPi3.

What you can do, if it helps, is try to enable/disable the "Override HDCP". In theory you should keep Override HDCP disabled, so in auto you would reach 480p at maximum. If that still has problem then it's a problem on the decoding/decryption chain, can't help you there.

**Comment by katjap** [comment]
"Override HDCP" On/Off made no difference at all.
