### ISSUE TITLE
Unable to login on error, Kodi Matrix

### ISSUE THREAD

**Issue by Varstahl** [Sandmann79/xbmc#335]
~Upon error during login with the latest nightly, credentials are never asked again. With `Store credentials` disabled the only way is to go to `Settings > Connection > Remove credentials and cookie` and then try to login again.~

Not our error, but still fixed in 17ae68a2bc105121a039f68bc0582cb18c1a5cc9. Ain't nobody got time to wait for Kodi fixes.

**Comment by Varstahl** [comment]
Also the `_Captcha` class is invalid and causes an error while triggering on PrimeVideo:

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
        - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <class 'AttributeError'>
    Error Contents: '_Captcha' object has no attribute 'background'
    Traceback (most recent call last):
        File "…\addons\plugin.video.amazon-test\default.py", line 5, in <module>
        EntryPoint()
        File "…\addons\plugin.video.amazon-test\resources\lib\startup.py", line 102, in EntryPoint
        exec('{}()'.format(mode))
        File "<string>", line 1, in <module>
        File "…\addons\plugin.video.amazon-test\resources\lib\network.py", line 488, in LogIn
        br = _MFACheck(br, email, soup)
        File "…\addons\plugin.video.amazon-test\resources\lib\network.py", line 350, in _MFACheck
        wnd = _Captcha((getString(30008).split('…')[0]), soup, email)
        File "…\addons\plugin.video.amazon-test\resources\lib\network.py", line 576, in __init__
        self.setGeometry(500, 550, 9, 2)
        File "…\addons\script.module.pyxbmct\lib\pyxbmct\addonwindow.py", line 746, in setGeometry
        self.background.setPosition(self.x, self.y)
    AttributeError: '_Captcha' object has no attribute 'background'
    -->End of Python script error report<--
```

**Comment by Varstahl** [comment]
It seems that in the first case, the keyboard modal window shuts down by itself, while in the second case it looks like some weird behaviour doesn't initialize the inherited class.

**Comment by Varstahl** [comment]
Keyboard prompts twice, canceling each other, also 2 territorial config requests are launched.

**Comment by Varstahl** [comment]
The _Captcha error is possibly due to a bug in PyXBMCt or some misconfiguration ([reported here](https://forum.kodi.tv/showthread.php?tid=174859&pid=2893601#pid2893601)). Solved by reversing `AddonDialogWindow` inheritance list inside `script.module.pyxbmct/lib/pyxbmct/addonwindow.py`:

```py
class AddonDialogWindow(AddonWindow, DialogWindowMixin):
```

**Comment by Sandmann79** [comment]
Seems a common problem with some addons in offical repo. As example myconnpy and autocompletion are not really python3 compatible for now.

**Comment by Varstahl** [comment]
I'm not sure, Roman said he'll look into it, in the meanwhile applying that small change fixes everything, so I didn't investigate any further. It might be an issue at the C level, because superclassing only triggers the first ancestor instead of all of them. In this case it's insignificant because `DialogWindowMixin` doesn't have an init, so even if it doesn't gets called it's a non issue.
