### ISSUE TITLE
No movies or tvshows under any category (HTTP 410 error)

### ISSUE THREAD

**Issue by bread-on-toast** [Sandmann79/xbmc#339]
When opening the Plugin all options (Movies...) exept of the Watchlist will show no entries.
From the log it seems that Amazon changed the URLs as it returns just a "HTTP 410 Gone":

`2019-10-27 17:53:04.982 T:2281698160  NOTICE: [Amazon VOD] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=XXX&deviceID=XXX&format=json&version=2&formatVersion=3&marketplaceId=XXX&IncludeAll=T&AID=1&OrderBy=Title&OfferGroups=B0043YVHMY&contentType=Movie&NumberOfResults=40&StartIndex=0&Detailed=T&mobileClient=true
2019-10-27 17:53:05.229 T:2281698160  `
` ERROR: [Amazon VOD] Error reason: 410 error (NoRetries)`

**Comment by debutanker** [comment]
Theres already a lot of action in the development-branch and it seems, that this issue has been already recognized -> https://github.com/Sandmann79/xbmc/commit/0ee91bdcd119ea713644b4bd6ecda60934f4cd49
So we only need to have a little patience till next release...

**Comment by bread-on-toast** [comment]
I looked for 410 in the issues only. 
Closed :)

**Comment by Sandmann79** [comment]
Just reopen as Information for other users.

**Comment by loeffelpan** [comment]
Nice, the dev branch solved this for me.
But I miss episode fanart.
Never used this addon before. Should this type of fanart be scraped?

**Comment by Steph71** [comment]
> 
> 
> Nice, the dev branch solved this for me.
> But I miss episode fanart.
> Never used this addon before. Should this type of fanart be scraped?

What would be the recommended way to install the dev branch (with the dependencies) into kodi ?

**Comment by loeffelpan** [comment]
Not as easy as other addon, because it's not released yet,
I extracted the relevant folders from the whole repository ZIP and zipped each of them to dedicated zip files. I had to install these two. Rest comes from Kodi and Kodinerds repo.

[plugin.video.amazon-test.zip](https://github.com/Sandmann79/xbmc/files/3785324/plugin.video.amazon-test.zip)
[script.module.mechanicalsoup.zip](https://github.com/Sandmann79/xbmc/files/3785325/script.module.mechanicalsoup.zip)

**Comment by elarei** [comment]
I've been struggling to make this addon work for about a day now. Thanks to this post by loeffelpan I got the episodes/movies to finally show up, but still cannot play any of them (it looks like it's going to start for a brief moment, then it just hops back to the menu without any error). Are you using "Amazon" or "Amazon VOD"?

**Comment by Steph71** [comment]
with the packages from the dev branch I was also able to see the the videos and series, but cannot play them due to some authentication issue. Then I logged my user out, but trying to log in again I run into an MFA authentication issue ... that I am now stuck with ... 

[log.txt](https://github.com/Sandmann79/xbmc/files/3785645/log.txt)

**Comment by bread-on-toast** [comment]
I can confirm the MFA/Captcha issue but maybe it's just Amazon preventing too many "reauthentications" due to the numerous reinstalls of the plugin I did today?

**Comment by Varstahl** [comment]
@elarei without logs I can't really help you there. You can find more info on [what to enable and where the files are in the FAQ](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi)
@Steph71 what country are you watching it from? 

@Sandmann79 are you aware of any recent captcha changes? It worked fine up to last time I logged in a couple days ago.

**Comment by debutanker** [comment]
Have had the same problems with log in and the dev branch.
"Remove Credentials and Cookie" did the trick for me...

**Comment by bread-on-toast** [comment]
@Varstahl 
solved the login problem by now and finaly see the entries again. Neverles I can not play the videos. Might be because I live in germany... 
[kodi.log](https://github.com/Sandmann79/xbmc/files/3785878/kodi.log)

**Comment by debutanker** [comment]
@bread-on-toast 
Have you tested with the latest commits integrated? ( https://github.com/Sandmann79/xbmc/commit/871f6e65a7258f46167457f3c36e305515bb1691 )
Also in germany here and with this commit, playback is fine again for me.

**Comment by bread-on-toast** [comment]
@debutanker I used the zip files from loeffelpan.. after a checkout from that commit and installing it, it worked

Thank you very much!

**Comment by Sandmann79** [comment]
@Varstahl no there's no new captcha form. Amazon added only a "Fixup Account" page, where you can leave your mobile phone number. I wrote some code about it, but didn't get this page again to test. However login with MFA works for me too. It's like @debutanker mentioned, you have to remove credentials, if you switch to dev branch.

**Comment by r-oldenburg** [comment]
Hi there,

I tried getting the branch version add-py3 working, but after logging in and entering the captcha it failed with this log:

```
2019-10-30 22:02:49.478 T:1937102144   DEBUG: ------ Window Deinit () ------
2019-10-30 22:02:51.009 T:1375630192  NOTICE: [Amazon VOD] network.py:311 MFA, DCQ or Captcha form
2019-10-30 22:02:51.125 T:1375630192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not callable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 102, in EntryPoint
                                                exec('{}()'.format(mode))
                                              File "<string>", line 1, in <module>
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 516, in LogIn
                                                br = _MFACheck(br, email, soup)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 370, in _MFACheck
                                                cs_hint = msg.find('div', attrs={'class': 'a-row'}).contents[0].strip()
                                            TypeError: 'NoneType' object is not callable
                                            -->End of Python script error report<--

```

I guess there is something different in the answer than expected. Too bad...

Still: Thanks a lot to all contributors!!!!

**Comment by Steph71** [comment]
exactly the same error on my side

**Comment by elarei** [comment]
You could try activating 2FA on the Amazon website. That did the trick for me (although I am not sure why).

**Comment by r-oldenburg** [comment]
Indeed! It did help!!!
So that route seems to be implemented correctly, but the one wihout 2FA not yet.

btw: I did activate 2FA, then logged in and then deactivated it again on amazon as I don't want it on all my devices...

**Comment by Steph71** [comment]
Can also confirm, enabling mfa solved the login issue ... and the dev branch fixes the 410 Error.

Thanks to all for the support

**Comment by plaetzchen79** [comment]
It think it would be nice if someone can publish a new (minor) version with just those fixes.

Its not easy for everyone to install those zip-files or to use the py3 branch.

Thanks for your hard work!

**Comment by Varstahl** [comment]
Seriously, it's not that hard. Grab [this zip](https://github.com/Sandmann79/xbmc/archive/add-py3.zip), extract it, zip the directories you need in their own zip, install them on Kodi. Install MechanicalSoup first, then update the addon. Done.

**Comment by wildcat2020** [comment]
> Not as easy as other addon, because it's not released yet,
> I extracted the relevant folders from the whole repository ZIP and zipped each of them to dedicated zip files. I had to install these two. Rest comes from Kodi and Kodinerds repo.
> plugin.video.amazon-test.zip
> script.module.mechanicalsoup.zip

Please note that when trying to install the development version: plugin.video.amazon-test.zip it fails because Mcafee On-Access Scan deletes userinput.exe as being Trojan.

Please keep this in mind for the production version.

**Comment by Varstahl** [comment]
False positive, nothing new to see here.

**Comment by sidey79** [comment]
@Varstahl 
Thanks for this small guide.  I've grabbed the zip and installed the addon on my odroid.
I also needed to enable mfa for my amazon account to be able to login. But now, i can look movies via kodi again :)

**Comment by robcast** [comment]
Using the add-py3 branch zips worked for me! 💯 
But I needed to name the zip files with a version number i.e. `script.module.mechanicalsoup-0.0.1.zip` or I would get an error about "invalid structure" when using "install module from zip". Just in case someone has the same problem ;-)

**Comment by Varstahl** [comment]
Hmm, strange, I don't think that'd be a problem, in fact I've tested it on both Leia and Matrix without version number. But, that would be easily explainable if you forgot to include the main directory `script.module.mechanicalsoup` in the zip file. That's what causes that issue usually.

**Comment by dromagnoli** [comment]
Hi :)
I know that it could be obvious when reading "add-py3" -> py3 meaning python 3.x :P
At the beginning, I didn't pay attention to that so once copying the latest amazon plugin from that zip file I finally managed to have the movies and tv series lists properly populated but video playing stopped working.
Checking the logs I have seen ERROR messages with:
typeError hex() argument can't be converted to hex 
So I thought that it could have been related to using a wrong python version.

I solved the issue by modifying the /usr/bin/python symlink switching it to point python3.5 instead of python2.7 and I got video working again :)

I'm reporting my experience in case anyone has my same issue.

That being said, thanks a lot for your hard work on that with these great plugins.

**Comment by Varstahl** [comment]
Hmm, that is strange. Actually it should work (and is working) with both Python 2.7 and Python 3, more specifically Kodi 18 with Python 2.7 and Kodi 19 alpha with Python 3.xx. The py3 just means it's py3 ready, not that it's py3 only.

Didn't test it on Linux though, there might be something going on there that I didn't notice or took care of, thanks for reporting this.

**Comment by dromagnoli** [comment]
FYI: I'm using OSMC on a Raspberry Pi3.

**Comment by Varstahl** [comment]
Heh, no good tale on this project ever started with "I was using OSMC and everything was fine". Figures, I should've guessed, haha.

**Comment by dromagnoli** [comment]
Ah ah... I have only spent a few hours this weekend surfing on the web looking for something like 
"Amazon Prime Video on Raspberry pi3" and I have found an old walkthrough with some steps to do that, based on OSMC. Then, I have started hammering it to have it work :D 
Almost wiped the memory card 3 times before getting some result.
In the meantime my wife was hearing my "WTF... WTF... PP..." and she was still saying "why not simply using the laptop to see a movie?!?" ... 
Because I like challenges and having a simple raspberry box behind the TV with Retropie and a movie player is better than taking the laptop, plugging the hdmi cable, plugging the power supply and so on, fight with windows updates ... 

Sorry for the offtopic. 
Back in topic:
Do you have any better suggestion to have Amazon Prime Video on a Raspberry Pi 3?

**Comment by Varstahl** [comment]
That would be [LibreElec](https://libreelec.tv/). Only tested it a couple times, but I recommend it each time people comes here using OSMC, it's been working great so far for the past couple years.

**Comment by sjetesjete** [comment]
Can you please make a rough guess when updates will be available through Libreelec Frontend without the hassle to update those libs manually?

**Comment by Varstahl** [comment]
When #345 is done plus a couple more fixes for Prime Video. If I can spare the time and everything goes right? A few days. If I can't find the time due to job/family? A couple weeks.
