### ISSUE TITLE
Latest update results in blank watchlist

### ISSUE THREAD

**Issue by mfarley281** [Sandmann79/xbmc#34]
Since we updated (Aug 8?), the Watchlist appears empty. I've tried logging out and logging in, no change. The issue exists on both our HTPCs.  (this is on a U.S. account)

**Comment by Sandmann79** [comment]
Should be fixed with 9770abdcc0ade47b6f7f535d3d66967ab9ca42fc. 
Please test and report back.

**Comment by mfarley281** [comment]
Confirmed working. Is there a link to donate to this plugin? (Thank you!)

**Comment by mfarley281** [comment]
Confirmed working. Is there a link to donate to this plugin? (Thank you!)

**Comment by Sandmann79** [comment]
You are welcome to donate. Donation Link: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=BSSACTP7G6Q3A

**Comment by mfarley281** [comment]
Sent! Thank you! Our family really enjoys this plugin. (especially the kids)
