### ISSUE TITLE
OTP needs to be entered

### ISSUE THREAD

**Issue by marcusobrien** [Sandmann79/xbmc#342]
Hi, 

Everything was working fine until Amazon froze my account thinking it was hacked but thats another  story. 

While my account was frozen I am trying to switch to a different account which is valid, When I am trying to log in to the Prime VOD plugin on OSMC I get sent a OTP (one time password) to my mobile, as the OSMC Pi is a new device unregistered on the account, There is no way to enter this OTP, so how can I authenticate my account on this device ?

**Comment by Sandmann79** [comment]
Please follow this [instructions](https://github.com/Sandmann79/xbmc/issues/343#issuecomment-549246720), to get current development version. This should fix your issue.
If not, please upload kodi.log and avod-login*.log log files here. Don't forget, to remove your email adress from these logs.
