### ISSUE TITLE
No more episodes are found.

### ISSUE THREAD

**Issue by MrMilk23** [Sandmann79/xbmc#343]
Hello
I reinstalled Windows 10 and Kodi today and wanted to reinstall Amazon VOD.

I did everything normally.
Install Repo, install VOD, login.

Then I wanted to add series from my watchlist which doesn't work. No episodes are displayed and the series is not exported.

When I go to Fear The Walking Dead I only see an empty list.

For movies it works. (Watching and Export)

Log:
http://batman.gyptis.org/zerobin/?bd6676e6748fe025#N/3bLBVcxcHatmONftEUNWK9HhIf5aifaYrbXNSPCeE=

**Comment by Varstahl** [comment]
The current version is broken, you should grab the [add-py3  repo](https://github.com/Sandmann79/xbmc/tree/add-py3) zip, and create two zip files, one with mechanicalsoup directory and the other with the amazon-test directory. Install via zip the mechanicalsoup first, then the amazon-test, and some things will be working correctly.

There are a number of backward incompatible changes and disruptions with the next update, we're making sure we're doing it properly.

If you're a primevideo.com user, note that some categories will show empty just as watchlist at the moment. General categories and search should work fine though.

**Comment by MrMilk23** [comment]
How can I create a Zip?
I don't quite understand this

**Comment by Varstahl** [comment]
[Grab the repo zip](https://github.com/Sandmann79/xbmc/archive/add-py3.zip), extract it somewhere on your PC, then create two zip archives. One should be named `script.module.mechanicalsoup.zip` contain the directory `script.module.mechanicalsoup`, while the other should be `plugin.video.amazon-test.zip` that should contain the directory `plugin.video.amazon-test`.

**Comment by re4dy2** [comment]
Movies show up after this, but now I get a credential error for Amazon Prime Germany and login does not work. After entering email and password it asks for a captcha. In 90% of the cases its completly unreadable or, if readable, login is still not accepted.

**Comment by Varstahl** [comment]
Try to go into settings, clear credentials, and try to login again.

**Comment by Sandmann79** [comment]
@re4dy2 login should now work with commit cc98003d2dbafe2e9fa0bfab224f50c3df2b4eb3

**Comment by Sandmann79** [comment]
By the way this issue is the same as #339

**Comment by yknivag** [comment]
Does anyone know when the fix for the HTTP 410 error when trying to list episodes will be released into the repository?

Or will it always be necessary to patch from zip?

**Comment by Varstahl** [comment]
Given the number of changes needed, I suppose a week or two. We're near-ish.

**Comment by re4dy2** [comment]
Unfortunately it does not, now I am in a loop where the App continuously asks for password, captcha followed by a one time password send to email. 

I deleted the app including credentials and reinstalled with newest commit from python branch.

> 
> 
> @re4dy2 login should now work with commit [cc98003](https://github.com/Sandmann79/xbmc/commit/cc98003d2dbafe2e9fa0bfab224f50c3df2b4eb3)

**Comment by Sandmann79** [comment]
Did you enabled "Store Credentials instead of using the Cookie?" at settings? If so, please disable it.
For now this setting is useless, because Amazon ask always for captcha, even if remember device is set.

**Comment by re4dy2** [comment]
> 
> 
> Did you enabled "Store Credentials instead of using the Cookie?" at settings?

No, that was disabled all the time.

**Comment by 5093** [comment]
Hey folks,

awesome job, putting together and maintaining this marvellous piece of SW.
Especially given how much Amazon behaves like an hermit kingdom (assuming there is lil technical doc made public on how their shiad works), credits to you for managing to tap into that nonetheless ! Guys, cudos !!

Got a few brief q's:
1. This OTP issue came back. Since yesterday I was trying to find my way around it. That old 2zip trick did work again. However, any clue as to why that keeps happening - anything I could do (maybe on my amazon account's side) to help circumvent ?

2. That feature "Store Credentials instead of using the Cookie?" is nowhere to be found (any longer).

My gear: RPi 3B+, Amazon VOD 0.8.2~beta, OSMC 2020,01-2, Kernel 4.19, Kodi 18.5
No crzy mods or other modifications, just basic stuff.


Thats the lil 2zip trick I was referring to: 
> 
> 
> [Grab the repo zip](https://github.com/Sandmann79/xbmc/archive/add-py3.zip), extract it somewhere on your PC, then create two zip archives. One should be named `script.module.mechanicalsoup.zip` contain the directory `script.module.mechanicalsoup`, while the other should be `plugin.video.amazon-test.zip` that should contain the directory `plugin.video.amazon-test`.

**Comment by Varstahl** [comment]
As soon as we push the next release, the issue will be gone. As for the store credentials, it's insecure and most likely has been removed for safety.
