### ISSUE TITLE
Roadmap for the next release

### ISSUE THREAD

**Issue by Varstahl** [Sandmann79/xbmc#345]
@Sandmann79 I've been thinking a bit about the current situation and I wanted to propose some ideas (to be evaluated). Given the current status and the incoming breaking changes, I thought we could do a few things, listed in no particular order:

- **Partially scrapped:** will rename to `amazonvod` on the official repos only.
Change the plugin name from `plugin.video.amazon-test` to `plugin.video.amazonvod`. Given the number of breaking changes, especially in the primevideo area, this should prove somewhat beneficial. It should reduce the number of false issues and general confusion caused by people who see it as the "test version" of the Amazon addon. The same thing happened when I mentioned the two addons in the Matrix Py3 addon compatibility and they only listed the first one thinking that avod is the test/development one >_>
- **Pending.**
With the binary dependency gone, we could request the main amazon addons to be put into the official Kodi repositories. Haven't 100% checked the requirements yet, but it should be a no brainer. I'll look into that.
- **Pending.**
Finally update the readme, #288. There's some stuff I need to add/change related to primevideo and its issues, so it's a good time to update it as soon as the next version's ready.
- **Done:** bfbd51bfab7e2aacb9b4d7e7cf65122ad8363d0a, [userinput](https://github.com/Sandmann79/xbmc/releases/tag/v0.7.5-ui).
Drop the `tools/userinput.exe` from the main addons. Since it's shared, platform specific, and often mistook for malware, we could detach it from the main releases and provide it as an external plugin/zip to be manually downloaded if needed. I'd go on a wild limb and assume that about 95% of our users have no need for it, especially considering it's windows only. This way we could fix a lot of false positives and issues, stop causing problems to our users, and still provide the same functionality for those who need them. Or you could talk to Google to whitelist it :D
- **Done.** 03f255e1ebe8829f157fdc88308d8091c6b1b854
Create a standard issue format for GitHub. This should help both us and the users, so that they can provide the information we need straight off the bat. Should be fairly simple for GitHub, I can tinker with it to cover the basics.
- **Partially done:** 66540a1452dd68a74ee01f3270c92171e34a565d, JSON data doesn't update itself yet.
#340 craft a tiny user agents scraper to host on our own servers as to not strain other people's servers.

I didn't mention the repository generated from releases in this list because I was focused on restoring functionality to the addon, so I temporarily halted the efforts on that front (that, and the fact that I have no way of actually contacting you in private to provide secure endpoints and tokens, but that's another matter). JFYI I'm available on a number of platforms, including Telegram, Discord, Twitter, Twitch or even by e-Mail, just let me know where I can reach you.

Other ideas? Opinions? Looking forward to hearing from you.

**Comment by Sandmann79** [comment]
1) That's generally a good idea. Hadn't done that until now, since many users export titles and these would then lead into emptiness 
To avoid confusion, i would only add the `Amazon VOD` Addon to the official repo. That's the most used for all users  and in the git readme we can refer to the ID after the title of the addon.
Currently, i am considering discontinuing the `Amazon` Addon - the db update is always causing problems.
2) You're right that have to be updated. 
3) Thats a very good idea. I think we should initiate an automatic download, if the file is needed. That's better than providing an seperate plugin and does the work in the background.
4) See 1.
5) Yep, no more wasting time on requests for logs or something else.

You can reach me at Telegramm `@Sandmann79`. But you have to give me some time to answer - you know my english is terrible :wink:

**Comment by Varstahl** [comment]
Okie dokie, und keine problem :)

**Comment by Varstahl** [comment]
I was just reading back at the issue, and I think it should be fairly easy to setup a simple url forwarder using the plugin name of `plugin.video.amazon-test` and just changing its title to something like, "AVOD export compatibility" or something like that. That should allow to change things while impacting nobody.

**Comment by bacon-cheeseburger** [comment]
All of the originally proposed changed sound great. I don't however agree with Varstahl that the plugin name should remain "plugin.video.amazon-test" and just change its title. Users don't only look at plugin titles and it would certainly cause confusion for some with a "amazon-test" plugin in the official repo. I haven't heard any good argument in favor of keeping "plugin.video.amazon-test", or any good argument against simply renaming it to the originally proposed "plugin.video.amazonvod". The latter makes the most sense and is what you'd expect to find in an official repo. If you're going to fix these issues then don't half-ass it. Proper fixes are always better for everyone.

**Comment by Varstahl** [comment]
No, @bacon-cheeseburger, you misunderstood. We **are** going to rename it to `*.amazonvod`, but @Sandmann79 mentioned that there would be issues for current users, since on exported libraries and such you would have links like `plugin://plugin.video.amazon-test/Play?<params>`. So if we can't do it programmaticaly the first time we launch the addon, we could create an off-repo amazon-test, so that users can upgrade without losing all their content and rendering their libraries useless. That's all.

**Comment by loeffelpan** [comment]
Maybe another enhancement for next release:

In my Kodi setup I use the option named „Jump to first unwatched episode“. Works fine in my library.

I was wondering if there is any way to get that feature in an video addon (e. g. Amazon)?

Is this a core function (outside library) or needs this an implementation in your addon?

**Comment by loeffelpan** [comment]
Just found this:
https://github.com/CastagnaIT/plugin.video.netflix/issues/69

I don‘t expect, that kodi devs will add that to their core function.
Maybe you can add this by yourself in your addon?

**Comment by Varstahl** [comment]
I was just answering you the same, both the library view and the playback (including resume times) are handled by Kodi itself. That means that these kind of features are specifically controlled by Kodi itself rather than the addon. I might propose/develop the feature for Kodi itself, but atm it's very unlikely I can find the time to do that.

**Comment by loeffelpan** [comment]
Sadly, but thanks for your answer.

**Comment by Varstahl** [comment]
@Sandmann79 I've been doing some thinking, and the change from amazon-test to amazonvod doesn't make sense as we stand.

We need to create another repo for module & plugins, otherwise we can't push to official repo, so in any case we need a different structure. With that being the case we can have the `…-test` in this repo as usual for faster releases and the `…vod` in the official repo. Seems like the best idea, so we could also sideload both version for development/debug.

I'm mostly done, so I think I'll be doing some writing for the READMEs and then I'll create a release and a PR to master as soon as I'm done. It's about time.

**Comment by Vikassm73** [comment]
It will be better to add "Year" in the Movie Title. That will help to us to filter movie by "Year" from the long list.

**Comment by loeffelpan** [comment]
I opened a feature request for „Jump to the first unwatched episode in addons lists“.

https://forum.kodi.tv/showthread.php?tid=349233
