### ISSUE TITLE
HTTP-Error

### ISSUE THREAD

**Issue by ChromaFrank** [Sandmann79/xbmc#347]
Hi!
I hope I do not post a stupid question here.
The Addon was working fine until yesterday. Suddenly it was no longer able to play a file and it stopped with an HTTP-error.

Any idea what is happening here?

I am running Libreelec 9.0.2 on a Raspberry 3.

Thanks for the good work! Was enjoying Amazon withou using Amazon-hardware.

Best regards,

Zeckito

[kodi.log](https://github.com/Sandmann79/xbmc/files/3843473/kodi.log)

**Comment by Sandmann79** [comment]
You should upgrade LE to Version 9.2 (Kodi 18.4) and grab the current addon versions from add_py3 branch. To do it, you can follow [these Instructions](https://github.com/Sandmann79/xbmc/issues/343#issuecomment-549246720) or download it [here](https://www.kodinerds.net/index.php/Thread/44211-Release-Amazon-Prime-Instant-Video/?postID=552870#post552870).
The old/stable addon versions are not working anymore

**Comment by ChromaFrank** [comment]
Hi Sandman,

Thanks, worked out without problems! Great work! Thumbs up for your effort!
