### ISSUE TITLE
SSH Handshake Failure

### ISSUE THREAD

**Issue by lodzen** [Sandmann79/xbmc#35]
If i try to open the Amazon VOD addon the URL: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/ can't be opened because of an SSL Handshake error.
I'm running Kodi 17.4 on a QNAP NAS.

This is the error log:
[kodi_amazon.txt](https://github.com/Sandmann79/xbmc/files/1308690/kodi_amazon.txt)

**Comment by Sandmann79** [comment]
This is a common error with an outdated python version. 
You have to update your python to version 2.7.9 or greater.

**Comment by lodzen** [comment]
Thanks for your reply. I'am using python version 2.7.12.Am 17.09.2017 18:03 schrieb Sandmann79 <notifications@github.com>:This is a common error with an outdated python version.
You have to update your python to version 2.7.9 or greater.

**Comment by Sandmann79** [comment]
Okay can you check your openssl version and tell me the os, that runs on your nas?

**Comment by lodzen** [comment]
The OpenSSL Verison is 1.0.2.k 26 Jan 2017. The NAS is a QNAP running QTS 4.2.6 build 20170905.

**Comment by Sandmann79** [comment]
I uploaded an commit 27df88b35d40e086244c3a7d0ac8940ae8b27d3b today, that should fix your issue. Please try it and report back.

**Comment by lodzen** [comment]
Thanks for the commit. I tried the fix but unfortunately my Kodi17 version uses python 2.7.6. 
Therefore a SSL/TLS connection is impossible.
Can you tell me how i can force Kodi to use my python 2.7.12 library?

**Comment by Sandmann79** [comment]
You can try this solution provided here: http://kodi.wiki/view/HOW-TO:Upgrade_Python_interpreter_on_Linux

**Comment by Sandmann79** [comment]
No feedback und no Add-on related bug - closing.
