### ISSUE TITLE
Cannot "rethink" e-mail address from the captcha dialog

### ISSUE THREAD

**Issue by mirh** [Sandmann79/xbmc#351]
**Amazon Account (select one)**
- [x] amazon.it

**System Setup (please provide the following information):**
- OS Version: Windows 7
- Kodi Version 18.4
- Addon 0.7.5

**Describe the bug**
Try to log in with a wrong account email. 
Get presented with the captcha dialog. 
Figure out the right email address was another one. 
Try to correct it, but the program still always employs the first one until you get out and retry from start.

**Comment by Varstahl** [comment]
I'm sorry I'm not sure I fully understand. When the captcha presents itself it's autofilled but you can still change it. What's the issue exactly?

**Comment by mirh** [comment]
It is autofilled - and it is "shown to change" when you edit it. 
But the new isn't ever POST to amazon (and when it fails back telling you "no account existing" the first one is shown again)

**Comment by Sandmann79** [comment]
Amazon added some times ago a second email field. That's the reason, why in the old version with Mechanize an error accoured.
Now with Mechanicalsoup the wrong wrong field gets filled.
Fixing this soon.

**Comment by Sandmann79** [comment]
After a little research, it's not as easy to solve as I thought. 
Since only the name of the input field can be used and both have the same name, I don't know how to change the second field.
So it's easier for me to disable the email field for input.

**Comment by Varstahl** [comment]
Is it a selector problem with Kodi or Amazon? May I help in any way?

**Comment by Sandmann79** [comment]
The problem are this input fields here:
```
<input name="email" type="hidden" value="**@**"/>
<div class="a-input-text-wrapper hide" data-claim="**@**"><input autocomplete="email" id="ap-credential-autofill-hint" name="email" type="text" value="**@**"/></div>
```
With MS i can only change one email control, because `form.set` or `form.set_input` accept only the name attribute, nothing more. So i don't know how to change the email in both controls.
But, i don't know if it's worth the effort, because it's easier to cancel the dialog and start the login from the beginning.

**Comment by Varstahl** [comment]
Yeah, I just checked that, it's a pretty wild and arbitrary limitation. Short of modifying MS and submitting a PR to allow selectors, we're better off bunny hopping the issue.

**Comment by mirh** [comment]
Chain open an issue on them then /s
