### ISSUE TITLE
Login errors

### ISSUE THREAD

**Issue by knappster1** [Sandmann79/xbmc#353]
**Amazon Account (select one)**

- [x ] amazon.com

**System Setup (please provide the following information):**
- Hardware: [PC]
- OS Version: [Arch Linux]
- Kodi Version [18.1] (I've also tried on 18.4, but the logs came from 18.1)
- Addon [e.g. amazon-test]

**Upload Logs**
avod-login.log https://pastebin.com/Qi3m7taJ
avod-login-mfa.log https://pastebin.com/d8Ace8Q9

**Describe the bug**
When I login, I get the Captcha screen.  If I get the Captcha wrong, I get the "Wrong Code" message (which makes sense).  If I get it right, I get a popup titled "We're sorry!" followed by the body:

> An error occurred when we tried to process your request.  Rest assured, we're already working on the problem and expect to resolve it shortly.Go to Amazon.com'sHomePage

I've attached the avod-login logs and in principle, I am happy to upload a debug log, but it seems to contain login credentials.  Would you like me to upload one without the login attempt?

I tried several methods to get this to work last night.  From a separate PC and browser I enabled and disabled 2 factor authentication as I had seen mentioned in a previous issue, but it did not seem to help.  However, by following a link from an Amazon page to the 2 factor page, it asked me for my password.  Upon entering the password, it stopped me and e-mailed me a "one-time password".  I used this in Kodi and it logged in without requiring Captcha and I confirmed that I could play back videos.  However, I went back to my web browser to test my amazon account still worked and the next time I tried to play a video in kodi, it would just become unresponsive (though I could still see the list of videos).  So I removed credentials and started over again.  I am now unable to get the one-time password from the browser so I am stuck in a loop with Kodi getting an error message after Captcha.  If I login from a new browser, I get the option to be emailed an authentication code or to have it sent to my amazon device (whatever that is).  It's basically as if 2 factor authentication is turned on, even though I have it disabled.

Maybe I am doing something fundamentally wrong since I don't see others mentioning these issues.  I was initially logged in with an older version of the add-on before the upgrade and I was unable to playback video after the upgrade, so I thought that logging out and back in would resolve it.  I've tried moving the plugin folder from addons and userdata to force everything to start over again and it hasn't helped either.  Unfortunately I didn't think to create any debug logs of the playback issues.  Please let me know if I can provide any additional details to help with this issue.

**Comment by Varstahl** [comment]
Another user on the forums has [reported the same thing happening](https://forum.kodi.tv/showthread.php?tid=349255&pid=2900673#pid2900673). Posting the [main log](https://pastebin.com/z2nvus62) provided, for completion.

**Comment by knappster1** [comment]
@Sandmann79 Thank you!  I was able to login with that commit.  I was prompted in the addon for a push notification to my amazon device or an e-mail.  I selected e-mail and received the one time password, entered it in the addon and it logged right in.

**Comment by Sandmann79** [comment]
Glad it's working. 
In spite of frequent logins, this error was not noticeable. :confused:
