### ISSUE TITLE
Thank you for all your work & time.

### ISSUE THREAD

**Issue by ggysbers** [Sandmann79/xbmc#354]
I appreciate the time and energy invested in your amazon vod app for kodi/xbmc.

**Comment by raoulbhatia** [comment]
+1 - i tried to figure the best place to say thank you and here seems to be a good opportunity! ;-)

Thank you for the marvellous work!

**Comment by Varstahl** [comment]
I wanted to jokingly flag this as “Invalid: can't reproduce”, but I’ll limit myself to a “thank you”, and “you’re welcome” :D

**Comment by debutanker** [comment]
1000% agree: Grazie mille und herzlichen Dank @Varstahl and @Sandmann79 for keeping us always up to date with Prime Video and Kodi!!
Is there a possibility to leave you guys a little donation for a beer (or sparkling water) or two...?

**Comment by Varstahl** [comment]
I can't talk for Sandmann, but if you're a primevideo user and would like to fuel my coffee addiction (like every good dev), you can find a donation button on my [twitch page](https://www.twitch.tv/varstahl/).

Heck, you might even keep my company as I stream :D

**Comment by Sandmann79** [comment]
Thanks for the compliments at all.
@debutanker you know, where where to find me :wink:

**Comment by debutanker** [comment]
> Thanks for the compliments at all.
> @debutanker you know, where where to find me

Yes, i know -> https://www.paypal.com/donate/?token=k4ibLofgnB9jQ4YGaWPkWZmIf61K4FpozSAptPNblqTkT-gEhBxIjJtAotaghx-976lDE0&country.x=DE&locale.x=DE
Just wanted to give you guys another platform for a couple of beers or coffees, cause you deserve it!!

**Comment by Cissoubaka** [comment]
+1 for me, it seems to be pain in the a** to follow all change amazon made (it seems) everyday.
Thank you for your effort

**Comment by christiancloudibility** [comment]
+1 for me, it is awesome what you guys do and it would get realy bad if there wouldn't be any possibility anymore to watch prime on an opensource device!
So big thanks

**Comment by raoulbhatia** [comment]
FYI the above link for @Sandmann79 seems to be broken.  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=BSSACTP7G6Q3A is the correct one that I got from the Kodinerds page.

**Comment by Varstahl** [comment]
**Important shameless plug**: if you want to support the addon's PrimeVideo development (for free), now you can! I became a Twitch Affiliate last sunday, and I took a day off for the event. I'll be streaming in a few minutes on [url=https://twitch.tv/varstahl/]twitch.tv/varstahl[/url], so you can come drop a free Prime Subscription on my channel, and have a friendly chat about anything. I'll be streaming in english and italian for the next ~10-12 hours, playing Brütal Legend campaign, hope to see you there.

**Also note**: if you're reading this in the far future, know that you can drop a sub even if I'm offline. Also, it's a monthly recurrence ;)

**Comment by GHamblin** [comment]
> I appreciate the time and energy invested in your amazon vod app for kodi/xbmc.

I also want to thank you for your efforts. I have been hesitant to cut the cord without Amazon prime video. I've been struggling to have it work on my pi with Kodi for about 2 years. But tonight I've got it, and it just works! I'm a sponsor for sure!
Thanks 😊
