### ISSUE TITLE
Impossible to log in

### ISSUE THREAD

**Issue by Cissoubaka** [Sandmann79/xbmc#356]
**Addon used**
- [X ] Amazon VOD (plugin.video.amazon-test)
- Addon Version [0.7.6]

**Prime Video Account (select one)**
- [ X] Amazon.fr

**System Setup (please provide the following information):**
- Hardware: [RPi 3b]
- OS Version: [libreelec 9.2beta2]
- Kodi Version [18.4]

**Upload Logs**
[login log](https://pastebin.com/kLP7GbAM)

**Describe the bug**
Hello, I can't login, it says only those error message :

[https://imgur.com/a/lkMc6ek](screenshot)

**Comment by Varstahl** [comment]
Probable dupe, see #353, already fixed, see also this [post on kodi forums](https://forum.kodi.tv/showthread.php?tid=349255&pid=2900709#pid2900709).

**Comment by Sandmann79** [comment]
No i recently pushed the new version 0.7.6. 
This is something new. Amazon returns: `Please enable cookies to continue`

**Comment by Sandmann79** [comment]
@Cissoubaka you're a primevideo.com - France user?

**Comment by Varstahl** [comment]
Judging by the logfile, yes.

**Comment by Cissoubaka** [comment]
Yes i'm using french site

**Comment by CGarces** [comment]
Similar error in Spain.
After the error I see en msg #30213
https://github.com/Sandmann79/xbmc/blob/185daf634a51d632986528a7ba6c39638a3d166c/plugin.video.amazon/resources/language/English/strings.po#L767

I have enabled debug logs at kodi but I can't find that files.

**Comment by Cissoubaka** [comment]
I have a wetek play 2 with libreelec 9.0.2 and plugin v 0.7.5. I didn't have this error, I could login but I have the catalog path error #355

**Comment by Varstahl** [comment]
@Cissoubaka that's been fixed right now. Investigating PrimeVideo login as we speak.

**Comment by Varstahl** [comment]
There's no longer an ATV URL endpoint.

**Comment by Varstahl** [comment]
Fixed in 0.7.7 which has been just pushed to public.
