### ISSUE TITLE
Failed to login: wrong code (spaces required in code)

### ISSUE THREAD

**Issue by dubstar-04** [Sandmann79/xbmc#357]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- [ x] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [ ] primevideo.com
- [Uk ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [e.g. RPi]
- OS Version: [e.g. Windows 10]
- Kodi Version [e.g. 18.4]

**Upload Logs**
Upload `kodi.log` somewhere and post the link here. If you need help finding it, [read the appropriate entry in the FAQs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi).
For Login issues, enable advanced logging in the settings, upload the `(amazon/avod)-login` files from the [userdata](https://kodi.wiki/view/Userdata) folder, and paste the link here, as well.

**Describe the bug**

I've been having an issue logging in with a dialog stating wrong code following any attempt. 

I have now successfully logged in after entering the correct captcha code that required the spaces to be included. 

Not a bug but if anyone comes here looking for help hopefully this will be useful.

**Comment by Varstahl** [comment]
Yup, as I stated before, whoever decided that spaces should be in a captcha challenge deserves a dedicated circle of hell.

**Comment by Spacewalker2** [comment]
I got this when I entered a wrong password but assumed that a wrong captcha caused the error message "wrong code".

**Comment by askdba** [comment]
I can't get pass by wrong code. Why there is a captcha in this? My prime does not ask at apple tv.

**Comment by osdieman** [comment]
Same here.. OTP is enable on Amazone for my account... went to Amazone trying to disable this.. but there is no option to do so.. Even on there site they refer to a link wich doesn't work.. when top is enabled you can only enable it again and again..
The plugin does come up with a dialog box  how to send OTP but does not come up with an input box to put the received code.. ( Running CoreElec  on a AML S905X box )

Kind regards.
