### ISSUE TITLE
Http error

### ISSUE THREAD

**Issue by satish0901** [Sandmann79/xbmc#359]
Hi 
Thanks for all the hardwork in updating.  I am getting http error. I have uninstalled and reinstalled,  now its not letting me login.  Its poping an error

**Comment by satish0901** [comment]
I can login now. but when i am playing a video error pops up :unable to play HTTP error.

**Comment by Sandmann79** [comment]
Without Logs and any Information about your system, i can only say, you have to upgrade Kodi or LE to the most recent Version.

**Comment by satish0901** [comment]
Hi thanks for the reply.  I am running kodi 18.4 . I have tried on android and windows 10 . Its the same issue

**Comment by Varstahl** [comment]
[Provide full logs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi)

**Comment by teryram** [comment]
With version 7.4-beta the same thing happened and it was solved by disabling language-settings-5.1 / 7.1

**Comment by satish0901** [comment]
Hi varstahl.  I will upload  the log report today.  @teryram Its alreafy disabled.  Thanks guys gor the reply

**Comment by satish0901** [comment]
@Sandmann79 @Varstahl , please see the crash details of the log
2019-11-20 11:52:36.223 T:10524  NOTICE: [Amazon VOD] Service: Proxy server stopped
2019-11-20 11:52:36.225 T:10524  NOTICE: [Amazon VOD] Service stopped

**Comment by Sandmann79** [comment]
Like @Varstahl wrote, please provide full logs, not just a snippet.

**Comment by Varstahl** [comment]
@satish0901 that's not a crash, that's the addon service shutting down with Kodi. You've been asked to provide the full logs 3 times already, I'll pretend I don't know why you're not doing it, closing this as invalid, until you provide them.

Have a nice day.

**Comment by satish0901** [comment]
Hi . I will upload full log today evening.  I thought its enough.  Sorry for that.  

Sent from Yahoo7 Mail on Android 
 
  On Thu., 21 Nov. 2019 at 0:08, Bruno Passeri<notifications@github.com> wrote:   
@satish0901 that's not a crash, that's the addon service shutting down with Kodi. You've been asked to provide the full logs 3 times already, I'll pretend I don't know why you're not doing it, closing this as invalid, until you provide them.

Have a nice day.

**Comment by satish0901** [comment]
@Sandmann79 @Varstahl .please see attached full log report
[kodi.log](https://github.com/Sandmann79/xbmc/files/3873303/kodi.log)

**Comment by Varstahl** [comment]
```
NOTICE: [Amazon VOD] postURL: http://127.0.0.1:55514/gpr/…
 ERROR: [Amazon VOD] Error reason: 400 error (NoRetries)
```
Looks like a misconfigured firewall or otherwise restrictive proxy/vpn. It's not an addon issue.

**Comment by satish0901** [comment]
Hi varstahl.  Thanks for your reply.  Its strange,  all the other addons are working fine.  Do i have to do anything in kodi?  
As its the same error on android and windows 
Thank u

**Comment by Varstahl** [comment]
Honestly I have no idea, we have reports of it working on all platform, RPi and Android devices too. It must be something specific to your platforms/network configuration/VPN setups/static routing. Can't really help you there, I wouldn't know where to start.
