### ISSUE TITLE
[Feature request] Allow multiple amazon accounts

### ISSUE THREAD

**Issue by johanneslumpe** [Sandmann79/xbmc#36]
First off: great great on the plugin! I was wondering if you'd be open to add support for multiple amazon accounts, to would make it easier to switch between different accounts with different content? The use case would simply be that there are multiple amazon customers in a single home, who all buy things using their own amazon account and switching between these accounts currently is quite cumbersome.

**Comment by Sandmann79** [comment]
Feature added at commit 7fe34b91a6dd0e69ede036a63a61a70f2ebdb0bb
