### ISSUE TITLE
amazon vod error version plugin 0.7.7

### ISSUE THREAD

**Issue by Faren81** [Sandmann79/xbmc#362]
**Addon used**
- [ x ] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [ x ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [ Asus]
- OS Version: [Windows 10]
- Kodi Version [18.5]
[avod-login-mfa.log](https://github.com/Sandmann79/xbmc/files/3868130/avod-login-mfa.log)
[kodi.log](https://github.com/Sandmann79/xbmc/files/3868131/kodi.log)
[avod-login.log](https://github.com/Sandmann79/xbmc/files/3868132/avod-login.log)

**Upload Logs**
Upload `kodi.log` somewhere and post the link here. If you need help finding it, [read the appropriate entry in the FAQs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi).
For Login issues, enable advanced logging in the settings, upload the `(amazon/avod)-login` files from the [Kodi Home](https://kodi.wiki/view/Special_protocol) folder, and paste the link here, as well.

**Describe the bug**
Trying to start to plugin i received the error:
Amazon Vod Error, i uploaded kodi.log avod-login.log avod-login-mfa.log, just tryed to unistall e install again the plugin, the version is 0.7.7

Regards,
Enrico

**Comment by Faren81** [comment]
The system has updated Amazon Vod to version 0.7.8
you can close the issue. Everythings works fine.

Regards,
Enrico

**Comment by Sandmann79** [comment]
Closed. Btw you can also close issues by your self.
