### ISSUE TITLE
http error

### ISSUE THREAD

**Issue by satish0901** [Sandmann79/xbmc#366]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [e.g. RPi]
- OS Version: [e.g. Windows 10]
- Kodi Version [e.g. 18.4]

**Upload Logs**
Upload `kodi.log` somewhere and post the link here. If you need help finding it, [read the appropriate entry in the FAQs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi).
For Login issues, enable advanced logging in the settings, upload the `(amazon/avod)-login` files from the [Kodi Home](https://kodi.wiki/view/Special_protocol) folder, and paste the link here, as well.

**Describe the bug**

**Comment by satish0901** [comment]
@Sandmann79 @Varstahl .please see attached full log report
kodi.log
[kodi.log](https://github.com/Sandmann79/xbmc/files/3873313/kodi.log)

**Comment by Varstahl** [comment]
dupe #359
