### ISSUE TITLE
If two items with the same are in a list, one of them is missing

### ISSUE THREAD

**Issue by mzanetti** [Sandmann79/xbmc#367]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [0.7.8]

**Prime Video Account (select one)**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [RPi & x86_64]
- OS Version: [LibreELEC & Ubuntu 18.04]
- Kodi Version [18.4]

**Describe the bug**
Most TV Shows on Amazon say "Name of Show - Season X" in their names. However, some of them only say "Name of Show" for all seasons. If multiple seasons are in the same list, the addon will only show one of them.

This is most visible when adding seasons to the watchlist. For example, on amazon.de there is a TV Show called "The Exes". There are 2 seasons available. When adding them individually to the watchlist, everything works fine, but adding both of them will cause the first one to be masked by the second one and only the second season will show up. Removing the second season again, will make the first one reappear.

**Comment by Sandmann79** [comment]
This fix should work for the most titles, where the season number is missing.
