### ISSUE TITLE
Green screen when playing video

### ISSUE THREAD

**Issue by rollnthndr** [Sandmann79/xbmc#375]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version 0.8~beta

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: RPi3
- OS Version: OSMC
- Kodi Version 18.5

**Upload Logs**

**Describe the bug**
Probably not related to the Amazon VOD addon but thought maybe someone would have some insight or possibly point me in the right direction to solve this.

When I try to play a video, it seems to load but there is no audio and the screen is green with some artifacts at top and bottom of screen. Seems like it's possibly a corrupt video stream.  Subtitles are visible. Other video plugins (i.e. YouTube, Twitch, etc.) play video correctly.

**Comment by Varstahl** [comment]
Dupe: #136, #323

That's a widevine decryption problem. Usually updating Kodi/OSMC/IS.A fixed the issue. Or changing OSMC for LibreElec. Not related to the addon, though.

**Comment by rollnthndr** [comment]
Ok, thanks for the heads up!

**Comment by rollnthndr** [comment]
What is the benefit of switching to LibreElec over OSMC? I think I have the latest Kodi/OSMC/IS.A as well as Widevine and nothing seems to help.

**Comment by Varstahl** [comment]
Honestly I'm not 100% sure, as I've only tested LibreElec in a VM, and never OSMC. Over the course of years however, LibreElec seems more up to date and less prone to breaking down. While OSMC has been apparently recommended for RPi's some time ago, so everyone keeps installing it by default, these kinds of issue keep happening.

I'm not a LibreElec pusher nor anything, but several users, often, switching from OSMC to LibreElec went from "I can't make this work" to "it worked out of the box".

I know there are several happy users of OSMC, but I don't know which magic skills are needed to keep it working. I don't know the details of what or how LibreElec does things better/different than OSMC (other than seemingly better standards and default configuration), so I can't go in more details than that.

**Comment by rollnthndr** [comment]
Ok. Thanks for the info. I don't have issue trying something new so I'll give LibreElec a try.

**Comment by rollnthndr** [comment]
I went to LibreElec and video now plays on both Amazon VOD and Netflix. Just an audio issue (no audio) for certain Amazon VOD videos. Most specifically, Tom Clancy's Jack Ryan. Can get audio playing the trailer but nothing for the episodes.

**Comment by Varstahl** [comment]
As mentioned in the other thread for that there's a setting to disable the proxy service. Closing this as solved.
