### ISSUE TITLE
Movies do not open in rpi3

### ISSUE THREAD

**Issue by cremilton** [Sandmann79/xbmc#376]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- Addon Version [e.g. 0.8.0]

**Prime Video Account (select one)**
- [x] primevideo.com

**System Setup (please provide the following information):**
- Hardware: [e.g. RPi3b]
- Kodi(LIbreElec) Version [e.g. 18.2]

**Log file**
[kodi.log](https://github.com/Sandmann79/xbmc/files/3935586/kodi.log)

**Describe the bug**
The films do not open, in previous versions they opened, but only after several insistences.
Series open normally, but sometimes without audio on the first attempt, which normalizes after the second attempt.

**Comment by Varstahl** [comment]
It looks like a connection issue. To be on the safe side, there's the option to disable the proxy service in the settings, disable "Proxy MPD alteration" and try again. If that doesn't work I'd look at network issues.

**Comment by cremilton** [comment]
Hi,

I deleted the files *pvdp and replaced , it is solved for me!

Thanks.
