### ISSUE TITLE
Error while autoplay next item

### ISSUE THREAD

**Issue by Goommer** [Sandmann79/xbmc#377]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version 0.8.1~beta

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: x86_64
- OS Version: GNU/Linux Debian
- Kodi Version: 19.0-ALPHA1

**Upload Logs**
[kodi.log](https://github.com/Sandmann79/xbmc/files/3935897/kodi.log)

**Describe the bug**
An error occurs when playing the next item when auto play is set
the failure occurs from commit 6af07160, undoing those changes solves the problem

Settings->Player->Videos->Play next video automatically->Uncategorized
In config file guisettings.xml:
`<setting id="videoplayer.autoplaynextitem">4</setting>`

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
           - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
          Error Type: <class 'TypeError'>
          Error Contents: '>' not supported between instances of 'NoneType' and 'int'
          Traceback (most recent call last):
            File "/home/goommer/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
              EntryPoint()
            File "/home/goommer/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 80, in EntryPoint
              PlayVideo(args.get('name', ''), args.get('asin'), args.get('adult', '0'), int(args.get('trailer', '0')), int(args.get('selbitrate', '0')))
            File "/home/goommer/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 479, in PlayVideo
              playable = _IStreamPlayback(asin, name, streamtype, isAdult, extern)
            File "/home/goommer/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 446, in _IStreamPlayback
              player.resolve(listitem)
            File "/home/goommer/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 622, in resolve
              if self.extern and not self.checkResume():
            File "/home/goommer/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 649, in checkResume
              if self.resume > 180 and self.extern:
          TypeError: '>' not supported between instances of 'NoneType' and 'int'
          -->End of Python script error report<--
```

**Comment by Sandmann79** [comment]
By means of these commits, the extern variable is correctly initialized and thus the resume point is also checked. This is available but apparently empty. 
This will be fixed soon.

**Comment by Varstahl** [comment]
Can confirm for PV too, not sure if it started with 0.8.0 or 0.7.9 though.

**Comment by Sandmann79** [comment]
It's just a missing default value at [line 665](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/resources/lib/playback.py#L665)

**Comment by Goommer** [comment]
> It's just a missing default value at [line 665](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/resources/lib/playback.py#L665)

That's right
With this patch I have solved the problem momentarily until you publish the final
```
--- a/plugin.video.amazon-test/resources/lib/playback.py
+++ b/plugin.video.amazon-test/resources/lib/playback.py
@@ -662,7 +662,8 @@ class _AmazonPlayer(xbmc.Player):
             return {}
         with co(self.resumedb, 'rb') as fp:
             items = pickle.load(fp)
-            self.resume = items.get(self.asin, {}).get('resume')
+            resume = items.get(self.asin, {}).get('resume')
+            self.resume = 0 if None is resume else resume
             fp.close()
         return items
 
```

Thanks a lot

**Comment by Varstahl** [comment]
It could be simplified to
```
self.resume = items.get(self.asin, {}).get('resume') or 0
```
Works for both py27 and py3.

**Comment by Goommer** [comment]
much better

Thanks a lot

**Comment by Sandmann79** [comment]
You can also use this line:
`self.resume = items.get(self.asin, {}).get('resume', 0)`

**Comment by Varstahl** [comment]
Whops, that's even better, but I need to revert the last 2 commits, lol…

**Comment by Varstahl** [comment]
Facepalm aside, amended with c16998bfdd2493e633ddb316783553b40c93230a.
