### ISSUE TITLE
Playback doesn't work anymore in my nvidia shield (Unable to find license;hdcpEnforcementResolutionPixels in JSON string)

### ISSUE THREAD

**Issue by Paco8** [Sandmann79/xbmc#378]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version 0.8.1

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: nvidia shield
- OS Version: android 8
- Kodi Version 18.4

**Upload Logs**
https://pastebin.com/p5xWfzHr

**Describe the bug**
Playback doesn't work anymore in my nvidia shield, I see this error in the log:
`InputStream Adaptive: Unable to find license;hdcpEnforcementResolutionPixels in JSON string`

**Comment by Varstahl** [comment]
There has recently been a Widevine update, make sure your Kodi/IS.A/Widevine are up to date.

**Comment by Paco8** [comment]
An update to Kodi 18.5 didn't fix the issue. I guess in order to update Widevine I have to update the firmware of the box.

**Comment by Varstahl** [comment]
Not 100% sure, but possible.

**Comment by Paco8** [comment]
After updating the firmware, the addon works again :D
