### ISSUE TITLE
Error: No login screen

### ISSUE THREAD

**Issue by trumanbaltar** [Sandmann79/xbmc#379]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- Addon Version [0.8.1]

**Prime Video Account (select one)**
- [X] primevideo.com

**System Setup (please provide the following information):**
- Hardware: [RPi 3]
- OS Version: [Xbian 1.0]
- Kodi Version [18.5]

**Upload Logs**
kodi.log: https://pastebin.com/tHWrK0be
Can't find the `(amazon/avod)-login` files

**Describe the bug**
When I click on Sign in on the Connection settings the menu disappears and nothing happens. The kodi log shows an SSL error. This did not happen with previous version 0.8.0 (had to uninstall the addon for unrelated reasons) Edit: actually, behavior reproduced with 0.7.5-beta

**Comment by Varstahl** [comment]
Well, yeah, as you said:
```
SSLError(1, u'[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:727)'))
```
It's an OS misconfiguration/problem. You might fix it by following the instructions in [this comment](https://github.com/Sandmann79/xbmc/issues/326#issuecomment-546262203) at your own risk. In any case, the addon works just fine.
