### ISSUE TITLE
html-amazon vod

### ISSUE THREAD

**Issue by massimilinux** [Sandmann79/xbmc#381]
when i start amazon vod it doesn't start
this is the html file you asked for!

[Prime Video.html.txt](https://github.com/Sandmann79/xbmc/files/3968174/Prime.Video.html.txt)

**Comment by Varstahl** [comment]
Scusa, ma la homepage di www.primevideo.com è troncata all'header, manca tutto il contenuto della pagina che mi serve. Puoi prendere la pagina intera, per cortesia?

**Comment by massimilinux** [comment]
scusami ma non sono molto competente credo adesso sia giusta !!
grazie mille!!

Il lun 16 dic 2019, 14:00 Bruno Passeri <notifications@github.com> ha
scritto:

**Comment by Varstahl** [comment]
Sembrerebbe di sì. Appena ho un attimo gli butto un occhio, grazie per i file.

**Comment by massimilinux** [comment]
grazie a te !!! spero di risolvere per evitare di comprare un altro trabiccolo per amazon video  grazie grazie grazie!!!!!!

**Comment by Varstahl** [comment]
Ho ricontrollato i dati che mi hai fornito, e sembra assolutamente tutto corretto… se hai la possibilità di modificare un file dell'addon installato, puoi convertire le linee 390-399 del file primevideo.py, sostituendo questo:

```py
        # Insert the main sections, in order
        try:
            for link in home['mainMenu']['links']:
                self._catalog['root'][link['text']] = {'title': self._BeautifyText(link['text']), 'lazyLoadURL': link['href']}
                if '/home/' in link['href']:
                    self._catalog['root'][link['text']]['lazyLoadData'] = home
        except:
            self._g.dialog.notification('PrimeVideo error', 'Unable to find the navigation menu for primevideo.com', xbmcgui.NOTIFICATION_ERROR)
            Log('Unable to parse the navigation menu for primevideo.com', Log.ERROR)
            return False
```

con questo?

```py
        # Insert the main sections, in order
        for link in home['mainMenu']['links']:
            self._catalog['root'][link['text']] = {'title': self._BeautifyText(link['text']), 'lazyLoadURL': link['href']}
            if '/home/' in link['href']:
                self._catalog['root'][link['text']]['lazyLoadData'] = home
```

Almeno se esplode dovremmo capirne il perché.

Una cosa però mi dà problemi mentali, stai usando VPN? Perché mi dice che l'account è francese?

**Comment by massimilinux** [comment]
Niente da fare !!!!!
ho modificato il file come hai detto ma non funziona !!
Avevo fatto varie prove con amazon vod nel mio raspberry 
ho provato con libreelec  e anche con  osmc 
reinstallandolo da zero ma nulla!!! sempre questo errore .
non uso VPN ..!!!   non so perchè ti dica sia francese !!
![IMG_20191218_203514](https://user-images.githubusercontent.com/44640644/71117905-5373ba80-21d7-11ea-8202-e77fd46bc195.jpg)

**Comment by Varstahl** [comment]
Ok, perfetto, mi puoi allegare il log nuovo?

**Comment by massimilinux** [comment]
Come non detto adesso funziona!!!!!!  ho rimosso le credenziali e i cookie e mi sono logato nuovamente e adesso  funziona.
Ti chiedo un'ultima cosa 
ma l'audio non è in dolby ! è possibile averlo in dolby o no ???
esiste una maniera per renderlo più veloce ? intendo nella ricerca del film deve caricare tutte le pagine prima di aprire la lista  la navigazione risulta lenta.

**Comment by Varstahl** [comment]
> ho rimosso le credenziali e i cookie e mi sono logato nuovamente e adesso funziona
Ok, allora era semplicemente un problema di login

> l'audio non è in dolby ! è possibile averlo in dolby o no?
Dovrebbe esserci Dolby Digital 5.1. Controlla tra le opzioni se hai attivato le descrizioni audio, e se sì disattivale.

> esiste una maniera per renderlo più veloce ? intendo nella ricerca del film deve caricare tutte le pagine prima di aprire la lista la navigazione risulta lenta.
I dati di video e serie vengono salvati in cache. La prima volta che vengono trovati dei film o delle serie bisogna fare più richieste HTTP per poter avere tutti i dati. Dalla seconda volta, avendo la cache, aprirà tutto più veloce.

Sono pianificate funzioni per lasciare la visualizzazione come sul sito, ma al momento non ho avuto il tempo di dedicarmici.

Chiudo comunque l'issue dato che è risolta.

**Comment by massimilinux** [comment]
Grazie mille gentilissimo!  Un grande!

Il mer 18 dic 2019, 21:27 Bruno Passeri <notifications@github.com> ha
scritto:

**Comment by massimilinux** [comment]
Ciao Bruno ho ancora  Bisogno di te. .!!
Si è aggiornato e adesso non va più  .
accedo vedo le cartelle .. vado ad esempio su i miei video (quelli che salvo nell'account amazon)  quando accedo mi da errore!!
ho provato anche a reinstallare libreelec e sucessivamente amazon vod ma mi da il medesimo errore.
/api/watchlist/ref=atv_wtlp_mv?startIndex=0&sort=  .......si ferma quì il messaggio di errore che mi da a video   perchè poi sparisce.
Riesci ad aiutarmi???

**Comment by Varstahl** [comment]
#466
Ci sono stati cambiamenti ai server di Amazon, abbastanza sostanziali, non ho ancora trovato il tempo per sistemarli.

**Comment by massimilinux** [comment]
Ok , Fammi sapere eventualmente su cosa devo fare .
Grazie mille !!



Il giorno dom 10 mag 2020 alle ore 21:33 Bruno Passeri <
notifications@github.com> ha scritto:

**Comment by RobotDodo** [comment]
Very grateful for your work on this - it looks pretty sticky trying to keep it up to date!  Just reporting that I'm seeing what I think is the same issue.  Log entries here:

![image](https://user-images.githubusercontent.com/16608499/81915830-abd3aa80-9605-11ea-8d69-998e13cb6ae0.png)

I'm accessing PrimeVideo from Singapore, no vpns.

**Comment by massimilinux** [comment]
Ciao Bruno!  nessuna  buona notizia da darmi?  :-)

**Comment by Varstahl** [comment]
Come ho già detto, sto scrivendo tutto nel #466. La maggior parte dei problemi sono risolti, ma prima di pushare l'update devo inserire un paio di feature aggiuntive, sennò è un disastro. Se ne hai voglia puoi andare a vedere i commit correlati, e aggiornare i file che vedi elencati nei commit a mano, sicuramente ci sono da scaricare il primevideo.py, common.py, e qualche altro file, più le traduzioni. Oppure scarichi tutto il repository e poi copi la cartella plugin.video.amazon-test sopra quella installata, come preferisci.

**Comment by massimilinux** [comment]
Ciao Bruno.
Ti chiedo..  Nei ultimi giorni non funziona più amazon vod
Ho provato a fare aggiornamenti ma continua a non funzionare.
Solo per capire... è un problema di addon?
o posso fare io qualcosa?
Grazie mille.

Il dom 17 mag 2020, 21:25 Bruno Passeri ***@***.***> ha
scritto:
