### ISSUE TITLE
entering sign In information impossible

### ISSUE THREAD

**Issue by med44600** [Sandmann79/xbmc#382]
**Addon used**
- [x ] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [x ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
-  RPi 4
- OS Version: Raspbian Buster 4.19.75-v7l+
- Kodi Version 18.4 20191027

**Upload Logs**
Upload `kodi.log` somewhere and post the link here. If you need help finding it, [read the appropriate entry in the FAQs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi).
For Login issues, enable advanced logging in the settings, upload the `(amazon/avod)-login` files from the [Kodi Home](https://kodi.wiki/view/Special_protocol) folder, and paste the link here, as well.

**Describe the bug**
Hi, I have a fresh install and in the config interface, i cannot enter any sign in informations. Nothing happend. No error message.

Kodi Log here: https://drive.google.com/open?id=1i5m46A2_WDdOyLk3qTGmJmagm5OPzAcl
Settings here: https://drive.google.com/file/d/1DDZOfiOcxtJv7BnHRXtmehSwdbywuuoa/view?usp=sharing

I installed apt-get install python-bs4 (version 4.7.1-1)
Don't know wath to do?

**Comment by Varstahl** [comment]
```
SSLError(1, u'[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:727)')
```

Debian by default (correctly) forces TLS1.2 but the login endpoint for amazon uses TLS1.0 only. See [this comment](https://github.com/Sandmann79/xbmc/issues/326#issuecomment-546262203) for a solution. After login is complete, you can re-enable TLS1.2.
