### ISSUE TITLE
Please include Spanish Languaje at 1080p

### ISSUE THREAD

**Issue by cfreds** [Sandmann79/xbmc#384]
Could you include please Spanish Languaje for watch at 1080p
I have New kindle fire 10 2019 and this allow to watch at 1080 in spanish from original app. But in kodi with your plugin only allow at 720 in spanish, if i set 1080 spanish is not aviable.

**Comment by Varstahl** [comment]
Amazon and Google restricted HD content on a lot of devices. Depending on what you have and how you set up Kodi it might not be available. There are configurations for android that use Kodi to browse the catalog and then playback with native application, you can find more info in the readme, but there is absolutely no limitation on our end of resolution or languages.
