### ISSUE TITLE
No fanart for episode

### ISSUE THREAD

**Issue by loeffelpan** [Sandmann79/xbmc#385]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)

**Prime Video Account (select one)**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: x64
- OS Version: Ubuntu 19.10
- Kodi Version: 18.4

I exported some season with default kodi scrapers and artwork beef.
Titles, Rating, Duration and everything is fine. Artwork for the show is set as expected. But fanart for the episode isn‘t set. Using artwork beef to set episode fanart for each episode work, but scraping fanart (with or without artwork beef) leads to empty artwork in episodes.

Any suggestions?

**Comment by loeffelpan** [comment]
Just did some testing.
When exporting without NFO episode fanart is shown.
Maybe <fanart>None</fanart> isn't the best idea, because kodi repects NFO before online information. Maybe you can provide less information in NFO files.
Here is an example from netflix addon which work pretty fine. Any other information is from TMDB scaper.

```
<?xml version='1.0' encoding='UTF-8'?>
<episodedetails>
  <plot>Scotland Yard beauftragt Sherlock mit einem kuriosen Fall. Dabei geht es um den Sohn eines Abgeordneten und zerstörte Statuen der ehemaligen Premierministerin Thatcher.</plot>
  <episode>1</episode>
  <title>Die sechs Thatchers</title>
  <season>4</season>
  <runtime>88.8333333333</runtime>
  <year>2017</year>
  <id>80082998</id>
  <showtitle>Sherlock</showtitle>
  <thumb>https://occ-0-3211-2773.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABZJhA_TN4o7rSTB6bgtlihwgE1SspCYGSjNNO8V6Inew2uB35R1cM1cbEQzIBWkbeHx8Tz5wauSYHuiFZSenZwSYVoL5dY_q_Am11w4soO2CcGZV.jpg?r=b5b</thumb>
</episodedetails>
```

**Comment by Sandmann79** [comment]
Seems that the episodedetail tag doesn't support attributes inside the thumb tag anymore.
Fixing this.

**Comment by loeffelpan** [comment]
Okay, I’ll wait for your fix but I‘m not sure if its done with that.

As I said, I would like to get only some information from NFO and then use online metadata from scraper (e. g. for rating). After exporting from your addon every episode has the same rating (I thinks maybe it’s the show rating instead?) which come from NFO. Also resolution, audio codec and channels seems to be always the same in NFO.

Any thoughts to this?

**Comment by Sandmann79** [comment]
You can't mix the nfo file and scrapper results, either the nfo file is used by kodi or the scrapper result.
If you cut out some tags from nfo file, you get incomplete infos displayed. 
The ratings are taken from the season, Amazon provides no episodes rating.
The same applies to audio codec and resolution, there's only a HD true/false tag.

**Comment by loeffelpan** [comment]
Thanks for fixing.
But there is something wrong in some shows.
Mostly I got NFO like this, which is fine.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<episodedetails>
<runtime>2880</runtime>
<genre>Drama</genre>
<actor>
    <name>Sanam Afrashteh</name>
</actor>
<actor>
    <name>Philipp Danne</name>
</actor>
<plot>Oberarzt Dr. Marc Lindner muss schwer schlucken, als die junge Leni Fichtner mit einem Hirntumor erneut bei ihm vorstellig wird. Marc hatte ihr bereits einmal das Leben gerettet, aber dieses Mal fällt die Diagnose noch schlechter aus. Egal wie oft er sie rettet, der Krebs wird wohl immer wieder kommen.</plot>
<votes>24</votes>
**<thumb>http://ecx.images-amazon.com/images/I/41BdlVqC25L.jpg</thumb>**
<title>Mein Herz</title>
<showtitle>In aller Freundschaft - Die jungen Ärzte</showtitle>
<episode>27</episode>
<seriesasin>B01AIQ97Y0</seriesasin>
<director>André Siebert</director>
<displaytitle>27 - Mein Herz</displaytitle>
<season>5</season>
<studio>ARD</studio>
<contenttype>episode</contenttype>
<mediatype>episode</mediatype>
<aired>2019-10-10</aired>
<isprime>True</isprime>
<seasonasin>B07P5N4Q85</seasonasin>
<rating>9.0</rating>
<mpaa>FSK12</mpaa>
<year>2019</year>
<fileinfo>
   <streamdetails>
       <audio>
           <channels>2</channels>
           <codec>aac</codec>
       </audio>
       <video>
           <codec>h264</codec>
           <durationinseconds>2880</durationinseconds>
           <height>1080</height>
           <width>1920</width>
           <language>ger</language>
           <scantype>Progressive</scantype>
       </video>
   </streamdetails>
</fileinfo>
</episodedetails>
```

But some shows/seasons (e. g. "Preacher S01") has double `thumb` tags. One with the right artwork for the episode and one with an artwork for the show. Unfortunately the second one wins for every episode.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<episodedetails>
<runtime>3840</runtime>
<genre>Drama</genre>
<genre>Sciencefiction</genre>
<genre>Action & Abenteuer</genre>
<genre>Fantasy</genre>
<actor>
    <name></name>
</actor>
<plot>Ein Priester begibt sich auf eine Reise, um das übernatürliche Böse zu bekämpfen, das seine texanische Kleinstadt dezimiert hat.</plot>
<votes>660</votes>
**<thumb>http://ecx.images-amazon.com/images/I/513UgiTqfsL.jpg</thumb>**
<title>Pilot</title>
<fanart>
    **<thumb>http://image.tmdb.org/t/p/original/p0BwOOwPf60ng1KOsusozOV0eyA.jpg</thumb>**
</fanart>
<showtitle>Preacher</showtitle>
<episode>1</episode>
<seriesasin>B01FIVYFJC</seriesasin>
<director>Evan Goldberg,Seth Rogen</director>
<displaytitle>1 - Pilot</displaytitle>
<season>1</season>
<studio>AMC</studio>
<contenttype>episode</contenttype>
<mediatype>episode</mediatype>
<aired>2016-05-22</aired>
<isprime>True</isprime>
<seasonasin>B01FIVXQAQ</seasonasin>
<rating>8.0</rating>
<mpaa>FSK16</mpaa>
<year>2016</year>
<fileinfo>
   <streamdetails>
       <audio>
           <channels>2</channels>
           <codec>aac</codec>
       </audio>
       <video>
           <codec>h264</codec>
           <durationinseconds>3840</durationinseconds>
           <height>1080</height>
           <width>1920</width>
           <language>ger</language>
           <scantype>Progressive</scantype>
       </video>
   </streamdetails>
</fileinfo>
</episodedetails>
```

**Comment by loeffelpan** [comment]
> 
> 
> You can't mix the nfo file and scrapper results, either the nfo file is used by kodi or the scrapper result.
> If you cut out some tags from nfo file, you get incomplete infos displayed.
> The ratings are taken from the season, Amazon provides no episodes rating.
> The same applies to audio codec and resolution, there's only a HD true/false tag.

Sorry, but you **can** mix NFO and scaper results.
Take a look at this: https://kodi.wiki/view/NFO_files/TV_shows
```
The order of importing metadata is as follows:

    nfo file. If no nfo file exists, then
    Depending on your scraper settings for your source, either
        Online scraper sites- if a scraper is set in your source settings
        Nothing- if Local Info Only is set
```

For my understanding kodi mixes it by default and scrapes anything missing in the NFO.

**Comment by loeffelpan** [comment]
> 
> 
> You can't mix the nfo file and scrapper results, either the nfo file is used by kodi or the scrapper result.
> If you cut out some tags from nfo file, you get incomplete infos displayed.
> The ratings are taken from the season, Amazon provides no episodes rating.
> The same applies to audio codec and resolution, there's only a HD true/false tag.

OK. Thanks for explaination.

**Comment by Sandmann79** [comment]
The first thumb is for the episode cover. 
The second one inside the fanart tag is for the background image (fanart), but it isn't used on episodes.

So this is my result:
![image](https://user-images.githubusercontent.com/4076968/71313192-9632ce00-2435-11ea-9157-04f1c07397e4.png)

And you get always the second thumb as episode cover?

**Comment by Varstahl** [comment]
I don't know if TLDs work in the same way as PrimeVideo but I might know what he means. There are multiple images for each episode, usually:
https://github.com/Sandmann79/xbmc/blob/5965b3befd9d04d1cd599953ab0f7e3e78b36adc/plugin.video.amazon-test/resources/lib/primevideo.py#L860-L864

I think something changed relatively recently, so it's possible that instead of picking this image, for the episode

![Thumbnail](https://images-eu.ssl-images-amazon.com/images/S/sgp-catalog-images/boxart_images/0bdedd1c-5406-4b4d-b545-8520ac38357e-cf5a6530-6bb6-4673-8e2c-42734454ae72_RGB_SD._V1IkQ3TCaUrIw8hObAieDED9xeyTdPXa_SX268_.jpg)

You get the one for the season

![Season Thumbnail](https://images-eu.ssl-images-amazon.com/images/S/sgp-catalog-images/boxart_images/dcd22395-ecd2-44e3-b3f8-1c68162ef95a-b654cfdf-6b31-4ed5-b346-586b7ee45ab9_RGB_SD._UX266RI_VegtgF1FlXYiu4XHrFz09gJloGLIkcKQ_TTW_.jpg)

**Comment by loeffelpan** [comment]
@Sandmann79 The same result in my setup. But I'm with @Varstahl . Shouldn't the episodes have one picture for each episode? Fanart is (in the background) is fine.

**Comment by Varstahl** [comment]
Mind you, I was talking about primevideo.com, I have no idea if that applies to amazon.TLDs, but since it happened there I thought I'd share in case it's the same thing happening for you guys as well.

**Comment by Sandmann79** [comment]
The TLD api is quit different from primevideos one. There are less informations provided for artwork pictures. Most times are only the cover thumb is avaible and sometimes the fanart. You can see it here for [Preacher S01](https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:28-app:3.0.258.45141&deviceTypeID=A2GFL5ZMWNE0PX&deviceID=428c339927cf3c0777bfcaaa7d37b4417550814744f34722f70cdf96&format=json&version=2&formatVersion=3&marketplaceId=A1PA6795UKMFR9&IncludeAll=T&AID=1&SeasonASIN=B01FIVXQAQ,B01FIVYKSS,B01FIVYOVQ,B01FIVZAIM&OfferGroups=B0043YVHMY&IncludeAll=T&AID=T&Detailed=T&tag=1&ContentType=TVEpisode&IncludeBlackList=T&NumberOfResults=40&StartIndex=0&Detailed=T&mobileClient=true)
The cover urls are always the same.

**Comment by loeffelpan** [comment]
OK, I see that the episode artwork from website is not available via API.

I would suggest to remove artwork from NFO. Kodi will solve this with scrapers or other addons like artwork beef.

**Comment by Sandmann79** [comment]
Maybe its the best option for you to disable nfo file creation at settings, so that some scrapper can do the work?

**Comment by loeffelpan** [comment]
I thought of this, too.
But in that case I will miss duration time.

Any other ideas. I just took a look on combination NFO. Would this be a case?
https://kodi.wiki/view/NFO_files#Combination_nfo

**Comment by Sandmann79** [comment]
For movies maybe, but not for episodes:
>Notes:
>- Parsing NFO files cannot be used for individual episodes

**Comment by loeffelpan** [comment]
I don‘t know what that note exactly means, but I just tried to remove artwork tags from NFO and added a TMDB link to the episode.
Seems to work. Maybe you can take a look.

**Comment by Sandmann79** [comment]
You're right with tmdb it worked. Tested the first time with tvdb, but forgot that there's no offical scrapper available anymore.
In this case it should be enough to put the fileinfo section in the nfo and get the rest of the informations from the scrapper.

**Comment by loeffelpan** [comment]
Some information (e. g. Duration) is not available at TMDB.
And sometimes the order of episodes is different between Amazon and TMDB. What about that cases?
If I were you, I would remove some tags from NFO and keep some information.

PS: I found a setting in your addon which is set to „Missing from TVDB/TMDB“ by default. Should this lead to other fanart URLs in the NFO if I switch that setting?
