### ISSUE TITLE
No Dolby Digital audio tracks

### ISSUE THREAD

**Issue by massimilinux** [Sandmann79/xbmc#386]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: RPi 2/3
- OS Version:  libreelec 9.2.0
- Kodi Version 18.5 leila

**Upload Logs**
Upload `kodi.log` somewhere and post the link here. If you need help finding it, [read the appropriate entry in the FAQs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi).
For Login issues, enable advanced logging in the settings, upload the `(amazon/avod)-login` files from the [Kodi Home](https://kodi.wiki/view/Special_protocol) folder, and paste the link here, as well.

**Describe the bug**
![IMG_20191220_221357](https://user-images.githubusercontent.com/44640644/71293777-c0718680-2376-11ea-9f59-b777d694e7f9.jpg)

I don't see the audio tracks in dolby digital.
why ?
do I have to set something?

**Comment by Varstahl** [comment]
Are you sure what you're watching actually supports DD+? Not all videos have surround. Try searching for the movie `Hot Fuzz`, and while playing it you should find out that the surround track is selected by default. If not, check if you enabled "Audio Descriptions" in the addon settings.

**Comment by massimilinux** [comment]
I tried like you said.
with the hot fuzz movie I only see stereo audio tracks.

**Comment by Varstahl** [comment]
Not sure… maybe the RPi is not able to decode it?

**Comment by massimilinux** [comment]
I did some tests.
with "Audio Descriptions" disabled
 dolby works with some films not with all.
example
It works with :
the wall
the snowman (l'uomo di neve)
freelancers

while with these films:
hot fuzz
man on fire (il fuoco della vendetta)

the video starts without audio track!! 
there is no sound!
the raspbarry i think supports dolby decoding!

**Comment by Varstahl** [comment]
Ok, those are two different things:
1. if it works with "some movies" then it works for all movies where DD+ is available
2. the video starting without audio track is a symptom of (relatively) slow connection, and it's a problem with the proxy service I've done, I had to rush it so it's not perfect. If you don't have visually impaired relatives and don't need the audio descriptions, you can both disable Audio Descriptions and disable the "MPD proxy alteration" feature. Since you're italian you don't need most of the things the service provides anyway.

**Comment by massimilinux** [comment]
OK now it works !!!
Audio Descriptions  already disabled
but by disabling MPD proxy alteration now works
thank you very much!!!!!
