### ISSUE TITLE
Kodi 18.5 crash when I hit PLAY

### ISSUE THREAD

**Issue by robustini** [Sandmann79/xbmc#393]
I do not exclude that it may depend on my hardware, but on this TV box I am unable to operate Amazon VOD.
As soon as I select PLAY the cursor starts to rotate and shortly after it stops, resetting the device.
Maybe I expect too much from this miserable hardware, but I can easily view 4K video, not streaming of course.

- Hardware: MXIII-G
- OS Version: LibreELEC-MXIII_Plus.arm-LE9-Kodi_18.5
- Kodi Version: 18.5
- Amazon VOD. V0.8.1

[kodi_crashlog_20200106224056.log](https://github.com/Sandmann79/xbmc/files/4029832/kodi_crashlog_20200106224056.log)

**Comment by Varstahl** [comment]
The only thing I can think of is to suggest you enable audio passthrough in Kodi's settings, as there's a ton of audio desync errors. As for the logs everything seems fairly normal up to the point where it resets. My knowledge of Kodi internals and requirements is limited, so you might have better luck asking in [Kodi's forums](https://forum.kodi.tv/forumdisplay.php?fid=111).

**Comment by robustini** [comment]
> 
> 
> The only thing I can think of is to suggest you enable audio passthrough in Kodi's settings, as there's a ton of audio desync errors. As for the logs everything seems fairly normal up to the point where it resets. My knowledge of Kodi internals and requirements is limited, so you might have better luck asking in [Kodi's forums](https://forum.kodi.tv/forumdisplay.php?fid=111).

Now I have installed Inputstream Adaptive 2.4.0 and it works perfectly, following these indications:

https://github.com/michaelarnauts/plugin.video.vtm.go/wiki/Inputstream-Adaptive

And I can view the contents of VMTV.GO without any problem, they are also protected with Widewine, so imho the problem is inside the Amazon VOD plugin.
Here the log with VMTV.GO che funziona, e Amazon VOD che invece resetta Kodi:

[kodi_crashlog_20200108105603.log](https://github.com/Sandmann79/xbmc/files/4034920/kodi_crashlog_20200108105603.log)

**Comment by Varstahl** [comment]
Non voglio essere scortese, ma vedo che non ci siamo capiti, quindi ti rispondo direttamente in italiano:

> And I can view the contents of VMTV.GO without any problem

Buon per te

> they are also protected with Widewine

Widevine ha diversi livelli di forza e brutalità, Netflix ad esempio ha delle impostazioni più lax, mentre Amazon utilizza degli standard molto più stretti e necessita più risorse

> so imho the problem is inside the Amazon VOD plugin

Nope.

> Here the log with VMTV.GO that works, and Amazon VOD that resets Kodi instead

L'addon non ha nulla a che fare con il playback. Letteralmente nulla. Si limita a dire, "se vuoi la stagione 1 di vattelappesca sta sul CDN collegato a primevideo.com/product/whatever". Da lì in poi il problema è di Kodi e IS.A. L'addon è in python, non è compilato, perciò al massimo può "non funzionare bene", ma non può far crashare Kodi. Come si vede dal tuo log, peraltro:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x9a1b82d4 in CInputStreamAdaptive::DemuxRead() () from /storage/.kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.4.0
[Current thread is 1 (Thread 0x9e485370 (LWP 2477))]
```

Sebbene ho lavorato un pochino con InputStream.Adaptive non conosco bene gli internals di Kodi, perciò come già detto prima non posso aiutarti oltre.

**Comment by robustini** [comment]
Grazie, l'importante è sapere che dal log non è colpa del tuo addon, tu lo sai interpretare sicuramente meglio di me, cercherò il problema altrove.

**Comment by Varstahl** [comment]
Figurati, np. Riguardo i log, giusto per specificare, dato che prima ho dimenticato:

```
# Apertura dell'addon
 NOTICE: [Amazon VOD] Version: 0.8.1
 NOTICE: [Amazon VOD] Unicode filename support: False
 NOTICE: [Amazon VOD] Locale: en-gb / Language: it

# Richiesta di informazioni su un video
 NOTICE: [Amazon VOD] postURL: http://127.0.0.1:44507/gpr/https%3A%2F%2Fatv-ps-eu.primevideo.com%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3Damzn1.dv.gti.f0b13c7d-98f5-172b-b5d3-e343ec6aa155%26deviceTypeID%3DAOAGZA014O5RE%26firmware%3D1%26deviceID%3D91a264948c746bacc045d11c7138198813a29edd4715a6492daed18b%26marketplaceID%3DA3K6Y4MI8GDYMT%26format%3Djson%26version%3D1%26gascEnabled%3Dtrue%26subtitleFormat%3DTTMLv2%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26languageFeature%3DMLFv2%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%26supportedDRMKeyScheme%3DDUAL_KEY

# Controllo e salvataggio del CDN tra le informazioni di Kodi
 NOTICE: [Amazon VOD] Using Host: Cloudfront
 NOTICE: [Amazon VOD] checkURL: https://s3-dub-2.cf.dash.row.aiv-cdn.net/dm/2$PDEysYZ61MK2YLxv1Pwq0UDQOxA~/27dd/579d/f28c/4507-8bfe-7d9b97620ff3/1c5abb88-ffa8-4049-9f01-e9fa74a0d1f0_corrected.mpd
 NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.4.0

# Dì a IS.A di partire
 NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?mode=PlayVideo&name=0TELDS64GJ8PPARMNTVN91S5SL&asin=amzn1.dv.gti.f0b13c7d-98f5-172b-b5d3-e343ec6aa155
 NOTICE: Creating InputStream
  ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/

# Il video è partito, dì ad Amazon che ci troviamo alla posizione 34s (e spicci)
 NOTICE: [Amazon VOD] Starting Playback: 34.7700004578/56.0000038147
 NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.primevideo.com/cdp/usage/UpdateStream?asin=amzn1.dv.gti.f0b13c7d-98f5-172b-b5d3-e343ec6aa155&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=91a264948c746bacc045d11c7138198813a29edd4715a6492daed18b&marketplaceID=A3K6Y4MI8GDYMT&format=json&version=1&gascEnabled=true&subtitleFormat=TTMLv2&event=START&timecode=34.7700004578

# Decodifica iniziata, creazione del Demuxer
  ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
WARNING: CCurlFile::FillBuffer - Reconnect, (re)try 1
  ERROR: CCurlFile::FillBuffer - Failed: Requested range was not delivered by the server(33)
 NOTICE: Creating Demuxer

# Tornando in alto nel log
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x9a1b82d4 in CInputStreamAdaptive::DemuxRead() () from /storage/.kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.4.0
[Current thread is 1 (Thread 0x9e485370 (LWP 2477))]

# ¯\_(ツ)_/¯
```

**Comment by robustini** [comment]
# Tornando in alto nel log
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x9a1b82d4 in CInputStreamAdaptive::DemuxRead() () from /storage/.kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.4.0
[Current thread is 1 (Thread 0x9e485370 (LWP 2477))]

Questo mi mette abbastanza fuori strada.
Non è un problema di Inputstream adaptive, del Widewine e del tuo plugin, che su un box più recente infatti funziona strabene.
Non so dove sbattere la testa.
Ok che questo tvbox l'ho riesumato ed è già un miracolo che funzioni benissimo con una LibreELEC adattata, ma quel che m'ammazza è che funziona benissimo tutto, pure Netflix, video in 4K, boh!!! :-)

**Comment by Varstahl** [comment]
Ti dico la verità, succedono cose strane. Io generalmente sviluppo con Kodi 19 oramai, ma sul Kodi che usiamo come HTPC che ha ancora Leia, alcune funzioni di base non vanno più e ieri tirando via un paio di "Play from here" mentre guardavamo una serie, Kodi è crashato 3 volte. Boh. Che poi con altre serie o facendo play automatico funziona. Anche lì, è da far scoppiare la testa.

Prova a installare Kodi 19 al posto di Kodi 18, ha parecchi improvement per gli addon e non solo, magari aiuta.

**Comment by robustini** [comment]
Ho risolto installando una build più vecchia di LibreELEC con Kodi 18.2, funziona tutto strabene ora, grazie ancora Bruno!

**Comment by Varstahl** [comment]
Figurati, se funziona son contento :)
