### ISSUE TITLE
Request Live Channels

### ISSUE THREAD

**Issue by FIetch** [Sandmann79/xbmc#395]
I hope I´m right to request Prime Channels here.
As i read in the FAQs Live Channels need to be requested if they are missing.
I use Amazon UK and i need the Channels : "PRIME Your Live and Upcoming events" and "PRIME Recently ended"

![channels](https://user-images.githubusercontent.com/59744922/72177940-18cdfe00-33e2-11ea-9d1e-5342f0eba861.JPG)

**Comment by Sandmann79** [comment]
Full Channels support has been introduced with bcf214573e9df0a0017ffe6104eb79549437228c.
