### ISSUE TITLE
Addon doesn't respect language choices from the website

### ISSUE THREAD

**Issue by Andrew908** [Sandmann79/xbmc#396]
Hello, 

I don't have a problem with the plugin as such except that I would like the option to change the language of the menu in which I see prime video and not use ip geolocation. 
I went back and forth through the menu but I didn't find an option to change the language of the menu as the menu name have been translated to another language instead of English. I can change the language within the amazon prime account, but it does not affect the account in the add-on. 

Can you please add this feature to the plugin or tell me if I can modify any config file to make it default to English ? 

Regards,

**Comment by Varstahl** [comment]
Currently the languages are not managed by the Addon but by Kodi. In order to change the language you need to go into Kodi Settings > Player > Languages > Audio and Subtitles. From there you can configure the defaults, with which Kodi will auto-pick your preferred languages.

**Comment by Andrew908** [comment]
I believe that was not understood correctly. The language of the kodi menu is already configured in English so what you have proposed has already been done. 
My problem on the other hand is this one: I have configured the account and everything works fine, but the section names inside the add-on like movies or when you go to the genres section( which is also written in another language) all the genres are translated based on the ip geolocalisation language. 
The same happens when I access video prime amazon, but I have the option to go to my account and change the language from there to English. 
My question is, would it be possible to do the same in the plugin as with the amazon account ?

**Comment by Varstahl** [comment]
Ah, pardon me for the slip up. In theory changing the language on primevideo.com should provide results in the correct language on the addon. Can you confirm that with english set on primevideo.com that's not happening? Since a lot of data is cached you might want to try to refresh a series' season to test.

**Comment by Andrew908** [comment]
I have tested it and it seems not to work. I even restarted the tv box just to make sure that it can refresh the cache correctly. It seems that amazon holds the language per device as I tested the account on other laptops after I configured it to english on another machine and it never keeps the language stored. You always need to select it from the account and then it remembers it.

**Comment by Varstahl** [comment]
Had the opposite problem before where sometimes the English language was provided instead of the correct one, I'll need to investigate this.

**Comment by Andrew908** [comment]
thank you for investigating and please tell me if you need me to provide you with more information.

**Comment by Varstahl** [comment]
There seems to be some kind of delay, and also cache will be unless refreshed or expired, and in a couple instances the language change involved a few retries (might be sync lag on their end), but as far as I can see everything works as intended:

![image](https://user-images.githubusercontent.com/284077/72616155-963fc400-3936-11ea-9c42-f2a066238fe4.png)
![image](https://user-images.githubusercontent.com/284077/72616564-896fa000-3937-11ea-8b8d-fee8b8033562.png)
![image](https://user-images.githubusercontent.com/284077/72616652-aefca980-3937-11ea-9572-d5ed4c33e811.png)
![image](https://user-images.githubusercontent.com/284077/72616772-e5d2bf80-3937-11ea-9e39-dfb8af886a7d.png)

It also works as intended if you go on the website to change the language with the addon loaded. I've tested this with a couple categories in russian, than switched to italian and browsed somewhere else, and the results were received in italian. The temporary "categories/menu" catalogue is saved in PVCatalog*.pvcp, while the video data (title and synopsis) is stored in PVVideoData*.pvdp. You can clear both to start anew and, again, as far as I can see everything is working as intended.

**Comment by Andrew908** [comment]
I will test this evening as you indicated and come back to you with the results as I can't currently test this. Thank you for your support.

**Comment by Varstahl** [comment]
No problem, I'll keep this open. I've noticed that in part you were correct and that if I open two separate browsers on the same PC, the language is browser based. So there might be a cookie specifically (lc-main-av I think?) which forces what type of language you get your results in, so we might need to suppress that if it's still a problem, but in Kodi on my 2 dev pipes, only one had the lc-main-av set, so I'm not sure if that's really an issue.

**Comment by Andrew908** [comment]
I have tested it during the weekend. It seems that the best solution was to delete the two file you mentioned above: PVVideoData*.pvdp and PVCatalog*.pvcp. What I noticed was that it was updating slowly the words in these catalogues ( so every restart 1-2 words would be updated but not all). 
The issues for me apperead that initially I setup the account in another language and connected to the plugin which downloaded the translations in that language. Then I selected English, but only a few words got translated ( 2-3 ) and then with each restart or closing of the application and reopening new words would be translated, but not all. 

You can close the issue as the solution you proposed worked and suggest that you add this information in the FAQ. 

Again thank you for your time and your help.
