### ISSUE TITLE
Seasons Incomplete and No Lists

### ISSUE THREAD

**Issue by Slotherer** [Sandmann79/xbmc#399]
hey, im using the german version and i can wath some videos if i search for them, but for example in vikings are only 4 of 6 seasons displayed and if i try to open popular, it loads forever and then tells me there was an error an i should watch the log. Sadly i dont know where that log is. im running kodi on libeelec. If you need the log or other data please tell me where to find it and i am happy to provide.
Thanks for your help and hard work.

**Comment by Varstahl** [comment]
[Fantastic logs and where to find them](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi). iirc in your case for LibreElec you should look for the ones that start with `/storage/`. Also, links and info were provided in the issue template you deleted, so… :P

**Comment by Slotherer** [comment]
i enabled the log, repeated what i did before and then tried to look up the path from /storage but ther ist no .kodi directory only a few empty files. the only directory i can finde with an addon_data directory is "special://profile/addon_data". sry what did i delete? xD thanks again.

**Comment by Varstahl** [comment]
In LibreElec the log file should be here `/storage/.kodi/temp/kodi.log`. Alternatively [you can upload them automatically](https://wiki.libreelec.tv/how_to/provide_logfile#tab__via_libreelec_settings_add-on) and paste the log here.

**Comment by Slotherer** [comment]
thx the upload worked. hope ther is something helpfull in it
[KodiLog.txt](https://github.com/Sandmann79/xbmc/files/4081281/KodiLog.txt)

**Comment by Sandmann79** [comment]
If you're using this addon, you have to wait till the database update has finished to see all content. This could take some hours on RPi's.
But be informed, that the support for this addon gets dropped in the future. 
Its better to switch to the Amazon VOD addon. It doesn't need database updates and displays the content immediately.

**Comment by Slotherer** [comment]
okay good to know, i thought the VOD version doesn't work in germany but if it does i will gladly switch. thx again
