### ISSUE TITLE
No Video but Audio is there 

### ISSUE THREAD

**Issue by johnygeorge** [Sandmann79/xbmc#40]
Thanks for the great plugin. I am trying to run it on a RP2. I get the sound but the audio is not present.
![img_20171013_204432](https://user-images.githubusercontent.com/12555816/31561550-86b55496-b058-11e7-927e-cba5c18db857.jpg)

I am running LibreELEC 8.1.2
Kodi 17.4

Is there something that I need to do ?

**Comment by Sandmann79** [comment]
At this time only a few videos are playable within Kodi 17/LE8. 

You have to update to LE 9 Milhouse builds, to get all videos working.
Just use the link provided at readme.md.

**Comment by johnygeorge** [comment]
Thanks a lot. It worked. I updated to the latest build.
