### ISSUE TITLE
Only 60 items from my watchlist are shown while there are more 

### ISSUE THREAD

**Issue by azumukupoe** [Sandmann79/xbmc#400]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version 0.8.1

**Prime Video Account (select one)**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Desktop PC
- OS Version: Windows 10 Pro
- Kodi Version 18.5

**Upload Logs**
[kodi.log](https://github.com/Sandmann79/xbmc/files/4081012/kodi.log)

**Describe the bug**
There're 82 movies on my watchlist but only 60 of them are shown.

**Comment by Sandmann79** [comment]
This issue has been already fixed with 0fe1b68211c93b604cde68cc95f22caaf1dcdf44, but it's not released yet.

**Comment by Sandmann79** [comment]
Amazon VOD 0.8.2 released, which fixed this issue. Closing.
