### ISSUE TITLE
Wrong code

### ISSUE THREAD

**Issue by srkimrki** [Sandmann79/xbmc#404]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- [x] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [e.g. RPi]
- OS Version: [e.g. Windows 10]
- Kodi Version [e.g. 18.4]

I can not pass 2nd security code werification on Amazon Fire Tv stick.
Allways say wrong code error

**Comment by Varstahl** [comment]
In case of login errors a few log files get generated, `avod-login*.log`. We need those logs in order to understand what is going on. Also, we neede the main Kodi.log, more info in the [FAQ](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi).

**Comment by Sandmann79** [comment]
This issue could be related to #357, @srkimrki please check for spaces in code

**Comment by srkimrki** [comment]
@Sandmann79 
I have tryed with spaces without spaces with 2 space between letters and nothing I allways geting same error 'wrong code'.
I will send logs what is Varstahl wanted... On my fire stick login do not going well ((

**Comment by srkimrki** [comment]
@Varstahl 
Only .log file what I was found is kodi.log file. 
avod-login*.log what you want I can not found. Can you give me spec. location?

**Comment by Varstahl** [comment]
depending on the system they could be in `%AppData%\Kodi`, `~/.kodi/` or `/storage/.kodi/`. On *nix based devices they might go in the `tmp` subdirectory. Provide also the Kodi.log when you upload it.

**Comment by srkimrki** [comment]
@Varstahl 
I am so sorry but this log file (avod-log*.log) do not exist I thinking that system do not generate it. I am sending you kodi log file. If you can see something in there ok. If you can not close this issuse post.

**Comment by srkimrki** [comment]
@Varstahl 
[kodi.log](https://github.com/Sandmann79/xbmc/files/4117127/kodi.log)

**Comment by Sandmann79** [comment]
You're using Prime Video with an german account? If not, please use Amazon VOD Addon.

Did you enabled verbose logging at addon settings? Without this the log files won't be generated.

**Comment by srkimrki** [comment]
@Sandmann79 
Yes I am using German account.
I will check how standing verbose logging tomorow and I will again try to find that log file.

**Comment by srkimrki** [comment]
@Varstahl @Sandmann79 
Finally vebrose was rurned off ((
Hier is log files
[Amazon-login.log](https://github.com/Sandmann79/xbmc/files/4135863/Amazon-login.log)
[Amazon-login-mfa.log](https://github.com/Sandmann79/xbmc/files/4135864/Amazon-login-mfa.log)
[kodi.log](https://github.com/Sandmann79/xbmc/files/4135865/kodi.log)

**Comment by Sandmann79** [comment]
Checked the logs, but it's looks like, what the addon says - you entered a wrong code.
Also just checked login with Captcha and it works for me.
