### ISSUE TITLE
Working hd on Xiaomi mbox4

### ISSUE THREAD

**Issue by osdieman** [Sandmann79/xbmc#411]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- Addon Version [e.g. 0.8.1]

**Prime Video Account (select one)**
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
Xiaomi mbox4 4K android tv player
Kodi 18.5

I would like to tell and hope it can help a bit..

I am using manny boxes Rasp Berry pi 3b and a bunche AML boxes..
These boxes all run fine but indeed none of them will play Amzone in hd.. ( also not series here )

I also do own a Xiaomi MBOX4 S  This box is netflix Certifed and will run Netflix in 4K
In Netflix app and also in Kodi..
Also Amazone is running full hd with the original App..
Then i tried to run Amazone VOD Withing kodi and also there it is playing full Hd..

I did not yet managed to find a UHD stream for testing as i just openend the Amazone account.
If there is any information i can extract from this box to help you guys please do 
let me know..

Kind regards..

**Comment by Sandmann79** [comment]
There is no need for this. 
Your Mibox has Widevine L1 support and with this you'll be able to playback videos up to Full HD. Higher resolutions are not possible with this Addon.
The most Widevine L1 certified Android devices should be able to playback at HD resolution.

**Comment by mpd99** [comment]
@Sandmann79 i  am very big fan of you i tried every thing to get 4K UHD profile of amazon prime video kindly tell how to get 4k SDR profile , i can do 4KUHD HDR thanks to you
