### ISSUE TITLE
Incompatible with Trakt Addon

### ISSUE THREAD

**Issue by SonOfDiablo** [Sandmann79/xbmc#412]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- App Version: 0.8.1

**Prime Video Account (select one)**
- [X] primevideo.com

**System Setup (please provide the following information):**
- Hardware: RPi 4
- OS Version: LibreELEC 9.2.0
- Kodi Version: 18.5

**I'm opening this issue because the [thread](https://forum.kodi.tv/showthread.php?tid=349255) on the Kodi forum is locked. This is a respond to @Varstahl's [message](https://forum.kodi.tv/showthread.php?tid=349255&pid=2914420#pid2914420)**
(Also just want to apologize to @Varstahl for the late response) 

The issues is in regards to the [Trakt addon](https://forum.kodi.tv/showthread.php?tid=220547). The Trakt addon can't pickup TV Episodes played through the Amazon addon.
(It can however pickup TV Episodes played through the [Netflix addon](https://forum.kodi.tv/showthread.php?tid=329767) and even at times it falsy pickup Youtube videos played through the Youtube addon.)

I'm not sure what exactly the issue is, but my best guess is that the Amazon addon is reporting a name to Kodi that is formatted differently than the other addons.

**Comment by Varstahl** [comment]
@SonOfDiablo thanks for the notification, it must've been an error by some mods, I notified it and the thread's been reopened already. As for the Trakt integration, this will take some time I'm afraid, before I can look into it.

**Comment by SonOfDiablo** [comment]
Oh good! I was worried something had changed and this addon had been flagged as a "Bad Addon", glad to hear the thread is open again.

As for the time needed. I fully understand! No need to hurry on my behalf, it takes the time it takes.
I do however appreciate the fact that you at least are willing to look into the issue.

**Comment by Sandmann79** [comment]
Stale issue. Feel free to reopen, if the issue still exists.
