### ISSUE TITLE
AMAZON PRIME VOD Loads all the search results EVERY.SINGLE.TIME

### ISSUE THREAD

**Issue by samritkunja** [Sandmann79/xbmc#414]
Hey, 
I have the same issue you had addressed before with another person namely:
https://github.com/Sandmann79/xbmc/issues/364
wherein the amazon prime vod loads all the search results every time, which is extremely time consuming. You had mentioned as the answer to that question as 
" The first time around the loading takes a lot of time because some information are hidden behind different calls, so in order to process a category, especially for TV series, it takes a whole lot of time. On subsequent calls, since most of the data is already stored, it will only take a handful of seconds though, on my end about 10 seconds for 22 pages and about ~440 results.

There is an enhancement planned to 100% respect primevideo.com's pagination, it didn't make the cut for this release though.

But, again, after the data is cached, you will see a dramatic speed increase."

However, I have used the Prime Video VOD at least 20 times now but it still takes a minimum of 20 minutes to load the search results.

Kindly help.

**Comment by Varstahl** [comment]
You can hit the search 200 times, but if you hit 1.000 new content for each of the 200 times you're still caching the hell out of it. This is a known issue for some users, but I couldn't work it out yet. Closing this as duplicate.
