### ISSUE TITLE
did not find certain shows - not even listed in watchlist

### ISSUE THREAD

**Issue by vladtepesch** [Sandmann79/xbmc#418]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- [x] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [ ] primevideo.com
- [x] amazon.de

**System Setup (please provide the following information):**
- Hardware:  RPi 4
- OS Version: raspbian - Linux raspberrypi4 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
- Kodi Version:  18.5 2020-01-13

**Describe the bug**
Star Trek: Picard is not present in the watchlist and also is not found by search. I tried in both sub options with "star trek" -> many results but not "Picard" and only with "Picard" - no results a all

**Comment by lardwick** [comment]
my issue is close of this one 

i can find startrek picard but only the 4th episode when there is 7 . i can find them fully on the amazon official app but not on the kodi . im on the same configuration listed above : 

System Setup (please provide the following information):

Hardware: RPi 4
OS Version: raspbian - Linux raspberrypi4 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
Kodi Version: 18.5 2020-01-13

**Comment by vladtepesch** [comment]
BtW: the Amzon VOD Plugin does not work at all. If I try to enter login-data I get kicked out of the config screen

**Comment by Varstahl** [comment]
@vladtepesch could your majesty try this version of Amazon VOD?
[plugin.video.amazon-test.zip](https://github.com/Sandmann79/xbmc/files/4317101/plugin.video.amazon-test.zip)

**Comment by vladtepesch** [comment]
@Varstahl currently not possible since my rpi4 is currently used for other tasks

**Comment by Sandmann79** [comment]
I'm sorry to say that, but I recently cancelled support and development for this addon. Please switch to Amazon VOD.

**Comment by lardwick** [comment]
my appologies for my late response i tested with the test version of amazon vod and it works ! i had to uninstall fully amazon vod pluging to get it works

thanks for your investigation
