### ISSUE TITLE
Kodi 19 support

### ISSUE THREAD

**Issue by Varstahl** [Sandmann79/xbmc#419]
@Sandmann79 https://github.com/xbmc/xbmc/pull/17188 got merged yesterday, which makes retro compatibility with Kodi 18 a no go.

There are several solutions, which all suck:
* Drop compatibility with Kodi 18 going forward
* Drop compatibility with Kodi 19 until it gets a release and then drop 18
* Keep this repo support for Kodi 18 and push Kodi 19 support to the official repository
* (Unfeasible in the short term) complete the release proxy I was working on to change addon.xml on the fly when people downloads the package
* Push a release with 2.7 support with the latest fixes, keep it there for people that need it (and don't delete it automatically on a new release), while immediately providing the same version with a 3.0 and update only that for the future.

The best solution would be to complete the GitHub proxy repo I was working on previously, and alter the zip file dynamically to change Addon.xml on the fly when the user downloads it on Kodi 18, but I'm currently on a deadline with a client and can't really spare the time.

I'll wait for your opinion before doing anything.

**Comment by Sandmann79** [comment]
Oh bad news.

Like you wrote, the proxy repo could be the best solution. I didn't know how it exactly works anymore 🙄, but as far as I remember it sounds good. 

In the meantime I can create repo zips for leia and matrix and let the script replace the versionnumbers at the addon.xml. So you have enough time to do your work.

**Comment by Varstahl** [comment]
I'm in the middle of a covid outbreak feeling not so good myself with supply chains blocked and a client deadline upon me, it's a fucking delirium over here, so yeah, it's going to take me a while :D

**Comment by Sandmann79** [comment]
Sad to hear about. Get well soon and all the best for you and your beloved ones for the next time.

**Comment by Essam311** [comment]
@Sandmann79 You still need script.module.pyxbmct to be submitted to the Kodi Matrix repo https://github.com/xbmc/repo-scripts/pull/1342, script.module.kodi-six and script.module.inputstreamhelper are now on the Kodi Matrix repo, you may read this thread and the comments in it first https://forum.kodi.tv/showthread.php?tid=351745.

**Comment by Sandmann79** [comment]
Kodi 19 repo added with aaa377b09bd90faa81f5313da7aea79cc0d81e02
