### ISSUE TITLE
Amazon VOD taking long to load content

### ISSUE THREAD

**Issue by Tarun75** [Sandmann79/xbmc#421]
I am using Kodi 18 version in India with Amazon repository.sandmann79.plugins-1.0.2.zip on Rpi 4. The AMAZON VOD starts loading pages each time it starts, and takes too long. Every time I start the application it loads pages.I supose it Does it not store the earlier episodes or movie data. I do not face the same issue in Netflix. Please provide some solution to this.

**Comment by Varstahl** [comment]
You assumed wrong. Closing for duplicate.
