### ISSUE TITLE
Unable to see any video from Amazon Prime "Video codec unknown: d"

### ISSUE THREAD

**Issue by Ralf-Jonas** [Sandmann79/xbmc#422]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- [ X ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version 2.0.7

**Prime Video Account (select one)**
- [ ] primevideo.com
- [ X ] amazon.de

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 4
- OS Version: Raspian Buster
- Kodi Version 18.5

**Upload Logs**
https://drive.google.com/open?id=1M6Q3A7-i-2iGzqy4mElM_WA7KGaHl3uw

**Describe the bug**
I can browse through all videos and see the description and the images. All works fine except: I can't play any movie at all. Whenever I click on a video link, the clock in the upper row flickers a bit, and that's all. In the log file appears the line "ERROR: CMMALVideo::Open : Video codec unknown: d"

**Comment by Varstahl** [comment]
```
[Amazon] InputStream.Adaptive addon is not installed
```

You need to install IS.A through the official Kodi repos.

**Comment by Ralf-Jonas** [comment]
Yes, you're right, and yes, you're not.
Yes, I had to install the InputStream-Adaptive, but I never found it since yesterday.
No, you do not install it "through the official Kodi repos", because it's not in there, at least not in raspian. In raspian you have to install the InputStream-Adaptive via "apt-get install" ! I didn't know that.
But nevertheless it works now. So thanks a lot for the answer.

**Comment by Varstahl** [comment]
Hah, that's news to me. Thanks for sharing, I'll keep it in mind for other users.
