### ISSUE TITLE
plugin.video.amazon scraping done in the frontend interferes with other addons

### ISSUE THREAD

**Issue by laclaro** [Sandmann79/xbmc#423]
Hi,

my RPi3 system running Kodi Version 18.5, OSMC/Debian stretch and has the plugin.video.amazon 2.07 installed, linked to an amazon.de account.

I open this bug to hint at an interference with plugin.video.netflix found at https://github.com/CastagnaIT/plugin.video.netflix/issues/512.

Best regards,

Henning

**Comment by Varstahl** [comment]
As reported in https://github.com/CastagnaIT/plugin.video.netflix/issues/512#issuecomment-597493022:
https://github.com/Sandmann79/xbmc/blob/1657c29e4ef6643e244281c5302e38e0ac430bfb/plugin.video.amazon/service.py#L73-L76

> in this way you delegate the operation in a frontend instance, while it should be performed within the service instance (backend)
>
> it is possible that this blocks the Python GIL causing the blocking of the other addons services

That seems to be the case, from the few tests they've performed.

**Comment by Sandmann79** [comment]
I'm sorry to say that, but I recently cancelled support and development for this Amazon. Please switch to Amazon VOD.
