### ISSUE TITLE
Browsing Videos and TV Shows fail

### ISSUE THREAD

**Issue by SkyBird1980** [Sandmann79/xbmc#424]
**Addon used**
- [ X] Amazon VOD (plugin.video.amazon-test)

**Prime Video Account (select one)**
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Ryzen 3 2200G / 8GB RAM
- OS Version: Windows 10 (2004)
- Kodi Version: 18.6

**Upload Logs**
[kodi.log](https://github.com/Sandmann79/xbmc/files/4363123/kodi.log)

**Describe the bug**
Browsing Series / TV Shows isn't possible anymore. Log says: http 403 (forbidden)
maybe Amazon locked out the device id?

**Comment by Handy-E** [comment]
Same problem here. Everything except watchlist and last viewed is empty.
Only the movies in the watchlist are watchable. Episodes-folder of a Series is always empty in watchlist, too.
So, in fact, no series can be watched, only films.

**Comment by Sandmann79** [comment]
I just released v0.8.2, which should fix this issue. Please try it and report back.

**Comment by Headlex** [comment]
> I just released v0.8.2, which should fix this issue. Please try it and report back.

Do I have to to something specific to install the version?
My addon-manager is just offering the version 0.8.1

**Comment by Varstahl** [comment]
You can either download the zip from the repo, clear Kodi's cache, or wait tomorrow for the update.

**Comment by Krokosh** [comment]
Applying the fix has caused the episodes of Picard to reappear in my Watchlist, which indicates that TV shows are working, but I don't seem to be getting any movies.  For the record, I was getting a 503 error before the fix.

**Comment by Sandmann79** [comment]
@Krokosh recently checked all countries and found no empty lists. Maybe a temporary server problem?

**Comment by Handy-E** [comment]
Tested new version and it works! Thank you so much for fixing!!
Your addon is the only software I can use with my TV. Good work!

**Comment by Sandmann79** [comment]
Fixed with 7cbee021fdee9816fd74677ffc2734f48a6901db
