### ISSUE TITLE
Amazon VOD - Just Watchlist working

### ISSUE THREAD

**Issue by Headlex** [Sandmann79/xbmc#425]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [ ] primevideo.com
- [x] amazon.(de)

**System Setup (please provide the following information):**
- Hardware: RPi 4
- OS Version: LibreELEC 9.2.1 RPi4.arm
- Kodi Version: 18.6 Git:leia_pi4_18.6-Leia

**Upload Logs**
https://pastebin.com/AURjkSEq

**Describe the bug**
My watchlist gets imported correctly and I am able to start film streams off it. The entries of series are empty in the subfolder.
I am also not able to browse for films or series.
When searching for a film or series it works.

Note: Using a PiHole in my network

**Comment by Handy-E** [comment]
Same like Issue #424

**Comment by Sandmann79** [comment]
I just released v0.8.2, which should fix this issue. Please try it and report back.

**Comment by Sandmann79** [comment]
Yep it's a duplicate, closing
