### ISSUE TITLE
Support JSON-RPC command Player.Open

### ISSUE THREAD

**Issue by Upabjojr** [Sandmann79/xbmc#426]
Hi,

I am sending a link similar to the following using `Player.Open` instruction with Kodi's JSON-RPC
```
https://app.primevideo.com/detail?gti=[ ... ... ... ]&ref_=atv_dp_share_seas&r=web
```

I am using the app Kore (Kodi remote for Android).

It looks like Amazon-VOD is unable to intercept the instructions coming from JSON-RPC. The YouTube addon OTOH is able to recognize links to YouTube, and starts playing automatically when Kodi receives JSON-RPC Player.Open command containing a YouTube link.

Is it possible to have a similar functionality for Amazon videos? If so, how can you do that?

**Comment by Varstahl** [comment]
I'm not sure if and how we could intercept (and what to do with) the link. I'll mark it as enhancement for the time being, I'll investigate this when I can.

**Comment by Upabjojr** [comment]
I actually notice that if I pass `plugin://plugin.video.amazon-test/[ ... SOMETHING ... ]` through JSON-RPC, the Amazon addon seems to react (returning an error). Maybe that's the way to go?

What I'm doing:
- Select a movie with the Prime Video app on Android
- Click share, then select Kore (Kodi Remote for Android, which I have installed in debug mode).
- At this point, I stop Kore with the debugger, extract the link to the Amazon video.
- The URL is then forwarded to Kodi with JSON-RPC.

I just noticed that YouTube links are transformed into `plugin://plugin.video.youtube/ ... ` paths by Kore, so maybe the same would be required for Amazon?

I feel more confident with the official Amazon app, and it would be nice if the official Amazon app could interact directly with Kodi.

**Comment by Sandmann79** [comment]
In this case the following link should work:
`plugin://plugin.video.amazon-test/?asin=[asin/gti]&mode=PlayVideo&adult=0&name=&trailer=0&selbitrate=0`

**Comment by Varstahl** [comment]
> I feel more confident with the official Amazon app, and it would be nice if the official Amazon app could interact directly with Kodi.

Of course, it all depends on what you mean by this. If you mean that you don't want to login in Kodi through the Addon, nothing is going to work. Obviously.

**Comment by Upabjojr** [comment]
> In this case the following link should work:
> `plugin://plugin.video.amazon-test/?asin=[asin/gti]&mode=PlayVideo&adult=0&name=&trailer=0&selbitrate=0`

That's great! I opened a PR to Kore:
https://github.com/xbmc/Kore/pull/719

It works on my mobile phone, I can launch Prime Videos on Kodi from the official Amazon app ;)

**Comment by Sandmann79** [comment]
Then it works as expected. Closing...
