### ISSUE TITLE
No picture, just audio

### ISSUE THREAD

**Issue by dmainslie** [Sandmann79/xbmc#429]
**Addon used**
- [x ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version 0.8.2

**Prime Video Account (select one)**
- [ ] primevideo.com
- [x ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Firestick
- Kodi Version 18.5

When playing prime videos, I am getting a default speaker picture backdrop and audio only. I have checked the inputstream and set to default settings.

This was working a month ago.

Any ideas?

Thanks
Dave

**Comment by Sandmann79** [comment]
Check that your inputstream settings really by default, particularly media is set to all. You can also check, if both MediaCodec Renders at Player Settings Video are enabled (should be default on new installs). You have to switch to advanced view, to see these options.

**Comment by dmainslie** [comment]
How do you access the advanced view?
________________________________

**Comment by dmainslie** [comment]
Don't worry, I've found it and works perfectly now. Thanks.
________________________________
