### ISSUE TITLE
Amazon VOD not loading, spinning wheel on Videos/Add-on page

### ISSUE THREAD

**Issue by VarunGonzy** [Sandmann79/xbmc#430]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
Add-on ZIP - repository.sandmann79.plugins-1.0.3-leia.zip
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]
Add on Version - 0.8.2

**Prime Video Account (select one)**
- [x] primevideo.com
Location - US
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [e.g. RPi]
-> Raspberry Pi 3B
- OS Version: [e.g. Windows 10]
-> Raspian with recommended software - https://www.raspberrypi.org/downloads/raspbian/
- Kodi Version [e.g. 18.4]
-> Kodi (18.5, Git:20191122-07c21acf71). Platform: Linux ARM 32-bit

**Upload Logs**
Upload `kodi.log` somewhere and post the link here. If you need help finding it, [read the appropriate entry in the FAQs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi).
******************************************************************
pi@raspberrypi:~ $ grep Kodi .kodi/temp/kodi.log | head -3
2020-03-28 23:04:55.446 T:1899832240 NOTICE: Starting Kodi (18.5 Git:20191122-07c21acf71). Platform: Linux ARM 32-bit
2020-03-28 23:04:55.446 T:1899832240 NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
2020-03-28 23:04:55.446 T:1899832240 NOTICE: Kodi compiled 2019-12-16 by GCC 8.3.0 for Linux ARM 32-bit version 4.18.20 (266772)
pi@raspberrypi:~ $ 
*******************************************************************
For Login issues, enable advanced logging in the settings, upload the `(amazon/avod)-login` files from the [Kodi Home](https://kodi.wiki/view/Special_protocol) folder, and paste the link here, as well.

**Describe the bug**
----------------
I am trying to figure out why the Amazon Dialog for login does not pop-up.
We tried the following:
Downloaded the ZIP file stated above (from the release) and then,
added it via Addon Browser > Install from ZIP.
Navigate to the path for the ZIP.
This will install the repository. 

Now we install the add-on from Video Add-ons Amazon VOD is installed.

Then, we go to Configure settings in Amazon VOD.
Under General, change Playback with to Input Stream.

The Amazon VOD is installed successfully, and when I navigate to the Add-on, I keep getting a spinning wheel on the page for indefinite time. I have not been able to load the app or login into it.
I have a screenshot of the screen at Videos / Add-ons as well.

Any help would be greatly appreciated. @Sandmann79 @Varstahl

**Comment by Varstahl** [comment]
Can't help if you don't provide the full logs, one thing I can tell you though, if you're in the US you can't use PrimeVideo.com, you must use amazon.com. The addon supports it, but if you've manually configured it to use primevideo instead, it's not gonna happen.

Also, instead of opening the plugin try opening the contextual menu for the addon settings and manually selecting "sign in".

**Comment by VarunGonzy** [comment]
Please find the Kodi logs here.

https://drive.google.com/file/d/1V09zFClpzXT9Ob5n7ERcpVd2hr20ivrQ/view?usp=drivesdk

**Comment by Varstahl** [comment]
```
(Caused by SSLError(
  SSLError(
    "bad handshake: Error(
      [('SSL routines', 'ssl_choose_client_version', 'unsupported protocol')],
    )",
  ),
)
```

[See this comment](https://github.com/Sandmann79/xbmc/issues/326#issuecomment-546262203) for more information.
