### ISSUE TITLE
Random sorting of Seasons and Episodes

### ISSUE THREAD

**Issue by blakknss** [Sandmann79/xbmc#431]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Wetek Play 2 (arm Device) / Intel
- OS Version: coreelec / Windows
- Kodi Version 18.5 / 18.2

**Describe the bug**
Since last update random sorting of Seasons and Episodes.

**Comment by Sandmann79** [comment]
Seems to work for me here. Maybe a skin related bug?
![image](https://user-images.githubusercontent.com/4076968/78459111-07318500-76b7-11ea-8804-536de7fba5fc.png)
![image](https://user-images.githubusercontent.com/4076968/78459091-f123c480-76b6-11ea-8561-a57060bce9e3.png)

**Comment by knappster1** [comment]
I noticed this last week.  I will see if it is still happening and try to post a debug log if it is.

**Comment by knappster1** [comment]
The order was correct on everything I looked at tonight.  Nvidia shield with kodi 18.6 and addon v0.8.2.  Could it have been a temporary issue with how amazon produced the listings?

**Comment by Sandmann79** [comment]
Issue not present anymore. Closing.
