### ISSUE TITLE
Unable to see Watchlist content

### ISSUE THREAD

**Issue by dfdario** [Sandmann79/xbmc#435]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version 0.8.2

**Prime Video Account (select one)**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: PC Desktop
- OS Version: Debian 10
- Kodi Version 18.6
[kodi.log](https://github.com/Sandmann79/xbmc/files/4428108/kodi.log)

Unable to see movie & TV show belonging to "Your Watchlist" (La mia Lista Video) even forcing update.

**Comment by Varstahl** [comment]
Eh, vabé, devo vedere che hanno combinato pure stavolta.

**Comment by dfdario** [comment]
Pls consider that all other lists are updated properly

**Comment by DoctorBR** [comment]
> Unable to see movie & TV show belonging to "Your Watchlist" (La mia Lista Video) even forcing update.

The problem is taking place on Android TV Oreo 8.0 from Xiaomi Mi Box 3 (MDZ-16-AB) as well. 

> Pls consider that all other lists are updated properly

The same thing here!

**Comment by reeslo** [comment]
Same problem for me under rpi4 Kodi 18.5.
Idk if its related but /dev/loop0 is full 
![Screenshot_20200404-223009](https://user-images.githubusercontent.com/2724844/78460803-431f1700-76c4-11ea-85e7-8682c172f336.jpg)

I've trying remove thumbnails cache but no effect that's already full.

**Comment by CGarces** [comment]
Same problem.

I have removed the files with
`rm .kodi/userdata/addon_data/plugin.video.amazon-test/*.pv??`

Logs after force the refresh:

```
2020-04-05 00:19:41.472 T:3515491200  NOTICE: [Amazon VOD] startup.py:39 Requested /pv/refresh/root/Watchlist
2020-04-05 00:19:41.476 T:3515491200  NOTICE: [Amazon VOD] primevideo.py:596 Refreshing element in the cache: Watchlist
2020-04-05 00:19:41.478 T:3515491200  NOTICE: [Amazon VOD] primevideo.py:632 Refresh params: ({u'lazyLoadURL': u'/mystuff/watchlist/ref=atv_nb_wtl', u'title': u'Your Watchlist'}, [u'root', u'Watchlist'], True)
2020-04-05 00:19:41.492 T:3515491200  NOTICE: [Amazon VOD] network.py:143 getURL: https://www.primevideo.com/mystuff/watchlist/ref=atv_nb_wtl

```
Video and catalog files are generated after the refresh.

```
# ls -l .kodi/userdata/addon_data/plugin.video.amazon-test/
total 7592
drwxr-xr-x    2 root     root          4096 Apr  4 21:34 config
-rw-r--r--    1 root     root       1864905 Apr  5 00:19 PVCatalogA3K6Y4MI8GDYMT.pvcp
-rw-r--r--    1 root     root       5882648 Apr  5 00:19 PVVideoDataA3K6Y4MI8GDYMT.pvdp
-rw-r--r--    1 root     root         12267 Apr  5 00:10 resume.db
-rw-r--r--    1 root     root          3192 Nov 19 23:31 settings.xml

```

**Comment by reeslo** [comment]
@CGarces thanks for the trick, I'll test that in a morning !

**Comment by reeslo** [comment]
No change for me After removing files..

**Comment by CGarces** [comment]
@reeslo there is no trick I was confirming that the files are regenerated after the refresh, but the error persist.

**Comment by Paco8** [comment]
The watchlist items are now in a different place in the json data.
I wrote this quick hack that copies them where the code below expects them:

```
===================================================================
--- Kodi/plugin.video.amazon-test/resources/lib/primevideo.py   (revisi¾n: 15563)
+++ Kodi/plugin.video.amazon-test/resources/lib/primevideo.py   (copia de trabajo)
@@ -1115,6 +1115,12 @@
                         o[collection['text']]['lazyLoadData'] = collection

             # Watchlist
+            try:
+                watchlist_filters = cnt['viewOutput']['features']['legacy-watchlist']['filters']
+                cnt['filters'] = watchlist_filters
+            except:
+                pass
+
             if ('filters' in cnt) and ('*classHierarchy*' not in cnt):
                 # Don't parse content and forbid pagination on the main watchlist page
                 if 'content' in cnt:

```

**Comment by Varstahl** [comment]
Sorry for the slowness guys, but these are crazy days for me. I've noticed already a few changes in the data provided by Amazon but I didn't find the time to work on it yet. I need to change far more than just the watchlist location, so it's going to take me a few days to get everything sorted out.

Let me know if the hack provided by @Paco8 works, though, didn't analyse the data yet myself.

**Comment by Blackstar77** [comment]
I confirm. The hack works. The watchlist came back ! Thanks to Paco8 !

**Comment by dfdario** [comment]
Sorry for being late. Also here it works like a charm. Thanks Paco8!
In Debian patch should be applied to:
.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py

**Comment by dfdario** [comment]
I applied the patch to my Oreo Android 8.0 on hacked M8S and it works.
Now awaiting the patch takes place at official release. In the meanwhile for those are not familiar at patching their systems I attached plug-in with hack. Sandman please remove it whenever you want.
[plugin.video.amazon-test.zip](https://github.com/Sandmann79/xbmc/files/4442832/plugin.video.amazon-test.zip)

**Comment by dfdario** [comment]
Scusa-------- Messaggio originale --------Da: Bruno Passeri <notifications@github.com>Data: mar 7 apr 2020, 10:27A: Sandmann79/xbmc <xbmc@noreply.github.com>Cc: DFDario <ddafre@gmail.com>, State change <state_change@noreply.github.com>Oggetto: Re: [Sandmann79/xbmc] Unable to see Watchlist content (#435)
Reopened #435.

**Comment by Varstahl** [comment]
np :D

**Comment by demod-au** [comment]
Unfortunately hack not working here.  I tried modifying the primevideo.py file, and also installing the package above.

**Comment by Varstahl** [comment]
I should be able to work on this later today. I might need your help to provide a few JSON files down the line.

**Comment by Blackstar77** [comment]
> 
> 
> Unfortunately hack not working here. I tried modifying the primevideo.py file, and also installing the package above.

Even after forcing the refresh ?

**Comment by Varstahl** [comment]
Yup, it seems it's all there is atm. More stuff will break in the short term, I think. @demod-au after applying the fix you must right-click/open the contextual menu and hit Refresh. The results are cached, so if you don't invalidate that part of the cache it will keep opening with no results.

**Comment by demod-au** [comment]
Sorry @Varstahl & @Blackstar77 .. it's good. My bad..  I did not refresh!  All working perfect after refresh.

**Comment by Varstahl** [comment]
np at all. In the meanwhile I made a proper fix and update other parts of the addon, it should go live in the next version update.
