### ISSUE TITLE
Video Stuttering on Coreelec and Libreelec

### ISSUE THREAD

**Issue by Willyfan** [Sandmann79/xbmc#436]
**Addon used**
- [ * ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [0.8.2]

**Prime Video Account (select one)**
- [ * ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [Intel Atom X5-Z8500 and Amlogic S905]
- OS Version: [LibreElec - CoreElec]
- Kodi Version [18.4]

**Describe the bug**
I own a Amlogic s905 TVBOX and a Beelink BT4. I tried to install Kodi and Amazon plugin on both box, also on Windows10 on Beelink.
I have some problems with Libreelec and coreelec (same problems in 2 differents hardware), but not under Window 10 installed on same box.
1) Using a 1080p display play is stuttering. I noticed that actually, in Italy, the max resolution stream (I can see it in manual mode) is 960 X 540, a quarter HD. Maybe is for COVID . If I set the display at original size, play is ok but the canvas is small. The problem is scaling up the video, but normally Kodi have no problem with others low resolution stream, and this problem happen on Intel Hardware and Amlogic also. But on Intel on windows is OK, So is not a hardware performance problem. 
2) When I start play, There is no audio for some minutes, and if I click on audio track I see "unknown audio". After one or two minutes the audio begin to play and I'm able to change audio stream. This not happen on same hardware on windows (I can't try Windows on Amlogic...)
3) Generally speaking, all navigation is very very slow, again, is not a performance problem because with the same Atom processor under windows is a bit quick. But Also in windows speed is not good.

To be exact, On Amlogic I tried only CoreElec, on Intel I tried LibreElec (and Windows). Unfortunately there is no libreelec distribution with kodi 18 for my Amlogic box.
Thanks for your support.

**Comment by Sandmann79** [comment]
Your amlogic box should came up with Android preinstalled. If this box is Widevine L1 certified, you could playback up to 1080p with hardware rendering at Android. All other systems are limited to 540p/SD quality and software rendering.

If you see that the performance differs between operating systems, you should ask at the corresponding forum. That's not an addon issue.

**Comment by Willyfan** [comment]
Yes, I have android preinstalled. I will try under android and kodi, But I have a lot of audio limitation (no able to passtrough for example). A question, why "All other systems are limited to 540p/SD quality and software rendering."?

**Comment by Willyfan** [comment]
Ok, Tried to install plugin in Andoid ( So, I have plugin in coreelec, Android and win10...) Seems work, but it freeze the system avery time I try to change audio. Anyway It start without audio, just like coreelec.

**Comment by Willyfan** [comment]
No, It freeze everytime just some seconds after star video. Unusable.

**Comment by Varstahl** [comment]
>  why "All other systems are limited to 540p/SD quality and software rendering."

Google/Amazon limitations.

In any case, if the playback starts we can't help you. It seems to me like a box-specific issue, you need to look into hardware manufacturer forums or something similar. Other than enabling audio pass-through, disable HDCP override in InputStream.Adaptive, we can't do. The playback is out of our control, it's between the O/S, Widevine/LibDRM and Kodi.
