### ISSUE TITLE
Audio language selection is erratic.

### ISSUE THREAD

**Issue by gary9872** [Sandmann79/xbmc#438]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [0.8.2]

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [S905W]
- OS Version: [CoreELEC 9.2.1]
- Kodi Version [e.g. 18.5]

**Describe the bug**

Videos play fine, but audio is not present. By stopping the video and re-starting the video the audio is present on the second or third attempt. On the second or third attempt the audio track is usually in German, even though all the preferences in Kodi are set to English (Infrequently when audio is available it will play in English. On the attempts where there is no audio, audio tracks available are 1 of 0 audio tracks. When there is audio, German is the first audio track in the list. 

Debug log attached.

Episodes played and results...

2x08 Played in English. (I had played this earlier today, not first attempt)
2x09 Played in German (I had played this earlier today, not first attempt)
2x10 No audio
2x10 No audio (attempt 2)
2x10 Played in English (attempt3)

Debug Log (1MB)

https://drive.google.com/file/d/1ts9CYjAJ9ooJZxEAWc71VehFakP0CInK/view?usp=sharing

**Comment by Varstahl** [comment]
Might be slow connection or their servers acting up. Sometimes it happens. If you have a slow connection you can try disabling the "MPD Proxy Alteration" and see if it makes things better for you.

**Comment by gary9872** [comment]
I have a good connection.

But disabling "MPD Proxy Alteration" seems to be fixing the problem. 

Thank you very much.
