### ISSUE TITLE
Some elements aren't avalible 

### ISSUE THREAD

**Issue by BrokenBaron** [Sandmann79/xbmc#441]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- Addon Version [0.8.3]

**Prime Video Account (select one)**
- [ ] amazon.(com/co.uk/de/jp)
Italian account

**System Setup (please provide the following information):**
- Hardware: [ RPi 2b+]
- OS Version: [OSMC 2020.01-2]
- Kodi Version [18.5]

**Upload Logs**
https://paste.osmc.tv/omexopejik

**Describe the bug**
Hello, this is my first time that I ask something here and I hope I'm doing it the right way
I'm watching Star Trek:Picard but episode 7 and 8 aren't on the list (but they are included in my subscription) It seems the addon doesn't update the content list(is there a way to do it manually?)
what could be the problem?
Thanks in advance.

**Comment by Varstahl** [comment]
It should already be fixed in Amazon VOD 0.8.2. Can you confirm you have it updated to the latest version?

**Comment by BrokenBaron** [comment]
I filled the previous post with the info needed,
I report that the add-on version is 0.8.3
The mistery is becoming deeper...
Thanks for the attention

**Comment by Varstahl** [comment]
Seems like an already solved issue but I don't manage that segment of the code, so I'm not entirely sure. @Sandmann79 does it ring a bell?

In any case @BrokenBaron you need to provide the full logs if you please. Enable debug logging and attack the full log in the original post or in an answer to this issue. OSMC just like LibreElec might provide a way to automatically upload the logs straight from Kodi. More info can be found in the FAQ section in the Wiki above.

**Comment by Sandmann79** [comment]
@Varstahl yes but only for the amazon db addon, with amazon vod i never encountered such issue.

I just recently checked this show for for US/UK and Germany accounts and all episodes are available.

**Comment by BrokenBaron** [comment]
I attached the log in the first post
Just to clarify,  this Amazon account is Italian
Thanks for your time

**Comment by Varstahl** [comment]
> Just to clarify, this Amazon account is Italian

Well, then right click/open contextual menù on the season, and hit Refresh :D

**Comment by BrokenBaron** [comment]
Oh,thanks
I'm sorry for opening this issue for such a stupid question
Thanks for your time
