### ISSUE TITLE
Unfortunately errored again

### ISSUE THREAD

**Issue by dfdario** [Sandmann79/xbmc#442]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: M8S / PC / Raspberry 
- OS Version: Android nougat / Debian 10 / LibreElec
- Kodi Version 18.6
[kodi.log](https://github.com/Sandmann79/xbmc/files/4456741/kodi.log)

**Upload Logs**
Uploaded `kodi.log` 
[kodi.log](https://github.com/Sandmann79/xbmc/files/4456743/kodi.log)

**Describe the bug**
Error check the log appears after a while.
Log attached

**Comment by Varstahl** [comment]
Fixed in 8d4e0285a1f36f67f6017a27cdad321cd1d91c49, will be out with the next release shortly.

**Comment by dfdario** [comment]
Patch works great

**Comment by Varstahl** [comment]
I know, I'm awesome like that ;)
