### ISSUE TITLE
Watchlist not showing

### ISSUE THREAD

**Issue by ddmakadia1699** [Sandmann79/xbmc#443]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [x] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [e.g. RPi]
- OS Version: [e.g. Windows 10]
- Kodi Version [e.g. 18.6]

**Upload Logs**
Upload `kodi.log` somewhere and post the link here. If you need help finding it, [read the appropriate entry in the FAQs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi).
For Login issues, enable advanced logging in the settings, upload the `(amazon/avod)-login` files from the [Kodi Home](https://kodi.wiki/view/Special_protocol) folder, and paste the link here, as well.

**Describe the bug**

Your watchlist is empty every time. I already watchlist some movies but didn't show here.

**Comment by Sandmann79** [comment]
This has been already fixed with 6ba0d40b56686369475d6c4907cc4f1be256f095, but it's not released yet.

@Varstahl please wait with the next release - i've to push some commits

**Comment by ddmakadia1699** [comment]
Can you share specific waiting time or anything ?

**Comment by Varstahl** [comment]
@Sandmann79 sure thing.
@ddmakadia1699 hawaiian time: it's coming out when it's ready. In the meanwhile you can grab [from here](https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon-test/resources/lib) common.py, logging.py, primevideo.py, and replace with them the ones on your device.

**Comment by ddmakadia1699** [comment]
> @Sandmann79 sure thing.
> @ddmakadia1699 hawaiian time: it's coming out when it's ready. In the meanwhile you can grab [from here](https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon-test/resources/lib) common.py, logging.py, primevideo.py, and replace with them the ones on your device.

Thank you Man

**Comment by ddmakadia1699** [comment]
Sorry but not working.

**Comment by Varstahl** [comment]
Refresh the watchlist :P

**Comment by ddmakadia1699** [comment]
> Refresh the watchlist :P

Also tried reboot

**Comment by ddmakadia1699** [comment]
> > @Sandmann79 sure thing.
> > @ddmakadia1699 hawaiian time: it's coming out when it's ready. In the meanwhile you can grab [from here](https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon-test/resources/lib) common.py, logging.py, primevideo.py, and replace with them the ones on your device.
> 
> Thank you Man

Any other files ?

**Comment by Varstahl** [comment]
Not that I could think of. If you got any error enable debug logging and attach the log in a reply to this issue. You can find more info in the FAQs, in the Wiki above.

**Comment by ddmakadia1699** [comment]
> Not that I could think of. If you got any error enable debug logging and attach the log in a reply to this issue. You can find more info in the FAQs, in the Wiki above.
> 
> **Edit:**
> 
> > Also tried reboot
> 
> Reboot doesn't work, the cache is stored on disk not volatile memory. Unless you right-click on the Watchlist and press refresh, it won't help.

cool man
now it's working.
