### ISSUE TITLE
player crashes on certain videos

### ISSUE THREAD

**Issue by drklanne** [Sandmann79/xbmc#445]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: RPi
- OS Version: Linux osmc 4.19.55-6-osmc
- Kodi Version 19 Matrix

**Upload Logs**
https://paste.osmc.tv/hikonozali

**Describe the bug**
Playing certain media crashes the player (sad face). However some videos do play without error.
I have no clue what is causing the issue.

**Comment by Varstahl** [comment]
I don't deal with german accounts, but so far everything seems working just fine, including passing the streams and drm keys to IS.A. My go to suggestion would be to drop OSMC and try LibreElec, OSMC has been known from a while to be a source of weirdness.

**Comment by drklanne** [comment]
Can you tell if this
DEBUG: AddOnLog: InputStream Adaptive: DecryptSampleData: Decrypt failed with error: 2 and key: 6F88148B12E945E6AF8B748D7D3BC3C0
is an error or just normal behaviour?

**Comment by Varstahl** [comment]
Should be normal, that might be that without HDCP Widevine requires a specialized hardware proprietary of Google to decrypt, so only SD quality content is available.
