### ISSUE TITLE
Problem in the subtitles synchronization after pressing the skip intro button

### ISSUE THREAD

**Issue by Essam311** [Sandmann79/xbmc#446]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version: 0.8.3

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: PC
- OS Version: Windows 10
- Kodi Version: Kodi 19 Matrix

**Upload Logs**
Upload `kodi.log` somewhere and post the link here. If you need help finding it, [read the appropriate entry in the FAQs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi).
For Login issues, enable advanced logging in the settings, upload the `(amazon/avod)-login` files from the [Kodi Home](https://kodi.wiki/view/Special_protocol) folder, and paste the link here, as well.

**Describe the bug**

The subtitles become not synchronized after pressing the skip intro button.

**Comment by Sandmann79** [comment]
Maybe a Kodi player related bug. It's a strange behaviour - by seeking to a specific time the subtitles won't synchronised, but by skipping with arrow keys everything is synchronised.

**Comment by Essam311** [comment]
Thank you so much, https://github.com/Sandmann79/xbmc/commit/c2a35f861c1e8bc8b85579898b528d091ad09599 fixed the problem for me.

**Comment by Essam311** [comment]
@Sandmann79 https://github.com/Sandmann79/xbmc/commit/590183e04b76331eb202ca94879b5735e68843f3 made the subtitles become not synchronized again after pressing the skip intro button, tested with the TV series "The office" season three episode 5.

**Comment by Sandmann79** [comment]
Yep forget to test this yesterday. 24edde0dab52ac1043886aec10cfdaf326e7a4cf should fix this. 
It's not my favourite solution for this bug, but maybe the only one.

**Comment by Essam311** [comment]
@Sandmann79 Thank you, https://github.com/Sandmann79/xbmc/commit/24edde0dab52ac1043886aec10cfdaf326e7a4cf works fine.

**Comment by Essam311** [comment]
@@Sandmann79 Is it possible to add an option to auto skip the intro to the settings?

**Comment by Essam311** [comment]
@Sandmann79 Skip Recap does not work right with https://github.com/Sandmann79/xbmc/commit/24edde0dab52ac1043886aec10cfdaf326e7a4cf it works right with https://github.com/Sandmann79/xbmc/commit/c2a35f861c1e8bc8b85579898b528d091ad09599 tested with the TV series "The Office" season 3 episode 11.

**Comment by Sandmann79** [comment]
@Essam311 You mean The Office (US) 3x11 - Back from vacation? If yes, this shouldn't work with the patch you mentioned.

But never mind there is something new to test for you. This time as attachment (i won't spam the commits with this trial & error testing). Just unzip this file to `plugin.video.amazon-test\resources\lib`. 
[playback.zip](https://github.com/Sandmann79/xbmc/files/4470141/playback.zip)

**Comment by Essam311** [comment]
@Sandmann79 Thank you, skipping intro and recap working great now and the subtitles are sunchronized after using https://github.com/Sandmann79/xbmc/files/4470141/playback.zip.

**Comment by Varstahl** [comment]
That might be useful as a sub-option for skip buttons enabling setting. Also, slight off topic, @Sandmann79 when selecting Script playback method the browser field is visible. It shouldn't right? Might have messed that at some point.

**Comment by Sandmann79** [comment]
@Essam311 that should be possible 
@Varstahl or as list setting "intro/recap scenes processing" with options do nothing, display button, autoskip intro, autoskip recap, autoskip all?
The browser field is just for using the correct fullscreen switch.

**Comment by Essam311** [comment]
@Sandmann79 The file https://github.com/Sandmann79/xbmc/files/4470141/playback.zip seems not to work all the time correctly after pressing the Skip Intro button it skips to much more time.

**Comment by Sandmann79** [comment]
You're talking from seconds or minutes? Can you provide a debug log?

**Comment by Essam311** [comment]
@Sandmann79 It skipped forward about two minutes, here is the debug log, tested with episode 20 in season 3 from The office (US) in primevideo.com "Safety Training" (the episodes in primevideo.com for season 3 from the office (US) have different numbers than the ones in imdb)

https://pastebin.com/JjxdA0Si

**Comment by Sandmann79** [comment]
Okay somewhere between your Kodi build (20200408) and my version (20200324) they fixed that issue with seeking from play position. That's the reason why commit https://github.com/Sandmann79/xbmc/commit/c2a35f861c1e8bc8b85579898b528d091ad09599 works perfectly for you. 
On older versions seeking forward with values lower 60 seconds will result in jumping direct to this position from the beginning instead current position of video.

**Comment by Essam311** [comment]
@Sandmann79  Shouldn't https://github.com/Sandmann79/xbmc/commit/24edde0dab52ac1043886aec10cfdaf326e7a4cf and https://github.com/Sandmann79/xbmc/commit/590183e04b76331eb202ca94879b5735e68843f3 reverted?

**Comment by Essam311** [comment]
@Sandmann79 Thank you so much for adding the option for automatically skipping intro and recap.
