### ISSUE TITLE
working chrome full screen switch amazon prime

### ISSUE THREAD

**Issue by tebrauer** [Sandmann79/xbmc#447]
<path to chrome>chrome.exe --start-fullscreen
has been tested and working in windows 10 pro x64
chrome versions 80 and 81
simply launches chrome in full screen not kiosk mode so it doesn't lock up kodi or the rest of the computer.

i did try editing the plugin settings file at appdata/roaming/kodi/userdata/addon_data/plugin.video.amazon-test and adding the switch after the filepath but with no luck

anyway i hope this info is usefull and i know myself and many other users would be grateful if we could find a way to use this behavior instead with chrome.

**Comment by Sandmann79** [comment]
If you want to add some custom switches, you can do that with the Script/Batch option. Just set at script path the path to your chrome.exe and at parameter your switches.
While Chrome browser runs the Kodi window becomes always blocked, to intercept remote commands.
