### ISSUE TITLE
Missing Amazon VOD icon with the latest Kodi 19

### ISSUE THREAD

**Issue by Essam311** [Sandmann79/xbmc#448]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version: 0.8.3

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: PC
- OS Version: Windows 10
- Kodi Version: Kodi 19

**Upload Logs**
Upload `kodi.log` somewhere and post the link here. If you need help finding it, [read the appropriate entry in the FAQs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi).
For Login issues, enable advanced logging in the settings, upload the `(amazon/avod)-login` files from the [Kodi Home](https://kodi.wiki/view/Special_protocol) folder, and paste the link here, as well.

**Describe the bug**

Just a minor problem I noticed, starting from the build KodiSetup-20200408-16d33391-master-x64.exe for Kodi 19 the Amazon VOD icon is missing.

<img width="408" alt="icon" src="https://user-images.githubusercontent.com/59211054/79039627-df747c80-7be2-11ea-9d88-1804a57b7ee0.png">

**Comment by Essam311** [comment]
This looks to be the reason of this problem.

https://github.com/xbmc/xbmc/pull/17479

The problem solved for me when I modified `addon.xml` to be 

    <platform>all</platform>
	<assets>
      <icon>icon.png</icon>
    </assets>

https://github.com/xbmc/xbmc/pull/17479#issuecomment-602846363

**Comment by Sandmann79** [comment]
Fixed with 4984d8f4ef340b8e160fc5dbbeae4b1840fe0374

**Comment by Essam311** [comment]
Thank you.
