### ISSUE TITLE
Update Amazon/PV iconography

### ISSUE THREAD

**Issue by 27hectormanuel** [Sandmann79/xbmc#449]
UPDATE YOUR ICONS

![fanart](https://user-images.githubusercontent.com/22853711/79051792-32106180-7c00-11ea-93da-bc4310215a28.jpg)
![icon](https://user-images.githubusercontent.com/22853711/79051793-32106180-7c00-11ea-972e-69ff0ef1a506.png)
![next](https://user-images.githubusercontent.com/22853711/79051812-4eac9980-7c00-11ea-8ca1-3d6a3820b930.png)

**Comment by Varstahl** [comment]
Looks good to me, but I'd personally keep the current VOD icon, and just update it for the new amazon styles. And I could rework the fanart while I'm at it. @Sandmann79 opinions?

**Comment by 27hectormanuel** [comment]
@Varstahl thank you

**Comment by Sandmann79** [comment]
If you add a home icon and the fanart in Full HD, we can use it.

**Comment by Varstahl** [comment]
I'll get to it tomorrow or monday at the latest, then.

**Comment by Varstahl** [comment]
Gave it a shot, I'm not sure about the logo, but the white one I really dislike, might give it a try with a different style later. In the meanwhile: opinions?

![pv_fanart_scaled](https://user-images.githubusercontent.com/284077/79371543-d6720b00-7f54-11ea-89dd-a0f777f7bea4.png)
![pv_logo_scaled](https://user-images.githubusercontent.com/284077/79371547-d70aa180-7f54-11ea-8afa-73c91ff0f727.png)

**Comment by 27hectormanuel** [comment]
I like the fan art.

**Comment by 27hectormanuel** [comment]
@Varstahl https://press.aboutamazon.com/images-videos/

**Comment by 27hectormanuel** [comment]
@27hectormanuel Consider, changing the add-on name to "Prime Video."

**Comment by Varstahl** [comment]
That's best left as it is. Both for international and copyright reasons.

**Comment by 27hectormanuel** [comment]
When can we expect an the iconography update for the add-on? In addition,
maybe you should establish various icons for, "User, watchlist, movies, TV
recently watched, etc."

I can help with that as well.

**Comment by Varstahl** [comment]
> When can we expect an the iconography update for the add-on

Will be bundle with the next update, a few days I guess

> maybe you should establish various icons for "User, watchlist, movies, TV recently watched, etc."

That's a pain, and can't really do it, because every nation does that differently, it's not uniform across the globe. So you'd have to mix and match, and best guess… just like the "Prime Video" title, it's more trouble than it's worth.
