### ISSUE TITLE
Missing win_inet_pton. Is it solely for windows?

### ISSUE THREAD

**Issue by chebureki** [Sandmann79/xbmc#450]
**Addon used**
Amazon VOD (plugin.video.amazon-test)
- Addon Version [e.g. 0.8.3]
-OS(uname output): (5.4.0-0.bpo.4-amd64 #1 SMP Debian 5.4.19-1~bpo10+1 (2020-03-09) x86_64 GNU/Linux)

So, it is missing the dependency and thus can not install.

**Comment by Varstahl** [comment]
You what?

**Comment by Sandmann79** [comment]
win_inet_pton is not a dependency of our addon. Closing.
