### ISSUE TITLE
Color channels are out of place

### ISSUE THREAD

**Issue by chrmue94** [Sandmann79/xbmc#451]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.8.3]

**Prime Video Account (select one)**
- [ ] primevideo.com
- [x] amazon.de

**System Setup (please provide the following information):**
- Hardware: RPi 4 (4GB RAM)
- OS Version: LibreELEC 9.2.1
- Kodi Version 18.6

[Logfile](https://pastebin.com/RHwbbCAk)

When playing certain movies or tv show episodes the RGB color channels are not in the same position as the actual video, which can be seen in grayscale:
![screenshot000](https://user-images.githubusercontent.com/13153987/79255261-45346300-7e86-11ea-8dc7-b1501656e6b2.png)

I tried it with episode 1 and 2 of Family Guy Season 1 (Season 16 seems to work), Back To The Future (German Version), Fight Club, My Name Is Somebody
I'm not sure if any of these are available in your Country

**Comment by Varstahl** [comment]
The bug is not related to the addon but the RPi4 itself, and there's already an issue submitted to Kodi.
