### ISSUE TITLE
Wrong episode thumbnail used when exporting series

### ISSUE THREAD

**Issue by mbroemme** [Sandmann79/xbmc#453]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [0.8.3]

**Prime Video Account (select one)**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [Intel NUC]
- OS Version: [Arch Linux]
- Kodi Version [e.g. 18.6]

**Describe the bug**
When exporting a series with creating the video information file (NFO), all exported episodes have the same thumbnail. This thumbnail is not from the matching episode, it is from the series. For example:

Carnival Row (S01E01) - current one in `<thumb>` tag which is wrong: http://ecx.images-amazon.com/images/I/51dyNGvIX3L.jpg
Carnival Row (S01E01) - correct one: https://images-na.ssl-images-amazon.com/images/I/81DTE0l5VXL._SX296_.jpg

I've tried it with Carnival Row, Paw Patrol and Peppa Pig.

**Comment by Sandmann79** [comment]
This behavior does not only occur during export - it occurs generally in the addon.

Some time ago I had to decide whether to show season image or episode previews. With the latter, for some seasons no pictures are shown anymore. The following image appears:
http://g-ecx.images-amazon.com/images/G/01/x-site/icons/no-img-sm._UR667,500_V1_PJPrime-Sash-Extra-Large-2017,TopLeft,0,0_.gif. 
So i decided to use the first one.

Which image is displayed is determined by the DeviceTypeID.
You can simply test this be changing the value from `AR8DE21S8PINM` to `A3SSWQ04XYPXBH` at [network.py](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/resources/lib/network.py#L264).

Maybe i add an option in future, to switch between this two options.

**Comment by mbroemme** [comment]
Thanks for the quick fix
