### ISSUE TITLE
Raspberry Pi 3+, Raspbian, Prime Video sound and subtitle issues

### ISSUE THREAD

**Issue by Pierric82** [Sandmann79/xbmc#454]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version 0.8.3

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 3+, plugged in via 100Mbs Ethernet
- OS Version: Raspbian Buster
- Kodi Version 18.6

**Upload Logs**
[kodi.log](https://github.com/Sandmann79/xbmc/files/4488399/kodi.log)

**Describe the bug**
I've finally managed to get Amazon Prime more or less running on my Pi with Kodi thanks to your awesome plugin (thanks so much for maintaining this for the community!), but I'm facing some real bad issues.
I've seen related threads:
https://github.com/Sandmann79/xbmc/issues/164
https://github.com/Sandmann79/xbmc/issues/287
but I couldn't solve my problem from there.

With default options, videos (while taking quite some time) will run perfectly. But some of them have audio, while others (most) don't. There is no audio stream in the list. Subtitles are similarly affected, with sometimes a few subtitles that work, sometimes subtitles listed correctly but not displaying, and sometimes no subtitles detected.

Here's a movie that does have working audio (in Spanish):
https://www.primevideo.com/detail/0LCRVR3OWFE0E8ZQ2FS2918ERM
Here's one with no audio detected (but it has several languages when accessed from a PC on the primevideo.com website):
https://www.primevideo.com/detail/0IMNQC2DTPCJ1Z8PA1ZSGNQIGE

Because of what I saw in the other threads I've tried the option related to MPD proxy. Then, things get wayyyy slower even, I get very long buffering times (i'm plugged directly into a verified symmetrical 100Mbs line; on the pi itself I have measured 92 down/89 up). Then it seems the video starts playing, but it's actually a blank (black screen) video, even if I can still pause, unpause, etc. Still no sound BUT a list of many audio streams that were missing before.

In the attached log, I believe I have the full session where I tried several times (the log is massive, maybe it's over-verbose, I'm not sure how to set that up properly). I can see, starting from the end, some Amazon VOD activity just after broken pipes errors. To be honest I'm not sure anymore if that is with the MPD option on or off.

I'm based in Spain, if that helps due to geographic restrictions.

What can I try to solve this?

Thanks,
Pierric.

**Comment by Varstahl** [comment]
In theory by having MPD proxy not disabled you shouldn't really have issues on a 100mbit, although as I can see from the logs, you have __a lot__ of disconnect issues, apparently. Some of them might be justified but some definitely not.

If you don't mind trying, I would above all suggest you try replacing the Raspbian with a LibreElec installation. Raspbian have been a cause of different types of issues, so to at least rule out specific distro problems, I'd try that.

With the MPD proxy disabled you should have a faster loading time, if it's faster but blank, then there's some codec troubles.

**Comment by Pierric82** [comment]
Thanks for your quick answer!

> If you don't mind trying, I would above all suggest you try replacing the Raspbian with a LibreElec installation. Raspbian have been a cause of different types of issues, so to at least rule out specific distro problems, I'd try that.
Ha, that's ironic... my SD was shared between a LibreElec I never used and Raspbian. In order to upgrade to Raspbian Buster and get Kodi working properly, I had to get rid of LibreElec and resize the Raspbian partition (small SD card). It took me 2 days to figure out how to do all of that, and it culminated in Kodi finally working with your plugin :) I'm not keen on doing partition surgery again after that. But if I can find an SD card lying around somewhere I might try this. I'll revert soon if that's the case.
Note that I do need to keep Raspbian as I also run a server and some automated tasks from the Pi (though I admit I don't know what LibreElec allows to do)

>With the MPD proxy disabled you should have a faster loading time, if it's faster but blank, then there's some codec troubles.
I have _slower_ loading times (by far) and the blank screen. :/

Cheers,
Pierric.

**Comment by Varstahl** [comment]
My only tests have been on an Orange Pi PC 2, so they don't count too much, but several reports of users over the years have confirmed that Raspbians and OSMC often make this type of issues crop up.

There are users running Raspbians, but I'm one of those that after a try and the lacking support for the embedded graphic processor happily switched over to LibreElec, so I can't help you configure the Raspbian properly.

I appreciate the sentiment of running other servers on top of the HTPC features, but I just don't have the answers.

**Comment by Pierric82** [comment]
Hi!

I have to apologize for wasting your time. Though you did help me, as your statement below made me think:

> I can see from the logs, you have a lot of disconnect issues, apparently. Some of them might be justified but some definitely not.

Having the Pi plugged by Ethernet was actually a recent change after first getting Kodi up and realizing the WiFi was very slow on the Pi. It turns out both wifi and LAN were on at the same time, each with a different local IP. In appearance things were working, and speed tests gave the best performance possible, but it seems it was complete chaos under the hood, at least for Kodi. After taking the WiFi down fully, I got access to all the audio channels, video and audio now work without a problem (tried with MPD option checked and unchecked and can no longer see a difference in performance or function).

The only thing that's not solved is that I'm still not seeing the subtitles on screen, even if I do get a (often long and therefore apparently over-exhaustive) list of them. I'm attaching a new log of when I run a few videos when only the subtitles were a problem. Maybe with the rest of the noise out of the picture, something will reveal itself?

[kodi.nosubs.log](https://github.com/Sandmann79/xbmc/files/4491526/kodi.nosubs.log)


Cheers,
Pierric.

**Comment by Varstahl** [comment]
I don't seem to see anything wrong in the logs, so before we go on make sure you read this [wiki entry](https://github.com/Sandmann79/xbmc/wiki/FAQ#how-can-i-select-the-appropriate-subtitles--where-are-my-subtitles), it might help you out.

**Comment by Pierric82** [comment]
Hi!
It wasn't language or connection-related at all, but the solution WAS in the Language menu of Kodi, enabling expert options. Forcing the subtitles position to "Bottom of video" brought the subtitles back. It seems they were there, but off-screen... Looks like my Linux Prime Video box is pretty much all set! The only thing I'm missing now is a way to jump directly to my favorite season of a show, to avoid all the intermediate menus. Maybe one day ;)
Thanks again for the great work, I really enjoy your plugin!
Cheers,
Pierric.

**Comment by Varstahl** [comment]
> The only thing I'm missing now is a way to jump directly to my favorite season of a show, to avoid all the intermediate menus. Maybe one day ;)

Kodi has a favourite menù which is fully supported by Amazon VOD. You can simply right-click/open the contextual menù with a season selected and add it to favourites. It will be listed there, so you can jump straight into episodes.

**Comment by Pierric82** [comment]
Indeed it worked! Top notch, thanks!
