### ISSUE TITLE
Request to add region India http error

### ISSUE THREAD

**Issue by sathish804** [Sandmann79/xbmc#456]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [e.g. RPi] OnePlus 6t
- OS Version: [e.g. Windows 10] Android 10
- Kodi Version [e.g. 18.4] 18.6

**Upload Logs**
[Pastebin.com/q1l3zpqr](https://pastebin.com/q1l3zpqr)

**Describe the bug**
After logging into Amazon VOD addon with Indian prime account while trying to view any video is showing the http error. Tried with the VPN as well but same error is being shown. Kodi log link posted above

**Comment by Varstahl** [comment]
There are multiple problems in your installation:
1. there's some weird python/connection issues.
2. you have misconfigured network on the machine, which is blocking local host connections.

India is fully supported, you need to fix the network on that box yourself, possibly firewall limitations, not 100% sure.

One thing you can do, is write `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36` inside `userdata/addon_data/plugin.video.amazon-test/config/UserAgent`. This will fix one of your issues, but unless you fix the remaining issues on the box, this addon will never work. The addon itself is working fine.

**Comment by sathish804** [comment]
Dear Developer,
Thank you!! I cleared the data of kodi and made a fresh setup with this add on now everything seems to be working!!
