### ISSUE TITLE
[Request] Add a openplayer json file to be used by OpenMeta & TheMovieDB Helper

### ISSUE THREAD

**Issue by prateek33** [Sandmann79/xbmc#459]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [e.g. RPi] - Mac Mini
- OS Version: [e.g. Windows 10] - Windows 10
- Kodi Version [e.g. 18.4] - 18.6

Please add a player.json file here - https://github.com/a4k-openproject/json.openplayers
so it can be used by OpenMeta and TheMovieDB Helper addons. It would be a lovely addition where those addons can try to play a video on amazon before falling back on other addons.

**Comment by Sandmann79** [comment]
There's no wiki or other useful informations, how to do this on their website. 

Regarding to the netflix json, you could use the following search sting:
`plugin://plugin.video.amazon-test/?mode=Search&searchstring={clearname_+}`
update the other values and create a pull request.

But i don't know, if this is the correct format.
