### ISSUE TITLE
Playback issue occurs when play movies

### ISSUE THREAD

**Issue by posterpico** [Sandmann79/xbmc#460]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [e.g. Amlogic S905]
- OS Version: [e.g. Android 6.01]
- Kodi Version [e.g. 18.6]

**Upload Logs**
[Kodi Log]https://pastebin.com/raw/qJHmxy6J)

**Describe the bug**
Movies won't play, but TV Shows worked fine. When attempt to play movie, it is just loading forever.
when i play Tom Clancy's Jack Ryan (TV Shows) and it worked fine. but when i play The Big Sick, Transformers, Ride Along, etc (Movies) it is just loading forever.

**Comment by Varstahl** [comment]
Well, netflix crashes, and then this:
```
CDVDVideoCodecAndroidMediaCodec::AddData error(-10000)
```
I'm sorry but this is beyond what I know of Kodi's playback, and it's not an addon problem, can't really help you there.
