### ISSUE TITLE
Strange color corruption when playing movies

### ISSUE THREAD

**Issue by filippobistaffa** [Sandmann79/xbmc#461]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.8.1]

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [RPi 3]
- OS Version: [LibreELEC devel-20200422001140]
- Kodi Version [19.0-ALPHA1]

**Upload Logs**
https://pastebin.com/FqTHej6S

**Describe the bug**
Sometimes when I play some movies (it never happened with tv series) colors are rendered with strange artifacts, see screenshots for "L.A. Confidential"

![screenshot000](https://user-images.githubusercontent.com/1221756/80747291-80d85980-8b23-11ea-8399-63ea0f5a3ddd.png)
![screenshot001](https://user-images.githubusercontent.com/1221756/80747293-82098680-8b23-11ea-93de-f80ab35ed531.png)
![screenshot002](https://user-images.githubusercontent.com/1221756/80747297-82a21d00-8b23-11ea-8d7a-d97c1454bc44.png)

**Comment by Varstahl** [comment]
Yep, known issue with Raspberry Pi / Kodi / IS.A, unrelated to the addon, I don't know the status of the fix or even if someone's looking at it. I think (not 100% sure) the same problems also affects other services like Netflix. You might find more info on [forum.kodi.tv](https://forum.kodi.tv), I know there was a thread somewhere, I just don't remember where.

**Comment by w1k1n9cc** [comment]
I face the same issue at the moment. With other add-ons it's working without any problems.
I take a look in the forum und searched for a while but only found [this post](https://forum.kodi.tv/showthread.php?tid=352978). Is this the thread you mentionend?

**Comment by Varstahl** [comment]
Not really. I'm sorry but I really, really, don't remember where the thread was linked, looked for it too but couldn't find it. I just remember that there was some problem on RPi and saw screenshots of both Netflix and AVOD in it, and then the user who initially reported the issue moved to the other thread and I don't know how it ended.

**Comment by Varstahl** [comment]
It should be linked to this issue: https://github.com/xbmc/xbmc/issues/17647

**Comment by w1k1n9cc** [comment]
No problem, thank you for your effort I will follow the issue you mentioned.
