### ISSUE TITLE
Allow language switch within the Addon

### ISSUE THREAD

**Issue by marcoboutch** [Sandmann79/xbmc#462]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: PC
- OS Version: Windows 10
- Kodi Version 18.6

Hi,

Solution:

in accounts.lst cookie i just replace "en_US" to "fr_FR

delete all cache files of this addon and restart. All will load in french ;)

I will attach my french .po file too.

Thank you

[resource.language.fr_fr.zip](https://github.com/Sandmann79/xbmc/files/4562682/resource.language.fr_fr.zip)

**Comment by Varstahl** [comment]
Question: did you go to primevideo.com to select French?

![French language selected](https://user-images.githubusercontent.com/284077/80803569-f8a19500-8bb2-11ea-9ed7-1640e3dfac49.png)

The addon uses an agnostic approach to language and locales, so whatever is defined globally gets carried over. Although I was already thinking about adding some selection in the addon.

**Comment by Varstahl** [comment]
Ooouch, you overrode the original strings instead of placing the translation… ok, it's going to take a bit more time than expected…

**Comment by marcoboutch** [comment]
Yes French is already selected. I dont know if i'm a isolate case. I think the cookie force to EN_US. You can check with other user if is only me..... or maybe if you just remove this argument in the cookie file will work. I will try without this argument and i come back to you.

**Comment by marcoboutch** [comment]
look working good whitout argument :) good news :)

**Comment by marcoboutch** [comment]
for the .po file if you can apply for all french region is  fr_fr (france) and fr_ca (quebec canada) is the same.
:)

**Comment by Varstahl** [comment]
Yeah, I was just trying to figure out what happened. Sometimes it does that and amazon decides to throw in the wrong locale, which then gets cached and used. At the moment there's no way to change that programmatically from within the addon, but should be relatively easy to do.

Since you mentioned fr_CA I'll assume you're canadian, so that's what I'm gonna write in it. Don't want frenchies breathing on my neck down the line :°D

**Comment by david-morris** [comment]
Hey, it would be great to add the workaround in detail to the readme.  I am in Germany, and I changed my audio language to English on primevideo.com, saw no change.   Signed out and signed in again on the app, and now I have no sound and Arabic script subtitles.  None of my devices have ever had any language with Arabic script as a locale option.

**Comment by Varstahl** [comment]
Sometimes amazon returns whatever it damn well pleases. As the workaround:

1. open `accounts.lst`
2. find the `cookie` hash map
3. If there is no `lc-main-av`, create it
4. change the `lc-main-av` to the locale you want, like `it_IT`, `de_DE`, or `en_US`

The end result should look something like this:
```
{"email": "", "password": "", "cookie": {"lc-main-av": "it_IT", …}]
```
After doing that you will need to either delete both *.pvcp and *.pvdp files, or delete *.pvcp and refresh where needed to update the old german/arabic/whatever content.

Also, note: this affects the *title/description/synopsis only*. The audio and subtitle languages are managed by Kodi. More information on how to change that is available on the Wiki.

**Comment by CGarces** [comment]
>and now I have no sound and Arabic script subtitles. None of my devices have ever had any language with Arabic script as a locale option.

Looks like the code is getting the first one on alphabetic order.

**Comment by Varstahl** [comment]
Kodi's code, yes.
