### ISSUE TITLE
Addon causes consistantly 100% CPU usage on Startup (OSMC, RPi3B)

### ISSUE THREAD

**Issue by gutiar-junky** [Sandmann79/xbmc#463]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version 0.8.3 and below

**Prime Video Account (select one)**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: RPi 3 B
- OS Version: OSMC (March 2020)
- Kodi Version 18.6

**Upload Logs**
-

**Describe the bug**
Every time I boot into Kodi with OSMC, the CPU usage of the kodi process is at 100% for very long time (like 20min to 1 hour mostly) and no Addon is able to run. 
That seems to be related to this addon since when I deactivate this addon and reboot, the CPU usage drops to 1-2 %.
I think, this is somewhat related to the addon's "Database Update" performing on every startup.
The problem exists since about half a year if not longer, both with the current Amazon VOD addon and the now aiscontinued Amazon Addon (former for accounts from amazon.de).

**Comment by Varstahl** [comment]
@Sandmann79 might it be the same problem of the other addon, with the scraping done in the foreground instead of the background?

**Comment by Sandmann79** [comment]
No there is no foreground service at Amazon VOD. On Startup it loads and parses a small [JSON file](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/resources/menu/A1PA6795UKMFR9.json) containing the categories and that's all (<10sec). Later while browsing the submenus it searches for fanart and posters in background.

Maybe you should disable or better remove the old discontinued Amazon Addon and restart Kodi/OSMC, to be shure that the background service is not running anymore.

**Comment by gutiar-junky** [comment]
I've tried every combination:

- Old discontinued Addon enabled: 100% CPU
- Old discontinued addon disabled then rebooted: normal CPU load
- New addon enabled then rebooted: 100% CPU load
- New addon disabled then rebooted: normal CPU load
- Boot without any amazon addon: normal CPU load, then installed any of both addons: normal load, then reboot: 100% CPU load

**Comment by Varstahl** [comment]
I don't know what to tell you, maybe add a full debug log, we're not aware of any similar issues, although we know OSMC usually breaks things. If you're testing distros, you might want to try switching OSMC with LibreElec, which has far superior compatibility in general.

**Comment by Varstahl** [comment]
Closing due to lack of follow up.
