### ISSUE TITLE
Fails to load all Shows (python error)

### ISSUE THREAD

**Issue by sammy2142** [Sandmann79/xbmc#470]
**Addon used**
-  Amazon VOD (plugin.video.amazon-test)
- Addon Version 0.8.4

**Prime Video Account (select one)**
- amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [e.g. RPi] Ryzen 2600 with x470 board
- OS Version: [e.g. Windows 10] Windows 10
- Kodi Version [e.g. 18.4] 18.6

**Upload Logs**

> 2020-05-12 18:30:49.759 T:14368  NOTICE: [Amazon VOD] getURL: "Censored (not sure if this contains any sensitive info - I have attached the output of this url below)
> 2020-05-12 18:30:51.000 T:14368   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.IndexError'>
>                                             Error Contents: list index out of range
>                                             Traceback (most recent call last):
>                                               File "C:\Users\sammy\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py", line 5, in <module>
>                                                 EntryPoint()
>                                               File "C:\Users\sammy\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\startup.py", line 77, in EntryPoint
>                                                 g.amz.listContent(args.get('cat'), url, int(args.get('page', '1')), args.get('opt', ''), int(args.get('export', '0')))
>                                               File "C:\Users\sammy\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\amazontld.py", line 419, in listContent
>                                                 contentType, infoLabels = self.getInfos(item, export)
>                                               File "C:\Users\sammy\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\amazontld.py", line 891, in getInfos
>                                                 infoLabels['TotalSeasons'] = item['childTitles'][0]['size'] if 'childTitles' in item else None
>                                             IndexError: list index out of range
>                                             -->End of Python script error report<--
> 

**Describe the bug**
Clicking All shows fails to load (it was working fine yesterday)

Regards
[output.txt](https://github.com/Sandmann79/xbmc/files/4617534/output.txt)

**Comment by Sandmann79** [comment]
Can confirm. This issue affects the complete TVShows category. 
Instead of seasons there're episodes displayed.
Amazon removed the `RollupToSeason` parameter from the Browse call.

There could be a quick dirty fix, to solve that issue, but in a long it need some more time.
Checking this
