### ISSUE TITLE
Changing website logo

### ISSUE THREAD

**Issue by Xaque8787** [Sandmann79/xbmc#471]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- [x ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:
- OS version:
- Kodi version number:

**Upload Logs**

**Describe the bug**

Would like to be able to change the icon from defaultfolder to another by editing the site text file. This worked for me the chrome launcher, same approach yields no results in broswer luancher.

**Comment by Varstahl** [comment]
Not sure if I understood correctly, but the addon logos and artworks are cached by Kodi. You need to manually delete the image cache database file, but I don't remember what it's called atm.

**Comment by Xaque8787** [comment]
Found the fix, the images need to go in the site folder in the userdata add-on, not in the skin add-on media folder (that worked from chrome launcher)
