### ISSUE TITLE
Issues in primevideo India

### ISSUE THREAD

**Issue by Vikassm73** [Sandmann79/xbmc#472]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:
- OS version: Windows 10
- Kodi version number: 18.6

**Upload Logs**

https://pastebin.com/1WWpDgNh

**Describe the bug**

In movies section, use to see "Movies in Hindi", "Movies in Marathi" initially but missing it now
Also "Movies by language" is completely blank. 

![image](https://user-images.githubusercontent.com/41675437/82523672-8802ee00-9b4a-11ea-8d29-703c32332bba.png)

**Comment by Varstahl** [comment]
Sorry that this issue got stale, but I'm dealing with the fallout of COVID issues at work, this is going to take a while, to check.
