### ISSUE TITLE
Watchlist

### ISSUE THREAD

**Issue by samritkunja** [Sandmann79/xbmc#474]
Hey. I had the same watchlist problem as discussed in #466 . I applied the patches as said in the discussion but now there's no error, but the watchlist infinite loops in itself. Eg. If I select "All" from the watchlist it just opens another watchlist menu with "Movies, TV shows and All" again and this keeps repeating. Please help.

**Comment by Varstahl** [comment]
Erm… is it solved or did you close it by accident?

**Comment by samritkunja** [comment]
It wasn't working at first, but I re-installed the add-on with the patches and it worked. Thanks again
