### ISSUE TITLE
HTTP Error (plus no watchlist)

### ISSUE THREAD

**Issue by ddceca** [Sandmann79/xbmc#475]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.8.5

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Both a PC and Raspberry Pi 2b
- OS version: Linux (KDE Neon) in the PC, OSMC 2020.03 in the Raspberry Pi
- Kodi version number: 18.7 in the PC, 18.6 in the Raspberry Pi

**Upload Logs**

https://pastebin.com/2xQx7SKe

**Describe the bug**

I installed Amazon VOD a few months ago in my both systems, and it worked without a problem. I hadn't touched it since then, but this week I tried to use it again and I found two problems:
- Can't play videos. I get a message that says "HTTP Error".
- I have lost my watchlist. I've read in the forum that it got moved, but I can't find it anywhere. My main menu has the following entries: "Start", "Shop", "TV series", "Movies", "Kids", "Included with Amazon Prime" and "Search" (translated from Spanish, mind you).

I've uploaded my logs (taken from the Kodi in the PC). I hope it helps. Thank you very much in advance.

**Comment by samritkunja** [comment]
refer #466 . There is a master zip file that if you extract the patches and paste into the user data folder it should fix (worked for me). Complete instructions are present there.

**Comment by Varstahl** [comment]
Ok, first things first:
1. try to disable "MPD proxy alteration" from the addon settings and check if that fixes the HTTP Error on playback
2. open a browser, go to [primevideo.com](https://www.primevideo.com/), save the html and attach it in a reply, here.

**Comment by ddceca** [comment]
I'm happy to report samritkunja's advice did work, but only after I uninstalled both Amazon VOD and Inputstream Helper. That is, only replacing Amazon VOD 0.8.5 with the master branch he linked didn't work, as both problems I reported were still present. But then I uninstalled both addons and reinstalled them again, and it did work.

Varstahl: I had tried disabling "MPD proxy alteration" before, and nothing had changed. In any case, here's my primevideo.com's html. I still haven't applied samritkunja's workaround in my Raspberry Pi, and I'm happy to keep it that way if you'd like to investigate the problem. Thanks a lot!
[Prime_Video_Firefox.zip](https://github.com/Sandmann79/xbmc/files/4672007/Prime_Video_Firefox.zip)

**Comment by samritkunja** [comment]
Happy to help :)

**Comment by Varstahl** [comment]
Ok, that was most unexpected, I wouldn't have bet on problems with IS.A, but glad you got it working. Feel free to uninstall/reinstall IS.A or other addons on the RPi too, it might be an issue not related to the addon itself, rather the environment.

**Comment by ddceca** [comment]
I have tried to repeat the process that worked on my PC, but it doesn't on my RPI. I still don't get my watchlist, and I still get an error when I try to play a video. However, some things have changed:
- The error I get when I try to play a video is no longer "HTTP error". Now it's "Invalid query" (or something similar, as it's in Spanish).
- My username doesn't look very good, as you can see in the picture :-)
![Amazon_VOD_rpi2b](https://user-images.githubusercontent.com/65789779/82740985-011e6300-9d4e-11ea-8b7e-bcf699b16709.jpg)
Here are my RPI logs.
[kodi.log.zip](https://github.com/Sandmann79/xbmc/files/4672554/kodi.log.zip)
Thanks a lot!

**Comment by Varstahl** [comment]
Well… try to erase the credentials and to log back in again.

**Comment by ddceca** [comment]
Yes, I've done that a few times and everytime it "registers" me as a different piece of code, always starting with an href attribute. I'm attaching a picture of the last one.
![Amazon VOD username](https://user-images.githubusercontent.com/65789779/82749972-4160fe00-9dad-11ea-8fcb-69d58d40716d.jpg)

**Comment by Varstahl** [comment]
Gotta love different canary background service changes across the globe…

**Comment by ddceca** [comment]
I have finally solved my RPi2 logging issues by copying both my .kodi/addons/plugin.video.amazon-test and .kodi/userdata/addon_data/plugin.video.amazon-test directories from my Linux PC to my RPi2 (with OSMC). That's the only way I could avoid registering from OSMC, which always resulted in an 'href=/blahblahblah...' username.

**Comment by paolinux79** [comment]
I don't have a computer to apply the @ddceca workaround. How can i solve It?

**Comment by Varstahl** [comment]
Never figured out the issue, I'm not sure. Are you experiencing the same issues, including the username error? Which country are you from?

**Comment by paolinux79** [comment]
I have the sane errore (no watchlist and http errore on playback). I m from italy

**Comment by Varstahl** [comment]
Do me a favour:
* Close Amazon VOD
* Delete everything inside `/.kodi/userdata/addon_data/plugin.video.amazon-test/`
* Make sure that Kodi and AVOD are up to date
* Log back in again
* If it doesn't work, zip everything from within that directory and upload it somewhere, even wetransfer is ok if you don't have the means to transfer from the RPi

**Comment by paolinux79** [comment]
I did it and now everything is working smoothly.
thanks!

**Comment by Varstahl** [comment]
I guess that whatever was causing this login related issues just solved itself. I'll close this issue.
