### ISSUE TITLE
Error at Amazon VOD start up

### ISSUE THREAD

**Issue by acquisgi** [Sandmann79/xbmc#476]
**Addon used**
- [X ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [X ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:
- OS version:
- Kodi version number:

**Upload Logs**

**Describe the bug**

file log attached. there is also one dependency not found (script.module.win_inet_pton)
[kodi.log](https://github.com/Sandmann79/xbmc/files/4673045/kodi.log)

**Comment by Varstahl** [comment]
[Unrelated to the addon](https://stackoverflow.com/questions/43267157/python-attributeerror-module-object-has-no-attribute-ssl-st-init), the problem is in your box.
