### ISSUE TITLE
http error after watching "foreign" streams

### ISSUE THREAD

**Issue by Steph71** [Sandmann79/xbmc#477]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: amazon-test v0.8.5

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Linux x86 64-bit
- OS version: LibreELEC (official): 9.2.2, kernel: Linux x86 64-bit version 5.1.16
- Kodi version number: 18.6 Git:18.6-Leia

**Upload Logs**

As the issue does not happen allways, I attach a good and a fail case log:

[vod_good.log](https://pastebin.com/t1qv1aCY)
[vod_fail.log](https://pastebin.com/rP3BFXGb)

**Describe the bug**

Replicatebility is a bit complicated for this, I try to describe as good as possible:

most times (not allways, 80% I would say) when I watch a different stream (could be youtube, or my favorate news channel) before starting my favorate series on Amazon VOD I see the following behavior:

opening my watchlist or (as in the logs)  a favorate entry from the season I want to watch takes very long. 

See fail log line 483 - 487 -> 30 seconds

My assumption is that the requests time out and I just get to see some cached entries ...

Then when trying to start an episode, a http error gets returned. See vod_fail.log line 493.

then when I restart kodi and navigate to the desired episode right away, everything works nicly.

This is what can be seen in the good log.

One more thing that cought my attention is, that in vod_fail.log entries like:

vod_good.log line 449, 455, 459 never happens.

I hope someone could have a look into what is going on here and suggest how to fix the issue.

**Comment by Varstahl** [comment]
I think we may have already discussed about this elsewhere, if not I'm sorry for the wait.
```
NOTICE: [Amazon VOD] Service: Proxy bound to 127.0.0.1:PORT_NUMBER
NOTICE: [Amazon VOD] Service: Proxy server started

NOTICE: [Amazon VOD] postURL: http://127.0.0.1:PORT_NUMBER/gpr/https%3A%2F%2Fatv-ps-eu.amazon.de…
  ERROR: [Amazon VOD] Error reason: HTTPConnectionPool(host='127.0.0.1', port=PORT_NUMBER): Max retries exceeded with url: /gpr/https%3A%2F%2Fatv-ps-eu.amazon.de…
         (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f959d8e0590>: Failed to establish a new connection: [Errno 111] Connection refused',)) (ConnectionError)
```
The thing is that on the "failed" attempt, there is no proxy server started. I don't know why that is, and as far as I can remember this is the only instance where I've seen it happen, and the issue might have already be gone by itself by now, but there's that.

Also, in regard to 449, 455 and 459:
```
NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.amazon.de/cdp/usage/UpdateStream?…
```
These are the remote "watched" updates sent to amazon servers while the video is playing. If the video doesn't start it obviously won't appear in the failed connection attempt.

If you're still experiencing this issue feel free to reopen with a debug log (info on the Wiki on what to enable) and we'll restart from there.
