### ISSUE TITLE
Option to browse subtitles from hard disk

### ISSUE THREAD

**Issue by foreverddong** [Sandmann79/xbmc#480]
When Subtitles- Browse Subtitles is selected, the default browsing window is skipped.
It would be nice to allow users to choose their own subtitles which Amazon may not offer.

**Comment by Paco8** [comment]
It works for me.

**Comment by Varstahl** [comment]
Sorry for the longest delayed answer, but to my knowledge there is no such issue, especially because we don't manage the streams past the point of providing URLs, it must be an issue between your Kodi installation or the skins you're using.
