### ISSUE TITLE
Fails to play under Android TV box

### ISSUE THREAD

**Issue by dfdario** [Sandmann79/xbmc#483]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.8.6

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Haked TV BOX
- OS version: Android TV 7.0.1
- Kodi version number: 18.7

**Upload Logs**

**Describe the bug**
Last version works fine on every device I have except my crappy spare TVbox. I am not use it frequently but indeed but I keep it as testing device.
I think the problem is the Widevine V1 L3 which equips as default in Android system which is not able to decrypt the stramed video. 

[kodi.log](https://github.com/Sandmann79/xbmc/files/4842281/kodi.log)
[kodi.log](https://github.com/Sandmann79/xbmc/files/4842292/kodi.log)

**Comment by Varstahl** [comment]
It's trying to playback with InputStream.Adaptive. Have you tried setting the playback method to [Android](https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon-test#android)?

**Comment by dfdario** [comment]
Yes I did but since the device is not Widevine certified play failed.
Before trying I restarted from scratch: Android restored to factory and installed Kodi, no chance.
In previous versions upon the first play it asked me to install Widevine (from Crhome) but now it doesn't I guess because it sees Widevine is installed or the it is an Android OS, but not every Android OS can play straight forward, crappy Chinese boxes like mine usually don't.

**Comment by dfdario** [comment]
I have updated Android Widevine is V1 L3 so it can't play DRM streams. That's way I needed Kodi to play since.

**Comment by Varstahl** [comment]
I'm not sure, it might be a change with InputStream.Helper. We don't deal with the DRM ourselves, so I'm unsure if the Widevine download is an available strategy, still. There should be a `/storage/.kodi/` folder, you might try to delete the `cdm` folder from there, but I'm unsure that'll have any effect.

**Comment by dfdario** [comment]
I completely reflashed the device then I installed Kodi and addons. No chance to make it working because it needs widevine being installed as it was in the past releases.
I am writing about this issue because other might need to play Amazon Primevide on such devices. As I sed I am keeping it alive just for testing purposes.

**Comment by marcomow** [comment]
Same here. Actually I see in the player that something is playing, but there's no audio or video, just the progress bar proceeding - the total lenght for the video is correct

**Comment by answer35** [comment]
I got the same issue. Tried all different parameters for InputStream.Adaptive but nothing works.
If someone find a fix for that it would be perfect.

**Comment by dfdario** [comment]
I solved everything by installing Corelec on SD and play with it. Now it works like a charm.
