### ISSUE TITLE
colors not properly decoded on leia 18

### ISSUE THREAD

**Issue by orkanaye** [Sandmann79/xbmc#484]
Some movies on prime have problems with colors. washed out and the blue/green is offset to one side. For example movie "7500"

It looks similar to old blue/red 3d from times past (the stream is not set to 3d and many other movies work ok with same settings)

where should I check for the logs?

**Comment by Varstahl** [comment]
https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi

But don't send it to us, that's for sure. There are some of these problems on some chinese boxes and Kodi/InputStream Adaptive, we can't really help you there. I don't remember where I found the thread and if it ever got fixed, but I'm sure it was 100% between Kodi, ISA and Widevine.

**Comment by orkanaye** [comment]
ok. thanks. I'll investigate further
