### ISSUE TITLE
Missing episode thumbnails when preferring them over posters

### ISSUE THREAD

**Issue by mbroemme** [Sandmann79/xbmc#485]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [0.8.6]

**Prime Video Account (select one)**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [Intel NUC]
- OS Version: [Arch Linux]
- Kodi Version [e.g. 18.6]

**Describe the bug**
A while ago you fixed the bug https://github.com/Sandmann79/xbmc/issues/453 reported by me. So far the new option to choose between episode or poster image works great. However there is another small glitch now. If enabling episode view, some seasons have episode images and some not, example:

Homeland (S04E01): http://ecx.images-amazon.com/images/I/41G-Y7sIShL.jpg
Homeland (S05E01): http://g-ecx.images-amazon.com/images/G/01/x-site/icons/no-img-sm.jpg

Of course this doesn't look good. :) There are 2 options to fix this problem:

1. Use the poster as fallback when no episode thumbnail is available.
2. Use the option which allows to download missing fanart for series and if it set to download missing ones, extend it to do it for episode thumbs too.

To be honest, option 1 looks bad from user experience point of view. If you want the episode thumbnails, the fallback to poster is not expected, option 2 makes more sense as it will fallback to episode download from configured source.

**Comment by Sandmann79** [comment]
Stale. Closing
