### ISSUE TITLE
No Configuraton Menu in Kodi 18 Alpha

### ISSUE THREAD

**Issue by aaronc1976** [Sandmann79/xbmc#49]
I installed the add-on and set it up to e able to play through the native kodi player, but when I start the add-on it goes to a blank configuration screen so I am not able to set anything up.

The only thing visible is:
Amazon VOD
Soften 0% ?0?

Then it has cancel and default buttons but nothing happens if you click them.

I have tried uninstalling and reinstaling the add-on without success.  Any help would be greatly appreciated.

**Comment by Sandmann79** [comment]
Which OS you're using?
Did you tried it with default skin?
Can you provide a debug log?

**Comment by aaronc1976** [comment]
Thank you for your reply.  I would have not thought the skin was the
problem.  I am on Around Nox.  I flipped to Estuary and was able to
completely configure everything and flip the skin back to Around Nox.
Everything is working perfectly now.

Thanks again

**Comment by Sandmann79** [comment]
This Aeon Nox skin should be compatible with kodi 18:
https://forum.kodi.tv/showthread.php?tid=210069
Maybe this works for you.
