### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by nogardeht** [Sandmann79/xbmc#490]
Addon used

 Amazon VOD (plugin.video.amazon-test)
 Addon Version [latest from leia]

Prime Video Account (select one) primevideo.com

System Setup (please provide the following information):
Hardware: [ODroid n2]
OS Version: [coreelec]
Kodi Version [18.7.1]
Describe the bug

On latest coreelec with kodi 18.7.1 I cannot install the add-on as xbmc.python 3.0.0 dependency is missing

**Comment by nogardeht** [comment]
Just in case, I will add, I tried both repos, matrix and Leia with the same results

**Comment by Varstahl** [comment]
Ok, hold up. You have made a mistake somewhere. On 18.7 you need to install [this repo here](https://github.com/Sandmann79/xbmc/releases/download/Repository/repository.sandmann79.plugins-1.0.3-leia.zip). So delete the repo, install this new repo, then if needed go manually in the dependencies list and if you find a `*-matrix*` dependency listed as installed, just uninstall it. You might have made a dependency mess, it's going to take you a bit to clean it up, not too difficult though.

**Comment by nogardeht** [comment]
Hey no worries, this is a testing I'm just doing on ODroid n2, I will do something then, I will just show a completely new image on the emmc and start again, I may have mess with this one on the anxiety of testing everything before going to sleep.
Will comment back on Wednesday that I will get back to my office where I do have the n2 for testing
