### ISSUE TITLE
Support for Profile Switching (Who's Watching?) Amazon VOD

### ISSUE THREAD

**Issue by 27hectormanuel** [Sandmann79/xbmc#494]
Recently, Amazon added support for _["Who's Watching](https://www.amazon.com/gp/video/profiles)?"_ Hopefully, you could find a way to support it.
![image](https://user-images.githubusercontent.com/22853711/89726343-afe64d00-d9e7-11ea-9a78-449cca143192.png)
 
link of reference: [here](https://www.amazon.com/gp/help/customer/display.html?nodeId=GEM24ZP4GX39MKU4)
@Varstahl, @Sandmann79

**Comment by Sandmann79** [comment]
@Varstahl already announced this feature at #427. 
Now it seems to be avaible for more countries and we can start to implement it.
Thanks for reporting.
Closing this.

**Comment by Varstahl** [comment]
Yes, in Italy has dropped a couple weeks ago, it's already planned. I've just became dad, though, it's going to take at least all the time I need until I can have a proper sleep.
