### ISSUE TITLE
Certain pages like Watch Next TV and Movies cannot be fetched.

### ISSUE THREAD

**Issue by gary9872** [Sandmann79/xbmc#496]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 
0.8.7

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: X86 64Bit, ARM32bit
- OS version: Arch Linux (rolling) CoreElec 9.2.3, 9.2.4
- Kodi version number: 18.7

**Upload Logs**

https://pastebin.com/PgbZHzew

**Describe the bug**

Plugin CANNOT fetch certain pages such as Watch Next TV and Movies, while other pages seem to load correctly. It seems to have started with 0.8.7 update?

**Comment by Varstahl** [comment]
I've noticed this last night, only a few categories seem not to work, I'm unsure why, got to investigate.

**Comment by gary9872** [comment]
From what I can tell, this commit breaks it. 

https://github.com/Sandmann79/xbmc/commit/fb65fe8c4eeeb8250ef3b1220879f4c69cd28ea8

**Comment by gary9872** [comment]
Might it be as easy catching the NoneType iteration? It works for me here. 

https://github.com/gary9872/xbmc/commit/914509d2d7e617015e41642a54231d0746175309

**Comment by Varstahl** [comment]
Seems like that was it, orphaned carousels have no URL to go along with them, they only use the cached data. Thanks for the patch.

**Comment by gary9872** [comment]
Thanks for all your work :)
