### ISSUE TITLE
Can only get Android playback method to work

### ISSUE THREAD

**Issue by EvilCaptKirk** [Sandmann79/xbmc#50]
Tried stream input, browser and script methods to no avail. Stream input plays, but the image is garbled and mostly blank. The other methods do nothing. Android method successfully loads and plays the stream in the Android Amazon video app, but at that point I might as well just use that app! Prefer to use yours with input stream. Any suggestions on how to get that working?

**Comment by Sandmann79** [comment]
You have to use an Kodi 18 Alpha build to get Inputstream properly working. 
On Android there only Android App and Inputstream available.

**Comment by mvimercati** [comment]
What are the effects using kodi 17 and input stream method? Video decoding errors? Actually I can get the audio, but the video is not properly decoded.

**Comment by Sandmann79** [comment]
With Kodi 17 only a few videos are playable through Inputstream, because of changes at Amazon's DRM encryption.
This has been fixed with Kodi 18. 
If you want to stay at v17, you should enable the DRM check option and choose Android as fallback in add-on settings.

**Comment by EvilCaptKirk** [comment]
Thanks @Sandmann79.
