### ISSUE TITLE
Movie and TV sections displays always the same content

### ISSUE THREAD

**Issue by Sandmann79** [Sandmann79/xbmc#502]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: All
- OS version: All
- Kodi version number: 0.8.8

**Upload Logs**

There is no error in the logs. 

**Describe the bug**

The `/cdp/catalog/Browse` call is broken and displays always the same content, no matter which parameters are set. 
This affects the Movie and TV show sections including submenus.
First test with different DeviceTypeIDs or other parameters were unsuccessful.

Amazon have cut this call more and more in the last few months, so it's time to switch to an different api as content provider. But it needs some time to implement.

In the meantime and as workaround you can add content to your Watchlist and access them through the Addon.

**Comment by GHamblin** [comment]
Good. I'm not actually losing my mind. 🤪

**Comment by Sandmann79** [comment]
Currently it works again...
