### ISSUE TITLE
Amazon VOD not playing selected video.

### ISSUE THREAD

**Issue by betatester3016** [Sandmann79/xbmc#504]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:  TaNiX TX5 Deluxe Edition
> Amlogic S905X3
Quad-Core Cortex-A55 2Ghz 64bits
RAM: 4GB
Storage: 64GB
Dual 2.4+5.8Ghz MIMO - a/b/g/n/ac
Bluetooth 5.0 
Gigabit LAN 1000
USB3.0
- OS version: CoreELEC-ng 9.2.4.2 stable 
- Kodi version number: 18.8.0 Git 02c2dd21befe52facee9bebdd37b0d159e416369

**Upload Logs**

https://pastebin.com/TVecje8U

**Describe the bug**

The add-on installs fine from the repository. I am able to log into Amazon Prime and see "My Stuff" being populated with my selections.

When trying to play any video, immediately an error message pops up stating: "One or more items failed to play, check the log for more information about this message.

I previously installed the add-on on a TaNiX TX3 Max, where it works as intended.

**Comment by Varstahl** [comment]
Given the logs you provided it's a problem between InputStream Helper, Widevine CDM and the platform you're on. If possible, try to install LibreElec instead of OpenElec/CoreElec, it usually doesn't have these issues.

**Comment by betatester3016** [comment]
Thank you.

I confirm it was a problem with InputStream no longer being "linked" with Widevine. Uninstalling InputStream and Amazon VOD, then manually removing the Widevine files by use of file explorer, and reinstalling Amazon VOD from scratch, solved the issue.
