### ISSUE TITLE
OTP Causing Log In to Fail

### ISSUE THREAD

**Issue by ag721git** [Sandmann79/xbmc#505]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.03

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: rpi4 armv71
- OS version: LibreElec 9.2.5
- Kodi version number: 18.8 Leia

**Upload Logs**

Kodi.log - https://pastebin.com/Fq88WA1n
avod-login-mfa.log - https://pastebin.com/yNGiprva - Just a copy of the html page for browser implementation of OTP attempt
avod-login.log - Same thing as above - https://pastebin.com/YVYaWgLG

**Describe the bug**
Log-in attempts work despite the terrible captcha but now redirect to OTP login page which you can't open in the application or on Kodi so no way to continue authentication. 
Was this resolved somewhere else? If so please direct towards link. 
I saw plenty of discussion on this but no resolution in the forums both here and with Kodi

**Comment by Varstahl** [comment]
This is not a proper reply as I'm telling things as I remember them and could be wrong, but if it's what I think it is we can't fix that at the moment because it requires JavaScript parsing, which is not available in Python's MechanicalSoup.

**Comment by Sandmann79** [comment]
There is no clue of an OTP request in your logs. 
Only a password wrong and a captcha request page are shown there.

I don't know how many different OTP pages Amazon uses, but one of them is supported since this commit: 4e5318afe9f4978b7fc01a9526730b08ad8c1517.
Please try it and report back or if it doesn't work post proper logs containing the OTP page.

**Comment by dreadpierate** [comment]
I am having the same issue.   After the add-on fails I get a a message on my phone "Amazon security alert. Tap link to respond: ".  With a unique link everytime.   I will try to upload some logs in the morning.   I'm guessing that you need more time to verify the login after you do the captcha.

**Comment by Sandmann79** [comment]
@dreadpierate Can you check the attached version. These are at commit 88dbc10a4c86eaa37933989ac7749a5fc19905a0 and supporting transaction approval.
[Kodi 18 - plugin.video.amazon-test-0.8.9_beta.zip](https://github.com/Sandmann79/xbmc/files/5265600/plugin.video.amazon-test-0.8.9_beta.zip)
[Kodi 19 - plugin.video.amazon-test-0.8.9_beta+matrix.1.zip](https://github.com/Sandmann79/xbmc/files/5265599/plugin.video.amazon-test-0.8.9_beta%2Bmatrix.1.zip)

**Comment by dreadpierate** [comment]
@Sandmann79  that has fixed it.

**Comment by Sandmann79** [comment]
No answer since months from issue creator. Closing this.
