### ISSUE TITLE
Cant install repository

### ISSUE THREAD

**Issue by fdl333** [Sandmann79/xbmc#506]
**Addon used**
- [ X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: RaspberryPi 4
- OS version: libreelec 9.2.5
- Kodi version number: 18.8

**Upload Logs**

https://pastebin.pl/view/36501cf0

**Describe the bug**

Cannot install xbmc-master.zip

**Comment by Varstahl** [comment]
That's not the repository, you can find the repositories [here at this link](https://github.com/Sandmann79/xbmc/releases/tag/Repository). [This ZIP](https://github.com/Sandmann79/xbmc/releases/download/Repository/repository.sandmann79.plugins-1.0.3-leia.zip) is for Leia (18.x), and [this ZIP](https://github.com/Sandmann79/xbmc/releases/download/Repository/repository.sandmann79-py3.plugins-1.0.0-matrix.zip) is for Matrix (19.x).

**Comment by fdl333** [comment]
Grazie Bruno, domani riprovo!

Francesco Facco de Lagarda
