### ISSUE TITLE
Video Export is changing my local directory pointers

### ISSUE THREAD

**Issue by lhassell** [Sandmann79/xbmc#509]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.8.8

**Account type**
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: ShieldTV
- OS version: Latest
- Kodi version number: 18.8

**Upload Logs**

**Describe the bug**

Not sure my issue would show up in a log file. Whenever I export shows or movies to my library, it exports to "Amazon Movies" and "Amazon TV" as normal, but for some reason it *also* moves the link to my *regular* "Movies" and "TV" libraries and points them at the relevant "Amazon..." directory. Every time I export, I have to go in and re-enter the link to my local Movie and TV files.

Any idea what is happening here?

**Comment by Sandmann79** [comment]
Checked this and can confirm, if there is a `Movie` or `TV` library it gets overwritten at export. 
There should be a source path changed message within the kodi.log.

**Comment by lhassell** [comment]
Thanks!

**Comment by Sandmann79** [comment]
Closed via 77d5992f244083c9d9fe5cc4d4a680b6beb8951c
