### ISSUE TITLE
HTTP ERROR 400 on play videos

### ISSUE THREAD

**Issue by mauriciogoncalves** [Sandmann79/xbmc#510]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: raspberry 3 and raspberry 4  (also tried clean install on both)
- OS version: Raspbian GNU/Linux 10 (buster) kernel 5.4.51
- Kodi version number: Kodi 18.4 - Leia

**Upload Logs**

https://pastebin.com/GBYqsYif

**Describe the bug**

HTTP ERROR on play video 

The Authentication works, navigation works, "my list" works. BUT when i try to Play any video i got the error: HTTP ERROR
We can see error 400 in logs. can you help me please?

**Comment by Varstahl** [comment]
Provide the full log.

**Comment by mauriciogoncalves** [comment]
https://pastebin.com/Czp80cFD

**Comment by Varstahl** [comment]
Is there a mistake on your issue or in your configuration? What country are you in at the moment, and what country's the amazon account from?

**Comment by mauriciogoncalves** [comment]
I think you right. I am sorry to take your time 
i think i got an  { "error": "wrong_region", "customer_home_region": "NA" } but i am not sure because i try a GET not a POST

my account was created in Brazil
Right now i am at Malta
It works fine on any web browser on windows and android devices it works fine
even when I was at Spain or Portugal was working fine on windows and android devices
but never was able to play on pi. (just tested pi on Malta at home). authentication and list tiles go fine 
just play not works 

do you have any suggestions?

**Comment by Varstahl** [comment]
It's strange because Brazil should be PrimeVideo just like Malta. So, if you go on a browser say, in incognito, go to primevideo.com, log in, then you can watch everything no problem? Or do you get redirected to amazon.com?

I'm not sure what the play is here, but you should at least be able to clear credentials, change region, and try again until it works. Either with region USA or ROW NA. If it doesn't work we need to investigate deeper. Had similar problems in the past but never this specific.

**Comment by mauriciogoncalves** [comment]
When I am on web browser URL is https://www.primevideo.com/region/na
It works on any browser. Tested chrome firefox edge on 2 different windows laptops
It works on prime video Android app. Using on two mobile phones.

I am not used to phyton but I work as a programmer if you want to give me instructions or directions I will be glad in to follow.
I really want amazon prime to work on my raspberry. 

Today I installed Kodi in my windows machine and I have the same error 400. 
Everything is the same, authentication and navigation works fine but play video not works with an HTTP error. 
This is the log from the moment when I click to play a video.
https://pastebin.com/cDUvqMrF
https://pastebin.com/0pUCbthH

**Comment by mauriciogoncalves** [comment]
Maybe this will help. I dont know what is a marketplaceID and how your addon decide with domain should be called

but that bad request works if i replace **domain** and **marketplaceID** 


### this URL request NOT works 
(from my kodi.log URL decoded)    response={ "error": "wrong_region", "customer_home_region": "NA" } 

https://**atv-ps-eu.primevideo.com**/cdp/catalog/GetPlaybackResources?asin=amzn1.dv.gti.06af4e17-214d-6d48-8daf-0ab3dcd02b6f&
deviceTypeID=AOAGZA014O5RE&
firmware=1&
deviceID=e9a1ebff37c96b40b3b05639a7de6e61564b8b34adcb482bbce259da&
marketplaceID=**A3K6Y4MI8GDYMT**&
format=json&
version=1&
gascEnabled=true&
subtitleFormat=TTMLv2&
resourceUsage=ImmediateConsumption&
consumptionType=Streaming&
deviceDrmOverride=CENC&
deviceStreamingTechnologyOverride=DASH&
deviceProtocolOverride=Https&
deviceBitrateAdaptationsOverride=CVBR%2CCBR&
audioTrackId=all&
languageFeature=MLFv2&
videoMaterialType=Feature&
desiredResources=PlaybackUrls,SubtitleUrls,ForcedNarratives,TransitionTimecodes&
supportedDRMKeyScheme=DUAL_KEY


### this URL request **works**   response = https://pastebin.com/T6rG0twR

https://**atv-ps.amazon.com**/cdp/catalog/GetPlaybackResources?
asin=amzn1.dv.gti.06af4e17-214d-6d48-8daf-0ab3dcd02b6f&
deviceTypeID=AOAGZA014O5RE&
firmware=1&
deviceID=e9a1ebff37c96b40b3b05639a7de6e61564b8b34adcb482bbce259da&
marketplaceID=**ATVPDKIKX0DER**&
format=json&
version=1&
gascEnabled=true&
subtitleFormat=TTMLv2&
resourceUsage=ImmediateConsumption&
consumptionType=Streaming&
deviceDrmOverride=CENC&
deviceStreamingTechnologyOverride=DASH&
deviceProtocolOverride=Https&
deviceBitrateAdaptationsOverride=CVBR%2CCBR&
audioTrackId=all&
languageFeature=MLFv2&
videoMaterialType=Feature&
desiredResources=PlaybackUrls,SubtitleUrls,ForcedNarratives,TransitionTimecodes&
supportedDRMKeyScheme=DUAL_KEY


is there any python file that I can do some string replace into domain and/ok marketplaceID 
if is a specific request or something I don't know

is it helps?

**Comment by mauriciogoncalves** [comment]
I open a new anonymous browser 

I open https://**www.primevideo.com**/ I **click sign in** and got redirected to and log in with my amazon credentials in URL:
https://www.amazon.com/ap/signin?accountStatusPolicy=P1&clientContext=261-2144294-1831365&language=pt_BR&openid.assoc_handle=amzn_prime_video_desktop_us&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.primevideo.com%2Fregion%2Fna%2Fauth%2Freturn%2Fref%3Dav_auth_ap%3F_encoding%3DUTF8%26location%3D%252Fregion%252Fna%252Fref%253Ddv_auth_ret

### open this URL gives error  { "error": "wrong_region", "customer_home_region": "EU" }
https://atv-ps.amazon.com/cdp/catalog/GetPlaybackResources?asin=amzn1.dv.gti.06af4e17-214d-6d48-8daf-0ab3dcd02b6f&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=e9a1ebff37c96b40b3b05639a7de6e61564b8b34adcb482bbce259da&marketplaceID=ATVPDKIKX0DER&format=json&version=1&gascEnabled=true&operatingSystemName=Windows&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProtocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&videoMaterialType=Feature&desiredResources=PlaybackUrls,SubtitleUrls,ForcedNarratives&supportedDRMKeyScheme=DUAL_KEY



**BUT** 
I open https://**www.amazon.com**/ I **click sign in** and got redirected to and log in with my amazon credentials  in URL:
https://www.amazon.com/-/pt/ap/signin?openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3Fref_%3Dnav_signin&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=usflex&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&

### open this URL gives HUGE Json
https://atv-ps.amazon.com/cdp/catalog/GetPlaybackResources?asin=amzn1.dv.gti.06af4e17-214d-6d48-8daf-0ab3dcd02b6f&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=e9a1ebff37c96b40b3b05639a7de6e61564b8b34adcb482bbce259da&marketplaceID=ATVPDKIKX0DER&format=json&version=1&gascEnabled=true&operatingSystemName=Windows&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProtocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&videoMaterialType=Feature&desiredResources=PlaybackUrls,SubtitleUrls,ForcedNarratives&supportedDRMKeyScheme=DUAL_KEY

is it helps ?

**Comment by mauriciogoncalves** [comment]
MAn ...

it works.

i dont know how. WHat i did

Change my amazon account for authentication in two steps with OTP
Change addown settings for region USA
Prefered Host cloud Front

Make login on your add 
login... password... otp 

for the first time i see images in my initial lists and navigation has changed. 

Most of the I play video it say "not available in your country"

Some videos play IT WORKS  but no sound   ='(

i will keep trying...

**Comment by mauriciogoncalves** [comment]
MAN 
### IT WORKS!!!!!

**Comment by Varstahl** [comment]
That was a rollercoaster, lmao. Glad you got it working.

We don't really pick servers, when you log in Amazon tells you and us "ok, point these queries at this host and these other queries at this other host". In some cases we can control how it behaves, but your case never stumbled on us as is. Actually maybe it did, but it behaved differently.

Can you tell me if in the addon connection settings you specified anything for the region?

**Comment by mauriciogoncalves** [comment]
I did:

Change amazon account settings on amazon website to authentication in two steps (with OTP)

Addon settings 

Genereal -> Preferred host: Clouldfront
Connection -> Region: USA
Connection -> remove credentia and cookie
Connection -> login

Logged in, navigated and played video with no sound. 
Then:

Kodi settings 
Audio -> passthrought: true

and 
it works now. 
That is some lag some times on videos. 
In my other Pi I will try different host and region


Another topic i am confused about... that is no profile selection on addon, right ? in web site I have more than one profile in the same prime video account (actually my amazon account), so maybe that why my watchlist from website is completely different than my watchlist on Kodi. but maybe this will be a topic for another thread.

Thanks for your attention and all your great job. 
Because of you and others like you, live is a little bit better for many of us.

**Comment by Varstahl** [comment]
In PrimeVideo there are profiles, and I've added them in the current beta, will be public soon, I'm not sure for Amazon.TLD support though, I'm not the one managing that portion of the code.

Closing this as solved, happy watching :)

**Comment by Varstahl** [comment]
Scratch that, profiles support has been added literally 12 hours ago for amazon.com with 5e98759f00fd28b08e3c112653331ea00ea3f28d. So yeah, it's going to be there in the next update.
