### ISSUE TITLE
Error when starting  v1.2.4+matrix.1 on 19.0.alpha 1 20201003

### ISSUE THREAD

**Issue by rikardfries** [Sandmann79/xbmc#511]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- [X] Browser Launcher (plugin.program.browser.launcher)

- Addon version: v1.2.4+matrix.1

**Account type**
- [ ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: H170M-DS3H-CF
System Manufacturer	Gigabyte Technology Co., Ltd.
System Model	H170M-DS3H
Processor	Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz, 3401 Mhz, 4 Core(s), 8 Logical Processor(s)
BaseBoard Manufacturer	Gigabyte Technology Co., Ltd.
BaseBoard Product	H170M-DS3H-CF
Total Physical Memory	63,9 GB
- OS version:Windows 10 Feature 2004  Version	10.0.19041 Build 19041
- Kodi version number:19.0.alpha 1 20201003

**Upload Logs**

Log files available at  https://pastebin.com/RniwHYX8
Trace log: https://pastebin.com/e09hRRJw

**Describe the bug**

When I start the Browser Launcher.
I get this error.

**Comment by rikardfries** [comment]
Works Very well. 
Perhaps the name could contain the word matrix and the python version be 3.0.0.
Thank you very much for this.! Appreciated.
/Rikard ¤ kind regards

**Comment by Varstahl** [comment]
We have automatic generation, didn't push the release yet. Glad it works properly, thanks for the feedback.
