### ISSUE TITLE
Wrong colors on "Avatar the last airbender"

### ISSUE THREAD

**Issue by JuleBert** [Sandmann79/xbmc#512]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.8.8

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 4B 4GB
- OS version: Raspbian GNU/Linux 10 (buster); Linux raspi 5.4.51 v71
- Kodi version number: v18.7 Leia

**Upload Logs**

**Describe the bug**

Hi,

first,
 thanks a lot for your awesome work.
Now to my problem I installed Kodi on Raspberry Pi OS on a Pi 3 and Pi 4. With both I can watch most shows perfectly. But when I try to watch "Avatar the last Airbende" the colors a weirdly wrong. Please see the attached picture. It happens in all three seasons. But not in the "Legend of Korra".

bests 

Julian
Wrong colors on Kodi addon
![IMG_20201008_113630](https://user-images.githubusercontent.com/26938997/95444570-3c68a980-095e-11eb-8d69-d47b7706869b.jpg)

Right colors on Win 10 Firefox:
![IMG_20201008_115751__01](https://user-images.githubusercontent.com/26938997/95444601-468aa800-095e-11eb-8767-154858ed8241.jpg)

**Comment by Varstahl** [comment]
Long story short: it's a distro problem, try LibreElec.

Slightly longer version: the issues cropped up a couple times over the years, and it was a combination of hardware/distro/Kodi/Widevine problems, but I don't remember where the thread was nor the discussion. Use LibreElec and the problem should go away by itself, as it's generally properly configured and updated.
