### ISSUE TITLE
ERROR: CAddonInstallJob[plugin.video.amazon-test]: The dependency on xbmc.python version 3.0.0 could not be satisfied.

### ISSUE THREAD

**Issue by clement-analogue** [Sandmann79/xbmc#513]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.8.9

**Account type**
- [ ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: PINE64 ROCKPro64
- OS version: LibreELEC 9.2.4 (Leila)
- Kodi version number: Kodi 18.8

**Upload Logs**

[kodi.log](https://github.com/Sandmann79/xbmc/files/5373326/kodi.log)

**Describe the bug**

After adding the repo (repository.sandmann79.plugins-1.0.3-leia.zip), attempt to install Amazon VOD fails due to unsatisfied dependency.
The relevant line in the log is:
ERROR: CAddonInstallJob[plugin.video.amazon-test]: The dependency on xbmc.python version 3.0.0 could not be satisfied.

**Comment by Varstahl** [comment]
```
NOTICE: ADDON: repository.sandmann79-py3.plugins v1.0.0 installed
NOTICE: ADDON: repository.sandmann79.plugins v1.0.3 installed
```

You've mistakenly added both, and Kodi is messing things up because the Matrix versions came up first. Remove the Kodi 19 repository (the -py3 one) and it should fix itself.

**Comment by clement-analogue** [comment]
Great! I though disabling the repo was enough. I uninstall the wrong repo and install went smoothly. Thank you!
