### ISSUE TITLE
Change language for TLDs

### ISSUE THREAD

**Issue by Nadonate** [Sandmann79/xbmc#514]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.8.9

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Intel NUC
- OS version: Ubuntu 20.04
- Kodi version number: 18.8

**Upload Logs**

[log](https://pastebin.com/fvmLzBfT)

**Describe the bug**
 Show descriptions are spanish, english is desired. Unable to change the text language (Language > Change text language). The addon throws an error, log included.

```
2020-10-14 08:19:11.011 T:139786614466304   DEBUG: [Amazon VOD] Requested /pv/languageselect/
2020-10-14 08:19:11.018 T:139786614466304   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'pv'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/kodi/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 67, in EntryPoint
                                                elif 'languageselect' == verb: g.pv.LanguageSelect()
                                              File "/home/kodi/.kodi/addons/plugin.video.amazon-test/resources/lib/common.py", line 50, in __getattr__
                                                def __getattr__(self, name): return self._globals[name]
                                            KeyError: 'pv'
                                            -->End of Python script error report<--
2020-10-14 08:19:11.018 T:139786614466304   DEBUG: onExecutionDone(11, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py)
2020-10-14 08:19:11.021 T:139788979096256   DEBUG: ------ Window Init (DialogNotification.xml) ------
```

**Comment by Varstahl** [comment]
I'm not sure how you triggered this error, and in the log you provided you never ran the addon itself, so I'm not sure how to troubleshoot this.

Running out of conjectures, have you logged in before changing the option? If you have logged in can you open the plugin, then change the language?

**Comment by Nadonate** [comment]
New log attached. This time I ran the addon & played video before trying to change the language text

[LOG](https://pastebin.com/LpnawnqU)
[Picture of the issue in kodi menu](https://i.imgur.com/T26Uylj.png)

Steps to recreate the issue:

1. Run addon
2. Enter addon settings
3. Navigate to 'Language' option
4. Select 'Change Text Language'

At this point, kodi throws an error: 'Amazon VOD error, check log for more details

I am logged in, and can play content fine. My region is set to **USA** in the addon. My prefered language in the video player settings in kodi is set to 'English USA'

To troubleshoot, I have logged out (credentials and cookie) and tried to change the language and region, which has resulted in the same error.

I will try the addon on my windows machine to see if I get the same error, later today..

**Comment by Varstahl** [comment]
ok, no, wait, there is no PrimeVideo.com in the USA, that's a PrimeVideo only option (every country except US, UK, DE & JP). This addon supports USA, just not that option. I'm not aware of this type of issues for USA though.

@Sandmann79 have there been problems with TLDs? Is it a cookie problem like it was for PrimeVideo, fixable by changing the `lc-main-av` locale (or TLD equivalent)?

**Comment by Schaka** [comment]
I'm not in the US but getting the exact same error when using that menu option. Failing miserably to change the audio language to English, despite that being my language I set in Kodi.

**Comment by Sandmann79** [comment]
Language changing with the old ATV-API isn't possible for TLD's. 
With the [upcoming](https://github.com/Sandmann79/xbmc/pull/542) integration of the Web-API (same as for PV) it's possible to switch the language.
