### ISSUE TITLE
Audio, subtitle, and language issues for TLDs

### ISSUE THREAD

**Issue by cjyar** [Sandmann79/xbmc#515]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.8.9

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: OSMC Vero 4K+
- OS version: 2020.06-1
- Kodi version number: 18.7

**Upload Logs**

[kodi.log](https://gist.github.com/cjyar/27c7f38bef12eaa45d6362ab2ed85449)

**Describe the bug**

Several problems:
- One show, MLP, has problems with audio and subtitles:
    - Main channel audio is missing. The other 4.1 channels seem to work fine.
    - Subtitles are enabled (English).
- A different show, The Expanse, has problems with language settings:
    - Main audio channel is not working, as above.
    - Episode titles and descriptions are in Spanish.
    - Subtitles are in Hebrew, I think.

Full 5.1 audio works for other Kodi add-ons such as YouTube.

**Comment by Varstahl** [comment]
Might be related to #514 for the language portion, the rest might be OSMC related.

**Comment by peter-clemenko** [comment]
I'm having similar problems, IE The Boys is in spanish

**Comment by Sandmann79** [comment]
There is an issue with US accounts at the moment. From what I see, the default language is set to Spanish by default, the reason for this behaviour is unclear. Maybe its related to the recently introduced language options.
As well there are much more languages avaible at playback, like for PrimeVideo users. Enabling MPD alteration at Settings -> General should filter the unneeded languages.

@Varstahl on TLDs we don't need a cookie to display the content and it makes no difference, if it used or not.

**Comment by Varstahl** [comment]
The MPD alteration fixes a few things like changing `es-419` into something parsable by Kodi, `Spanish Latinoamerica`, to differentiate it from regular `Spanish`, but it doesn't filter out languages unless you changed it and I didn't notice.

Question @cjyar @peter-clemenko: what language did you select in "Kodi settings > Player > Language" for audio and subtitles?

**Comment by cjyar** [comment]
Mine was set to:

- `Preferred audio language`: `Media default`
- `Preferred subtitle language`: `Media language`

I just changed both of them to en-US, and it fixed the subtitles but not the series/episode titles.

MPD alteration was already enabled. I tried disabling it, but that didn't affect anything that I saw.

When I enabled `Language` -> `Audio descriptions`, the main channel audio started working. For MLP, that comes out as English now; but for The Expanse it comes out in Japanese (with English subtitles).

**Comment by Varstahl** [comment]
More and more users are reporting the same problems, so to you guys over yonder in the US I need you to find a test. On amazonvideo.com or wherever you can watch streams from Amazon, check cookies for the presence of a `en_US` string, similar to this:

![image](https://user-images.githubusercontent.com/284077/97537573-4b6fd400-19bf-11eb-9036-5c6a62148630.png)

The name might change or it may not be there, doesn't matter. I was told in the US they introduced a language switcher though, so try to select Spanish, and check the cookies again, to see if there's something like `es_ES` or `es_419`.

**Comment by StefanoDeVuono** [comment]
I'm a US user and my `lc-main` (I have no `lc-main-av` cookie) looks like this:

```
lc-main	en_US	.amazon.com	/	1/1/2036, 12:00:01 AM	12 B			
```

That appears to be the only cookie with `en_US` in it

---

When I switch to Spanish, my `lc_main` cookie looks like this:

```
lc-main	es_US	.amazon.com	/	1/1/2036, 12:00:01 AM	12 B			
```

Again, the only cookie with `es_US` in it.

**Comment by Varstahl** [comment]
Ok, then, worth a try. Open accounts.lst, depending on what platform you're using it might be one of the following:
```
%AppData%\Kodi\userdata\addon_data\plugin.video.amazon-test\config\accounts.lst
~/.kodi/userdata/addon_data/plugin.video.amazon-test/config/accounts.lst
/storage/.kodi/userdata/addon_data/plugin.video.amazon-test/config/accounts.lst
```
The file is a JSON containing various info and cookies, find the cookie dictionary and add the `lc-main` as so:
```
[
  {
    […]
    "cookie": {
      "lc-main": "en_US",
      […]
    },
    […]
  }
]
```
If it's responsible of localised content then new items and descriptions should start being in english. Try to scrape something new and see if this works.

**Comment by Sandmann79** [comment]
Sorry for the late answer, but this solution should not work - the cookie isn't used on TLDs to get the content. I tested it already with a cookie and changed the lc_main/sp-cdn, but it's changed nothing, the content is still in Spanish. Tryed also to change the headers and the query of the request, but still no luck with that.

**Comment by knappster1** [comment]
I have the same issue and the same cookie as @StefanoDeVuono .  I've added the json info as indicated by @Varstahl but as @Sandmann79 suspected the titles and descriptions of some things are still in Spanish.  For example "the expanse - season 4" is "the expanse - temporada 4".  At first glance it only seems to be a problem with amazon original content.

**Comment by Varstahl** [comment]
oh, I didn't want to butt in, I know you already told me you had tested this, it's just… strange… I thought that there would maybe be something else influencing it (and there must be). It's hard to debug something when you don't have access to it >_<"

**Comment by bknapp2** [comment]
I've had this behavior for several weeks now and I saw that you were already aware of the issue and didn't want to post a "me too" without anything constructive to add.  If I can provide any information to help, I am happy to do so.  I may not be able to respond immediately at all times, but I will do the best I can.

**Comment by knappster1** [comment]
I've had this behavior for several weeks now and I saw that you were already aware of the issue and didn't want to post a "me too" without anything constructive to add. If I can provide any information to help, I am happy to do so. I may not be able to respond immediately at all times, but I will do the best I can.

**Comment by lars-a** [comment]
> I don't know what else can do. It's strange that this only happen on US, other countries also have this language option on their website.
I have the same issue with an amazon account from Germany. And it seems, that every few days additional entries from my watch list switch to Spanish. e.g. since today season 5 of Bosch is no longer "Bosch - Staffel 5" but "Bosch - Temporada 5" and 2 of the episodes (3 and 9) from this season now have their title also in Spanish whereas the rest of the episode is still shown with the german titles.

**Comment by ldc7675** [comment]
I am in the US and also have the same issue. mostly all titles and descriptions are in Spanish. I have tried everything listed above and have the same results as others. I am even tried using a  Canada proxy, was going to try Germany proxy but that appears to be having an issue now also. One thing I do know is Amazon sees me switching countries as it asks me to validate who's signing in. So much so it forced me to reset my password. Don't know if this tidbit helps. If I can be of assistance please let me know.

**Comment by unmarkedvector** [comment]
**Greetings from the USA!**
Okay, I am also having this issue however, disabling MPD helped me disable the subtitles. I have not been able to look into menu languages. I did look into the cookie issue and i just want to state the obvious, primevideo.com does not exist in the USA (Unless you do some strange ritual with your amazon account). Taking from my rudimentary understanding of this plugin I am guessing that the plugin cannot access the database from the US so it changes itself to Spanish to actually gain access. I don't know though, I'm probably wrong.
