### ISSUE TITLE
Movie in black and white

### ISSUE THREAD

**Issue by Dikakus** [Sandmann79/xbmc#519]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 
0.8.9

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 4 
- OS version: Raspbian Buster
- Kodi version number: 18.8 Leia

**Upload Logs**

**Describe the bug**

I don't know if it is really a bug due the pluging but when I play the "Her" movie on kodi with the plugin of Amazon, it plays in black and white (and some kind or green color in the right border or a green halo sometimes). I can see it in color on my mobile phone or tablet. Curiojusly, it's the only movie with that problem for now.

In any case, thank you very much for the great plugin.

**Comment by aston966** [comment]
Hi,
This issue is due to the resolution difference between stream and screen. To fix this, you can go in settings >> Extension >> my extension >> all >>  Amazon VOD >> Settings >>  InputStream addon Settings. Change Value of "Maximum decoder resolution" to 720p ( in option to avoid to change resolution for each movie) and "Stream selection" to "Show all video stream" ( in case of black and white movie you can change resolution stream during the movie to a standard ratio).

**Comment by Dikakus** [comment]
> Hi,
> This issue is due to the resolution difference between stream and screen. To fix this, you can go in settings >> Extension >> my extension >> all >> Amazon VOD >> Settings >> InputStream addon Settings. Change Value of "Maximum decoder resolution" to 720p ( in option to avoid to change resolution for each movie) and "Stream selection" to "Show all video stream" ( in case of black and white movie you can change resolution stream during the movie to a standard ratio).

Hi @aston966. Thank you for your reply. Unfortunately, changing those parameters in InputStream addon dind't fix the problem. There were a new update of Widevine but it din't solve the problem either. The curious thing is that it happens with 'Her' movie.

**Comment by escoand** [comment]
I've the same problem, also with only one movie: https://www.amazon.de/gp/video/detail/B076ZW3ZYS/ref=atv_dp_share_cu_r
And as @Dikakus stated none of the settings is working.

**Comment by Sandmann79** [comment]
Inputstream related. Not an addon issue. Closing
