### ISSUE TITLE
Library integration

### ISSUE THREAD

**Issue by EvilCaptKirk** [Sandmann79/xbmc#52]
I may be missing it, but the Amazon Prime Video plugin does not seem to support Kodi library integration. It would be cool to be able to add Prime Video movies and TV series to the Kodi Library. Any chance of this feature being added?

**Comment by Sandmann79** [comment]
This feature is already available. Just navigate to your movie or tv show and open the context menu (default key **c**) and choose Export in List.

**Comment by EvilCaptKirk** [comment]
Thanks, I did so and it seems to work - had to add the export path as a video source in Kodi and give it the correct type (TV or Movies) etc. Will I need to manually rescan that path each time I export something from your plugin? Also, what does the 'Update Library' context menu item do?

**Comment by EvilCaptKirk** [comment]
K, so I answered my own question - 'Update Library' forces a rescan of the export folder by Kodi so that the exported items are added to the Kodi library. It would be a bonus if this kind of scan could happen automatically.
