### ISSUE TITLE
Amazon VOD on raspberry pi3b+

### ISSUE THREAD

**Issue by lucajust** [Sandmann79/xbmc#520]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:
- OS version: Libreelec 9.2.6
- Kodi version number: 18.9

**Upload Logs**
 https://pastebin.com/YE9RWw3V

**Describe the bug**
 Hi sandmann79, thanks for your work. I have a raspberry p3b+, but i can't use amazon vod. The playback start, but the image is green. The audio is ok. The widevine was installed correctly. 
There are any solution? Thanks

**Comment by Varstahl** [comment]
There is literally nothing in the log you posted, other than remote key presses. Also, visual artifacts are a problem between Kodi, IS.A and Widevine, not the addon itself, I doubt we can help much with that.

**Comment by Varstahl** [comment]
Also, might be related to this: https://github.com/Sandmann79/xbmc/issues/519#issuecomment-727048342

**Comment by nicotchoum** [comment]
I got the same issue a few days ago, until I realized that I had changed Video setting from MMAL to OMXPlayer...
> select again MMAL instead of OMXPlayer did solve the issue

**Comment by Sandmann79** [comment]
Stale. Closing
