### ISSUE TITLE
Audio tracks not loaded

### ISSUE THREAD

**Issue by Balza84** [Sandmann79/xbmc#522]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: PC
- OS version: Linux (RecalBox)
- Kodi version number: Leia

**Upload Logs**

**Describe the bug**

With specific movies, audio tracks won't be loaded on the VOD plugin. Audio track selection menu remain empty.

My test subject:
Movie: CAST AWAY
Account:  Amazon with Prime (ITA/EU)
On Amazon VOD: no audio tracks are loaded.  Movie is mute and the audio track selection is empty.
On PS3 Primevideo/Android Primevideo: All audio tracks are correctly loaded.

**Comment by Varstahl** [comment]
You provided no logs, so my assumption is a slow connection/linux box. Try to disable the MPD Alteration Proxy from the addon settings, if it works it's a general slowness problem.

**Comment by Balza84** [comment]
Tried without MPD with same result.
I'll share logs asap.

**Comment by Balza84** [comment]
[PVLogs.zip](https://github.com/Sandmann79/xbmc/files/5586098/PVLogs.zip)

**Comment by Varstahl** [comment]
Those are not the logs, those are the cache files. Which might be useful, but a log is useful*er*. [Here in the Wiki](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi) you can find the exact location.

**Comment by Balza84** [comment]
Wops my bad ;)
Here it is.
[kodi.log](https://github.com/Sandmann79/xbmc/files/5586136/kodi.log)

**Comment by Varstahl** [comment]
```
DEBUG: AddOnLog: InputStream Adaptive: Download https://s3-dub-ww.cf.dash.row.aiv-cdn.net/…_video_11.mp4 finished, avg speed: 5351015.00byte/s, current speed: 5351015.00byte/s
DEBUG: [Amazon VOD] [PS] Parsing languages
DEBUG: [Amazon VOD] [PS] Altering <AdaptationSet>s
DEBUG: ----------------------------------------
DEBUG: Exception happened during processing of request from
DEBUG: ('127.0.0.1', 41654)
ERROR: Traceback (most recent call last):
ERROR:   …
ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
ERROR:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
ERROR: error: [Errno 32] Broken pipe
DEBUG: ----------------------------------------
```

This is with MPD Proxy enabled, and this kind of error is usually due to connection timeouts, but in your case lasts less than 80 milliseconds, there's something wrong.

Are you sure that by disabling MPD proxy alteration you still have audio problems?

![image](https://user-images.githubusercontent.com/284077/100134678-db068680-2e88-11eb-95ed-1624e3702972.png)

If so it might be due to a CDN problem…

**Comment by fabpolli** [comment]
Hi, same issue on Raspberry 4 with LibreElec (Kodi Leia) on primvideo.com from Italy without proxy or VPN, but I get no audio track on other film (Bohemian Rapsody) but all works well with other playback (Eg. Criminal Minds serie).
If it can be useful I can upload log

**Comment by BlackEdder** [comment]
I have the same issue with amazon prime and "The grand tour presents... A massive hunt". No proxy involved.

**Comment by sttehh** [comment]
i had a similar problem, disabling Proxy MPD alteration did fix it for me

Raspberry 3b with LibreElec (Kodi Leia) in germany

**Comment by Sandmann79** [comment]
Has been fixed. Closing.
