### ISSUE TITLE
Amazon VOD Error after watching movie

### ISSUE THREAD

**Issue by mfreeman72** [Sandmann79/xbmc#523]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [X] amazon.com (U.S.)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 3B+
- OS version: OSMC November Update
- Kodi version number: 18.9

**Upload Logs**

https://paste.osmc.tv/bujodakaxe

**Describe the bug**

We finished watching a movie, and immediately as the movie stopped itself at the end of the credits, Kodi gave an "Amazon VOD Error" notification, and we were completely kicked out of the addon. After that, I could not get back into any part of the addon that had to do with our account, such as the Movies or TV folders of the Library or the Watchlist. It's still giving the same error after a full system reboot.

**Comment by Sandmann79** [comment]
Did you tried to login at the Addon again? 
It seems that your cookie get's corrupted.

**Comment by mfreeman72** [comment]
Looks like it has resolved itself somehow. I didn't have to log out/in. Weird. Thank you for your time!
