### ISSUE TITLE
Dolby Atmos support

### ISSUE THREAD

**Issue by Varstahl** [Sandmann79/xbmc#526]
Users reported the presence of Dolby Atmos audio tracks on top of the Dolby Digital + we currently have available. Since we're requestin DTS streams, there might be a different flag to support Atmos. We'll have to look into that.

**Comment by Sandmann79** [comment]
I think these won't be easy, because we're requesting only stereo tracks. The devicetypeid used for this request is for html5 web browser and they are limited to stereo audio. 
Only with a simple modification of the mpd url we're getting DD+ 5.1 tracks. I don't know, if Atmos is present on these tracks.

Using other devicetypeids needs another type of cookie / login process.

**Comment by deaduu** [comment]
> I think these won't be easy, because we're requesting only stereo tracks. The devicetypeid used for this request is for html5 web browser and they are limited to stereo audio.
> Only with a simple modification of the mpd url we're getting DD+ 5.1 tracks. I don't know, if Atmos is present on these tracks.
> 
> Using other devicetypeids needs another type of cookie / login process.

Is there any way we can modify browser mpd xml so we can get 5.1 track on browser too?

**Comment by ThreeDeeJay** [comment]
> > I think these won't be easy, because we're requesting only stereo tracks. The devicetypeid used for this request is for html5 web browser and they are limited to stereo audio.
> > Only with a simple modification of the mpd url we're getting DD+ 5.1 tracks. I don't know, if Atmos is present on these tracks.
> > Using other devicetypeids needs another type of cookie / login process.
> 
> Is there any way we can modify browser mpd xml so we can get 5.1 track on browser too?

I'm also curious about this. any luck?

**Comment by jsilverYVR** [comment]
Atmos support is the feature that actually prompted me to install Kodi on my Nvidia Shield Pro to begin with.  I recently put in a new Atmos soundbar but I'm using it with an older 1080p plasma TV.  The native Disney+ and Prime Video apps will only deliver Atmos to a 4K TV.  I'd read in other forums that users were able to workaround this limitation on some platforms with Kodi Add-Ons so I've installed the Amazon VOD and the Disney+ add-ons.  I'm able to get Disney+ to work but it appears that the add-on for Prime does not yet have that capability.

I'm attaching screenshots of the relevant settings in case you find that helpful in finding a solution to this issue.

![Kodi System Audio](https://github.com/Sandmann79/xbmc/assets/31831408/dac197fe-1b66-4c32-b724-2984085da0ff)

![Amazon VOD General Settings](https://github.com/Sandmann79/xbmc/assets/31831408/e37a106f-f747-40d3-b2c7-9cd8b3362840)

![Amazon VOD InputStream Adaptive](https://github.com/Sandmann79/xbmc/assets/31831408/34ae3095-ab96-4a55-a2b7-a87fde9e7de4)

![Amazon VOD Content Audio](https://github.com/Sandmann79/xbmc/assets/31831408/1f5d31b9-1d3e-44e0-add9-33cf3d10b673)

![Disney Plus Playback](https://github.com/Sandmann79/xbmc/assets/31831408/0a975f9a-058f-4353-ae31-89e6aadd2569)

![Disney Plus Content Audio](https://github.com/Sandmann79/xbmc/assets/31831408/86df6ece-fe19-49ec-869b-5bb371fa4c42)

Thanks for keeping this issue open and hoping for a speedy resolution.

**Comment by mirh** [comment]
The actual commit for this bug was bf23d246b9d4ff2be16df48638b6b5b548610d9b tbf

**Comment by Sandmann79** [comment]
That's true, but on the other hand there were also users who were surprised that the issue was closed although the bug was not yet fixed in the current stable version.
