### ISSUE TITLE
Amazon VOD GetDirectory Error during login

### ISSUE THREAD

**Issue by georgol11** [Sandmann79/xbmc#528]
**Addon used**
- [X ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: v0.9.0

**Account type**
- [ ] primevideo.com
- [X ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi3
- OS version: LibreELEC (official): 9.2.6, kernel: Linux ARM 32-bit version 4.19.127
- Kodi version number: Kodi (18.9 (18.9.0) Git:newclock5_18.9-Leia). 

**Upload Logs**

kodi.log
https://drive.google.com/file/d/1KHU8rMbH7D3dr1VhmUCrSB9l7EGsq60f/view?usp=sharing

**Describe the bug**

After password change I could not login. Password is correct. 

2020-12-28 16:44:50.455 T:1267721088 WARNING: CPythonInvoker(9, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/p
2020-12-28 16:44:50.456 T:1276113792   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/
2020-12-28 16:44:50.462 T:1937031184   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/) failed

No actual *avod* logs though extended log mode

**Comment by MikeColeGuru** [comment]
I'm also getting this error.  New Install.  However, I also get an html file in the avod-login.log file.

It renders to this (I blanked out my phone number)

![avod-login](https://user-images.githubusercontent.com/19918682/103510364-bb209600-4e2a-11eb-96ff-89db4503dd11.PNG)

**Comment by Sandmann79** [comment]
@georgol11 these log files are mandatory, if you have login problems .They will be generated by enabling advanced logging at addon settings (not Kodi settings).

@MikeColeGuru a password reset form is not implemented in the addon and it won't be available. For these you can use any web browser. This addon handles only common login forms and the corresponding confirmation checks.

**Comment by georgol11** [comment]
Sorry. I have overlooked this option.Seems to be an Account Problem.In Amazon Shopping App the password worked. When I put in a wrong password in the Addon , I've got a wrong password Message. But then I tried out to log off all apps in Amazon Prime video on Android. After logging on again, I had to reset my account.This new password worked also in the VOD.Strange, but it works now. Please close the issue.Thanks a lotGeorg-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 05.01.21, 21:05 schrieb Sandmann79 <notifications@github.com>:

   
  @georgol11 these log files are mandatory, if you have login problems .They will be generated by enabling advanced logging at addon settings (not Kodi settings). 
  @MikeColeGuru a password reset form is not implemented in the addon and it won't be available. For these you can use any web browser. This addon handles only common login forms and the corresponding confirmation checks.

**Comment by MikeColeGuru** [comment]
@georgol11 

> @MikeColeGuru a password reset form is not implemented in the addon and it won't be available. For these you can use any web browser. This addon handles only common login forms and the corresponding confirmation checks.

Ah understand.  It seems to me that there could be a better error rather than Unknown Error - check the logs.  Or it might could bring up a browser?

**Comment by Sandmann79** [comment]
@MikeColeGuru at this point this is an unknown error, that's the reason why the avod logs are generated. We don't know all forms and amazon changes them or add new ones sometimes. 
Rendering these htmls could be possible, but it needs dependencies, wich are not available for all platforms.
