### ISSUE TITLE
Kodi failed to display two-step verification message

### ISSUE THREAD

**Issue by aitormendez** [Sandmann79/xbmc#529]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi3 model B
- OS version: OSMC 2020-11-1
- Kodi version number: 18.9

**Upload Logs**

When I try to login to Amazon, Kodi shows an Unknow error window.
I see that avod-login.log has an HTML document inside. Opening it with a browser I can see the right two step verification dialog box: https://imgur.com/EHuDP6d

Kodi never show me this dialog box. Instead, I get the error message.

**Comment by Sandmann79** [comment]
This form has been already added with commit 89560673ac7d7dec45802453d12a44f46ec59e7d.
Wait for the next release or replace your network.py manually with that from the master branch.

**Comment by aitormendez** [comment]
Sorry for reopen. I updated network.py and now I can see the dialog box with captcha. After hit enter with my login info, there is an addon error that prompt me to see the log: https://hastebin.com/yirutoregu.apache

**Comment by Sandmann79** [comment]
Please provide the avod-login logs. 
Without them it's impossible to find the error.

**Comment by aitormendez** [comment]
Here is: https://www.dropbox.com/s/iki56c8mq0q59xn/Archivo%20comprimido.zip?dl=0
I don't know what info is personal in them.

**Comment by Sandmann79** [comment]
The error should be fixed with bd9c115f7913e35a694d5f1951d20ec376690a15.

Please test and report back.

**Comment by aitormendez** [comment]
It works now. I can login with two step verification process. Thank you for the work.

Now there is another issue. There is no sound for the movies. There is no sound channel interface in Kodi and there is no sound channel interface in Yatse remote control for Android.

Should I open another issue for this?

**Comment by Sandmann79** [comment]
This issue could be related to #522.
Check if the solutions works for you, if not you can open an new issue for this.
