### ISSUE TITLE
Amazon Prime Channels

### ISSUE THREAD

**Issue by floyd65** [Sandmann79/xbmc#53]
This is 2 question not an issue. Is there a way to get the prime channels to show up and be selected in this? I added a channel to my account in prime, but don't see a way to find it in the app.

Also, how do I get to control the video from a remote? I have a hauppauge remote that is RC5 type and can only get it to jump forward or back.

thanks

**Comment by Sandmann79** [comment]
Amazon Channels are currently not supported by the api, which the addon uses. 
If there is an live channel included, i can add it, but not the other content.

**Comment by ErAzOr2k** [comment]
@Sandmann79 If I understood it correctly, you could add a livestream of a Amazon channel. 

Geo TV does actually provide a livestream. Would bei great, If you can add the stream

**Comment by ACiDC0re** [comment]
Hi, 
is it possible to add Motorvision TV Live Stream?
Want to watch NASCAR :D

`Channel page:
https://www.amazon.de/gp/video/storefront/ref=atv_hm_hom_4_c_t_zcymot_3_1?ie=UTF8&benefitId=motorvision&pf_rd_i=home&pf_rd_m=A3JWKAKR8XB7XF&pf_rd_p=1672399607&pf_rd_r=PJ3PT0NNN1SJZQTATHSC&pf_rd_s=center-7&pf_rd_t=12401`

`Livestream: 
https://www.amazon.de/gp/video/detail/B06Y5GGDWM/ref=atv_dp_pb_core?autoplay=1&t=-1`

**Comment by Sandmann79** [comment]
German Livestream channels added with commit 0c5be3320638eec0d9c0f763df9de324301791c0. 
After at most of 8 hours it should appear at main menu.

**Comment by Varstahl** [comment]
Closing this as the relevant information are now inside the [FAQ](https://github.com/Sandmann79/xbmc/wiki/FAQ#can-i-watch-amazon-channels).
