### ISSUE TITLE
very few movies ACTUALLY PLAY

### ISSUE THREAD

**Issue by thesentrycoder** [Sandmann79/xbmc#532]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.0 Leia

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:Andriod Phone
- OS version:Android 8
- Kodi version number:Leia Latest Stable

**Upload Logs**

**Describe the bug**

very few movies play through the program

**Comment by Varstahl** [comment]
Need the full logs, not an option.

**Comment by thesentrycoder** [comment]
[kodi[1].log](https://github.com/Sandmann79/xbmc/files/5810695/kodi.1.log)

**Comment by thesentrycoder** [comment]
might have found the problem. my version of android does not have a compatible version of Widevine CDM. is there a way i can manually update it or add it to my kodi?

**Comment by thesentrycoder** [comment]
The problem seems to be only the film's that aren't in sd. Is there a way I can force sd playback?

**Comment by Varstahl** [comment]
It's an issue with Widevine content decription, unrelated to our addon:
```
ERROR: AddOnLog: InputStream Adaptive: Unable to find license;hdcpEnforcementResolutionPixels in JSON string
ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
```
There's a plethora of devices, both certified and not, so it's impossible to give you the rundown for your exact case. You can start by using the [android playback method](https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon-test#android) and installing the suggested application on your box.
