### ISSUE TITLE
error with refresh option

### ISSUE THREAD

**Issue by luizoti** [Sandmann79/xbmc#534]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.0

**Account type**

- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**

- Hardware: Intel 3570k
- OS version: Kubuntu 20.04
- Kodi version number: 18.9.0

**Upload Logs**

https://pastebin.com/Supuh7tz

**Describe the bug**

Inside mylist/shows i receive this error when use 'refresh', I suppose it will happen elsewhere as well.

**Comment by Varstahl** [comment]
@luizoti I'm sorry, but what country are you using Amazon VOD from?

**Comment by luizoti** [comment]
The episodes are listed in PT-BR, audio and etc, PT-BR as well.

**Comment by Varstahl** [comment]
Are you in Brazil, USA, Canada…? That makes a lot of difference, just trying to understand.

**Comment by luizoti** [comment]
In Brazil.

You can ask without problems, or it is important to identify and resolve the error.

**Comment by Varstahl** [comment]
It is important because you made a mistake in the form, I was trying to understand which portion of the code was involved, because what you said and the logs didn't match. It's okay, I'll take a deeper look.

**Comment by Varstahl** [comment]
In any case it seems like it's a refresh of a TV show, but with a season that went wrong, maybe because the TV show has been pulled from primevideo.com, I'm not entirely sure. There seems to be a problem with refresh though, so I'll try to fix this if possible when I'm going to resolve the refreshing problem as well.

**Comment by luizoti** [comment]
Initially I was going to open this issue because the first season of 'The X-Files' appeared empty, the directory label came in a different way, it came as 'The X-Files Season 1' instead of just 'Season 1' after I used the refresh option it updated and became 'Season 1' and the episodes came back, but there was always the error that I mentioned first, considering your contact, this can be useful too.

Thx for atention and addon.

**Comment by Sandmann79** [comment]
This has been fixed for a while. Closing.
