### ISSUE TITLE
Login failing 2 step verification mobile phone/sms

### ISSUE THREAD

**Issue by Varstahl** [Sandmann79/xbmc#536]
[Forum post ref](https://forum.kodi.tv/showthread.php?tid=349255&pid=3010129#pid3010129), [avod-login.log](https://pastebin.com/tgu24W8N), AVOD 0.9.0

Login form seems to be failing at SMS/Phone call stage. @Sandmann79 is this a new type of form? I recalled it was (seemingly) already fixed. Or maybe there's a problem because there's multiple phone numbers?

**Comment by Sandmann79** [comment]
Yep, you're right this form has been added with 89560673ac7d7dec45802453d12a44f46ec59e7d.

Just like to finish the work on the web_api_tld branch and create a PR for it, before releasing a new version.
I think it should be done in the next two days.

**Comment by Varstahl** [comment]
Suggested he tried to update `network.py` out of speculation, worked first try. No need to rush :)
