### ISSUE TITLE
Add-On does not load on Raspberry Pi 4

### ISSUE THREAD

**Issue by AleXSR700** [Sandmann79/xbmc#537]
Hello everyone,
I installed Amazon VOD and successfully logged in. But every time I open the Add-On it just says that it was not possible and I should check www.primevideo.com fro more info.

Could someone help me find the fix? Netflix and all other add-ons work perfectly, so it is not a Widevine issue.

https://pastebin.com/jJ2ve4G4

Thank you for your help.
Alex

**Comment by Varstahl** [comment]
You didn't fill in the form, log alone:
1. where are you from (as in which country are you accessing the service from)
2. are you logged in yet in the addon?
3. If you're not from DE/JP/UK/US enable "Dump JSON Replies" from the "PrimeVideo" addon settings, zip the JSONs together and attach them to a comment here.
You can find the path on the RPi by reading the Wiki of this repo, same location as log files.

**Comment by AleXSR700** [comment]
Hi,
my account is a German account. I logged in from Finnland (so yes, I am logged in already).
I tried it through my VPN also (which on other add-ons successfully shows me as in Germany). Also did not work.

There was just one JSON file created. Which information do you need from it because it contains personal information?

**Comment by AleXSR700** [comment]
Hi,
I think it is a problem with using primevideo.com

When I login in my browser I get redirected to www.amazon.de

And I get the message in my JSON files about using amazon instead of primevideo website.

Is there a fix for this?

**Comment by Varstahl** [comment]
In the addon you should be able to select Deutschland, then disconnect and reconnect. This should fix it.

**Comment by AleXSR700** [comment]
Ah, yes, thank you! Now it is working :-)
I had it set to Auto.
