### ISSUE TITLE
Custom Subs

### ISSUE THREAD

**Issue by escochain** [Sandmann79/xbmc#538]
**Addon used**
- [x ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [x ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:
- OS version:
- Kodi version number:

**Upload Logs**

**Describe the bug**

Hi i'm new to GitHub and i dont know how this goes, please excuse and mistakes . So with that been said, i world like to know if there is and Way to inoert custom subs? For example if i download subs from a situ, can i Import the info the movie?
thanks in Advance

**Comment by Varstahl** [comment]
Same as any other video from Kodi, I guess, you can select them manually:

![image](https://user-images.githubusercontent.com/284077/106532176-f8db1200-64ef-11eb-954b-0b98ccf381b1.png)
