### ISSUE TITLE
No audio tracks

### ISSUE THREAD

**Issue by escochain** [Sandmann79/xbmc#539]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.0

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Laptop
- OS version: Big Sur 11.1
- Kodi version number: 18.9

**Upload Logs**

**Describe the bug**

hi, i have a Little Problem. I made the same exactly setup on my MacBook and on my Android tv. At first i had an old Problem from a Kodi forum where the only thing i had to do was to replace the network.py file. After i did that on my laptop everything works excelent, but on my Android tv, for some reason, i dont have audio, so when i go on the icon down-right on the player and select audio settings, it wont let me select anything and it says none with shady letters.
What should i do ?

**Comment by Varstahl** [comment]
Without logs it's a bit hard to guess. It could be a network error, or an error specific to a region. The easiest test you could do is go to addon general settings, and disable "Proxy MPD alteration". If that doesn't work you can try enabling audio description in the addon language settings.

**Comment by Sandmann79** [comment]
Duplicate. Closing
