### ISSUE TITLE
Unable to drill down folders

### ISSUE THREAD

**Issue by dfdario** [Sandmann79/xbmc#544]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Atom-based single-board computer
- OS version: Linux Debian 10 Buster-backports (Debian 5.10.13-1~bpo10+1 (2021-02-11))
- Kodi version number: Matrix (19) from www.deb-multimedia.org buster-backports
[kodi.log](https://github.com/Sandmann79/xbmc/files/6048890/kodi.log)

**Upload Logs**

**Describe the bug**

Just testing the behaviour of various plugins ever new Matrix.
Amazon VOD plugin reports error when browsing any of the folders.

**Comment by Paco8** [comment]
This seems to be working for me:
```
--- primevideo-orig.py	2021-03-01 09:28:15.921606369 +0100
+++ primevideo.py	2021-03-01 09:28:35.833670921 +0100
@@ -964,6 +964,12 @@
             details = state['detail']
             if 'detail' in details:
                 details = details['detail']
+            # headerDetail contains sometimes gtis/asins, which are not included in details
+            if 'headerDetail' in state['detail']:
+                details.update(state['detail']['headerDetail'])
+                del state['detail']['headerDetail']
+            if 'btfMoreDetails' in state['detail']:
+                del state['detail']['btfMoreDetails']
 
             # Get details, seasons first
             # WARNING: seasons may not have proper initialization at this stage

```

**Comment by Sandmann79** [comment]
@Paco8 can you explain, why you remove this 2 keys from the `state` dict? Maybe I'm wrong, but this dict didn't get parsed anymore only the `details` dict.

**Comment by Paco8** [comment]
In some movies there's

```
state
    detail
          headerDetail
          btfMoreDetails

```
_details.update(state['detail']['headerDetail'])_ copies the gti list to details, but details still contains headerDetail and btfMoreDetails which makes the code below (_for gti in sorted(details, ..._) to treat them as gti and crashes.

**Comment by Sandmann79** [comment]
Ah okay you have the gtis on the same level as the headerDetail/btfMoreDetails:
```
state
    detail
          headerDetail
          btfMoreDetails
          amzn1.dv.gti...
          amzn1.dv.gti...
```
Than this makes sense. Changing this soon

**Comment by dfdario** [comment]
I tested the patch and it works great! Thanks
