### ISSUE TITLE
Movies/All are inaccessible in watchlist

### ISSUE THREAD

**Issue by DevilBlackDeath** [Sandmann79/xbmc#545]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.0

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry PI 4 - 4GB Version
- OS version: LibreElec 9.2.6
- Kodi version number: Leia 18.9.0

**Upload Logs**

https://justpaste.it/3oufk

**Describe the bug**

When trying to access movies and all from my personal watchlist, an error message shows up telling me to look at the logs. From looking at the logs it seems like the URL it's trying to access is invalid. I tried changing the region just in case but it did not help. Clearing cache didn't help either (not that I expected it to, but better safe than sorry).
Accessing shows works as expected however.

**Comment by Varstahl** [comment]
It looks like it's accessing Amazon.co.uk. Are you/is your account UK based? Because it also tries to access PrimeVideo, which fails, since it's not available for the UK.

**Comment by DevilBlackDeath** [comment]
My account is France-based. Also afaik it worked a few weeks/a month back, despite the fact I did not update the plugin in between (at least I believe, might have been some auto-update that lingered). PrimeVideo should be the one accessed, it's the one I access when watching from a computer.

**Comment by Woodhousemelena** [comment]
The patch suggested in [#545](https://github.com/Sandmann79/xbmc/issues/545) Fixes my issue. I did apply it to primevideo.py instead of web_api.py. 

Is there any reason this patch is still not applied in the main download after 9 days? This would seem to be a bug that totally cripples the plug in for everyone doing a fresh install right now.  Just curious... ;-)

**Comment by Sandmann79** [comment]
This patch is part of bigger changes to the addon and these have to be reviewed. That's the reason, why the filename differs.
But I think we could add this patch to the master branch and release it, @Varstahl?

**Comment by Sandmann79** [comment]
@DevilBlackDeath if this issue still exist, try to change the region at addon settings to **ROE Europe**, save the settings and log in again.

**Comment by koboldskind** [comment]
> @DevilBlackDeath if this issue still exist, try to change the region at addon settings to **ROE Europe**, save the settings and log in again.

I was having the same issue, this finally solved it. Region **auto** didn't work, **ROE Europe** does.

**Comment by Sandmann79** [comment]
Issue fixed. Closing
