### ISSUE TITLE
Unable to use or login into Amazon Prime Addon

### ISSUE THREAD

**Issue by drmodem** [Sandmann79/xbmc#550]
The plugin worked fine until yesterday (20 march).

I am now unable to use the add-on. It fail logging into my Amazon Prime account. It give me a Amazon VOD error or just put me back to the Kodi menu list. When i get back to the settings of the plugin the account hasn't been saved. I do not get any "Logged in with account name" and i also do not get any captcha at all.

I tried a fresh install of the plugin and get the same issue. I upgraded then Kodi to version 18.7, i was with 18.6 before, and get the same issue. I am using a Raspberry Pi 4 with Raspbian Buster version.

I provide my log also from Kodi. I can see many errors referring to csoup, BeautifulSoup4 though i am not sure if its the root cause of the problem. The BS4 come from Kodi repository (lastest version)

[kodi.log](https://github.com/Sandmann79/xbmc/files/6178709/kodi.log)

**Comment by drmodem** [comment]
I forgot to mention that i use "ROW North America" since i am located in Canada.

**Comment by Sandmann79** [comment]
Try to update the [Soupsieve addon](https://mirrors.kodi.tv/addons/leia/script.module.soupsieve/) to 1.9.6+leia.1.
If this not help downgrade BS4 to 4.6.2 from [here](https://mirrors.kodi.tv/addons/leia/script.module.beautifulsoup4/) and disable automatic updates.

**Comment by drmodem** [comment]
Version 1.9.6+lea.1 didn't work. I was using that version from Kodi repo.

Version 4.6.2 worked, it fix the issue with the old version. Kodi repo then broken something in the new version or work in a different way. Thanks!

**Comment by bassman56** [comment]
> Version 1.9.6+lea.1 didn't work. I was using that version from Kodi repo.
> 
> Version 4.6.2 worked, it fix the issue with the old version. Kodi repo then broken something in the new version or work in a different way. Thanks!

I had a similar login problem, but manual installation of these 2 zips did not work, neither on libreelec nor on windows. this is the log file:
[avod-login.log](https://github.com/Sandmann79/xbmc/files/8119591/avod-login.log)

Any proposal what to try? Thank you!

**Comment by Chissper** [comment]
Same issue as bassman56 here. Tried everything above, but with no success.
The response from amazon in the logfile is only a html page with german Text "Wir entschuldigen uns fÃ¼r die Unannehmlichkeiten. In unserem System ist ein interner Fehler aufgetreten."
Any ideas would be great :-)
Thanks

**Comment by Sandmann79** [comment]
@bassman56 @Chissper 
See answer here: https://github.com/Sandmann79/xbmc/issues/615#issuecomment-1054696864
