### ISSUE TITLE
unable to update

### ISSUE THREAD

**Issue by p060477** [Sandmann79/xbmc#551]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:
- OS version:
- Kodi version number:

**Upload Logs**

**Describe the bug**

i've kodi 17.3 portable and trying to update some add on i get errors:

16:53:18.219 T:4164 ERROR: ADDON: extension '' is not currently supported for service addon
16:53:57.014 T:4164 ERROR: Previous line repeats 7 times.
16:53:57.014 T:4164 ERROR: XFILE::CDirectory::GetDirectory - Error getting zip://special%3a%2f%2fhome%2faddons%2fpackages%2fscript.module.six-1.14.0%2bmatrix.2.zip/
16:53:57.014 T:4164 ERROR: CAddonInstallJob[script.module.six]: invalid package special://home/addons/packages/script.module.six-1.14.0+matrix.2.zip
16:53:57.074 T:4164 ERROR: ADDON: extension '' is not currently supported for service addon

how to solve..??
pls guide me as i was a little child cause i'm really not skilled..
thxs so much in adv
cheers

**Comment by Sandmann79** [comment]
First of all you should update your Kodi installation - 17.3 is almost 4 years old. 
The current version is v19.0.

Then you're using the wrong repository for 17.3, so you have to remove the matrix repo and install the leia repo:
https://github.com/Sandmann79/xbmc/releases/download/Repository/repository.sandmann79.plugins-1.0.3-leia.zip

Just for information:
On Kodi 17.3 the most movies/episodes won't play with Kodi's internal player, due missing DRM implementations.
The support of this version will be dropped in the future.

**Comment by p060477** [comment]
hi, first thxs , i also get the error while trying to update these..:
![screenshot000](https://user-images.githubusercontent.com/12773559/112522822-609a3480-8d9e-11eb-966c-ec583d055747.jpg)
..may be they are only suitable for vers 19..??
..the bug is that the new 19 is really not suitable for a plenty of add ons...the web is full of user's complaints..
:(

**Comment by Sandmann79** [comment]
The addons with matrix next at version number are for Kodi 19 and won't work on versions below.
You can also use Kodi 18.9, if you don't like to use v19. Almost all addons should work with it.

**Comment by p060477** [comment]
thxs again,
you mean that all those 5 add ons will works and will be able to finally update in vers 18.9..?
