### ISSUE TITLE
cannot open home folder

### ISSUE THREAD

**Issue by marcoriccine** [Sandmann79/xbmc#554]
**Addon used**
- [x ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.2

**Account type**
- [x ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:RPI4.arm
- OS version:libreELEC 9.2.6
- Kodi version number:Leia 18.9.0 

**Upload Logs**
[kodi.log](https://github.com/Sandmann79/xbmc/files/6280193/kodi.log)

**Describe the bug**

in the last days, when try to open the amazon VOD home folder i got an error popup (the same error in log)  "ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/coll1_Home" other folder are loaded successfully. 
and i can play videos.
Tank's for your work, very good work!

**Comment by Sandmann79** [comment]
Stale issue. Closing.
