### ISSUE TITLE
Profile switching fails

### ISSUE THREAD

**Issue by hpannenb** [Sandmann79/xbmc#555]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.2

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Intel PC
- OS version: Ubuntu 20.04
- Kodi version number: 19.0

**Upload Logs**

[amazon-vod-switch-profile-fails.log](https://github.com/Sandmann79/xbmc/files/6291509/amazon-vod-switch-profile-fails.log)

**Describe the bug**

If one uses different profiles in Amazon Prime Video switching between them currently fails. This seems to happen since a week or so. See the log.

**Comment by Sandmann79** [comment]
Amazon changed something on her servers.
Thus been fixed with b63885d40579b7ca0084a408238e9133e2839aa7 and will be available on the next release.

**Comment by hpannenb** [comment]
Great. Thanks for the info.

**Comment by Starbase12** [comment]
Thx. Installed this application for the first time and also faced that type of issue. Is there any way to use the fixed build in LibreElec before it's going to be official released? What I have to do?

**Comment by Sandmann79** [comment]
@Starbase12 nothing, just released v0.9.3 with 24d556d9ef59621cf49f5463e2413b12a6aaf153.
