### ISSUE TITLE
Problem after moving to kodi matrix

### ISSUE THREAD

**Issue by nadiadobg** [Sandmann79/xbmc#557]
I used to have kodi leia with amazon vod and it worked perfectly. Yesterday my kodi got updated to matrix 19.0 (without my consent): of course most addons do not work anymore. I tried to install a matrix version of Amazon Vod. I downloaded the matrix repository zip file and installed it successfully, but when I try to install the add on itself I get the following messages:
Mechanical soup: the add-on is not compatible with this version of kodi.
Amazon VOD: the dependency on xbmc. Python version 2.25.0 could not be satisfied. 

Any ideas how to make this work? (oh how I hate it when they change perfectly working things!).

**Comment by luizoti** [comment]
To me, kodi crash with all addons in repo.

**Comment by dfdario** [comment]
Same here

**Comment by nadiadobg** [comment]
Well I suspected a problem with the python version. Since I did not know how to install the right one, I uninstalled kodi and installed it again, then I installed the repo and the Amazon Vod addon. Now it works fine.
If you have the same problem there might be an easier solution than this, but even though installing/un installing kodi is long at least it works.

**Comment by luizoti** [comment]
Strange, i will delete de addon and try again, if not work i will reinstall kodi.

**Comment by loggin** [comment]
I'm getting this after a matrix upgrade too, I've moved to sandmans matrix repo and tried reinstalling from there but get a dependency issue on python 2.25, clearly something is lingering from the Leia setup and need to figure out what it is and hopefully clean just that up as a Kodi reinstall for me is quite nuclear and time consuming

**Comment by RobjSky** [comment]
Im having the same issue. Would be great if there will be a fix.

**Comment by RobjSky** [comment]
FYI:
I found this solution on Kodi Forum and it worked for me. Just in case somebody is running into the same issue:

--  "Mechanical soup: the add-on is not compatible with this version of kodi."
--  "Amazon VOD: the dependency on xbmc. Python version 2.25.0 could not be satisfied."

Solution: 
"remove orphaned addons using Settings -> System -> Addons -> Manage dependencies"

Original Post:
https://forum.kodi.tv/showthread.php?tid=349255&pid=3031950#pid3031950

**Comment by jasonfrancis** [comment]
Specifically I had an old version of PyAutoGUI that required `xbmc.Python 2.25.0`.

I had to manually delete PyAutoGUI from my addons folder, but then I was able to install the Amazon VOD addon - and it added PyAutoGUI `0.9.51+matrix.1`.

**Comment by luizoti** [comment]
> FYI:
> I found this solution on Kodi Forum and it worked for me. Just in case somebody is running into the same issue:
> 
> -- "Mechanical soup: the add-on is not compatible with this version of kodi."
> -- "Amazon VOD: the dependency on xbmc. Python version 2.25.0 could not be satisfied."
> 
> Solution:
> "remove orphaned addons using Settings -> System -> Addons -> Manage dependencies"
> 
> Original Post:
> https://forum.kodi.tv/showthread.php?tid=349255&pid=3031950#pid3031950

Confirmed, remove orphaned dependencies and reinstall works.

**Comment by Sandmann79** [comment]
Should be fixed with new repo schema released with 69da66d2949ae6bf3b3e63c33ffe0ff4012de242
