### ISSUE TITLE
Input streams on Kodi linux

### ISSUE THREAD

**Issue by theboy181** [Sandmann79/xbmc#56]
I can’t seem to get any movies to playback. I have Kodi 18, Input Stream , and libwidevinecdm.so in the cdm directory. Netflix plugin is working for me so I know that it should work.

Anyone able to point me in the right direction?

https://pastebin.com/sDgRHYb8

**Comment by theboy181** [comment]
https://pastebin.com/sDgRHYb8

**Comment by theboy181** [comment]
I can’t seem to get any movies to playback.  I have Kodi 18, Input Stream , and libwidevinecdm.so in the cdm directory. Netflix plugin is working for me so I know that it should work. 

Anyone able to point me in the right direction?

https://pastebin.com/sDgRHYb8

**Comment by Sandmann79** [comment]
Yesterday Amazon changed some things on their website that breaks Inputstream playback.
I'm working on it and an fixed release should be done in the next 24 hours.

**Comment by Sandmann79** [comment]
Issue fixed with commit 2ea28046595f00ae49fdf544ee3180cf99cfa020 and new version 0.4.6 released.

**Comment by theboy181** [comment]
Thank you I’ll test it out

**Comment by theboy181** [comment]
I do t see 4.6 in the update feature

**Comment by Sandmann79** [comment]
You have to refresh the repo in Kodi Addon browser or install the add-on manually from here: https://github.com/Sandmann79/xbmc/blob/master/packages/plugin.video.amazon-test/plugin.video.amazon-test-0.4.6.zip?raw=true

**Comment by RobbesU** [comment]
Hi Sandmann79, 
Just updated your add-on with 4.6 on Amazon VOD (I'm in the UK).  The streaming error message is gone, but sadly replaced by an error window "Unable to play.  Due to changes at Amazon's DRM encryption, it's not possible to use Inputsteam for this video. [....]"

**Comment by Sandmann79** [comment]
Be sure to disable DRM check and enable check audio track at Kodi 18 Builds.

**Comment by RobbesU** [comment]
Thanks Sandman, 
Update: Fully working after also updating the whole Kodi to latest overnight build (#1219, 20-Dec-2017).
I noticed this latest kodi update "Includes latest addons: inputstream.adaptive (564981a), inputstream.rtmp (c772497), ..." so maybe it's no longer required to do a manual inputstream install for amazon ??

**Comment by RobbesU** [comment]
Are you sure you meant

> Be sure to **dis**able DRM check and enable check audio track at Kodi 18 Builds.

I always had DRM check "on", so I checked: when disabled, all I got was a black screen during play-back. ENabled and it worked again. That was the only thing I changed and it is indeed an on/off thing.

**Comment by Sandmann79** [comment]
Like I wrote above, only on Kodi 18 builds you should disable DRM check - on Kodi 17 leave it enabled.

**Comment by RobbesU** [comment]
This is why I mention it: I _am_ using Kodi 18  (Milhouse's #1219, 20-Dec-2017).  These are the settings for perfect playback. :-) 

![20171221_094511](https://user-images.githubusercontent.com/33870532/34250333-75737da4-e634-11e7-81bf-86446d0fa3a7.jpg)

![20171221_094557_001](https://user-images.githubusercontent.com/33870532/34250332-75582f90-e634-11e7-8e74-618a8b22b990.jpg)

DRM 'off' gives a black screen, although the stream timer etc is counting up.
BTW: your work is fantastic !!  This is only meant to be constructive feedback to make it even better :-)

**Comment by Sandmann79** [comment]
You are right. But in this case you only get stereo audiotracks. 
If you disable drm check, enable switch audio track and choose your desired language, you should get multi channel audiotracks (if available).

**Comment by RobbesU** [comment]
Ah, now I see. Danke !
