### ISSUE TITLE
4k hdr 

### ISSUE THREAD

**Issue by tigait62** [Sandmann79/xbmc#560]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:
- OS version:
- Kodi version number:

**Upload Logs**

**Describe the bug**

Bonjour, suite à installation de l'addon, je n'arrive pas à lire en 4k hdr ayant pourtant le matériel compatible. Avez vous une solution ? Merci

**Comment by Sandmann79** [comment]
Please read the [FAQ](https://github.com/Sandmann79/xbmc/wiki/FAQ#how-can-i-play-movies-in-hduhd).

**Comment by tigait62** [comment]
OK mais donc ce n'est pas possible encore à l'heure actuelle ? Car le problème date depuis 2018 visiblement ?

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
