### ISSUE TITLE
How to disable updating of (last/recently) watched content from Kodi addon client?

### ISSUE THREAD

**Issue by weyzax** [Sandmann79/xbmc#562]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.3+matrix.1

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 4 (Irrelevant)
- OS version: LibreELEC 10 (Irrelevant)
- Kodi version number: 19.1

**Describe the bug**

First of all, thank you for maintaining this project and making Prime available on Kodi. It's incredibly helpful that I can play Prime and other services on my non-smart TV. Would it be possible to disable the sync of watch status/playback progress with the amazon servers? Because simply browsing content is unnecessarily populating the Recently watched list everywhere (which does not happen in the browser as it only updates after a certain interval of watch time is completed). It becomes harder to navigate to the actual recently watched content because of the preview ones. It would be really helpful to have an option (in the settings) to disable/toggle this [feature]<https://github.com/Sandmann79/xbmc/issues/363#issuecomment-557868368>.

**Comment by Sandmann79** [comment]
Just to be sure, you just browsing some categories and your watched state at amazon gets updated? Without playing any video?
If yes, please provide a log here of this behaviour.
Usally the addon does the same as the Web browser - it sends the progress at start-/stopping the playback and every 3 minutes.

**Comment by weyzax** [comment]
>Just to be sure, you just browsing some categories and your watched state at amazon gets updated? Without playing any video?

No, no. The first few minutes were actually watched and did get updated (just like expected behavior in the browser). What I meant was the option to disable this feature like how its done with the Netflix and Disney+ addon (to disable sync of watched content).

This is useful when the user watching the first few minutes (browsing through movies) to check if it's worth watching and not populate the watch list and can toggle it to 'OFF' in the settings.

**Comment by Sandmann79** [comment]
Okay this should be possible

**Comment by Varstahl** [comment]
We could also delay the first sync by custom amount of minutes. Same effect, but still lets you sync TV series and so on, without over populating. Multi options, like "Disable, sync after N minutes", 5, 15, 30. Something similar to the effect of what's also use for audio scrobbling, like Last.FM.

**Comment by Sandmann79** [comment]
Released with 69da66d2949ae6bf3b3e63c33ffe0ff4012de242
