### ISSUE TITLE
Dependency script.module.mechanicalsoup in Version 0.12.0+matrix.1 could not be resolved

### ISSUE THREAD

**Issue by pipsen** [Sandmann79/xbmc#565]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Intel NUC 7i3 BNK
- OS version: LibreELEC 9.95.4
- Kodi version number: 19.1 Matrixk

**Upload Logs**

Hello,

currently, I am using LibreELEC 9.95.4 with KODI 19.1.0 Matrix. I had playback problems with Amazon VOD Plugin and tried to reinstall it, but I ad always dependency problems with script.module.mechanicalsoup.

This is what I did:

Step 1: Under Settings / System / Addons: Removed all orphaned dependecies
=> Still dependency problems with mechanicalsoup

Step 2: Remove mechanicalsoup from file system and downloaded it manually from repo as zip and installed it
=> Problems with dependency to script.module.pyautogui

Step 3: Download script.module.pyautogui manually from repo as zip and try to install it
=> Problem with dependency to xbmc.python in Version 2.25.0 (I thought, KODI 19.1 uses Python 3?)

I used repository.sandmann79-py3.plugins-1.0.0-matrix repo.
Thank you very much in advance!

**Comment by Essam312** [comment]
In a clean installation try using Amazon VOD from @Paco8 repo, it's the same as @Sandmann79 but with support for the subtitles in SSA format and fixing some problems with Amazon's subtitles using the add-on "Improved Subtitles" (script.module.ttml2ssa).

https://raw.githubusercontent.com/Paco8/kodi-repo/master/packages-kodi-19/repository.paco8/repository.paco8-1.1.0.zip

**Comment by thombet** [comment]
I am facing the same issue as you @pipsen: did you find a solution?

**Comment by krokodylowy** [comment]
HI

The problem still exists.for Matrix installation
I tried this fork https://github.com/Paco8/kodi-repo/tree/master/packages-kodi-19/repository.paco8  and this version works fine.

**Comment by Varstahl** [comment]
Sorry, this slipped under my radar. These problems have cropped up over time, but it's always a problem with the user installing something by mistake. A list of steps to fix this issue is also present in #592.
