### ISSUE TITLE
TV Shows that have been bought (instead of included in Prime) aren't exported to library.

### ISSUE THREAD

**Issue by t0mtee** [Sandmann79/xbmc#567]
**Addon used**
- [ X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Intel i7 6700, GTX 1070, 16gb RAM
- OS version: Windows 10, latest version
- Kodi version number: 18.9

**Upload Logs**

With automatically export to watchlist enabled, Movies / TV shows that were bought from Amazon instead of free from Prime aren't automatically exported.

**Comment by OsoaGitHub** [comment]
Nevermind, it just applies to TV shows. Movies are fine

**Comment by OsoaGitHub** [comment]
Also doesn't work when manually exporting them

**Comment by OsoaGH** [comment]
as a workaround, use TMDBHelper and Trakt lists

**Comment by Sandmann79** [comment]
Has been fixed for a while. Closing.
