### ISSUE TITLE
Missing episode info in show/season/episode Information context menu option

### ISSUE THREAD

**Issue by luizoti** [Sandmann79/xbmc#571]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4+matrix.1

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: intel i3 - 4gb - ssd 120 sansung
- OS version: Ubuntu 20.04
- Kodi version number: 19.1

**Upload Logs**

Addon won't return error.

**Describe the bug**

This request is for more information to be entered in the content information screens, by using the 'Information' option in the context menu.

This modification will also reflect the feedback generated by JsonRPC, which currently does not bring all the information.

This is the return of the Goliath series, in this case the missing information is the "showtitle" information, in my head I don't remember any other missing information.

```
    {
        "art": {
            "thumb": "fanart.jpg"
        },
        "episode": 1,
        "fanart": "",
        "file": "path.path",
        "filetype": "file",
        "label": "De Ratos e Homens",
        "season": 1,
        "showtitle": "",
        "title": "De Ratos e Homens",
        "type": "episode",
        "year": 2016
    }
```

**Comment by Varstahl** [comment]
Yes, this is a long standing enhancement way overdue. We only show partial information, which is a bit annoying.

**Comment by luizoti** [comment]
True, I'm writing the Library Integration Tool addon, and no matter what solution I create to deal with this missing data, something always gets out of place, I tried to fix it by modifying Amazon VOD, but I couldn't find a solution.

**Comment by Sandmann79** [comment]
tvshowtitle included since a while. Closing
