### ISSUE TITLE
Playback on Android 9 (MINIX) displays Music window instead of Video

### ISSUE THREAD

**Issue by Victorvdc** [Sandmann79/xbmc#572]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4+Matix.1

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:MINIX U22-XJ
- OS version: Android 9
- Kodi version number: 19.1

**Upload Logs**

LINK
https://drive.google.com/drive/folders/1nQABqa5f8LLOMB6Kk-8rCBzqG7zvvTHr?usp=sharing

4 logs
SHORTokkodi = Playback on MINIX U9-H Android 6.1 . Results OK on Video Window Log starts at playback click and shows “********** Video window initiated here OK”
SHORTbadkodi = Playback on MINIX U22.XJ Android 9. . Results BAD  on Video Window Log starts at playback click and shows “*************** Music window initiated instead of  Video here  BAD”
FULLbadorginalkodi = Full bad Android 9 log
FULLokorginalkodi= full OK android 6.1 log

**Describe the bug**

Play back of Videos on MINIX U22-XJ Android 9 device (And some other borrowed Android 9 Devices) using “inputstream”  displays on Music window instead of Video window.  Result is audio playback  but no video playback.  
I have captured the play back logs of the same video file on my MINIX U22-XJ Android 9 and MINIX U9-H Android 6.1 device.  Showing correct play back on the 6.1 and incorrect on the 9 Android. Short logs start at play back click and have additional comment where Video or Music window is initiate.  

Any questions contact me at vdelcol.5@gmail.com

**Comment by Victorvdc** [comment]
Added excel spread sheet to logs and parsed data to compare differences.

I can see some suspected problems but I am not familiar enough with this type of development to make sense of it.  Hopefully this will help.

**Comment by Sandmann79** [comment]
Stale. Closing.
