### ISSUE TITLE
Prime Video Channels folder is empty

### ISSUE THREAD

**Issue by Liqianyu** [Sandmann79/xbmc#574]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4+Matix.1

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:SHIELD TV Pro 2019
- OS version:8.2.3
- Kodi version number:19.1

**Upload Logs**

**Describe the bug**

After logging in and opening Home - Your Channels/Prime Video Channels both folders are empty, in fact I am currently subscribed to two channels.
I tried to add the channel movies & TV series to the watch list and it works fine. So the problem is only with the list display.

**Comment by Sandmann79** [comment]
This issue should have been fixed, if not feel free to reopen this issue.
