### ISSUE TITLE
Champions League in Germany

### ISSUE THREAD

**Issue by MRLB** [Sandmann79/xbmc#578]
Hello,
Is it possible to add the champions league stream for Germany to your addon?

Thank you for your great kodi addon :-)

**Comment by MRLB** [comment]
Tuesday will be the first Match. I hope there will be any solution:-)

**Comment by RdTrxx** [comment]
Hi,
Yes that would be great!
At this time it is not possible to watch a live Stream.
Neither by stepping through the topics nor with the search.
Only movies and series but no Events are Wirkung.
Regards RdTrxx

**Comment by Varstahl** [comment]
Are you guys sure? We implemented live streams support a long time ago. Should be already supported. Unless they'd change something, I guess 🤔

**Comment by RdTrxx** [comment]
I am unable to find the Stream.
There is no topic  inside the Addon which belong to events or  live. I do not know how to find the stream.
The search function only return Movies and old stuff from the Channels.
I tried to put the Stream into my Watchlist via the Prime App on my Phone. But the Watchlist also does not work (no entrys in the Addon are lsisted)
I tried the function "last seen" after I watched the stream on my mobile but this topic is also empty inside the Addon.

**Comment by Sandmann79** [comment]
I think you're talking about TLDs here and with this the're such live events not listed by the old api.
There is an implemention of the Web api for TLD users [done here](https://github.com/Sandmann79/xbmc/pull/542), but it isn't released to public yet. 
With this all the content from Amazons webpage are available within the addon. 

If you want, you can try/install the attached zip that contains the current development status. 
For using the Web-api enable the corresponding option at addon settings > Amazon.TLD. 
To reduce loading times you can set Pagination to Everywhere at settings > PrimeVideo > Pagination. 

[plugin.video.amazon-test_0.9.5~beta.zip](https://github.com/Sandmann79/xbmc/files/7254226/plugin.video.amazon-test_0.9.5.beta.zip)

**Comment by RdTrxx** [comment]
Thanks a lot!
I will try it on Friday!
