### ISSUE TITLE
Option to complete hide Trailhers and others

### ISSUE THREAD

**Issue by luizoti** [Sandmann79/xbmc#580]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4 matrix1

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Intel(R) Core(TM) i3-2328M CPU @ 2.20GHz, 4 cores available 4gb
- OS version: Linux x86 64-bit
- Kodi version number: Kodi (19.1 (19.1.0) Git:20210509-85e05228b4). Platform: 

**Upload Logs**

**Describe the bug**

Is possible to add a options to complete hide extras/trailhers and non-normal episodes from episode list?

**Comment by Varstahl** [comment]
Yes, it shouldn't be too much of a problem. I'm still not fully back to the project yet, so it's going to take me a few weeks though, at least.

**Comment by luizoti** [comment]
No problem, I managed to dodge these items in my addon, but if there is something directly on Amazon VOD it would be much more guaranteed that it will work.

**Comment by Sandmann79** [comment]
Feature already implemented. Closing.
