### ISSUE TITLE
Padronize first season year for all seasons

### ISSUE THREAD

**Issue by luizoti** [Sandmann79/xbmc#581]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4+matrix.1

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: intel i3 - 4gb - ssd 120 sansung
- OS version: Ubuntu 20.04
- Kodi version number: 19.1

**Upload Logs**

Addon won't return error.

**Describe the bug**

This problem is slightly connected to issue #571, the two are information in the list of yet, this json is the return of the show Goliath, as you can see, each season has a specific year, this is reflected also in the episodes, where each episode of each season has its own year, (X-file has 2 different years that probably reflect the division when they were released)

My request is that the year information be standardized, based on the information from the first season reflecting this information for all.

Golias exemple: https://pastebin.com/Z9nH1cvK

**Comment by Varstahl** [comment]
I don't think this will be implemented ever, we use as accurate information as possible when we can. Still, I have no idea why you would need this.

I don't remember if the TV Show uses the year of the first available season, that I could probably add, but we're not going to feed incorrect information to the users.

**Comment by luizoti** [comment]
Usually (at least that's what I see) when searching for the information of a series, for example using tinymediamanager (and as far as I understand kodi's own scraper) the search for data uses the series' release date and/or first season, the Archive X even, the first season if I'm not mistaken comes as 1994 (on amazon-vod), but the first episode the release date is 1993, and it's 1993 the date referenced as the actual release date, the really accurate one.

**Comment by Sandmann79** [comment]
Will not be implemented in the future. Closing.
