### ISSUE TITLE
Install fails due to py3 dependency on leia

### ISSUE THREAD

**Issue by ChristianOrgler** [Sandmann79/xbmc#582]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.0.3-leia

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 3-b
- OS version: libreelec
- Kodi version number:

**Upload Logs**

**Describe the bug**

**Comment by Varstahl** [comment]
You probably installed the wrong addon. There are two versions, one fore Leia (18), one for Matrix (19). Also the 1.0.3-leia is the repo, not the addon.

**Comment by ChristianOrgler** [comment]
I've downloaded the 1.0.3-leia repo, then I went to "Install from Repo", chose this repo and selected the add-on "amazon-vod"

**Comment by Varstahl** [comment]
All good in theory, but there must be some conflicts with other software, maybe. We need logs for a reason. I don't think we require anything py3 on Leia branches, you're the only one reporting the issue. What could happen, is that if you installed another repo *that also* has the same modules, but py3, then there's where the error comes out, but without logs I can't help you.

**Comment by ChristianOrgler** [comment]
Sure I will delete all add-ons (was a fresh install anyway and only netflix was on there at the time), install and provide logs.

It looked like the deendencies of the leia amazon version poibted to some -matrix versions.

But I will provide logs tomorrow - thanks for your quick responses thus far!

**Comment by bewi93** [comment]
Hey, i got the same issue as i tried to install the addon the first time. My fault was that i tried to install the wrong repo via zip in the first time. After i found out my mistake i deleted amazon app again for kodi18 and tried to install the right repo for kodi 19 via zip. I dont know why but it didn´t work. I had to deinstall the old repo first then install the new one, otherwise it will always just install the kodi 18 addon. So a clean install could be a solution

**Comment by ChristianOrgler** [comment]
That was it, I had the matrix repository still installed - so somehow it might took those dependencies.

I've removed the matrix repository and then installing worked!
