### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by madhavnair69** [Sandmann79/xbmc#583]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4

**Account type**
- [ ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:Raspberry pi 4
- OS version:reclabox
- Kodi version number:Kodi 18.9

**Upload Logs**

[http://paste.kodi.tv/gazelakufe](http://paste.kodi.tv/gazelakufe)

**Describe the bug**

It starts the playback,and then just stops after saying on the top right that it started

**Comment by Varstahl** [comment]
You have a bunch of problems on your end, unrelated to the addon itself. You have issues with Widevine (possibly due to the ARM box).

```
 ERROR: [script.module.inputstreamhelper] Failed to check for missing Widevine libraries.
NOTICE: [script.module.inputstreamhelper] Widevine update check was made on 2021-09-17 12:54
 ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/recalbox/share/system/.kodi/cdm/libwidevinecdm.so)
 ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
```

ARM is a bit of a bitch on this front. There are many boxes that barely work, but I'm not sure if Widevine ARM binaries still exist. You would have the same problems with anything DRM related. If you only use that as a home theater box with Kodi, you might try dedicated distros such as LibreElec or OSMC, that work hard keeping the DRMs in check and working.

**Comment by madhavnair69** [comment]
> 
> 
> You have a bunch of problems on your end, unrelated to the addon itself. You have issues with Widevine (possibly due to the ARM box).
> 
> ```
>  ERROR: [script.module.inputstreamhelper] Failed to check for missing Widevine libraries.
> NOTICE: [script.module.inputstreamhelper] Widevine update check was made on 2021-09-17 12:54
>  ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/recalbox/share/system/.kodi/cdm/libwidevinecdm.so)
>  ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
> ```
> 
> ARM is a bit of a bitch on this front. There are many boxes that barely work, but I'm not sure if Widevine ARM binaries still exist. You would have the same problems with anything DRM related. If you only use that as a home theater box with Kodi, you might try dedicated distros such as LibreElec or OSMC, that work hard keeping the DRMs in check and working.

Does this mean i cant run this like this? Is there any way to get widewine working?

**Comment by Varstahl** [comment]
I'm not saying that it's impossible, I'm saying that every platform has its quirks and oftentimes it works until it doesn't. You'd have to look at a way to import Widevine CDM into your ARM platform. If you manage to get Widevine going, everything else should come along.

**Comment by madhavnair69** [comment]
> 
> 
> I'm not saying that it's impossible, I'm saying that every platform has its quirks and oftentimes it works until it doesn't. You'd have to look at a way to import Widevine CDM into your ARM platform. If you manage to get Widevine going, everything else should come along.

Alright so i updated widewine with the instructions i found on a website but now kodi crashes everytime i use widewine

**Comment by Varstahl** [comment]
I'd go on a limb and say that's probably not the way it was supposed to go :D
If you installed it onto CDM, you can just remove the directory and Kodi should be able to start again.

I'm sorry but I can't really help you further, I'm out of my water.
