### ISSUE TITLE
Fails to open videos after addons update: "http error"

### ISSUE THREAD

**Issue by empanadablues** [Sandmann79/xbmc#586]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: v0.9.4

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 4
- OS version: Raspbian GNU/Linux 10 (buster), kernel: Linux ARM 32-bit version 5.10.60-v7l+
- Kodi version number: Kodi (18.7 Git:20200528-2c5354e70a). Platform: Linux ARM 32-bit

**Upload Logs**

https://drive.google.com/file/d/1ESf_R9xeIP3i2DUNbqdO3Da1VF9bTfgc/view?usp=sharing

**Describe the bug**

Amazon VOD addon worked perfectly until I updated the kodi addons, now, fails to open any video. I suspect that inputsream adaptative update broke Amazon VOD, but I'm not sure.  Netflix addon works well. Tried to change the libwidevine (and the *.json ) to some of the backups, but doesn't work.
Thanks

**Comment by Varstahl** [comment]
Looks like a connection error of sorts. I was stupid enough not to wrap an exception handler around it (that part of the code was supposed to be temporary until I reworked the stuff a bit, it's sitting there from 3 years, untouched). If you want to know what exactly is giving issues, you can temporarily patch resources/lib/proxy.pd, line 243, and change this:
```py
        content = json.loads(content)
```
into this:
```py
        try:
            content = json.loads(content)
        except Exception:
            Log('[PS] Invalid response received:\nHTTP {}\n{}\n\n{}'.format(status_code, '\n'.join(headers), content))
            return
```
If you do and try again, in the logs there should be a bunch of stuff (possibly cookies and credentials you might need to remove from the log), but should also contain the server's response, to know what exactly didn't work.

**Comment by empanadablues** [comment]
Thank you very much! You make great job guys!
I edited the $HOME/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py, and then tried again but I probably missed some additional step, because I would bet that the log output is identical tah before: same number of lines, no credentials...
[This is the "new" log](https://drive.google.com/file/d/16EJoBqtBN57Df8mm1TpVVEMYsNRHetWh/view?usp=sharing).
Thanks again!

**Comment by Varstahl** [comment]
yeah, that didn't trigger, so either you didn't reload kodi or you concatenated the two. if it shows:

```py
        content = json.loads(content)
        try:
            content = json.loads(content)
```

then it won't work

**Comment by empanadablues** [comment]
I missed the kodi restart. I didn't think it was necessary.
So I'm back with a new log...but I don't find too much information. Up to you :-D
[kodi_2.log](https://drive.google.com/file/d/1iD-uwRWnPYdkV7Lu5rTkaOCDa8jgVxTn/view?usp=sharing)

**Comment by Varstahl** [comment]
![403 Forbidden](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fdigitalsynopsis.com%2Fwp-content%2Fuploads%2F2016%2F12%2Fhttp-status-codes-dogs-403.jpg&f=1&nofb=1)

You don't have access to amazon's servers. Either your Prime subscription expired, or possibly there's some problems with the cookies. In the addon connection options there an entry that allows you to reset your cookies, and then you can log in again with the addon.

The addon itself works, but Amazon is not responding to your requests.

**Comment by empanadablues** [comment]
Thank you very much! It was like you said: log in again and it's working perfecly again.
Thanks again for this great work!

**Comment by Varstahl** [comment]
Np, glad you got it fixed :)
