### ISSUE TITLE
TLS 1.0 not necessarily working with recent requests/urllib3

### ISSUE THREAD

**Issue by emerald79** [Sandmann79/xbmc#589]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Intel(R) Core(TM) i3-3220T CPU @ 2.80GHz
- OS version: Gentoo (amd64), python 3.9.6
- Kodi version number: 19.0

**Upload Logs**

Kodi 19.0 log entry:

`Error reason: HTTPSConnectionPool(host='na.api.amazonvideo.com', port=443): Max retries exceeded with url: /cdp/usage/v2/GetAppStartupConfig?deviceTypeID=A28RQHJKHM2A2W&deviceID=<...>&firmware=1&version=1&format=json (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1145)'))) (SSLError)
`

**Describe the bug**

The `MyTLS1Adapter` class in `network.py` needs an additional line for TLS 1.0 to actually being available, otherwise the system may only accept tls 1.2 and higher (maybe python 3.9 change?)
```
context.minimum_version = ssl.TLSVersion.TLSv1
```
Adding this line to the adapter makes it work.

I'm not in-depth with Kodi, python and the request/urllib3 packages that I'm sure it won't break anything by unconditionally adding the line.

**Comment by ErnstNeger** [comment]
> **Addon used**
> 
> * [x]  Amazon VOD (plugin.video.amazon-test)
> * [ ]  Browser Launcher (plugin.program.browser.launcher)
> 
> * Addon version:
> 
> **Account type**
> 
> * [ ]  primevideo.com
> * [x]  amazon.(com/co.uk/de/jp)
> 
> **System Setup (please provide the following information):**
> 
> * Hardware: Intel(R) Core(TM) i3-3220T CPU @ 2.80GHz
> * OS version: Gentoo (amd64), python 3.9.6
> * Kodi version number: 19.0
> 
> **Upload Logs**
> 
> Kodi 19.0 log entry:
> 
> `Error reason: HTTPSConnectionPool(host='na.api.amazonvideo.com', port=443): Max retries exceeded with url: /cdp/usage/v2/GetAppStartupConfig?deviceTypeID=A28RQHJKHM2A2W&deviceID=<...>&firmware=1&version=1&format=json (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1145)'))) (SSLError) `
> 
> **Describe the bug**
> 
> The `MyTLS1Adapter` class in `network.py` needs an additional line for TLS 1.0 to actually being available, otherwise the system may only accept tls 1.2 and higher (maybe python 3.9 change?)
> 
> ```
> context.minimum_version = ssl.TLSVersion.TLSv1
> ```
> 
> Adding this line to the adapter makes it work.
> 
> I'm not in-depth with Kodi, python and the request/urllib3 packages that I'm sure it won't break anything by unconditionally adding the line.

After installation, I initially had the exact same log entries in kodi.log as you when trying to login from the plugin itself. I could work around it as described [here](https://github.com/Sandmann79/xbmc/issues/591#issuecomment-1006118901). Maybe this helps you as well.

**Comment by Sandmann79** [comment]
Fixed with 69da66d2949ae6bf3b3e63c33ffe0ff4012de242
