### ISSUE TITLE
Amazon TLD Login Exceptions

### ISSUE THREAD

**Issue by Liqianyu** [Sandmann79/xbmc#591]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 
0.9.4

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:Shield TV Pro 2019
- OS version:8.2.3
- Kodi version number:19.2

**Upload Logs**

[kodi.log](https://paste.kodi.tv/iqimiyoxof.kodi)
[avod-login.log](https://paste.kodi.tv/ejuzoratok.kodi)
[avod-login-si.log](https://paste.kodi.tv/ogemehekul)
[avod-login-mfa.log](https://paste.kodi.tv/gefayoluta)

**Describe the bug**

Full clean install. Login to US TLD. most logins will prompt "Unknown Error, please enable advanced debugging in settings and check avod-login.log/avod-login-si.log/avod-login-mfa.log". In a few cases, the verification code window can appear, but an exception will occur if the login is successful.
I have tried to replace network.py in the web_api_tld branch, and it has the same exception.

**Comment by sat2050** [comment]
I changed from auto to roe Europe and it works for me. Running 19.3 on gentoo system.

**Comment by ErnstNeger** [comment]
> I changed from auto to roe Europe and it works for me. Running 19.3 on gentoo system.

I had to do the same thing in Switzerland (connected via VPN to Germany as the account is German) and do the login from the settings as mentioned [here](Linux kodi 5.10.90-1-rpi-ARCH #1 SMP Wed Jan 5 14:52:56 UTC 2022 armv7l GNU/Linux).

Running Kodi 19.3 on Archlinux (Linux kodi 5.10.90-1-rpi-ARCH #1 SMP Wed Jan 5 14:52:56 UTC 2022 armv7l GNU/Linux).

**Comment by Sandmann79** [comment]
Fixed with 69da66d2949ae6bf3b3e63c33ffe0ff4012de242
