### ISSUE TITLE
Include IMDB TV for Library Export

### ISSUE THREAD

**Issue by RW1986** [Sandmann79/xbmc#596]
**Addon used**
- [X ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [ X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Amazon Fire Cube
- OS version: Unknown (Latest?)
- Kodi version number: 19.3

**Upload Logs**

**Describe the bug**

With Amazon introducing IMDB TV, they have shifted a bunch of movies and shows over to it from Prime Video. IMDB TV content **DOES** play inside the add-on, although it shows up as paid content (orange titles) and cannot be exported. Since IMDB TV is just a free part of the Prime Video service, would it be possible to have it be allowed to be Exported to Library? As I say, they play fine in the add-on. Thank you.

**Comment by Sandmann79** [comment]
Support has been added for a long while. Closing.
