### ISSUE TITLE
plugin.video.amazon-test: Playing multiple episodes in a row via "play from here" works, but FullscreenVideo loses focus after every episode

### ISSUE THREAD

**Issue by axbmcuser** [Sandmann79/xbmc#6]
Hi,

Playing multiple episodes in a row via "play from here" works basically, but FullscreenVideo loses focus after every episode.

Test:
- Open Contextmenu on fist episode
- Select "play from here"
- Episode finishes, Addon leaves Fullscreen Mode, starts next episode
- Playing of next episode continues in the background

Thanks! :)

**Comment by Sandmann79** [comment]
Should be fixed with Commit 99c4ab8683326f7047fe81db34e26dcada5e42c4.

**Comment by axbmcuser** [comment]
Quick test confirms: It's fixed. Many thanks.
