### ISSUE TITLE
Amazon VOD error during login in Xbian

### ISSUE THREAD

**Issue by bhaskarndas** [Sandmann79/xbmc#600]
[

**Addon used**
- [x ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.18.3+matrix

**Account type**
- [ x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 2
- OS version: Xbian latest 4
- Kodi version number: Matrix 19.3

**Upload Logs**

After installation when I configure and provide login credentials I receive Amazon VOD error. It doesn't allow to sign in.

**Comment by Varstahl** [comment]
Upload the full debug logs somewhere and post the link here, without it we can't help you.

**Comment by bhaskarndas** [comment]
added the logs

**Comment by bhaskarndas** [comment]
> Upload the full debug logs somewhere and post the link here, without it we can't help you.

https://drive.google.com/file/d/1B4qS9i0hDQJareydhtFFsW4bw6xfNbVK/view?usp=sharing

**Comment by Varstahl** [comment]
```
 INFO <general>: [Amazon VOD] getURL: https://na.api.amazonvideo.com/cdp/usage/v2/GetAppStartupConfig?deviceTypeID=A28RQHJKHM2A2W&deviceID=44ae018262ccbf27ab1a40da86ccf6e8d6415c436d795e8d6fe9eb0a&firmware=1&version=1&format=json
ERROR <general>: [Amazon VOD] Error reason: HTTPSConnectionPool(host='na.api.amazonvideo.com', port=443): Max retries exceeded with url: /cdp/usage/v2/GetAppStartupConfig?deviceTypeID=A28RQHJKHM2A2W&deviceID=44ae018262ccbf27ab1a40da86ccf6e8d6415c436d795e8d6fe9eb0a&firmware=1&version=1&format=json (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1123)'))) (SSLError)
```

#589
