### ISSUE TITLE
primevideo.py error - You might be unable to access the service: check the website www.primevideo.com for more information.

### ISSUE THREAD

**Issue by ErnstNeger** [Sandmann79/xbmc#602]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4+matrix.1

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 3 Model B Rev 1.2
- OS version: Linux kodi 5.10.90-1-rpi-ARCH # 1 SMP Wed Jan 5 14:52:56 UTC 2022 armv7l GNU/Linux
- Kodi version number: [kodi-rpi 19.3-3](https://archlinuxarm.org/packages/armv7h/kodi-rpi)

**Upload Logs**

Here's the [kodi.log](https://paste.kodi.tv/oyuhoqikoc.kodi) of me trying to start the addon _three_ times.

**Describe the bug**

The options of the addon state that I am logged in (to my German account). I use a VPN to tunnel to Germany (confirmed using DNS Leak Test that the DNS is _not_ leaking). I checked the IP address using iplocation.net and it shows a server in Germany. I tried three different servers from my provider (NordVPN) to make sure that this particular server is not blacklisted, none of them change the behaviour of the addon (the VPN servers all are okay and I can connect properly).

I tested on Windows using the official NordVPN app that the Prime account is okay and I used that _very same_ VPN server for my openvpn connection in ArchLinuxARM to make sure that I did not by coincidence use a blacklisted server.

I honestly have no idea where to start looking. This setup worked roughly half a year ago before my SD card died, so _theoretically_ it should _not_ be connected to using a VPN.

I'm happy for any help. Thanks and regards.

**Comment by ErnstNeger** [comment]
I tried again to start the plugin, each time using another location in the _connection_ settings, still the same error message popping up and the [kodi.log](https://paste.kodi.tv/) is not being very helpful (to me).

What made me suspicious however is the fact that both `[Amazon VOD] network.py` and `[Amazon VOD] primevideo.py` are connecting to _https://www.primevideo.com_. IMHO this should _not_ be the case as if I connect there (after using NordVPN's official app on Windows 10 to connect to a German server), I will be redirected to _https://www.amazon.de_. Is the website the addon is trying to reach dependent on the location setting?

I tested on Windows using the official NordVPN app that the Prime account is okay and I used the _very same_ VPN server for my openvpn connection in Kodi to make sure that I did not by coincidence use blacklisted servers.

**Comment by ErnstNeger** [comment]
After trying again several times to start the plugin (each time using different locations in the _connection_ settings), I figured out that apparently I'm catching [this](https://github.com/Sandmann79/xbmc/blob/5f8e5a57a1f5b7adc988b826ac9cdfd3bc43283a/plugin.video.amazon-test/resources/lib/primevideo.py#L412) exception in _primevideo.py_ (creating the log entry `[Amazon VOD] primevideo.py:420 Unable to parse the navigation menu for primevideo.com` in my [kodi.log](https://paste.kodi.tv/vinawepize.kodi)).

This made me  look a bit closer and I saw that both `[Amazon VOD] network.py` and `[Amazon VOD] primevideo.py` are connecting to https://www.primevideo.com. IMHO this should not be the case as if I connect to that site (after using NordVPN's official app on Windows 10 to connect to a German server), I will be redirected to https://www.amazon.de. Shouldn't the website the addon is trying to reach be depending on the location setting or my account respectively?

**Comment by Sandmann79** [comment]
To log in from abroad, it is best to disable the VPN, because Amazon blocks some IPs. In the settings, select the correct country (Germany) and save the settings. Then log in. 
During the further use of the addon, the VPN should be enabled again.

The primevideo.com error should never appear with a German account, because here the amazon.de website is used.

**Comment by Gemini88** [comment]
Ok, I have a US account and it seems like Amazon changed the way you access primevideo.com

**Comment by Sandmann79** [comment]
@Gemini88 but with a us account you should usually have registered or logged in to amazon.com and not primevideo.com? Or am i wrong?

**Comment by Gemini88** [comment]
Right 💯 but I am logged in amazon changed the way you access primevideo.com marketing it no longer primevideo.com. now it's a redirect you the url I provided its the same on any platform you try to access when putting in primevideo.com

**Comment by Sandmann79** [comment]
If you have a DE/JP/UK or US account you will always be redirected from primevideo.com to the corresponding amazon.TLD url. All other users use primevideo.com. This is the reason why the addon distinguishes between TLD and PV accounts and performs a location detection before logging in. 

In my opinion, this has not changed recently.

**Comment by Gemini88** [comment]
It wasn't like that before when you typed primevideo.com you went directly to primevideo.com no need for a redirect amazon just changed the way you access this was a problem before even amazon said themselves they just switched url to just redirect to go through Amazon.com not primevideo.com standalone unless I missed something

**Comment by Gemini88** [comment]
Or maybe your right its something else as if I don't have prime which I do

**Comment by Gemini88** [comment]
@Sandmann79 it's fixed now using the 0.9.5 beta3 everything works flawless thanks brother much appreciated

**Comment by Gemini88** [comment]
Just that purchases are not showing up

**Comment by Sandmann79** [comment]
Did you tried a refresh via context menu at parent folder? 
You can also clear the catalogue cache at addon settings > PrimeVideo.

If this not help open a new issue with the associated logs.

**Comment by Gemini88** [comment]
Ok thanks brother will do forgot about the context refreshing, and did not clear the catalogue will try that as well🙌
