### ISSUE TITLE
no HD res with Amazon VOD

### ISSUE THREAD

**Issue by Lazar81** [Sandmann79/xbmc#604]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: R5 2600x, GTX 1080, 16GB RAM, 500GB M.2 
- OS version: Windows 11
- Kodi version number: 19.3

**Upload Logs**

**Describe the bug**

Hello,
I am new here and hope everything filled in correctly. I didn't put in a log because after some research it looks ok - this seem to be no bug and the addon is working correctly. But I only can playback Amazon streams in SD (960x400max). After reading some threads here I found a hint how to bring back the HD streams. Some additional lines have to be filled in to the network.py - this was back in 2018. Can this still be used as workaround to get HD streaming? 
Greets and sry if a log is needed to - you tell me and I will provide it.

--------
Edit: I just read a more recent thread here and if I got it right, there is no way to get back hd or fhd. Hope I misunderstood that.

**Comment by Varstahl** [comment]
Not on a PC. The only way (for the moment) to watch it in FHD is through our support of browser ([see here in the documentation](https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon-test#browser)), which will launch the browsers in full screen mode with the video you specify in Kodi. I'm unsure whether the feature that would allow FHD playback in Kodi has been developed yet, I've been out of the loop for a while now, a little over a year ago.

**Comment by luizoti** [comment]
> Not on a PC. The only way (for the moment) to watch it in FHD is through our support of browser ([see here in the documentation](https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon-test#browser)), which will launch the browsers in full screen mode with the video you specify in Kodi. I'm unsure whether the feature that would allow FHD playback in Kodi has been developed yet, I've been out of the loop for a while now, a little over a year ago.

What is the name of the resource under development?

**Comment by Gemini88** [comment]
I have np streaming in FHD definitely tinkle around with the inputstream adaptive addon settings the browser launcher is not needed any longer on any platform that Kodi is running on change the min/max bitrate and definitely tick ignore display resolution also tick override HDCP 2.2 status and make sure "manually choose stream" is ticked as well if that doesn't work you may have a underlying problem. On a 2 note UHD has never worked on my platform "android" but that maybe a limitation on from the addon and or how Amazon actually delivers its 4K content, I get 4K through the official app with np

**Comment by maxoku** [comment]
@Gemini88 Override HDCP **2.2** status? I don't have **2.2** in there. Was there an update that changed that or something?

**Comment by Gemini88** [comment]
@maxoku it should be in the "inputstreamadaptive" addon settings in Kodi brother

**Comment by maxoku** [comment]
@Gemini88 I know where it is, that's not what I'm asking. I'm asking about that number in the setting.

**Comment by luizoti** [comment]
The crunchyroll addon plays at 1080p without problems, but I don't remember if it uses adaptive inputstream, Disney gets to 720 and Amazon below that, but I don't remember how much.

I have enabled dhcp override and other options for testing, but I believe the issue will remain with service restrictions.

**Comment by Gemini88** [comment]
Ok thought you didn't my bad that version has to do with your tv more so for copy right protection to be able to playback 4K/4K HDR if your tv's HDMI port is not HDCP 2.2 that option won't do anything unless the addon Amazon uses that which it should but overrides the HDCP 2.2 status making the addon not search for that for HDCP  "handshake" and just playback 4K/FHD

**Comment by maxoku** [comment]
@Gemini88 What tv? We're talking about pc here and HD/FHD, not 4K.

**Comment by Gemini88** [comment]
@maxoku Bruh HDCP 2.2 has to do with your HDMI port and that setting I've explained to you what that is for HDCP 2.2 is for 4K mainly we all know HD/FHD is the topic (hence the op) I specifically explained what that setting is and what it does in inputstream adaptive settings for you asking about HDCP status pls stop making it seem like idu what I'm explaining or that you don't know why I'm mentioning something. If you did know you would know that it wouldn't matter if a tv or pc its HDMI port SPECIFICALLY This makes me feel like this is exactly why your not understanding something that maybe simple bruh. Do you know what you need or what your actually asking help for.

**Comment by maxoku** [comment]
@Gemini88 Yeah, you said that HD/FHD would work on pc. It doesn't for me. I'm asking about the "Override HDCP **2.2** status" setting, cuz I don't have it, I have "Override HDCP status" without that **2.2**. And I still don't get what HDMI port have anything to do with it? I don't play videos through a HDMI port.

Oki, this whole explanation is a mess and about stuff that I don't need apparently. Do you know how can I watch HD/FHD on my laptop or not?

**Comment by Gemini88** [comment]
Are you concerned with knowing what it is or just that you don't have it
