### ISSUE TITLE
"Stream Stalled" error lagging stream with recent wivdevine

### ISSUE THREAD

**Issue by laclaro** [Sandmann79/xbmc#605]
Hello,

only recently I experience errors with the plugin: Streams are not playing smoothly (also low-res streams) and frequent buffering and stuttering occurs. This is a new problem with the recent wivdevine.

Other addons, which use inputstream (and also DRM streams?) like CastagnaIT/Netflix do not show this problem.

1. Platform: Raspberry Pi 4, OSMC Debian, Kodi 19
2. Wivdevine Version unknown (error occured for the first time after the wivdevine update Jan 14, 2022)
3. Recent Amazon VOD Addon, installed by the Kodi Matrix Addon Repo
4. I use a prime video account with username/password. I was strangely asked to give my credentials again after the last update.

PS: This person seems to have the same problem: https://forum.kodi.tv/showthread.php?tid=349255&pid=3079384#pid3079384

Extended log on starting a stream:
[stream_stalled_error_netflix.txt](https://github.com/Sandmann79/xbmc/files/7875882/stream_stalled_error_netflix.txt)

Best regards,

Henning

**Comment by aschiller2** [comment]
I had the same problem (using OSMC with Kodi 19.3 on RPi3 as well as Libreelec with Kodi 18.9 on RPi3).

Replacing .kodi/cdm/libwidewinecdm.so with an older version (and rebooting) did the trick.

**Comment by gwutz** [comment]
stupid question but where do i get an older version :)

**Comment by aschiller2** [comment]
> stupid question but where do i get an older version :)

There is an option on the addon Inputstream Adaptive to restore Widevine. If you have got no backup, I could send you my libwidewinecdm.so via PN

**Comment by fumo88** [comment]
> I had the same problem (using OSMC with Kodi 19.3 on RPi3 as well as Libreelec with Kodi 18.9 on RPi3).
> 
> Replacing .kodi/cdm/libwidewinecdm.so with an older version (and rebooting) did the trick.

I had the same problem, reverting to a previous widevine version solved it!
I had to check settings in the InputStream *helper* plugin and found that by default it keeps the last 4 versions downloaded.
Thanks a lot guys!

I hope that the problem can be solved for future versions of widevine

**Comment by rogerioronin** [comment]
> There is an option on the addon Inputstream Adaptive to restore Widevine. If you have got no backup, I could send you my libwidewinecdm.so via PN

Please send libwidewinecdm.so via PN to me?

**Comment by fnordson** [comment]
I'd be interested in a libwidewinecdm.so also.

**Comment by Haifirion** [comment]
I'm in need of the previous libwidevinecdm.so too

**Comment by fnordson** [comment]
I managed to find it. 
curl https://k.slyguy.xyz/.decryptmodules/widevine/4.10.2252.0-linux-armv7.so | sudo tee /home/osmc/.kodi/cdm/libwidevinecdm.so >/dev/null

**Comment by michelesr** [comment]
On the Raspberry OS (ex Raspian) this issue started when updating from Buster to Bullseye (and so from Kodi Leia to Matrix). This seemed to help in my case (even though haven't tested it thoroughly):

```
sudo apt install libwidevinecdm0
cp /opt/WidevineCdm/_platform_specific/linux_arm/libwidevinecdm.so libwidevinecdm.so ~/.kodi/cdm/libwidevinecdm.so
```

**Comment by fabpolli** [comment]
I had the same problem on Rpi 4 with Libreelec and Kodi 19 Matrix, reverting to a previous widevine version solved it!
On first Rpi InputStream helper had 4 backup and was simple to revert. On second Rpi with newer and fresh installation i had no backup so I simple copied libwidevinecdm.so from first Rpi to second one.

**Comment by kmehtab** [comment]
I cannot play anything on my mobile can someone help me
![2022-02-10 10 09 25](https://user-images.githubusercontent.com/36443737/153338351-2b7c12c3-2c9a-4b2b-b98f-2eefeab92a4d.jpg)
![2022-02-10 10 09 32](https://user-images.githubusercontent.com/36443737/153338364-48189f07-124e-4fc5-8a92-4472b4fa33ad.jpg)
.

**Comment by kmehtab** [comment]
> I cannot play anything on my mobile can someone help me ![2022-02-10 10 09 25](https://user-images.githubusercontent.com/36443737/153338351-2b7c12c3-2c9a-4b2b-b98f-2eefeab92a4d.jpg) ![2022-02-10 10 09 32](https://user-images.githubusercontent.com/36443737/153338364-48189f07-124e-4fc5-8a92-4472b4fa33ad.jpg) .

here is the log
[kodi.log](https://github.com/Sandmann79/xbmc/files/8038359/kodi.log)

**Comment by Blaimi** [comment]
see also https://github.com/xbmc/inputstream.adaptive/issues/877.

**Comment by mrengy** [comment]
Per [this earlier comment](https://github.com/Sandmann79/xbmc/issues/605#issuecomment-1030715692)

> curl https://k.slyguy.xyz/.decryptmodules/widevine/4.10.2252.0-linux-armv7.so | sudo tee /home/osmc/.kodi/cdm/libwidevinecdm.so >/dev/null

resolved this same issue for me. This is crucial for getting playback to work smoothly on a Raspberry Pi 3B. Would be really helpful to roll this old version of Widevine into the default setup and avoid having to change the file manually. Or at least, it would be helpful to put these instructions in the readme. Without this, video is basically unviewable.

**Comment by blacklaboratory** [comment]
> I managed to find it. `curl https://k.slyguy.xyz/.decryptmodules/widevine/4.10.2252.0-linux-armv7.so | sudo tee /home/osmc/.kodi/cdm/libwidevinecdm.so >/dev/null`

I can't manage to find the proper command for the same problem but with a rpi3b+ libreelec 10.0.2 under Kodi 19.4 instead of OSMC.. can someone help please ?

**Comment by Sandmann79** [comment]
Widevine related and stale. Closing
