### ISSUE TITLE
Stuttering/buffering videos on Pi3B+ 

### ISSUE THREAD

**Issue by chewiiie** [Sandmann79/xbmc#606]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4+matrix.1

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 3B+
- OS version: OSMC 2021.12-1
- Kodi version number: 19.3
- Amazon VOD 0.9.4+matrix.1 from Sandmann79’s repo

**Upload Logs**
https://pastebin.com/NU4TbRZX
Playing a random tv show episode at 12:11

**Describe the bug**
I just installed the Amazon VOD plugin on my Pi 3B+ running the last version of OSMC, with everything up-to-date. Unfortunately, the player seems to be buffering all the time, the video and audio are jerky. CPU usage is very high.
I can play perfectly fine highres videos from my NAS or in the Youtube extension, so it’s not a wifi/bandwidth issue.
On the other hand, I have the same extension running fine on another Kodi 19.3 but running on a Windows 10 PC.

**Comment by Varstahl** [comment]
I'm unable to tell if 6MB/s per chunk is enough, but in any case iirc users used to have problems with PrimeVideo on RPi 3 and lower, due to the heavy duty needed by the video decoding. You could try to cap the maximum resolution or bandwidth within InputStream Adaptive for a quick test.

The video seems to run fine in Kodi, so at that point it's between Kodi/IS.A/Network, we don't control videos past that point.

**Comment by chewiiie** [comment]
I already tried to decrease the resolution in the Inputstream Adaptive
settings, even to 480p, and that didn't change anything.
But if I change the Media Played setting to Video only, then the video is
perfectly smooth, no buffering issues anymore.


Le lun. 17 janv. 2022 à 20:45, Bruno Passeri ***@***.***> a
écrit :

**Comment by gwutz** [comment]
Have the same problem. Especially i had no problem on Kodi 18 with the python2 addon.

**Comment by chewiiie** [comment]
I just solved my issue by downgrading the version of widevine to 4.10.2252.0
