### ISSUE TITLE
virus detected in zip file dowload

### ISSUE THREAD

**Issue by dangr58** [Sandmann79/xbmc#61]
Hello Sir,
my pc antivirus, antivir, found a trojan tr/Rogue.762277 in the zip file download (xbmc-master.zip)
and on www.antivirus.com the zip file is positive 11/62

I am not understand why

**Comment by Sandmann79** [comment]
The reason for this is the userinput.exe file, which contains an AutoIt script for controlling mouse and keyboard events. 
It's needed to set full-screen window and enter the pin for age restricted videos at playback with browser on windows based machines.
If you don't use this feature or OS, you can safely delete this file.
The source code is located here: https://github.com/Sandmann79/xbmc/blob/master/tools_addon/userinput.au3

**Comment by ammgws** [comment]
This non-issue seems to be creating a lot of noise in the issue tracker.
Would you be open to a PR which reimplements the Windows mouse/keyboard events using pywin32 or pyautogui? I imagine that it would not trigger any AV, and while it would introduce a Python dependency, it would remove the external dependency for AutoIt.
