### ISSUE TITLE
Problem with TV show "Reacher"

### ISSUE THREAD

**Issue by haakeitc** [Sandmann79/xbmc#610]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4+matrix.1

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Prozessor	Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz, 3600 MHz, 2 Kern(e), 4 logische(r) Prozessor(en) 16GB
- OS version: Version	10.0.19044 Build 19044
- Kodi version number: 19.3.0

**Upload Logs**
https://www.dropbox.com/s/j1qj16mozj9ocsm/kodi.reacher.log?dl=0

**Describe the bug**
+ navigate to the tv show "reacher season 1" --> no episodes are shown inside Amazon VOD
(export the series to local library --> episodes are  shown in kodi tv shows as *.strm files)
+ play episode 1 from *.strm file --> kodi freezes

Actually I exported the show earlier, so this does not come in the debug log.
Tv show "Sherlock" plays correctly inside the addon.
My system has no issues otherwise.

Thanks!

**Comment by Kaesarx83** [comment]
Can also confirm this happens for me. Still on Kodi 18 with a different spec PC; I can get the details if it helps but it really seems to be something specific to the "Reacher" series as I've not seen it happen with any others. The episodes do show/work when using a native (TV) prime app.

**Comment by Sandmann79** [comment]
This issue is related to #607. For more information please read on there.
Closing this.
