### ISSUE TITLE
Amazon VOD: Crash when hardware acceleration is enabled

### ISSUE THREAD

**Issue by maxoku** [Sandmann79/xbmc#611]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Laptop
- OS version: Windows 8.1
- Kodi version number: 19.3 Matrix x64

**Upload Logs**

https://www.dropbox.com/s/jty4ugtl6z4kn2z/kodi.log?dl=0

**Describe the bug**

Kodi crashes when I try to play video with hardware acceleration enabled with integrated video card. It doesn't do that with local files or other stream services.
I can play videos with hardware acceleration when if I use dedicated graphic card or with hardware acceleration disabled. That isn't the solution though, cuz it takes more CPU usage.

**Comment by Sandmann79** [comment]
Not addon releated. Closing
