### ISSUE TITLE
Amazon VOD: Stops responding when H.265 codec is enabled

### ISSUE THREAD

**Issue by maxoku** [Sandmann79/xbmc#612]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Laptop
- OS version: Windows 8.1
- Kodi version number: 19.3 Matrix x64

**Upload Logs**

https://www.dropbox.com/s/ipwaedgdmh6sj5j/kodi%202.log?dl=0

**Describe the bug**

When I enable the setting "Use H.265 Videocodec" none video plays. It's loading infinitely and Kodi is taking 40% of my CPU. Can't close it then and have to kill the process.

**Comment by Sandmann79** [comment]
This feature is only available on supported devices. In my test it worked only on Widevine L1 certified hardware, but it can work on others too. 
So it's not a real addon issue.

**Comment by maxoku** [comment]
Then it should be stated on which devices it works or be just inactive where it does't work. If there is an option that works (can be enabled) and nowhere is stated where it will work then the user assumes that the function should work.

**Comment by Sandmann79** [comment]
It's already mentioned at the [features section]( https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon-test#features) and it makes no sense to disable it by default for some platforms as far as we know where it works.

**Comment by maxoku** [comment]
I'm sorry, but it's not clear enough. I don't know what are Widevine L1 devices, so it doesn't tell me anything.
