### ISSUE TITLE
Unknown error at login

### ISSUE THREAD

**Issue by Adiventure** [Sandmann79/xbmc#613]
**Addon used**
- [X ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4+matrix.1

**Account type**
- [ ] primevideo.com
- [X ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: AMD Desktop
- OS version: Windows 10
- Kodi version number:19.3

**Upload Logs**

https://pastebin.com/emEiZ3HD
https://pastebin.com/ZGRiHeEy
https://pastebin.com/PEtEePER
https://pastebin.com/PViBL3Kh

**Describe the bug**

Unable to login. Upon entering username and password I receive an unknown error directing me to reference the logs. Once, in the course of troubleshooting I received a captcha prompt, however that was the only time. This had occurred before when I first tried the addon, however I gave up. This is a new attempt with a fresh Kodi install.

Thanks

**Comment by Sandmann79** [comment]
Should be related to #608
Try Beta 3 from here: https://github.com/Sandmann79/xbmc/issues/608#issuecomment-1045953050

**Comment by Adiventure** [comment]
> Should be related to #608 Try Beta 3 from here: [#608 (comment)](https://github.com/Sandmann79/xbmc/issues/608#issuecomment-1045953050)

That appears to have resolved the problem. Thank you.

I assume when this release goes live I'll have to uninstall the beta and reinstall from the repo?

**Comment by Sandmann79** [comment]
This is not necessary. The addon is updated automatically.
