### ISSUE TITLE
Unable to sign in to Amazon

### ISSUE THREAD

**Issue by mrengy** [Sandmann79/xbmc#614]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4 Matrix

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 3B
- OS version: OSMC 2021-12-1
- Kodi version number: 19.3

**Upload Logs**

[Kodi.log](https://pastebin.com/Cz3W4jJC)
[avod-login-si.log](https://pastebin.com/zXHRRCBq)

**I looked for avod-login.log and avod-login-mva.log but could not find them.** Under the directory "/home/osmc/.kodi", all I see (when showing hidden files) is:

1. addons
2. avod-login-si.log
3. media
4. .smb
5. system
6. temp
7. userdata

**Describe the bug**

Currently when I try to sign in to Amazon, I get stuck on the OSMC logo.
![osmc-logo](https://user-images.githubusercontent.com/2223603/155827875-a91e1ffd-caad-4a3a-a3f5-9e11b6af18d8.jpeg)

When I try to sign in to Amazon, I get "Unknown error, please enable advanced debugging in settings and check avod-login.log/avod-login-si.log/avod-login-mfa.log"

**Comment by Sandmann79** [comment]
The attached log isn't very helpful, there are no addon related entries not even a start attempt to find. 

Advanced logging can be enabled at addon settings > miscellaneous.

**Comment by mrengy** [comment]
I uninstalled the beta version and installed addon version 0.9.4 Matrix and enabled advanced logging (thanks for the instructions on where to find that). Updated logs: 

[Kodi.log](https://pastebin.com/Cz3W4jJC)
[avod-login-si.log](https://pastebin.com/zXHRRCBq)

Also, I looked for avod-login.log and avod-login-mva.log but could not find them. Under the directory "/home/osmc/.kodi", all I see (when showing hidden files) is:

    addons
    avod-login-si.log
    media
    .smb
    system
    temp
    userdata


I updated the original issue with all of the above.

**Comment by Sandmann79** [comment]
With 0.9.4 login doesn't work for TLD users. You have to install the beta again. 
Download it from here: https://github.com/Sandmann79/xbmc/issues/608#issuecomment-1045953050.

**Comment by mrengy** [comment]
Thanks. I was able to log in with the beta version this time. Not sure what was different. Maybe I was just more patient and waited longer for login to complete. ;)

-- 
Mike Eng
Pronouns: he/him
www.mike-eng.com
www.linkedin.com/in/mikeeng401
