### ISSUE TITLE
Unable to use or login into Amazon Prime Addon

### ISSUE THREAD

**Issue by Chissper** [Sandmann79/xbmc#615]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: raspBerry 4
- OS version: Libreelec 9.2.8
- Kodi version number: 

**Upload Logs**

[avod-login.log](https://github.com/Sandmann79/xbmc/files/8156650/avod-login.log)

**Describe the bug**

Same issue as in #550 decribed. Tried the options;

> Try to update the [Soupsieve addon](https://mirrors.kodi.tv/addons/leia/script.module.soupsieve/) to 1.9.6+leia.1. If this not help downgrade BS4 to 4.6.2 from [here](https://mirrors.kodi.tv/addons/leia/script.module.beautifulsoup4/) and disable automatic updates.

but nothing helped. 

Any ideas what may help?

Thank you in advance!

**Comment by Sandmann79** [comment]
Nope, same issue as in #608 .
Installing beta3 from [here](https://github.com/Sandmann79/xbmc/issues/608#issuecomment-1045953050) should fix this issue.

**Comment by bassman56** [comment]
Thanks, the beta is working :-)
