### ISSUE TITLE
"Automoto la chaine" Channel not present in the menu

### ISSUE THREAD

**Issue by vinceducat** [Sandmann79/xbmc#616]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version:  1.0.1 matrix 0.9.4 ?

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: OSMC Vero4 K+
- OS version: 2021 12 .
- Kodi version number: 19.1

**Upload Logs**

**Describe the bug**

i subsrib at "Automoto La chaine" French TV but i m unable to find it in the menus....

**Comment by Sandmann79** [comment]
Stale issue. Closing.
