### ISSUE TITLE
Unable to play item - playback error

### ISSUE THREAD

**Issue by mrengy** [Sandmann79/xbmc#617]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.5 beta 3

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**

    Hardware: Raspberry Pi 3B
    OS version: OSMC 2021-12-1
    Kodi version number: 19.3

**Upload Logs**

[kodi.log](https://pastebin.com/ug0W94s4)

**Describe the bug**

I recently installed the beta version and tried to play a tv series on Amazon. Got directed to add some other required add-on from a Google CDN (Crowdvine?), and that completed, then I saw an error in the UI that playback failed for the item and to check the logs. Hit OK and tried to play it again and got the same error. I haven't been able to play anything successfully yet - just tried that one item.

**Comment by Sandmann79** [comment]
There are no playback specific entries in the log.
Btw. the avod-login* logs are only needed in case of login problems.

**Comment by mrengy** [comment]
Mysteriously I didn’t get the error again after a restart. Thanks for the addon!
