### ISSUE TITLE
upgrade to LE10 and Amazon VOD dependency problems

### ISSUE THREAD

**Issue by tkocou** [Sandmann79/xbmc#618]
**Addon used**
- [X ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [ X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: RPi 4, 8GB
- OS version: LibreElec OS 10.0.1
- Kodi version number: 19.3

**Upload Logs**

**Describe the bug**

Amazon VOD addon has dependency issues. I did some research on the issue. The Amazon VOD addon is dependent on the "Soup Sieve and BeautifulSoup" modules and both have dependency issues with xbmc.python. Soup Sieve is looking for xbmc.python version 2.26.0. BeautifulSoup is looking for xbmc.python version 2.25.0. Both modules claim that the xbmc.python dependency in not being met.

**Comment by Varstahl** [comment]
Long story short: you have installed a wrong dependency, possibly through another repository, and that needs to be cleaned up. The BeautifulSoup3 provided by our repository has soup sieve integrated in it, not as an external dependency. Also, the [-matrix](https://github.com/Sandmann79/xbmc/releases/tag/Repository) repo only has py3 dependencies. If you need help with that, you can find for similar closed issues here on GitHub, the process has been explained in detail multiple times.

**Comment by tkocou** [comment]
The BETA version fixed the login issue. Thank you.
