### ISSUE TITLE
no playback possible on ARM devices (License update not successful)

### ISSUE THREAD

**Issue by RobbesU** [Sandmann79/xbmc#62]
Hi Sandman, 
As of tonight Amazon Prime has stopped playing. 
Flashes up 'VOD error' with error msg "One or more items failed to play. Check the log for more info..."
But cannot see anything in the (Kodi system) log.
Was fine yesterday, Kodi is good (can play youtube), Amazon account is good (can play elsewhere).

Any suggestions?

Vielen Dank.

**Comment by consulion** [comment]
Hi
Same issue here - however, the logs show:

23:04:31.766 T:1204806400  NOTICE: Creating InputStream
23:04:31.930 T:1515025152  NOTICE: [Amazon] Player Starting: 0.0/0.0
23:04:32.810 T:1204806400   ERROR: Interface_Filesystem::get_property_values - invalid data (addon='0x473f0ec8', file='0x47316de0')
23:04:33.252 T:1515025152  NOTICE: [Amazon] Player Caching: 0.0/0.0
23:04:33.252 T:1515025152  NOTICE: [Amazon] Player Resuming: 0.0/0.0
23:04:33.253 T:1515025152  NOTICE: [Amazon] Codec: Samplerate:0 Channels:I()R(1)
23:04:34.868 T:1204806400   ERROR: AddOnLog: InputStream Adaptive: Unable to find license;hdcpEnforcementResolutionPixels in JSON string
23:04:34.868 T:1204806400   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
23:04:34.868 T:1204806400   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
23:04:34.870 T:1204806400   ERROR: CVideoPlayer::OpenInputStream - error opening [https://d1l0nb3g075aoz.cloudfront.net/dm/2$-KMwuKNJa_7DAA7PPefFNnejsrA/67b1/529f/c6e7/4a43-9fa9-14a76cf91909/861cff58-80c3-4ac0-ae97-bb74891397ed_corrected.mpd]
23:04:34.871 T:1204806400  NOTICE: CVideoPlayer::OnExit()

**Comment by sindbard** [comment]
I also have the same Problem.
At yesterday the Plugin worked properply

**Comment by jbond47** [comment]
Updating Widevine library solved this for me on LibreELEC (community): 8.90.2 (S905.arm) with KODI Leia 18.0-ALPHA1 Git:4e01f3d.
Source: https://www.kodinerds.net/index.php/Thread/44211-Release-Amazon-Prime-Instant-Video/?postID=439060#post439060

Script to extract updated widevine library from Chromebook recovery image:
``` bash
#!/bin/bash
curl -s https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.conf | grep -A 12 'Acer Chromebook R13' | grep -o 'https.*' | xargs curl | zcat > /tmp/image.bin
mkdir /tmp/chromeos
MOUNTCMD=$(fdisk -l /tmp/image.bin 2> /dev/null | grep 'bin3 ' | awk '{print "mount -o loop,ro,offset="$2*512" /tmp/image.bin /tmp/chromeos"}')
echo $MOUNTCMD
$(sudo $MOUNTCMD)
cp /tmp/chromeos/opt/google/chrome/libwidevinecdm*.so .
sudo umount /tmp/chromeos
rmdir /tmp/chromeos
rm /tmp/image.bin
```
Note: This script does not run on LibreELEC. I used Ubuntu to extract the files and copied them to LibreELEC into folder ~/.kodi/cdm/:
```bash
LibreELEC:~ # ls -l ~/.kodi/cdm/l*
-rwxr-xr-x    1 root     root       7440588 Jan 18 13:14 /storage/.kodi/cdm/libwidevinecdm.so
-rwxr-xr-x    1 root     root       5122508 Jan 18 12:26 /storage/.kodi/cdm/libwidevinecdm.so.lastused
-rwxr-xr-x    1 root     root         67700 Jan 18 13:14 /storage/.kodi/cdm/libwidevinecdmadapter.so



```

**Comment by NuxRo** [comment]
Those .so do not work on the Rpi3 & LE (just to spare time should someone else feel tempted to try).
Also tried the .so from a Samsung image from the same forum thread, no go, it just crashes LE.

**Comment by Sandmann79** [comment]
That's actually a common issue on ARM devices with old widevine library. 
I've added the inputstream helper script with commit 5a59d53ef5276be0a980fef369f63b27f4352d94, which should download and install the newest library automatically (it does the same like the script, which @jbond47 posted above).
But it didn't work on RPi's at the moment on all other ARM devices it should working.

**Comment by RobbesU** [comment]
Thank you Sandmann,
Sorry to ask but do you mean "But it [still] doesn't work on RPi's at the moment.."

If so, then it sounds like RPi's are not the best platform for this job. ;-/

**Comment by Sandmann79** [comment]
Until last week it worked for RPi's running Libreelec 9 Millhouse Builds. Then changed Amazon anything, so we had to update the widevine library to a newer version. And this version doesn't work for now.
 
But the Kodi devs working on a solution.

**Comment by RobbesU** [comment]
**Super**. Wir warten gespannt !
  (ps: My German is just good enough to follow the kodinerds.net thread and get 99% of it, but sometimes miss key detail  ;-)   )

**Comment by agschaid** [comment]
@RobbesU could you point me towards that kodinerds thread.

(German is my mothers-tongue. So feel free to ask me about that 1% ;) )

**Comment by agschaid** [comment]
thx!

**Comment by Sandmann79** [comment]
Starting with Milhouse LE Build 207 this issue has been fixed for Rpi

**Comment by RobbesU** [comment]
Super. (Having followed kodinerds.net it looks like it wasn't all that straightforward)
Danke!

**Comment by thetruemachine** [comment]
I have done everything, in my RP2, it does not work.

**Comment by RobbesU** [comment]
Try the detailed instructions at
https://robbesshed.blogspot.co.uk/2017/12/watching-amazon-prime-using-raspberry.html?m=1

Mine was working again fine last night.

Sent from my phone.
