### ISSUE TITLE
Amazon VOD doesn't play video since few days (widevine?)

### ISSUE THREAD

**Issue by cpassuel** [Sandmann79/xbmc#620]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: v0.9.4 (and v0.9.5~beta3)

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 4
- OS version: LibreElec 9.2.8
- Kodi version number: 18.9.0

**Upload Logs**

Here is an extract of kodi.log [https://paste.kodi.tv/idexufepir.kodi](https://paste.kodi.tv/idexufepir.kodi)

**Describe the bug**

Since few days (less that one week) I have an error when I try to play a video. I tried both the official version and the v0.9.5~beta3. From the log it may be related to widevine.

**Comment by 1023660** [comment]
Same for me on:

Raspberry Pi 3+
Kodi 18.9
Libreelec 9.2.8

**Comment by stefano-salari** [comment]
I have the same error here, noticed just yesterday, with same plugin version. I tried to upgrade to version 0.9.4.1 but with no result.

Here my kodi.log extract with plugin version 0.9.4.1 (the line number in the exceptions are slightly different, hope it can help): [Kodi.log](https://github.com/Sandmann79/xbmc/files/8239379/Kodi.log)

The rest of the setup is quite similar: LibreElec 9.2.8 with Kodi 18.9.0 but everything runs on a Raspberry 3 +.

 I'm available to provide further info, should you need it.

**Comment by 1023660** [comment]
I also tried the ...beta3. And tried to update Widewine in Inputstream Helper, which is not possible.

**Comment by Sandmann79** [comment]
This issue is causes by inputstream helper, look here for a solution:
https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/495

**Comment by stefano-salari** [comment]
Thanks a lot, that worked fine for me.

**Comment by cpassuel** [comment]
It worked for me too. Thanks

**Comment by fpusersuggest** [comment]
I checked that fix but it's non-sense. I mean the fix should be a line 73 susbstitution with **return content.decode("utf-8")** but that line already exist.
My problem is that I click on the movie title and it try to load without success. No errors. Just it stay on loading.
Any help would be very apreciated.
Thanks.

**Comment by fpusersuggest** [comment]
also I have upgraded script.module.inputstreamhelper to the latest version: v0.5.10 
ok I try to reinstall widevine beucase I installed it with the old version of script.module.inputstreamhelper
Thanks

**Comment by fpusersuggest** [comment]
reinstalled widevine but does not work. I click on the movie title, start wheel for loading and nothing.

**Comment by sb9x** [comment]
i have the same problem with amazon vod, since the last widewineupdate.
i had opened an issue in "input stream adaptive"
[https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/518](url)

i have restored to an earlier version of widewine, but it doesnt solve the problem (i had also rebooted the pi). i am using the latest release of libreelec (nightly). all versions input stream adaptive and input stream helper are installed. 

here is my debug log: 
[http://ix.io/3Ywp](url)

**Comment by Sandmann79** [comment]
No addon issue, closing
