### ISSUE TITLE
Amazon VOD alphabetically order instead of default

### ISSUE THREAD

**Issue by mkaflowski** [Sandmann79/xbmc#622]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Shield
- OS version:
- Kodi version number: 19.4

**Upload Logs**

**Describe the bug**

When I select some category like "Recently added" I get movies sorted alphabetically instead of default order (by date in that case). I t works good when I use it as widget.

**Comment by Varstahl** [comment]
As of 0.9.5 defaults to same order as the website.
