### ISSUE TITLE
Prime video error 

### ISSUE THREAD

**Issue by trentjw** [Sandmann79/xbmc#624]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:
- OS version:
- Kodi version number:

**Upload Logs**

**Describe the bug**

Won't log into prime video says to check website prime video for more info nothing shows up on Amazon

**Comment by Varstahl** [comment]
This is late as hell, but try installing this [beta version](https://github.com/Sandmann79/xbmc/blob/web_api_tld/packages-py3/plugin.video.amazon-test/plugin.video.amazon-test-0.9.4.1%2Bmatrix.1.zip).
