### ISSUE TITLE
amazon.nl  ???

### ISSUE THREAD

**Issue by tvthiel** [Sandmann79/xbmc#631]
Hi, I have a valid and paid Amazon Prime account on amazon.nl. The plugin does not let me choose the TLD where my Amazon Prime account is and I think that's the reason why I can't login. Am I missing something, or is it not possible to log in with other TLD's than .com...???

**Comment by Varstahl** [comment]
All the europeans are served through `primevideo.com`. From there the user is transparently redirected to whatever amazon decides the user should login from.

**Comment by Varstahl** [comment]
I pushed a new update that should fix the login issue. It should pop up on your Kodi at max in a few hours, version 0.9.5. See if that fixes the issue on your end, otherwise I need to investigate.

**Comment by LuisMayo** [comment]
As an amazon.es user I'm having problems too.

After login Kodi is just loading for a really long time. After that, a form with email, password and a captcha is shown. Filling this form repeats the process (showing me the same form again)
