### ISSUE TITLE
Turn on HDR cause lose high-bitrate audio

### ISSUE THREAD

**Issue by Liqianyu** [Sandmann79/xbmc#634]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:Shield TV 2019 Pro
- OS version:9.1.0
- Kodi version number:20 Alpha 2

**Upload Logs**

**Describe the bug**

With HDR10+ turned on, I noticed that the audio was only DD+ 192Kbps. 
If it is SDR, it has two audio tracks of DD+ 192 and 640Kbps.
Is this some kind of limitation of Prime Video? Add-On Technical limitations?
Can someone confirm Dolby Vision?

**Comment by Liqianyu** [comment]
I tested it using another movie that has an Atmos track.
I found that under SDR, without Atmos, DD+ has 192, 440, 640 Kbps.
If HDR is turned on, the audio track becomes DD+ and Dolby Atmos.
Waiting for my return for further testing.

**Comment by Liqianyu** [comment]
@StollD 
I have set the stream selection type of I.S.A to Manual OSD, Manual stream selection mode Audio/Video streams.
I think this should show all the streams provided by mpd ?

I would like to try your plugin.video.tmsp-amazon, but an error occurs when I login, details are as follows
`07-18 18:40:02.421 22001 23191 E Kodi    :                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tmsp-amazon/default.py", line 13, in <module>
07-18 18:40:02.421 22001 23191 E Kodi    :                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tmsp-amazon/resources/lib/auth.py", line 55, in login
07-18 18:40:02.421 22001 23191 E Kodi    :                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tmsp-amazon/resources/lib/api/login.py", line 100, in login
07-18 18:40:02.421 22001 23191 E Kodi    :                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tmsp-amazon/resources/lib/api/login.py", line 83, in get_form_inputs`

I wonder if it's because my account username is empty?
https://github.com/Sandmann79/xbmc/issues/516

**Comment by StollD** [comment]
That could be. I never intended my plugin to be widely used, so the login code is not very sophisticated.

**Comment by Liqianyu** [comment]
By capturing the Apple TV data, it looks like Amazon is also only offering DD+ (E-AC3) 192Kbps at the highest in tvOS, in addition to HE-AAC 32\64,AAC-LC 128Kbps.
Next time I look at Dolby Atmos...

**Comment by Sandmann79** [comment]
This should have been fixed with v0.9.9. Closing.
