### ISSUE TITLE
Widget inhalt

### ISSUE THREAD

**Issue by ghost** [Sandmann79/xbmc#638]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:
- OS version:
- Kodi version number:

**Upload Logs**

**Describe the bug**

Ich nutze fire tv stick 4k maxx
Mit kodi 18.9

Also ich weis nicht ob das ein fehler ist oder nicht aber wenn ich ein widget erstelle von amazon vod dann wird der inhalt nie aktualliesiert. Ich muss das widget dann neu machen um neuen inhalt zu bekommen. Ist das normal oder woran könnte das liegen?

**Comment by jiminorris** [comment]
I also have this issue. Not every time, so sometimes Kodi seems to pull chached data, but sometimes it pulls new. 

 Amazon VOD (plugin.video.amazon-test)
 amazon.(com/co.uk/de/jp)

    Hardware: HTPC
    OS version: Linux (Debian Testing)
    Kodi version number: 20.1
