### ISSUE TITLE
Amazon US Web API Error

### ISSUE THREAD

**Issue by Liqianyu** [Sandmann79/xbmc#639]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.5

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:Shield TV 2019 Pro
- OS version:9.1.0
- Kodi version number:20 Alpha 2

**Upload Logs**

https://paste.kodi.tv/zozokobinu.kodi

**Describe the bug**

When accessing Amazon's US site with the Web API feature turned on, most menus would error out or indicate that no data was returned.
And a few days ago, there was no such problem. Currently there is no problem on Amazon UK site. So this could be caused by a change in the US site?

**Comment by Varstahl** [comment]
This is late, but are you still experiencing these issues?
