### ISSUE TITLE
Error while logging in

### ISSUE THREAD

**Issue by Daredevil1092** [Sandmann79/xbmc#649]
An error has been occurred while logging in.. please if someone know what's wrong and how to solve it.. 

![Capture](https://user-images.githubusercontent.com/112254137/189470491-a08567cf-b03f-4e13-8272-9ea1618716bd.JPG)

**Comment by ragnos** [comment]
I'm having the same issue on PC. It still works on my FireTV stick.

[avod-login.log](https://github.com/Sandmann79/xbmc/files/9701340/avod-login.log)
