### ISSUE TITLE
"Use H.265 Videocodec" option gone

### ISSUE THREAD

**Issue by pachulo** [Sandmann79/xbmc#651]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.5+matrix.1

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Xiaomi Box S
- OS version: Android 9
- Kodi version number: 19.4

**Describe the bug**
[There use to be an option in the addon to use the H.265 codec](https://github.com/Sandmann79/xbmc/commit/36c1d9d0cbad51e037378c616f973b9e3e7bfa85), but I can't find it anymore.

Thanks a lot!

**Comment by Sandmann79** [comment]
In the next addon version 0.9.7 the h265 codec will be used automatically if available and supported by the device.
