### ISSUE TITLE
Error when trying to log in

### ISSUE THREAD

**Issue by Llianeubd** [Sandmann79/xbmc#66]
Hello,
I get the following error on Kodi when trying to enter my credentials. It lets me enter my email address and my password, I then get "Unknown Error, please enable advanced debugging in settings and check avod-login.log/avod-login-si.log/avod-login-mfa.log"
How can I solve this?
Many thanks!

**Comment by Sandmann79** [comment]
Just enable advanced debugging at add-on settings, then login and upload the resulting login log files here. This files are located at Kodi's profile folder.

**Comment by unixgod94** [comment]
I am getting a similar problem but it tells me to check the log. Looking at the kodi.log in ~/.kodi/temp/ I am getting..

```20:42:16.798 T:1837102000  NOTICE: [Amazon VOD] {'mode': 'LogIn'} 
20:42:43.694 T:1837102000   ERROR: /home/pi/.kodi/addons/plugin.video.amazon-test/default.py:1669: UserWarning: gzip transfer encoding is experimental!
                                              br.set_handle_gzip(True)
20:42:43.695 T:1837102000  NOTICE: [Amazon VOD] Connect to SignIn Page 5 attempts left
20:43:11.573 T:1837102000   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: timestamp out of range for platform time_t
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.amazon-test/default.py", line 2558, in <module>
                                                exec mode + '()'
                                              File "<string>", line 1, in <module>
                                              File "/home/pi/.kodi/addons/plugin.video.amazon-test/default.py", line 1747, in LogIn
                                                cj.save(CookieFile, ignore_discard=True, ignore_expires=True)
                                              File "/usr/lib/python2.7/_LWPCookieJar.py", line 89, in save
                                                f.write(self.as_lwp_str(ignore_discard, ignore_expires))
                                              File "/usr/lib/python2.7/_LWPCookieJar.py", line 75, in as_lwp_str
                                                r.append("Set-Cookie3: %s" % lwp_cookie_str(cookie))
                                              File "/usr/lib/python2.7/_LWPCookieJar.py", line 35, in lwp_cookie_str
                                                time2isoz(float(cookie.expires))))
                                              File "/usr/lib/python2.7/cookielib.py", line 99, in time2isoz
                                                year, mon, mday, hour, min, sec = time.gmtime(t)[:6]
                                            ValueError: timestamp out of range for platform time_t
                                            -->End of Python script error report<--
20:43:11.935 T:1837102000 WARNING: CPythonInvoker(28, /home/pi/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/pi/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE 
```
this is on a raspbian 8 (jessie) rpi3  using the RetroPie image.

**Comment by unixgod94** [comment]
I went into settings and disabled cookies and just had it store credentials for now... that seems to be working.. just the cookie part thats broken

**Comment by Varstahl** [comment]
That looks like a problem with the standard library, you can see that it's caused inside the `cookielib` module. Possibly a bug on the raspbian port.

**Comment by Sandmann79** [comment]
This error was also reported from libreelec and android. Looks like it has something to do with the cookie time stamp, it has another format then before. But investigating on smartphone is a little bit difficult, so i can look deeper at the earliest next week.

**Comment by Varstahl** [comment]
I've searched a bit trying to understand @unixgod94's problem, but the only things I found were troubles with cookielib dating as far back as 2013, where they stated that the only thing that fixed the problem was a complete reinstall of libreelec. Whatever this is, it doesn't appear to be a new issue.

Some claim that is LWP causing problems, and by using another cookie jar, like Mozilla, the problem solves itself.

Since I've changed the Amazon VOD getURL method in the primevideo fork, switching from urllib2 to requests (for connection pooling, keep-alive and session management), we could in theory extract it from there and use the builtin cookiejar from requests, that should solve the problem too once and for all.

**Comment by Carter9304** [comment]
Contributing, I hope this helps. I'm on a RPI3 with Debian Stretch, Kodi 17.6 updated today. Getting the error after entering email and password, see log below.

22:08:37.205 T:1911558144   DEBUG: ------ Window Deinit (DialogKeyboard.xml) ------
22:08:37.205 T:1911554816   DEBUG: CAnnouncementManager - Announcement: OnInputFinished from xbmc
22:08:37.205 T:1911554816   DEBUG: GOT ANNOUNCEMENT, type: 128, from xbmc, message OnInputFinished
22:08:38.942 T:1711821568   DEBUG: https://www.amazon.com
22:08:40.721 T:1911558144   DEBUG: Previous line repeats 1 times.
22:08:40.721 T:1911558144   DEBUG: ------ Window Init (DialogKeyboard.xml) ------
22:08:40.727 T:1911554816   DEBUG: CAnnouncementManager - Announcement: OnInputRequested from xbmc
22:08:40.727 T:1911554816   DEBUG: GOT ANNOUNCEMENT, type: 128, from xbmc, message OnInputRequested
22:08:43.488 T:1743778560   DEBUG: PushCecKeypress - received key a7 duration 0 (rep:0 size:0)
22:08:43.488 T:1743778560   DEBUG: PushCecKeypress - added key a7
22:08:43.497 T:1911558144   DEBUG: OnKey: 167 (0xa7, obc88) pressed, action is Down
22:08:43.685 T:1743778560   DEBUG: PushCecKeypress - received key a7 duration 197 (rep:0 size:0)
22:08:43.685 T:1743778560   DEBUG: PushCecKeypress - ignored key a7
22:08:45.197 T:1743778560   DEBUG: PushCecKeypress - received key  b duration 0 (rep:0 size:0)
22:08:45.198 T:1743778560   DEBUG: PushCecKeypress - added key  b
22:08:45.214 T:1911558144   DEBUG: OnKey: 11 (0x0b, obc244) pressed, action is Select
22:08:45.385 T:1743778560   DEBUG: PushCecKeypress - received key  b duration 188 (rep:0 size:0)
22:08:45.385 T:1743778560   DEBUG: PushCecKeypress - ignored key  b
22:08:45.621 T:1911558144   DEBUG: ------ Window Deinit (DialogKeyboard.xml) ------
22:08:45.621 T:1911554816   DEBUG: CAnnouncementManager - Announcement: OnInputFinished from xbmc
22:08:45.621 T:1911554816   DEBUG: GOT ANNOUNCEMENT, type: 128, from xbmc, message OnInputFinished
22:08:45.751 T:1711821568   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.prime_instant/default.py", line 1499, in <module>
                                                index()
                                              File "/home/pi/.kodi/addons/plugin.video.prime_instant/default.py", line 107, in index
                                                loginResult = login()
                                              File "/home/pi/.kodi/addons/plugin.video.prime_instant/default.py", line 1124, in login
                                                elif signoutmatch[0].strip() != "null":
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
22:08:45.795 T:1711821568    INFO: Python script stopped
22:08:45.796 T:1711821568   DEBUG: Thread LanguageInvoker 1711821568 terminating
22:08:45.803 T:1911558144   ERROR: GetDirectory - Error getting plugin://plugin.video.prime_instant/
22:08:45.804 T:1911558144   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.prime_instant/) failed

**Comment by Sandmann79** [comment]
@Carter9304 the addon you're using is from this source: https://github.com/liberty-developer/plugin.video.prime_instant

**Comment by robustini** [comment]
Excuse me if I list my problem which is similar I think, I do not open another issue for this.
It has always worked flawlessly, and has not logged in for about two weeks.
I append the logs, version 0.9.4.1-matrix.1 (CoreElec).
Thanks for this awesome plugin!

[avod-login-pollingform.log](https://github.com/Sandmann79/xbmc/files/8412441/avod-login-pollingform.log)
[avod-login.log](https://github.com/Sandmann79/xbmc/files/8412439/avod-login.log)
[avod-login-mfa.log](https://github.com/Sandmann79/xbmc/files/8412440/avod-login-mfa.log)

**Comment by Sandmann79** [comment]
You should check your payment method:
![IMG_20220408_160521](https://user-images.githubusercontent.com/4076968/162452506-d0f78120-c73a-4700-86f6-77ea87866505.jpg)

**Comment by robustini** [comment]
> You should check your payment method: ![IMG_20220408_160521](https://user-images.githubusercontent.com/4076968/162452506-d0f78120-c73a-4700-86f6-77ea87866505.jpg)

Damn, thanks!
