### ISSUE TITLE
Missing subtitles from videos

### ISSUE THREAD

**Issue by ramborikk** [Sandmann79/xbmc#667]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Nvidia Shield TV
- OS version: Android TV 11
- Kodi version number: 19.3
- Plugin version: 0.9.6+matrix.1

**Upload Logs**

**Describe the bug**

The plugin is selecting wrong language when playing content. This applies to both audio and subtitles.
Both are loading the first available (looks like it is sorted by the ISO 639-1 codes alphabetically).
All the audio tracks are listed as default in kodi, so I guess the player is confused.
It is possible to change to the correct languages, but I have to do that for every movies and episodes.

Kodi is set to prefer the default audio and Norwegian subtitles.
The addon is also set to prefer Norwegian text/subtitles.

**Comment by yrp888** [comment]
Same problem here, always get non-English audio & sometimes subs despite choosing English and choosing "make default", have to change it time something plays.

**Comment by cappa758** [comment]
Same problem also on Raspberry Pi 4, Libreelec 10.0.3, Kodi 19.4, addon version 0.9.6. Despite what has been selected in Kodi preferences as default language (ita), I always get the first one in the list both for language and subtitles section.

**Comment by Kravatak76** [comment]
I have same problem on Sony Bravia with Google TV , Kodi 20 RC2 and addon last version 0.9.6

**Comment by Varstahl** [comment]
Audio management is done by Kodi, you need to select your desired language from Kodi Settings > Player > Language.

Also, original/default are not really supported, see also #122.

> Despite what has been selected in Kodi preferences as default language (ita), I always get the first one in the list both for language and subtitles section.

This shouldn't happen and can't reproduce, make sure to have properly configured the language and not subtitles by mistake.

**Comment by yrp888** [comment]
OK, so I set the preferred language for Audio and Subtitles to English, and yes now the Audio is in English, however now I don't seem to get any subtitles. Previously it'd list available subtitles, but now shows nothing.

We haven't used the Add-On a lot but I'm pretty sure the subs were there before I made these changes as, being hearing impaired, I always make sure they're on. I've only just started using Amazon Prime.

I'll fire up the TV later and check what its app does for the same shows.

**Comment by ramborikk** [comment]
Hi @Varstahl , and thank you for taking the time to reply.
I don't agree with your conclusion that this is only a kodi issue and not an addon issue.

As for the soundtrack, I've looked a bit at the code for the add-on. I am by no means a python programmer, but I do program in other languages. I have tested with the title "The Tomorrow War" as this has non-original language soundtracks that come first.

I see that a call is made to a json file first. This defines, among other things, "urlSets" which later appear to be used to retrieve the playlist to start the playback itself.
From what I observe, nowhere in the playlist file does it say which language is the original language for the soundtrack. BUT in the json response there is a value that says "defaultAudioTrackId":"en-us_dialog_0". We should be able to use this later when we start the playback to set the correct audio track since the audio tracks are marked with "en-us_dialog_0"!?

As for the subtitles, I got them working now. But you have to be very specific to choose correctly in the kodi settings for the content you want to see.
When it comes to Norwegian subtitles, we have three choices in Kodi:
Norwegian
Norwegian Bokmål
Norwegian Nynorsk
All of these do the same thing, but only define small flavors in the text. I have never seen several of these available on the same movie/dvd/bluray or similar. Norwegian is Norwegian.
This part I can agree is a kodi challenge.
I have kodi set to "Norwegian" and it works fine for all the other streaming services I have, so by changing it to "Norwegian Bokmål" I might be ruining the other services.

**Comment by yrp888** [comment]
I can confirm that the TV's Amazon Prime app can display subtitles which are missing in this add-on after I set the languages for Audio and Subtitles. There is only "English" for that language as a choice.

I think this case should be reopened.

**Comment by Varstahl** [comment]
> From what I observe, nowhere in the playlist file does it say which language is the original language for the soundtrack. BUT in the json response there is a value that says "defaultAudioTrackId":"en-us_dialog_0". We should be able to use this later when we start the playback to set the correct audio track since the audio tracks are marked with "en-us_dialog_0"!?

Yes, this is true. There are also definition for sight impaired, the metadata Amazon provides them has mostly everything. The problem is that there is no implementation in our backend to support that yet. It is possible, it *will* be possible, but it's a thing that I wasn't been able to do due to time constraints for the past couple years, possibly more.

> When it comes to Norwegian subtitles, we have three choices in Kodi:
Norwegian
Norwegian Bokmål
Norwegian Nynorsk
All of these do the same thing, but only define small flavors in the text. I have never seen several of these available on the same movie/dvd/bluray or similar. Norwegian is Norwegian.

This is straight up something I hate Kodi for. Suppose you want the spanish language, you have no way to tell Kodi between latinoamerican spanish and iberic spanish. Which are not the same at all. This is one thing I wanted to do way back when but sandman was scared that it would overcomplicate things too much.

Granted, this needs the work I mentioned in the previous post done, as it's a follow up.

> I can confirm that the TV's Amazon Prime app can display subtitles which are missing in this add-on after I set the languages for Audio and Subtitles. There is only "English" for that language as a choice.

Haven't used PrimeVideo in a while for the same lack of time, by default Kodi should display everything available, if it doesn't then possibly Amazon changed something in the background, I'll change the issue scope.

**Comment by yrp888** [comment]
> Haven't used PrimeVideo in a while for the same lack of time, by default Kodi should display everything available, if it doesn't then possibly Amazon changed something in the background, I'll change the issue scope.

Thank you for reopening, and of course thank you for all your efforts in bringing this add-on to the Kodi community.

When I first installed this add-on a few weeks ago it would display all the subtitle languages so I could choose. I suspect Amazon must have done something recently as resetting the Kodi Player languages to the default doesn't restore the subtitle list.

As someone who is hearing impaired subtitles are critical for me on any platform. It's interesting that not many others are reporting this ... either the subs are still working for them or they don't use them.

I'll try removing and reinstalling the add-on, will report back later.

**Comment by yrp888** [comment]
Just to confirm, limited testing on my 3 Kodi boxes with beta6 seems to have sorted out the subtitles, they now appear in EN automatically. 

Now that we can connect and watch we'll be able to do more checking and report back.
