### ISSUE TITLE
Question about this repo

### ISSUE THREAD

**Issue by ammgws** [Sandmann79/xbmc#68]
What is the relationship between `plugin.video.amazon-test` and `plugin.video.amazon` in this repo?
Which one should I be looking at if I want to contribute to the most recently released version?

**Comment by Sandmann79** [comment]
The  `plugin.video.amazon` add-on works only with German Amazon accounts. This one creates a database of almost all Amazon content and updates it periodically. But it can not index the complete catalog, so I added some filters. In case of this, this add-on doesn't support other countries.

**Comment by ammgws** [comment]
OK cheers. The name `test` was throwing me off.
