### ISSUE TITLE
OSMC 540p

### ISSUE THREAD

**Issue by Arndorferd** [Sandmann79/xbmc#681]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.0.4

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 4
- OS version: OSMC 2023.01-1
- Kodi version number: 19.5

**Upload Logs**

No errors

**Describe the bug**

I know HD issues are reported a lot but on pi, OSMC I can only get 540p. I see that there are other play methods but Idk if any will work on OSMC. Do you know of any work arounds because 540p makes this really unusable on modern tvs. Also is in not possible to just spoof the source so amazon believes its coming from something else?

**Comment by strugee** [comment]
> Also is in not possible to just spoof the source so amazon believes its coming from something else?

Amazon will not negotiate more than 540p with Widevine L3. Higher levels of Widevine use hardware-backed security which cannot be spoofed.

**Comment by Arndorferd** [comment]
Hey so as you may know Vero V has L1 keys burned. Have you discussed with them on implementation. @Sandmann79

**Comment by Arndorferd** [comment]
Will require [OSMC Inputstream Support](https://github.com/osmc/osmc/issues/761)

**Comment by Arndorferd** [comment]
They said this add on should not need adjusting so I'm closing this issue as it should may be solved independently in the Vero V and and cannot be solved in the Pis
