### ISSUE TITLE
Library does not recognize exported episodes

### ISSUE THREAD

**Issue by ZelKami** [Sandmann79/xbmc#682]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: v0.9.7~beta.3+matrix.1

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Fire TV Stick 4K Max
- OS version: Fire OS 7.6.3.3
- Kodi version number: 20.1

**Upload Logs**

**Describe the bug**

When exporting shows from the plugin and scanning the show folder into the library, the episodes are not recognized. This is because the file names are prepended with the show title. When removing the show title from the file and rescanning the folder, the episodes are imported into the library.

**Comment by Gemini88** [comment]
@danielerl when scanning uncheck keep tv show or show title or whatever its called (not by Kodi  rn) but uncheck it "has to do with "title"

**Comment by danielerl** [comment]
I can't find such an option. What's weird is for one show 'One Tree Hill' scanning into the library doesn't work but for another (Teen Wolf) it does. 

Also playing an episode from the library does not work (there is an Amazon VOD error) but navigating to Video Files and selecting an episode in the Amazon TV folder does work.

Here is the log
[kodi.log](https://github.com/Sandmann79/xbmc/files/11239116/kodi.log)
