### ISSUE TITLE
Widget view looks bad

### ISSUE THREAD

**Issue by jiminorris** [Sandmann79/xbmc#683]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Custom build, AMD-based HTPC. 
- OS version: Debian Testing 
- Kodi version number: 20.1

**Upload Logs**

**Describe the bug**

Amazon listings seem to have coverart in two formats; poster (1.5:1) or thumbnail (1:1.3). I think this depends on if it is a movie (poster) or TV (thumbnail) but if you use the widget view on the kodi homepage, it stretches the thumbnails to poster size and looks weird. 

[https://ibb.co/n3FXrNg]([img]https://i.ibb.co/n3FXrNg/Screenshot-20230418-195135.jpg[/img])

**Comment by Sandmann79** [comment]
In the Android data source settings, you can activate the retrieval of covers & fanart via TMDB/TVDB, which will be displayed in the correct format.
The addon has no influence on the format provided by Amazon.
