### ISSUE TITLE
Add Device

### ISSUE THREAD

**Issue by bikb** [Sandmann79/xbmc#685]
Hello,

I want to add a device for Amazon Prime Video.
I goto: "Konto & Einstellungen" then "Meine Geräte" then "Neues Gerät registrieren".
I want to display a number and add it to Amazon Account.
Are you able to generate suck a device number?

Why should this be able? Because we don't want to input account credentials an 2FA secret when a better solution is available!

TIA

Best

**Comment by Sandmann79** [comment]
Unfortunately, this is not possible with the two DeviceTypeIDs used in the add-on.

With other IDs intended for TV devices, the login with code (device pairing) would work, but not the video playback.

**Comment by bikb** [comment]
Short questions towards the advantages of pairing instead of login with credentials:
1. I assume there is stored a cookie after logging in with credentials?
2. The cookie is the only thing needed to login / stay logged in?
3. Is the cookie stored is a "special" storage? 
4. Can another App access the cookie with read permission?

You know for sure I want to make clear if another App can use the Cookie to access the whole Amazon account.
Thats no good design and I think using the pairing method has only access to movies and not the whole account.
