### ISSUE TITLE
Not showing all available episodes for a TV show

### ISSUE THREAD

**Issue by mrengy** [Sandmann79/xbmc#690]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.7 beta (I think, not 100% sure how to check this)

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 3B
- OS version: OSMC (not sure which version)
- Kodi version number: 19.3

**Upload Logs**
[Log file](https://pastes.io/9iaksz6m2s)

**Describe the bug**
I'm trying to watch Season 5 of The Marvelous Mrs. Maisel. When I go to Home > Continue Watching > The Marvelous Mrs. Maisel > Season 5, it only shows the first 3 episodes. They are the first 3 that were released when this season became available. Then Amazon has released one additional episode every week. Right now there are [6 episodes available on Amazon.com](https://www.amazon.com/Marvelous-Mrs-Maisel-Season/dp/B0B7F6XRGS). How can I get the additional episodes to be available in Kodi?
![2023-05-04_20-38-50_152](https://user-images.githubusercontent.com/2223603/236469936-e22c7c11-3654-4321-82ad-b6461b0d80b3.jpeg)

**Comment by Kampfader** [comment]
Test this.
Go to you serie, press and hold the OK button, press refresh on the context menu, see pic 
Im on german interface.

![Uploading 16832944599158848889119197703551.jpg…]()

**Comment by Kampfader** [comment]
![Uploading 16832949348212426050722556141916.jpg…]()

**Comment by Kampfader** [comment]
![IMG_20230505_155716](https://user-images.githubusercontent.com/23200748/236478389-2bcfaf4d-161f-4a7f-b986-a94b05c620ac.jpg)

**Comment by mrengy** [comment]
Danke!
That worked. 

Wow, I definitely would not have known to do that without someone explicitly giving me those instructions. Could be nice to either not have to manually refresh (like automatically refresh when navigating into a show) or otherwise make it apparent that you can do that with a “refresh” menu item if needed.

**Comment by Sandmann79** [comment]
Done with https://github.com/Sandmann79/xbmc/wiki/FAQ#why-are-some-episodes-missing

**Comment by mrengy** [comment]
Thanks for the FAQ. Personally I wouldn’t call this “resolved” with that. My issue was that I didn’t know a contextual menu existed or how to access it, and I probably wouldn’t have found my way to that FAQ on my own. Is there a way to automatically refresh the list of episodes?

**Comment by mrengy** [comment]
Also the FAQ could use more clarity on how to access the context menu and what exactly you mean by “the season view”. Screenshots could help.

**Comment by Sandmann79** [comment]
A screenshot has been added.
It was meant the season overview, this has been corrected.
The context menu is a feature in Kodi, where favorites can be created, for example. Describing access to it here would be the wrong place.
