### ISSUE TITLE
Catalog path not available error for favorites

### ISSUE THREAD

**Issue by alexgit2k** [Sandmann79/xbmc#691]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.8

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: x86_64
- OS version: Windows 10
- Kodi version number: Kodi 19.5

**Upload Logs**

[kodi.log](https://github.com/Sandmann79/xbmc/files/11507728/kodi.log)

**Describe the bug**

Since the switch to the WebAPI in 0.9.6 favorites of Amazon-series can no longer be played. The error "Catalog error: Catalog path not available" is shown and then the wheel is spinning forever.

It only works if immediately previously a search via the plugin is done for the series. Then the corresponding  favorite can be selected and played.

**Comment by Sandmann79** [comment]
Favourites from the different APIs are not compatible with each other, as each has a different folder structure.
Unfortunately, the favourites have to be created again.

**Comment by alexgit2k** [comment]
@Sandmann79 Of course I created new favorites with the new version of the AddOn. Just wanted to note that it worked with the old version without the Web-API . So please reopen the issue.

**Comment by Sandmann79** [comment]
No, it cannot work. The Favourites links have a completely different structure. 
Picard S1:
Android API: plugin://plugin.video.amazon-test/?cat=Browse&amp;mode=getPage&amp;opt=itemId%3damzn1.dv.gti.2e7bf47e-f209-42fa-a0e7-8329b1dee023&amp;page=1&amp;url=details
Web API: plugin://plugin.video.amazon-test/pv/browse/root/coll1_Startseite/%5BCOLOR+FF00A8E0%5DPrime%5B%2FCOLOR%5D+Amazon+Originals+und+Exclusives/amzn1.dv.gti.ceb7cfd7-f316-f9a9-0cbc-d63a14ac3a99/B0B683QHWC

**Comment by alexgit2k** [comment]
I understand, but as said I made a favorite when using the Web-API and then I called **this** favorite again and it did not work.

**Comment by Sandmann79** [comment]
That's right. As you can see in the link above, the complete navigation path is saved. If the menu structure changes, the series may be in a different submenu and the old path will be invalid.
The only way around this is to add Watchlist items to the Favourites. The structure rarely changes.
