### ISSUE TITLE
Widevine Extraction error

### ISSUE THREAD

**Issue by Shreyas-Alse** [Sandmann79/xbmc#694]
****
- [X ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [X ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: RPI3
- OS version: Linbreelec 10.4
- Kodi version number: 19.5

**Upload Logs**

The bug is that the widevine CDM cannot exxtract and is showing error, leaving no log. Can u plz help...

**Comment by Shreyas-Alse** [comment]
Plzzz help me..

**Comment by Varstahl** [comment]
No Kodi log provided, and your question makes no sense, care to rephrase your question? Widevine CDM cannot extract *what*? The zip file? Is it a readonly file system? And in any case if it's a O/S related error there's nothing we can do to help you, that's more of a sysad problem then an addon one.

**Comment by Shreyas-Alse** [comment]
It worked now I installed slyguy input stream helper wrapper. Thanks anyway

**Comment by Sandmann79** [comment]
Btw. that's not an Addon issue. Closed
