### ISSUE TITLE
Server return no content

### ISSUE THREAD

**Issue by inthelight12** [Sandmann79/xbmc#697]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.8

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: pi4
- OS version: libreelec 10.0.4
- Kodi version number: matrix

**Upload Logs**

**Describe the bug**

In the last week I started seeing "server returned no content" errors while navigating menus. 

log file here https://paste.kodi.tv/boxaparemo.kodi

**Comment by Gemini88** [comment]
@inthelight12 same here so something definitely changed on Amazon's end

**Comment by cow-crash** [comment]
https://github.com/Sandmann79/xbmc/issues/696
is the same issue

**Comment by cow-crash** [comment]
see https://github.com/Sandmann79/xbmc/issues/696

**Comment by Sandmann79** [comment]
Duplicate of #696.
Try the current beta from here: https://github.com/Sandmann79/xbmc/issues/696#issuecomment-1653343463
