### ISSUE TITLE
Error when selecting video to play - Amazon 0.2.7

### ISSUE THREAD

**Issue by SuperDonkey2016** [Sandmann79/xbmc#7]
Hi,

i got directly an error when I try to play a Movie/Serie.
Amazon Login - works
Showing Lists - works
Watch Movie directly in Chrome - works
Watch Movie out of the Amazon plugin - doesn't work

Here are a small dump of the error log:
[kodi_amazon_error.txt](https://github.com/Sandmann79/xbmc/files/362604/kodi_amazon_error.txt)

Couldn't figure out the problem...
If you need something in addtion, drop me an message.
Could be, that I need some days to reply.

BR
Manuel

**Comment by Sandmann79** [comment]
There is something wrong with your addon configuration. If the browser is not installed in the default location, you should enable the custom browser path setting. Sometimes this error raises, if the "Detect Framerate" setting is enabled, try to disable for testing.
In the next addon version, this error/crash should not appear anymore and display the correct error reason.

**Comment by SuperDonkey2016** [comment]
Thanks for your reply and the hint with the framerates ;-)
BUT...
I had the setting "Detect Framerate" disabled... Just for testing, I enabled it and whoom, it's working now!
Default setup/settings like described [here ](http://openelec.tv/forum/128-addons/77591-chromium-html5-guide-for-netflix-amazon-prime) and than turn on framerate detection.

![amazonvod-settings](https://cloud.githubusercontent.com/assets/20447835/18390614/2a750556-76ab-11e6-9c7f-aa26092a45c6.png)


If you'd like to get some logs, drop me a message.

Thanks & BR
Manuel

**Comment by Sandmann79** [comment]
Is the problem still present in the new version (0.2.8)? 

If so, please post a full log.

**Comment by SuperDonkey2016** [comment]
After updating to version 0.2.8 everything works as expected.
Also with turned "Detect Framerate" off, everything runs smooth.

Issue solved - ticket can be closed.

Thank you for your good work!
