### ISSUE TITLE
DOWNLOAD

### ISSUE THREAD

**Issue by lovetherisk** [Sandmann79/xbmc#70]
hi.
i need help in amazon downloader, as my bandwidth is not much fast to Watch Streaming flawlessly.
or please share contact info in pvt.
Thank You

**Comment by CGarces** [comment]
Spam? 
https://github.com/liberty-developer/plugin.video.prime_instant/issues/12

**Comment by drt420** [comment]
No it is not spam, we are very much aware about new version of wvdownloader and wvclient which is used to direct download from amazon but it is not available publicly.
We need help with direct download from amazon instead of streaming it to kodi.

**Comment by Sandmann79** [comment]
As is wrote in another issue - i don't support any kind of downloading content from Amazon for any reason whatsoever.
Closed.
