### ISSUE TITLE
No S/PDIF Audio  on libreelec 10.0.4 (kodi 19.5)

### ISSUE THREAD

**Issue by rocktobe** [Sandmann79/xbmc#701]
**Addon used**
- [0.9.9 ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: beta 3

**Account type**
- [ x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:rpi3 + Kuman SC07C Raspberry Pi HiFi Digi+ with spdif.(Soundcard)
- OS version: libreelec 10.0.4
- Kodi version number: 19.5

**Upload Logs**

**Describe the bug**

Hi guys, 
Since I have installed Libreelec 10 (kodi 19.5),
I cannot make my spdif output on my soundcard work !
It is supposed to be selected in kodi sound settings but only the PCM 2.0 or HDMI work.

As i have an old DENON amplifier without HDMI I still need to use the spdif output to get dolby digital from amazon prime !

I followed a thread on libreelec forum...Unfortunately The procedure described doesnt work for me.
I found that threat on libreelec forum :
No more audio after upgrading from LE9 to LE10 (generic x64 build).
"Audio device in LE9 was ALSA/SPDIF device with SPDIF passthrough enabled. Can no longer be selected in LE10, only PulseAudio/BlueTooth device listed (greyed out). I don't remember seeing PulseAudio/BlueTooth device there in LE9 (but I might be wrong; was definitely never used)."
https://forum.libreelec.tv/thread/24602-no-audio-or-no-remote-since-le10/

Unfortunately The procedure described doesnt work for me.
I dont find the file /storage/.config/system.d/kodi.service.
I opened a session in raspbian and I cannot edit or create the file (I dont find it either).
I understood that the only way to edit a file is via the pi console in raspbian and a sudo command.
The thing is that the file kodi.service doesnt exist in my system.d directory.
Is there another way to force KODI to add the SPDIF output?
is there another file to be edited?

Thanks in advance

**Comment by Sandmann79** [comment]
Sorry, but this is not an addon error. 
You have already posted a forum link, maybe you should ask there.
