### ISSUE TITLE
Fails when loading the root Amazon menu

### ISSUE THREAD

**Issue by DevilBlackDeath** [Sandmann79/xbmc#709]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 4
- OS version: Libreelec 11
- Kodi version number: v20.2

**Upload Logs**

[01_KODI.log](https://github.com/Sandmann79/xbmc/files/13164125/01_KODI.log)

**Describe the bug**

There's not much to report since it crashes when loading the plugin. It seems to not be able to build the root folder.

**Comment by DevilBlackDeath** [comment]
I haven't changed DNS settings on my router or on the Pi (never had the need to, just on the computer really). I'll try to see where the DNS settings are in LibreElec and change that, see if that makes a difference.

I also just did the 11.0.1 to 11.0.3 transition without trouble by downloading the update from the Pi, in LibreElec's menu. If I need to I'll resort to a clean install but I'll try to avoid it if I can.

**Comment by DevilBlackDeath** [comment]
As I expected I'm using automatic DNS settings on the Pi. My router also uses standard DNS. I've tried setting the Pi to use Google's public DNS, but it fails with the same errors (at "self.BuildRoot():" basically).

I wonder if it could be a python error as this could potentially have updated automatically but I doubt it.

Is there any "advanced" log I should enable that could give you more information ?

**Comment by Sandmann79** [comment]
Just tested it and unfortunately it is an addon error. 
Yesterday before I uploaded the stable update, there were no problems with it.

I'll take a closer look.

**Comment by DevilBlackDeath** [comment]
Ah glad to know it wasn't a mistake on my end. Thanks for looking into it :)

**Comment by AnneLaureF** [comment]
Hey,
Here is a quick fix that works for me. It isn't thoroughly tested and probably breaks some things, but it works with my account for the couple of series I am currently watching.
I made a change to the unescape function, and to the regex used to extract Json from the page.
Maybe it can help:
[network.py](https://github.com/Sandmann79/xbmc/files/13181508/network.py.txt)

**Comment by praspp** [comment]
@AnneLaureF 
It works for me! Thank you.

**Comment by Forlorn-Hope** [comment]
@AnneLaureF. 
I concur that this also work for me.  Thank you for the help.
