### ISSUE TITLE
inputstream.helper not available

### ISSUE THREAD

**Issue by CGarces** [Sandmann79/xbmc#71]
I can't use the last version of the addond.
inputstream.helper is not available on my system (Amlogix S905 device), so I can't test it on ARM.
And clue to install inputstream.helper by hand?

**Comment by Sandmann79** [comment]
So far as I know the helper works on all platforms. Try to refresh the repository manually, if this not work you can download the addon from here: https://github.com/emilsvennesson/script.module.inputstreamhelper

**Comment by Sandmann79** [comment]
Did you got it working?

**Comment by CGarces** [comment]
I haven't try. I was waiting for  new version to uninstall/install again.

**Comment by Varstahl** [comment]
@CGarces any updates?

**Comment by CGarces** [comment]
I can't see Amazon version="0.5.1", just 0.4.7

But after manual installation of 0.5.1 inputstream.helper was installed.

Now I'm fetching 2GB of Chrome OS to get one library...

Original problem solved in any case.
