### ISSUE TITLE
Can see Profile but can't go any further !

### ISSUE THREAD

**Issue by sircsaba** [Sandmann79/xbmc#712]
**Addon used**
- [ x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [x ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 4
- OS version: Raspian OS
- Kodi version number: 18.7

**Upload Logs**

**Describe the bug**

I enter the Addon and then I see my profile name. When I click on it, It just gives me a Amazon VOD error and nothing else. I haven't used this addon for quite awhile but want to use it now ... There's no WebApi for me to activate in the menus. I have searched far and wide without any luck. When I first started to fix the problem, I installed Beta 3, then Beta 5 and now Beta 7 and still no luck !
[kodi-leia.log](https://github.com/Sandmann79/xbmc/files/13192688/kodi-leia.log)

**Comment by praspp** [comment]
@sircsaba 
Install the latest version 1.0.1~beta1
[plugin.video.amazon-test-1.0.1~beta1.zip](https://github.com/Sandmann79/xbmc/files/13193700/plugin.video.amazon-test-1.0.1.beta1.zip)

**Comment by Sandmann79** [comment]
Your addon version 0.9.7b7 is outdated. Please use the current version (1.0.0) from the repo.
It is not necessary to install a beta. Version 1.0.0 from the repo corresponds to the current state on github.

**Comment by sircsaba** [comment]
I installed from the repo, as before, and I have version 1.0.0. I get the list of categories but when I try and watch something, it just turns and turns and then comes back to the list of videos. I have attached the log for this specific time.

Should I clear my credentials and start over ?
[kodi.log](https://github.com/Sandmann79/xbmc/files/13196234/kodi.log)

**Comment by Sandmann79** [comment]
You should update Widevine as requested by Inputstream Helper:
```
2023-10-28 11:53:46.314 T:1756643536  NOTICE: [script.module.inputstreamhelper] There is an update available for Chrome OS
2023-10-28 11:53:50.156 T:2972982368 WARNING: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2023-10-28 11:53:50.256 T:1756643536 WARNING: Previous line repeats 2 times.
2023-10-28 11:53:50.256 T:1756643536 WARNING: [script.module.inputstreamhelper] User declined to update Chrome OS.
```

**Comment by sircsaba** [comment]
Updated Widevine and still doesn't work. Just turns in circles and then comes back to the list. Also, my Netflix does the same thing now. Netflix was working perfectly before I updated Widevine !!
I remember awhile back that it was posted NOT to update Widevine because this would be the resulting problem ...
What else to suggest please ...
[kodi(1).log](https://github.com/Sandmann79/xbmc/files/13198451/kodi.1.log)

**Comment by sircsaba** [comment]
I reinstalled the previous Widevine and my Netflix is working but Amazon still isn't ... Any other things to try ?

**Comment by Sandmann79** [comment]
> Updated Widevine and still doesn't work. Just turns in circles and then comes back to the list. Also, my Netflix does the same thing now. Netflix was working perfectly before I updated Widevine !! I remember awhile back that it was posted NOT to update Widevine because this would be the resulting problem ... What else to suggest please ... [kodi(1).log](https://github.com/Sandmann79/xbmc/files/13198451/kodi.1.log)

The installation of Widevine was not successful. Therefore, nothing could be played with Amazon or Netflix.
```
2023-10-29 11:05:00.888 T:2006966480   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/home/pi/.kodi/cdm/libwidevinecdm.so)
```

**Comment by sircsaba** [comment]
The installation was successful when I installed it ... 

Does this newer version of Widevine work proerly with Kodi Leai and Nteflix and Amazon ?

I will give it another try !

**Comment by sircsaba** [comment]
The problem is that the system isn't able to run the ldd command as indicated in log file :

[script.module.inputstreamhelper] [u'**ldd**', u'**/home/pi/.kodi/cdm/libwidevinecdm.so**'] cmd failed

Anyone care to guess why ? Everything seems to be properly installed ...
