### ISSUE TITLE
"Amazon VOD error" message on launch

### ISSUE THREAD

**Issue by yrp888** [Sandmann79/xbmc#713]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.9-beta5

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: RPi4, NUC8
- OS version: RPi4 LibreElec 11.0.3, NUC8 LibreElec 10.03
- Kodi version number:

**Upload Logs**

**Describe the bug**

[kodi.log](https://github.com/Sandmann79/xbmc/files/13194905/kodi.log)

RPi4 was updated to Nexus, Amazon VOD 0.9.9-Beta5 was installed and worked OK. At the time the NUC was working too but on a earlier version.

A few days later the NUC came up with an error "Amazon VOD error, check the log for more information" so I cleared cache & data, same. Updated to 0.9.9-beta5, cleared the cookie and logged in again, login seemed successful but same error occurs when opening VOD.

RPi4 tested today, same error. Log from RPi4 attached, Amazon VOD starts at 18:46:45.

Maybe they changed something ... again.

**Comment by praspp** [comment]
@yrp888 
https://github.com/Sandmann79/xbmc/issues/712#issuecomment-1783575719

**Comment by Sandmann79** [comment]
It is not necessary to install a beta. Version 1.0.0 from the repo corresponds to the current state on github. Please update from the repo.

**Comment by yrp888** [comment]
Thanks for your reply, I updated two machines so far from the repo and they are pulling up the categories as normal. Waiting to download all the usual info but I'm sure it'll play just fine.

As usual, huge appreciation for all your hard work on this add-on!
