### ISSUE TITLE
screen brightens and dims

### ISSUE THREAD

**Issue by kubencki** [Sandmann79/xbmc#717]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 3, 4 and 4
- OS version: Raspberry Pi OS (Debian version: 12 (bookworm))
- Kodi version number:

**Upload Logs**

**Describe the bug**

While playing Amazon Vod videos, the screen dims and brightens. the problem only occurs on the latest raspbian os, regardless of the platform, 3, 4 or 5

**Comment by Sandmann79** [comment]
This error has nothing to do with the addon. The addon only passes the manifest to Inputstream Adaptive, which is then used for playback in Kodi. 

Either open an issue there or ask in the Rasbian forum, as it only seems to occur with the latest versions.
