### ISSUE TITLE
"REACHER" - new episodes need both caches cleared

### ISSUE THREAD

**Issue by yrp888** [Sandmann79/xbmc#719]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Intel NUC8, RPi4
- OS version: LibreElec 10.04 Matrix (NUC), LibreElec 11.0 Nexus
- Kodi version number: NUC 19.5, RPi4 20.2

**Upload Logs**

**Describe the bug**

Intel NUC - When Season 2 of Reacher was released 15 Dec with Ep1-3, all were available to watch. When Ep4 was released 22 Dec it would not appear until I cleared both caches. Clearing Catalog only was not enough, both needed to be cleared.

Same for Ep5 and Ep6 each week that followed.

RPi4 - When I ran up the RPi4 box 4 Jan which hasn't been used since 10 October, Ep1-3 were visible and both caches needed clearing as well to bring up the newer episodes, so it doesn't look like a cache expiration issue (default 12h).

**Comment by Sandmann79** [comment]
It's not necessary to clear both caches, just follow the instructions provided [here](https://github.com/Sandmann79/xbmc/wiki/FAQ#why-are-some-episodes-missing).
This is normal behavior for tv series where the episodes are not put online all at once.

**Comment by yrp888** [comment]
Thanks for your prompt response Sandmann79, I should have investigated that option first.
