### ISSUE TITLE
Use PR instead master branch

### ISSUE THREAD

**Issue by CGarces** [Sandmann79/xbmc#72]
This is a suggestion, not an issue.

Now that there are more than one developer, consider commit in a separate branch or fork and send a PR to evaluate each other changes instead of write directly to master.

This allow to discuss the changes and avoid revert commits.
Look how work for example LibreELEC, no one commit directly into master.

**Comment by Varstahl** [comment]
In regard to the revert, that was an exception and a mistake on my part on a bandaid emergency fix, which I kind of rushed considering Sandmann might want to release the new version ASAP, I take full responsibility for it.

Other than that, while you're not wrong and I perfectly agree with the concept (as I stated myself in the previous PR), LibreELEC has 240 contributors, this repo has 2 (myself included). It's not exactly the same thing.

**Comment by CGarces** [comment]
no rush was only a remained/advice
