### ISSUE TITLE
First Audiotrack selected by default

### ISSUE THREAD

**Issue by codingPF** [Sandmann79/xbmc#725]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: RP5
- OS version: Libreelec 11.0.5
- Kodi version number: 20.3

**Upload Logs**

Please let me know if required

**Describe the bug**

When starting a stream, the first audiotrack in the list is selected/used. This often turns out to be Arabic in case multiple are available...Is there any setting to preselect the proper language? I am using the API version. I did try the region "auto" and specific Germany.
Thanks for any hints

**Comment by Sandmann79** [comment]
You can change this at Kodi Settings > Player > Language > Preferred audio language

**Comment by FunctionalHacker** [comment]
Every other streaming addon on Kodi seems to at least select English audio for shows that have that as their original language without needing to tweak Kodi settings. This addon seems to select the language quite randomly by default. 

Don't know the first thing about Amazon's Api or how this addon works, but perhaps there could be some kind of a default flag available for the audio tracks?
