### ISSUE TITLE
Login error - Unknown Error

### ISSUE THREAD

**Issue by joaosagrath** [Sandmann79/xbmc#726]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version:  1.0.5+MATRIX.1

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:  AMD RYZEN 5G, 16 GB RAM, SSD KINGSTON 120GB
- OS version: Windows 10
- Kodi version number: 20.2

**Upload Logs**

[kodi.log](https://github.com/Sandmann79/xbmc/files/14040749/kodi.log)
[login.log](https://github.com/Sandmann79/xbmc/files/14040875/login.log)

**Describe the bug**

<img width="869" alt="Capturar" src="https://github.com/Sandmann79/xbmc/assets/16491360/c92782ee-9c40-44be-9217-27e58f42f537">

I'm getting this error message every time I try to log in. Login and password working correctly on the website https://www.primevideo.com/. Password does not contain special characters, only letters and numbers. I also entered the wrong password on purpose and the error was the same. My account is from Brazil.

**Comment by Sandmann79** [comment]
Strangely, this is the only country where this type of login does not work.
So far I have not noticed any difference between the login in the browser and in the addon, except that an error page is returned in the addon.

But there is still a workaround for this problem: 
Simply select Android in the settings under data source and log in. After that you can then switch back to the web data source.

**Comment by joaosagrath** [comment]
Thats It!!!!! Now its working. I think that Android option was for android users LOL. Thanks for the workaround!!!
