### ISSUE TITLE
Error switching to next episode

### ISSUE THREAD

**Issue by maltejahn** [Sandmann79/xbmc#727]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.0.5+matrix1

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Fire Stick
- OS version:
- Kodi version number: 20.2

**Upload Logs**

![Screenshot 2024-01-24 195408](https://github.com/Sandmann79/xbmc/assets/21693654/1f57c7eb-fe01-486c-9a9c-1407ac63d84f)
[Kodilog_reduced.txt](https://github.com/Sandmann79/xbmc/files/14042580/Kodilog_reduced.txt)

**Describe the bug**
So.... I installed the plugin inside Kodi which is inside a fire TV stick. It was ok for months

If I start a tv show, normaly it should show the next tv show/episode at the end of the movie. But instead I get an error like "playback not possible. general error during playback. More information in log file"

Here is the last entry.. doenst it find the next episode (ran out of input). I was running "Goliath S01E01" -> so there are more episodes to come. Also tried another tv show with the same result

> 2024-01-24 19:43:00.100 T:13684   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'EOFError'>
>                                                    Error Contents: Ran out of input
>                                                    Traceback (most recent call last):
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 664, in onPlayBackEnded
>                                                        self.finished()
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 695, in finished
>                                                        self.saveResumePoint()
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 654, in saveResumePoint
>                                                        items = self.getResumePoint()
>                                                                ^^^^^^^^^^^^^^^^^^^^^
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 643, in getResumePoint
>                                                        items = pickle.load(fp)
>                                                                ^^^^^^^^^^^^^^^
>                                                    EOFError: Ran out of input
>                                                    -->End of Python script error report<--
>

**Comment by Sandmann79** [comment]
Has been fixed with https://github.com/Sandmann79/xbmc/commit/9024d15aec4cd4c2725098fc5933b53e527f5069
