### ISSUE TITLE
Genre Lists are empty and Prime folders are gone

### ISSUE THREAD

**Issue by mikeyounge** [Sandmann79/xbmc#728]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.0.5+Matrix.1

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: GMKTek G3 NUC
- OS version: LibreElec 11.0.6
- Kodi version number: 20.3

**Upload Logs**

**Describe the bug**

Not sure if I can provide any logs that will help as I don't see any errors. But the menus that used to have all of the Prime labels are mostly gone. Also, the Genres folder loads fine with all of the different lists, but those lists are not populating. I used to have links like "plugin://plugin.video.amazon-test/pv/browse/root/coll4_Categories/Genres/tile_2/%5BCOLOR+FF00A8E0%5DPrime%5B%2FCOLOR%5D+Movies" but they don't exist anymore. Let me know if I can provide any logs or testing to help.

Thanks.

**Comment by Kenny606** [comment]
I'm in the US do using amazon.com but I'm seeing the same behavior.
I can see things in my movie watchlist but it's hit or miss on which ones play.

**Comment by Sandmann79** [comment]
Fixed with https://github.com/Sandmann79/xbmc/commit/a23002261939cded4b13e66f5587aef9571ec676
