### ISSUE TITLE
libreELEC und Rpi3

### ISSUE THREAD

**Issue by rkunschke** [Sandmann79/xbmc#73]
Hi, 
when i try to look a video the addons extracts the windevine file from the chrome image. That works perfectly good. But if i try to watch a video after that the video seems to start first (videoname and play symbol in the corner) than the screen gets black and the OS restarts. I tryed it in 480p and 720p and different settings but it makes no difference
Any ideas?

**Comment by Sandmann79** [comment]
It's the same like this #62
