### ISSUE TITLE
Impossible de lancer une video

### ISSUE THREAD

**Issue by crocketear** [Sandmann79/xbmc#730]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.0.5+matrix.1

**Account type**
- [ ] primevideo.com
- [x ] amazon.fr

**System Setup (please provide the following information):**
- Hardware: raspberry 4
- OS version: libreelec 11.0.6
- Kodi version number: 20.3

**Upload Logs**

**Describe the bug**

Bonjour, dès que j'essaie de lancer une vidéo, j ai ce message,:"
Browser or script not found.  Please check settings."
Je ne sais pas comment régler ce problème. 
Merci de votre aide.

**Comment by Sandmann79** [comment]
See here for available playback methods:
https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon-test#playback-methods

There is also a Wiki page:
https://github.com/Sandmann79/xbmc/wiki
