### ISSUE TITLE
Playback Failed: One or more items failed to play, on all videos

### ISSUE THREAD

**Issue by Forlorn-Hope** [Sandmann79/xbmc#735]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version:  1.0.5

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Intel NUC i5-8259
- OS version: LibreElec 11.0.6
- Kodi version number: 20.3

**Upload Logs**

When I attempt to play a video, I get an error that one or more items failed to play.  This happens on all videos. Even those that I watched a few days ago.

**Comment by Forlorn-Hope** [comment]
log:  https://paste.kodi.tv/osebinudas

**Comment by Sandmann79** [comment]
This is an widevine related issue. Possibly due to a failed update. Try to reinstall the widevine library.

`2024-04-19 17:51:52.464 T:919     error <general>: AddOnLog: inputstream.adaptive: Initialize: Failed to load library: /storage/.kodi/cdm/libwidevinecdm.so: wrong ELF class: ELFCLASS32`

**Comment by Forlorn-Hope** [comment]
Bless you.  It worked.  Thank you for you continued work.

 

 

From: Sandmann79 ***@***.***>
Reply-To: Sandmann79/xbmc ***@***.***>
Date: Sunday, April 21, 2024 at 7:09 AM
To: Sandmann79/xbmc ***@***.***>
Cc: Forlorn-Hope ***@***.***>, Author ***@***.***>
Subject: Re: [Sandmann79/xbmc] Playback Failed: One or more items failed to play, on all videos (Issue #735)

 

This is an widevine related issue. Possibly due to a failed update. Try to reinstall the widevine library.

2024-04-19 17:51:52.464 T:919 error <general>: AddOnLog: inputstream.adaptive: Initialize: Failed to load library: /storage/.kodi/cdm/libwidevinecdm.so: wrong ELF class: ELFCLASS32
