### ISSUE TITLE
When launching the app, get error "Amazon VOD error. Check the log for more information"

### ISSUE THREAD

**Issue by mrengy** [Sandmann79/xbmc#740]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 3B
- OS version: OSMC 2024.04-1
- Kodi version number: 20.5
grep Kodi .kodi/temp/kodi.log | head -3
2024-05-24 22:08:40.582 T:515      info <general>: Starting Kodi (20.5). Platform: Linux ARM (Thumb) 32-bit
2024-05-24 22:08:40.582 T:515      info <general>: Using Release Kodi x32
2024-05-24 22:08:40.582 T:515      info <general>: Kodi compiled 2024-04-07 by GCC 10.2.1 for Linux ARM (Thumb) 32-bit version 5.15.92 (331612)

**Upload Logs**

[Log file](https://paste.kodi.tv/enegeyodik)

**Describe the bug**

Lately every time I try to launch the Amazon VOD app, I get this error and cannot open it: "Amazon VOD error. Check the log for more information"

**Comment by Sandmann79** [comment]
You are using an outdated version. Please update to the current version 1.0.6.

**Comment by mrengy** [comment]
Thanks. I am probably doing something silly, but I can't figure out how to get version 1.0.6. 

[Repository instructions](https://github.com/Sandmann79/xbmc?tab=readme-ov-file#repository-instructions) say 

> To install this repository in Kodi, [download it from the releases](https://github.com/Sandmann79/xbmc/releases/tag/Repository) and add it via Addon Browser > Install from ZIP.


I went to [the releases page](https://github.com/Sandmann79/xbmc/releases/tag/Repository), which shows Plugin Repository v1.0.4 as the "latest" version (released Jul 24, 2016). copied the url of [repository.sandmann79.plugins-1.0.4.zip ](https://github.com/Sandmann79/xbmc/releases/download/Repository/repository.sandmann79.plugins-1.0.4.zip), used wget to download it into my Kodi home folder. From Kodi, went to "settings" > "add on browser" > "install from zip file". navigated to the zip in my home folder. Got a message saying plugin updated successfully. Restarted Kodi.

Went to "videos" > "video add-ons" > "Amazon VOD" (the menu shows "version: 0.9.7-beta3+matrix.1"). When trying to launch, I still get the error "Amazon VOD error. Check the log for more information"

**Comment by Sandmann79** [comment]
The update should be displayed if you go to the Addon Browser > Install from Repository > Sandmann79s Repository > Video Addons > Amazon VOD.
If not you have to search for Repository updates by opening the context menu at Sandmann79s Repository entry.
