### ISSUE TITLE
Audio bug?

### ISSUE THREAD

**Issue by gmjh123** [Sandmann79/xbmc#741]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.06+matrix.1
- 

**Account type*

- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Onn 4k pro
- OS version: 13
- Kodi version number: 21

**Describe the bug**

Audio has a sudden drop in volume. This is especially noticeable on shows such as Them :The Scare. E.g On episode 5 of this show at 2.04 when the scene changes from the desert back to the preacher in the church, the audio suddenly dips in volume. This happens on my soundbar, but also happens with just the TV speakers. Can someone play this particular scene on their own setup to see if there is a similar audio drop? Thanks very much. 
EDIT : this issue also occurs on Android TV and on fire stick.

**Comment by nonobio** [comment]
I just tried reading the passage you indicated: the sound also drops for me (add-on version 1.0.6+matrix.1 and Kodi 20.2 (Windows))

**Comment by OldManBrook** [comment]
Same here.

LIBREelec 11.04
Titan Bingie MOD

Tried multiple config changes Inc. Passthrough with no success.

**Comment by OldManBrook** [comment]
> Same here.
> 
> LIBREelec 11.04 Titan Bingie MOD
> 
> Tried multiple config changes Inc. Passthrough with no success.



> Same here.
> 
> LIBREelec 11.04 Titan Bingie MOD
> 
> Tried multiple config changes Inc. Passthrough with no success.

This audio defect is present in my SONY TV Amazon app as well so must be an issue at Amazon source..

Great add-on Sandmann79 🍻👍

**Comment by Sandmann79** [comment]
If the same issue also occurs in the Android app, then it is not an addon bug.
Thanks for the clarification @OldManBrook

Closing
