### ISSUE TITLE
"Content not paid" messages for some files in Amazon VOD

### ISSUE THREAD

**Issue by bstabens** [Sandmann79/xbmc#744]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.07

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi4
- OS version: XBIan 12.0 (Debian Bookworm, Kernel 6.6.31-64+ aarch64)
- Kodi version number: 21.0

**Upload Logs**
https://ufile.io/tvvsnrzd

**Describe the bug**
Some files won't be played, in this case episodes of "Elementary". The plugin reports "content not paid". At the same time with the same login on a laptop it's no problem watching this series. 
Also, an episode of Wheel of Time was played without issues on the raspbi.

**Comment by Sandmann79** [comment]
I assume that you have a German Amazon account.
Is a VPN or proxy used for playback?
Do you live near the border?

**Comment by bstabens** [comment]
Yes, sorry, it's a german account.
No VPN or proxy used.
No border close. I live on the eastern side of NRW, that's quite nicely in the middle of Germany. :)

**Comment by Sandmann79** [comment]
Sorry for the late reply.
Amazon had the series on offer twice at the time, once for free with a Prime subscription and once for a fee. This is sometimes the case with Amazon. Usually the series only differ in the number of available languages.

**Comment by bstabens** [comment]
Well, great. Gotta love them. 
Thanks for still coming back and helping me out!
