### ISSUE TITLE
No 5.1 audio tracks

### ISSUE THREAD

**Issue by nonobio** [Sandmann79/xbmc#745]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.0.7+matrix.1

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: PC
- OS version: Windows 10
- Kodi version number: 20.5

**Upload Logs**

![Amazon Kodi no 5 1 audio](https://github.com/Sandmann79/xbmc/assets/7425799/90a9f09e-115e-4467-b00e-26f990b96c91)

**Describe the bug**

I no longer have 5.1 audio tracks, only AAC 2.0 (stereo).
I noticed the problem with Lord of the Rings and then tried several films and series including The Boys.
When I first see this issue I had add-on version 1.0.6+matrix.1.

Then, I watched Bourne Identity and I was surprised to find 5.1 audio tracks 🙂 , so I tried Lord of the Rings again and I also got 5.1 🙂. The plugin was updated to version 1.0.7-matrix.1, I thought this version should had fixed the problem, even if I didn't see anything related in the changelog.

But today I just watched The Boys: no 5.1 🙁
I tested Lord of the Rings again: no 5.1 again 🙁

Do you have any idea of ​​the problem?

I also posted [on the Kodi forum.](https://forum.kodi.tv/showthread.php?tid=349255&pid=3200069#pid3200069)

Thanks

**Comment by Sandmann79** [comment]
I have now changed the manipulation of the MPD url again. This makes it possible to get DD+ sound via the Cloudfront CDN again for the time being. 
But you should keep in mind that this is just a hack that can disappear quickly.
The playback method used with non Widevine L1 devices officially only offers stereo sound.

The release commit only contains the updated archive files for the repo and no changes to the code.
The relevant commits are these:
https://github.com/Sandmann79/xbmc/commit/c59ad0043d2224d7bd129551174ee6b55aacbbd3
https://github.com/Sandmann79/xbmc/commit/f50d195f564b24843671cc3652c6d3c40952be4f

**Comment by nonobio** [comment]
Great, it works, thank you very much :)

I hope it will hold because the video is already in SD, if the audio is in stereo that's a lot ;)
