### ISSUE TITLE
Watchlist is empty

### ISSUE THREAD

**Issue by cow-crash** [Sandmann79/xbmc#747]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:Raspberry Pi 3
- OS version:libreelec 8.2
- Kodi version number:18.9

**Upload Logs**

**Describe the bug**

Since a few days i have following error.
When opening Watchlist/Both there are no entries. Neither series nor films, but i have their several entries. Has amazon changed the structure?
Please help

**Comment by Sandmann79** [comment]
Yes Amazon has tinkered a bit with the website again, should be fixed with version 1.0.9.
