### ISSUE TITLE
Navigation Change on Amazon.com

### ISSUE THREAD

**Issue by diverdeep01** [Sandmann79/xbmc#749]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: MS SURFACE
- OS version: win  11
- Kodi version number: 21.0

**Upload Logs**

**Describe the bug**

It appears as though Amazon made a change to the Navigation structure again. Now when you attempt to access the plugin it kicks back an error stating it is: Unable to locate Navigation menu for http://amazon.com/

Items added to library (exported) still work.

[kodi.log](https://github.com/user-attachments/files/16380114/kodi.log)

**Comment by cpassuel** [comment]
I have the same issue on primevideo.com on m'y Pi 4 with Libreelec 11

**Comment by dfdario** [comment]
Same here with Linux Ubuntu 20.04 / 22.04 / 24.04. Looking with my Mi BOX I've seen that starting from Jul 24th Amazon deeply changed the menus then it seems it would need more time to align this app to the new site.
