### ISSUE TITLE
"PrimeVideo Error Unable to find the navigation menu"

### ISSUE THREAD

**Issue by newbie-stack** [Sandmann79/xbmc#750]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.0.9+matrix.1

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Ugoos AM6b+ AMlogic S922X rev b
- OS version: CoreELEC (official) 21.1-Omega_nightly_20240727
- Kodi version number: 21.0.1

**Upload Logs**
[kodi.log](https://github.com/user-attachments/files/16404384/kodi.log)
[log-2024-07-28-15.41.43.zip](https://github.com/user-attachments/files/16404385/log-2024-07-28-15.41.43.zip)
[Amazon Add-On Logs.zip](https://github.com/user-attachments/files/16404395/Amazon.Add-On.Logs.zip)

**Describe the bug**
I have followed the instructions to install and log in to prime video. All that went fine. But every time I launch the add-on to watch prime, I get the above error. I have included the logs from the locations provided in the FAQs. I have also included a crash dump that was created by the OS. I am not sure if it will be of any help or not.

Please let me know if you need any further info/data to help debug this issue.

PS: This is my 1st time using CoreELEC. So please bear with me when I ask for more details to provide you the information you are requesting.

**Comment by Vichman67** [comment]
Same issue here since three days but on different system:
Raspberry Pi 5
LibreELEC 11.0.6
Kodi 20.3
Amazon VOD 1.0.9+matrix.1

Maybe Amazon has changed its web structure?

**Comment by Sturmlocke86** [comment]
Same issue here.

- Batocera 39 with Kodi preinstalled
- Kodi version: placeholder, will check tonight
- Trying to reach Amazon.de (Germany) for Prime Video

Will check out the fix linked above and report back asap. Thanks!
