### ISSUE TITLE
unable to find the navigation menu

### ISSUE THREAD

**Issue by jjplano** [Sandmann79/xbmc#752]
**Addon used**
- [ x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.0.9+matrix.1

**Account type**
- [ x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 3 model b+
- OS version: libreelec 11.0.6
- Kodi version number: 20.3

**Upload Logs**

https://paste.libreelec.tv/united-gelding.log

**Describe the bug**

since a couple of days now, I receive the message "prime video error - unable to find the navigation menu for http://www.primevideo.com."
I have not made any changes on the account, not the system. everything else works perfectly fine. I've tried logging again, restarting, reinstalling the addon and widevine, nothing works

**Comment by werimail** [comment]
as a temporary solution please look here: https://github.com/Sandmann79/xbmc/pull/751

**Comment by jjplano** [comment]
> as a temporary solution please look here: #751

I don't really understand the solution =( don't know what to do with the few sentences I see over there. english is my second language and I'm not a programmer, I just dab a little in coding and such. would love to follow instructions, if there were any

thanks for trying to help!

**Comment by dfdario** [comment]
The proposed solution works great. Thanks

**Comment by Sandmann79** [comment]
This has been fixed with 55df51a
