### ISSUE TITLE
Amazon VOD fails to play videos through Amazon Prime

### ISSUE THREAD

**Issue by jsullivan3** [Sandmann79/xbmc#753]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.1.0+matrix.1

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 4
- OS version: OSMC 2024.05-1
- Kodi version number: 20.5

**Upload Logs**

[debug-short.log](https://github.com/user-attachments/files/16488443/debug-short.log)

**Describe the bug**

Yesterday evening I was able to browse my watch list through Amazon Prime as usual, but any attempt to play a video failed with a generic error to check the logs.  The only really notable message in the log appears to be as follows:
```
2024-08-04 13:31:14.004 T:6725    error <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.amazon-test/?asin=B01MRD4HTF&mode=PlayVideo&name=The+Seven+Year+Itch&adult=0&trailer=0&selbitrate=0]
```
This issue is occurring on two OSMC devices.  I do not see any issue with other Widevine-based streaming services such as Paramount+.

Thank you in advance for any help that can offered!

**Comment by christihan66** [comment]
same problem...

LibreELEC 10.0.4
19.5-Matrix

ERROR <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.amazon-test/?asin=amzn1.dv.gti.acafd115-1b6e-33ac-9a24-a90983fdbf62&mode=PlayVideo&name=2.+Jessica&adult=0&trailer=0&selbitrate=0]
.
.
.

ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 're.error'>
                                                   Error Contents: invalid group reference 17 at position 1
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 9, in <module>
                                                       EntryPoint(argv)

Thx in advance..!!

**Comment by Sandmann79** [comment]
Sorry for the inconvenience. I made a stupid mistake with commit  195be492a42a3d211820b99e0392586c5f0c2da5 - there should have been a version heck. As a result, playback in Kodi 20 and lower is currently not possible.
I'll try to fix it as soon as possible, but I'm currently on vacation.

**Comment by NoneCreator** [comment]
Sandmann, Sandmann, you da man

**Comment by NoneCreator** [comment]
Sandmann, Sandmann, you da man, if you can't do it, noone can! :-)  
you da man though, seriously! thank you and have a good time on your vacation!!

**Comment by jsullivan3** [comment]
Thank you very much!  I just edited the playback.py file to revert this
change, restarted the mediacenter service, and confirmed that it works like
a champ.  I also hope you have an excellent vacation, and thank you for
your hard work in making this plugin available!

**Comment by jsullivan3** [comment]
**WARNING 1**:  The process here is dangerous as it involves hand-editing code.  You can break things, so please be careful!

**WARNING 2**:  This patch doesn't check versions as Sandmann79 indicated should be done.  It's a hack to get things working for Kodi 20 and earlier, if you can't wait for the fix.

I edited the file `/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py` and applied the following diff:

```
diff --git a/plugin.video.amazon-test/resources/lib/playback.py b/plugin.video.amazon-test/resources/lib/playback.py
index 855b647..528b512 100644
--- a/plugin.video.amazon-test/resources/lib/playback.py
+++ b/plugin.video.amazon-test/resources/lib/playback.py
@@ -396,6 +396,8 @@ def PlayVideo(name, asin, adultstr, streamtype, forcefb=0):
         Log('Using %s Version: %s' % (_g.is_addon, is_version))
 
         listitem = xbmcgui.ListItem(label=title, path=mpd)
+        if 'adaptive' in _g.is_addon:
+            listitem.setProperty('inputstream.adaptive.manifest_type', 'mpd')
         listitem.setArt({'thumb': thumb})
         listitem.setSubtitles(subs)
         listitem.setProperty('%s.license_type' % _g.is_addon, 'com.widevine.alpha')
```

If you're not familiar with reading `diff` files, go to line 398 which should have the line:

```
        listitem = xbmcgui.ListItem(label=title, path=mpd)
```

Then add the following two lines, making sure to use spaces for indentation, with four spaces to indent the first line and eight spaces to indent the second:

```
        if 'adaptive' in _g.is_addon:
            listitem.setProperty('inputstream.adaptive.manifest_type', 'mpd')
```

You'll need to either reboot, or since you're already on the command line you can simply restart the `mediacenter` service:

```
$ sudo systemctl restart mediacenter.service
```

Once the UI is available again, you should be able to watch videos through Amazon.

**Comment by Sturmlocke86** [comment]
+1 same issue here on Batocera V39 with Kodi V20.5. Happy vacation, Sandman! Will test the fix once it's out. Thanks!

**Comment by jsullivan3** [comment]
My pleasure - you're very welcome!  I'm sorry, though, I'm not familiar
with Android TV so I can't advise as to the nature of the problem in that
environment.

**Comment by jjplano** [comment]
same happens with Kodi 20.3

**Comment by cow-crash** [comment]
same issue with kod 19.8 8(

**Comment by cow-crash** [comment]
> **WARNING 1**: The process here is dangerous as it involves hand-editing code. You can break things, so please be careful!
> 
> **WARNING 2**: This patch doesn't check versions as Sandmann79 indicated should be done. It's a hack to get things working for Kodi 20 and earlier, if you can't wait for the fix.
> 
> I edited the file `/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py` and applied the following diff:
> 
> ```
> diff --git a/plugin.video.amazon-test/resources/lib/playback.py b/plugin.video.amazon-test/resources/lib/playback.py
> index 855b647..528b512 100644
> --- a/plugin.video.amazon-test/resources/lib/playback.py
> +++ b/plugin.video.amazon-test/resources/lib/playback.py
> @@ -396,6 +396,8 @@ def PlayVideo(name, asin, adultstr, streamtype, forcefb=0):
>          Log('Using %s Version: %s' % (_g.is_addon, is_version))
>  
>          listitem = xbmcgui.ListItem(label=title, path=mpd)
> +        if 'adaptive' in _g.is_addon:
> +            listitem.setProperty('inputstream.adaptive.manifest_type', 'mpd')
>          listitem.setArt({'thumb': thumb})
>          listitem.setSubtitles(subs)
>          listitem.setProperty('%s.license_type' % _g.is_addon, 'com.widevine.alpha')
> ```
> 
> If you're not familiar with reading `diff` files, go to line 398 which should have the line:
> 
> ```
>         listitem = xbmcgui.ListItem(label=title, path=mpd)
> ```
> 
> Then add the following two lines, making sure to use spaces for indentation, with four spaces to indent the first line and eight spaces to indent the second:
> 
> ```
>         if 'adaptive' in _g.is_addon:
>             listitem.setProperty('inputstream.adaptive.manifest_type', 'mpd')
> ```
> 
> You'll need to either reboot, or since you're already on the command line you can simply restart the `mediacenter` service:
> 
> ```
> $ sudo systemctl restart mediacenter.service
> ```
> 
> Once the UI is available again, you should be able to watch videos through Amazon.

added the two lines and all is perfect. thanx
have good vacations Sandman

**Comment by Sandmann79** [comment]
This issue has been fixed with a7abccbbf9465e04bd4980b6e03b757aec291f97.
Thanks @jsullivan3 for your support.

**Comment by christihan66** [comment]
Thank you Sandmann79..!!

**Comment by Sturmlocke86** [comment]
Thanks for the fix, worked like a charm!

**Comment by cow-crash** [comment]
thanx for fast fixing
