### ISSUE TITLE
Amazon. Login error. No credentials present

### ISSUE THREAD

**Issue by CGarces** [Sandmann79/xbmc#83]
Using version 1.9.0 installed in a clean environment after remove the old one.

On the first launch of the application I get the "Login error. No credentials present"

But while I try to login (very slow process due the limitation of my remote), some process is runing on background and  "Login error. No credentials present" popup again, going back to the settings window.

This behaviour made impossible login if you are not faster enough to set user/pasword between two login errors.

**Comment by Sandmann79** [comment]
In this case you should disable automatic update at add-on settings and restart Kodi. Now you're be able to login. 
But the Amazon add-on (without VOD in the name)  works only with german accounts.

**Comment by Varstahl** [comment]
@CGarces is this still a problem? Could you post a log if it is?

**Comment by CGarces** [comment]
I haven't test Amazon VOD again.
