### ISSUE TITLE
Error open app in kodi 18 + ubuntu 14.04

### ISSUE THREAD

**Issue by Ninoh-FOX** [Sandmann79/xbmc#85]
Hi, the add, after of screen setup, said me error and see the log file, i tried reinstall the add, but nothing, in raspberry pi work fine, but said me error when i tried see a video. How i could fix the configuration in ubuntu?

**Comment by Sandmann79** [comment]
With this error description is hard to say. 
Maybe your python version is to old.
For further assistant you need to upload the kodi.log here.

**Comment by Varstahl** [comment]
You can find the kodi.log in `~/.kodi/temp/kodi.log`.

**Comment by Ninoh-FOX** [comment]
`13:35:25.036 T:140317781538560  NOTICE: [Amazon VOD] Switching UserAgent
13:35:25.037 T:140317781538560  NOTICE: [Amazon VOD] Loading list of common UserAgents
13:35:25.046 T:140317781538560  NOTICE: [Amazon VOD] getURL: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
13:35:29.078 T:140317781538560   ERROR: /home/ninoh-fox/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              SNIMissingWarning
13:35:29.079 T:140317781538560   ERROR: /home/ninoh-fox/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecurePlatformWarning
13:35:29.229 T:140317781538560   ERROR: [Amazon VOD] Error reason: HTTPSConnectionPool(host='techblog.willshouse.com', port=443): Max retries exceeded with url: /2012/01/03/most-common-user-agents/ (Caused by SSLError(SSLError(1, '_ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))
13:35:29.229 T:140317781538560  NOTICE: [Amazon VOD] Attempt #2
13:35:29.230 T:140317781538560  NOTICE: [Amazon VOD] getURL: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
13:35:33.135 T:140317781538560   ERROR: /home/ninoh-fox/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecurePlatformWarning
13:35:33.295 T:140317781538560   ERROR: [Amazon VOD] Error reason: HTTPSConnectionPool(host='techblog.willshouse.com', port=443): Max retries exceeded with url: /2012/01/03/most-common-user-agents/ (Caused by SSLError(SSLError(1, '_ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))
13:35:33.296 T:140317781538560  NOTICE: [Amazon VOD] Attempt #3
13:35:33.302 T:140317781538560   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'string'
                                            Traceback (most recent call last):
                                              File "/home/ninoh-fox/.kodi/addons/plugin.video.amazon-test/default.py", line 3094, in <module>
                                                getUA()
                                              File "/home/ninoh-fox/.kodi/addons/plugin.video.amazon-test/default.py", line 2821, in getUA
                                                UAlist = text.string.split('\n')
                                            AttributeError: 'NoneType' object has no attribute 'string'
                                            -->End of Python script error report<--
13:35:33.578 T:140319826470912   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/
13:35:33.580 T:140319826470912   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/) failed`

**Comment by Sandmann79** [comment]
Like I wrote above - your Python version is outdated. Follow this guide to get a newer version:
https://kodi.wiki/view/HOW-TO:Upgrade_Python_interpreter_on_Linux

**Comment by Ninoh-FOX** [comment]
thanks, i tried follow the steps, but some error... I go to see more info about the python error and upgrade this. Netflix work fine, then I think that I go to correct way.

**Comment by Sandmann79** [comment]
@Ninoh-FOX is this issue still present?

**Comment by Ninoh-FOX** [comment]
Nop, I upgrade to ubuntu 16.04 (if I upgraded only python repository, the system down) and now works fine.

Now well, I see other bug in windows 10 x64, if I use kodi 18 for 64 bits systems, the wirevine helper install the dll in cdm folder, but the video playback fail (error cpythoninvoker), in changed, if I use Kodi 18 for 32 bits in a system of 64 bits, all work fine.

**Comment by Varstahl** [comment]
> Now well, I see other bug in windows 10 x64, if I use kodi 18 for 64 bits systems, the wirevine helper install the dll in cdm folder, but the video playback fail (error cpythoninvoker), in changed, if I use Kodi 18 for 32 bits in a system of 64 bits, all work fine.

Huh, strange, I use x64 Kodi on Win7, and have no such problem. Could you open another issue providing the win10 logs? I'll close this thread in the meanwhile.
