### ISSUE TITLE
Video won't play

### ISSUE THREAD

**Issue by mp-pinheiro** [Sandmann79/xbmc#87]
Hello, I've been trying to get Amazon VOD to work, I'm from Brazil, and facing this error when trying to play  "8 mile": 

22:58:08.695 T:1615369088  NOTICE: [Amazon VOD] Convert Deutsch Subtitle
22:58:08.700 T:1615369088  NOTICE: [Amazon VOD] getURL: https://dmqdd6hw24ucf.cloudfront.net/3cd3/3cff/328a/40b9-aa07-4d1cf03e0eb6/ec6121a5-ea57-42dd-beab-4538eb792c0d.dfxp
22:58:19.143 T:1615369088  NOTICE: [Amazon VOD] Convert English [CC] Subtitle
22:58:19.144 T:1615369088  NOTICE: [Amazon VOD] getURL: https://dmqdd6hw24ucf.cloudfront.net/dbdb/1bfd/602b/4628-8028-02f75a18e34f/38be3252-41f4-4322-8f72-f84c2656d68b.dfxp
22:58:32.525 T:1615369088  NOTICE: [Amazon VOD] Convert Español Subtitle
22:58:32.532 T:1615369088   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xf1' in position 24: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 3089, in <module>
                                                PrimeVideo_Browse(None if 'path' not in args else args['path'])
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 461, in PrimeVideo_Browse
                                                PlayVideo(node['metadata']['video'], node['metadata']['asin'], '', 0)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 1583, in PlayVideo
                                                playable = IStreamPlayback(asin, name, trailer, isAdult, extern)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 1707, in IStreamPlayback
                                                opt='&titleDecorationScheme=primary-content', dRes=dRes, useCookie=cookie), retmpd=True)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 1965, in getStreams
                                                subUrls = parseSubs(data)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 2015, in parseSubs
                                                with codecs.open(srtfile, 'w', encoding='utf-8') as srt:
                                              File "/usr/lib/python2.7/codecs.py", line 896, in open
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 24: ordinal not in range(128)
                                            -->End of Python script error report<--
22:58:32.538 T:1941737088   DEBUG: ------ Window Init (DialogNotification.xml) ------
22:58:32.818 T:1615369088 WARNING: CPythonInvoker(58, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
22:58:32.818 T:1615369088    INFO: Python script stopped

**Comment by Varstahl** [comment]
The current version you're using has a well known bug, the current nightly already has the fix. While you wait for the version to be updated by Kodi you can bypass the problem by either:
- disabling subtitles
- manually updating default.py with the version [found here](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/default.py)

**Comment by Varstahl** [comment]
Update should be now pushed to Kodi, as per bcc079dc402e1b52359248de610794c7fc172b4a.
