### ISSUE TITLE
check for ssl.HAS_SNI instead of requiring python >= 2.7.9

### ISSUE THREAD

**Issue by leo-b** [Sandmann79/xbmc#88]
Hi!

Your recent commit https://github.com/Sandmann79/xbmc/commit/39b12597e5845e3b1dfe1f85d9bdfe92900ca603 causes the amazon plugin to fail on Redhat/Centos 7, which worked fine up to now.

Requiring Python 2.7.9 isn't necessary. I guess your intention was to require openssl and a python ssl module that provide the SNI feature.

Redhat ships with python 2.7.5 with backports of important features (like SNI):

    $ python
    Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
    [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import ssl 
    >>> ssl.HAS_SNI    
    True

So I guess what you really want is to check for [ssl.HAS_SNI](https://docs.python.org/2/library/ssl.html#ssl.HAS_SNI):

    if not getattr(ssl, 'HAS_SNI', False):
        Log('Using an python or openssl version that doesn't support SNI.')

**Comment by leo-b** [comment]
Actually, since your plugin uses requests, an even better check would be:

    import requests.packages.urllib3.util
    if not getattr(requests.packages.urllib3.util, 'HAS_SNI', False):
        Log('Using an python or openssl version that doesn't support SNI. Consider upgrading your python version or installing pyOpenSSL if your openssl version supports SNI and you are stuck to an older python.')

The advantage is that even if the python ssl module doesn't support SNI, requests will make its urllib3 use pyopenssl, which will also enable SNI if the openssl libraries support it.

**Comment by Varstahl** [comment]
There are more problems than that, although it's one of the reasons the check was set in place. Thanks for the additional information though, will come in handy.

**Comment by Sandmann79** [comment]
Pushed to Kodi at f666f929b593fd90ad76faefa160ad20f30dd84f
