### ISSUE TITLE
amazon does not play

### ISSUE THREAD

**Issue by rome1983** [Sandmann79/xbmc#9]
http://paste.ubuntu.com/19644843/

**Comment by Sandmann79** [comment]
There is no decrypter in your /home/kodi/.kodi/cdm folder.
You need to have 2 files in this folder: 
1) libssd_wv.so (Download at [this Thread](http://www.kodinerds.net/index.php/Thread/51486-Kodi-17-Inputstream-AddOns-fuer-den-Kodi-17-VideoPlayer-aktuelle-Git-builds-Upda/))
2) libwidevinecdm.so - pull this one out from an google chrome installation. You can find the file at this location: /opt/google/chrome

**Comment by rome1983** [comment]
working now thanks
