### ISSUE TITLE
RPI 3/LibreElec 9- Widevine config is missing. Reinstall is required.

### ISSUE THREAD

**Issue by ejantzen** [Sandmann79/xbmc#92]
hello,
when i start a video, I have error message: "an update of Widevine CDM is required to play this content"
I installed getwidevine.sh. 
Netflix work well.

here is all logs:
18:32:41.637 T:1549267840  NOTICE: [Amazon VOD] {'path': 'root-//-Films-//-Films populaires-//-0QOJE4QB963BTN638PRFCA5GJR', 'mode': 'PrimeVideo_Browse'}
18:32:41.673 T:1549267840   DEBUG: [script.module.inputstreamhelper-0.3.3]: Platform information: ('Linux', 'LibreELEC', '4.14.20', '#1 SMP Wed Feb 21 21:04:46 GMT 2018', 'armv7l', '')
18:32:41.674 T:1549267840   DEBUG: [script.module.inputstreamhelper-0.3.3]: jsonrpc payload: {'params': {'addonid': 'inputstream.adaptive'}, 'jsonrpc': '2.0', 'id': 1, 'method': 'Addons.GetAddonDetails'}
18:32:41.675 T:1549267840   DEBUG: [script.module.inputstreamhelper-0.3.3]: jsonrpc response: {"id":1,"jsonrpc":"2.0","result":{"addon":{"addonid":"inputstream.adaptive","type":"kodi.inputstream"}}}
18:32:41.675 T:1549267840   DEBUG: [script.module.inputstreamhelper-0.3.3]: inputstream.adaptive is installed.
18:32:41.676 T:1549267840   DEBUG: [script.module.inputstreamhelper-0.3.3]: jsonrpc payload: {'params': {'properties': ['enabled'], 'addonid': 'inputstream.adaptive'}, 'jsonrpc': '2.0', 'id': 1, 'method': 'Addons.GetAddonDetails'}
18:32:41.676 T:1549267840   DEBUG: [script.module.inputstreamhelper-0.3.3]: jsonrpc response: {"id":1,"jsonrpc":"2.0","result":{"addon":{"addonid":"inputstream.adaptive","enabled":true,"type":"kodi.inputstream"}}}
18:32:41.677 T:1549267840   DEBUG: [script.module.inputstreamhelper-0.3.3]: inputstream.adaptive 999.2.1.13 is enabled.
18:32:41.677 T:1549267840   DEBUG: [script.module.inputstreamhelper-0.3.3]: inputstream.adaptive 999.2.1.13 is installed and enabled.
18:32:41.689 T:1549267840   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
18:32:41.690 T:1549267840   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
18:32:41.692 T:1549267840   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
18:32:41.695 T:1549267840   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
18:32:41.695 T:1549267840   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
18:32:41.696 T:1549267840   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
18:32:41.698 T:1549267840   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
18:32:41.698 T:1549267840   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
18:32:41.699 T:1549267840   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
18:32:41.700 T:1549267840   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
18:32:41.700 T:1549267840   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
18:32:41.701 T:1549267840   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
18:32:41.702 T:1549267840   DEBUG: [script.module.inputstreamhelper-0.3.3]: Found Widevine binary at /storage/.kodi/cdm/libwidevinecdm.so
18:32:41.797 T:1549267840   DEBUG: [script.module.inputstreamhelper-0.3.3]: Widevine config is missing. Reinstall is required.
18:32:41.903 T:1941833024   DEBUG: ------ Window Init (DialogConfirm.xml) ------
18:32:41.903 T:1941833024    INFO: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
18:32:41.923 T:1941833024   DEBUG: GLES: Extension Support Test - GL_EXT_texture_format_BGRA8888 YES

Thank's

**Comment by Sandmann79** [comment]
The getwidevine.sh script downloads an outdated libwidevine library. 
In order to watch Prime Video you have to update to the latest available version.

**Comment by ejantzen** [comment]
ok, but where can I find a good version?

**Comment by Sandmann79** [comment]
Inputstream Helper do this. 
If it not asked to download a new version of libwidevine, you have to manually remove the entire `~/.kodi/userdata/addon_data/script.module.inputstreamhelper` directory and delete this file `~/.kodi/cdm/libwidevinecdm.so`. 
After that start any video and Inputstream Helper downloads the newest version.
Please be patient the size of download is about 1,5Gb.

**Comment by ejantzen** [comment]
good. it's ok
