### ISSUE TITLE
Watchlist no longer loading

### ISSUE THREAD

**Issue by EvilCaptKirk** [Sandmann79/xbmc#96]
Hello -

Like the Amazon VOD plugin a lot and use it frequently, however the last time I went to my watchlist, it is not loading any of the TV Shows or Movies I have in my Amazon Prime watchlist. All other plugin functions seem to work and I can browse the various TV and Movie categories, but when I got to look at my watchlist (which does have many entries) it shows an empty screen. Ideas on how to fix?

Best,
Ed

**Comment by Sandmann79** [comment]
This has been already fixed at 85ebac1c9919c27f4dcd98f10213b56007b94f72.
Just have to be released.

**Comment by EvilCaptKirk** [comment]
Thanks, will watch for next push.
