### ISSUE TITLE
Two different sets of export folders created

### ISSUE THREAD

**Issue by EvilCaptKirk** [Sandmann79/xbmc#97]
Hello - just wondering why the plugin creates export folders under both plugin.video.amazon and plugin.video,amazon-test. Would prefer just one location if possible.

Best,
Ed

**Comment by Varstahl** [comment]
Those addons are separate. The `plugin.video.amazon` supports only amazon.de account. while `plugin.video.amazon-test` has support for all the amazon accounts and for PrimeVideo. As for the difference between the amazon and amazon-test for DE accounts, you'd have to ask @Sandmann79 about.

**Comment by EvilCaptKirk** [comment]
@Sandmann79 That is interesting. I've only installed one instance of the plugin and I have selected US as my region. This has happened to me twice, where I've installed the plugin, initially it uses one path, then a couple weeks into it it's suddenly using a different path. What could cause that?

**Comment by Sandmann79** [comment]
Did you changed something at settings, where you can setup a different export location?
There was a bug at VOD v0.5.0/0.5.1 regarding to this. In this versions the custom location has been ignored.

**Comment by EvilCaptKirk** [comment]
I did not - it just happened automagically: I went into the addon one day like I always to, selected a title and choose 'export' from it's menu, and I suddenly got a dialog I had not seen before, something like "the export location has changed" or "a new export location has been added" (sorry, don't recall exact language), then I was prompted to restart Kodi for the change to take effect. I had made no changes to the addon config prior to this happening and I've always used the default export location.

**Comment by Sandmann79** [comment]
That's strange, didn't heard that before. 
You didn't removed the Amazon video sources or changed something in sources.xml?

**Comment by EvilCaptKirk** [comment]
Not that I know if - is there some action via the UI in Kodi, other than explicitly going to the addon config and messing with library settings, that could result in this as a side-effect?

**Comment by Sandmann79** [comment]
Yes if you delete or rename the video sources at Kodi Settings / Media / Library / Video...

**Comment by EvilCaptKirk** [comment]
Hmmm... I don't think that I've done that.

**Comment by Sandmann79** [comment]
So i found a copy & paste mistake at settings.xml, where the folder of plugin.video.amazon are used for export. This happens only, if the custom export folder setting are enabled and the path is not changed.
It has been fixed with eca97cae84e4ac6e5c3d2bb65452e9fb9a556413.
If custom export folder setting are enabled, disable it to use the default folder at addon_data

**Comment by Sandmann79** [comment]
I close this for now, if the error occurs again, reopen this issue.

**Comment by EvilCaptKirk** [comment]
Thanks for identifying the cause, 

Best,
Ed
