### ISSUE TITLE
License update not successful

### ISSUE THREAD

**Issue by SPDurkee** [Sandmann79/xbmc#99]
I don't know where else to go for help with this. I don't know if it's an issue with this plugin or inputstream.adaptive, but when I try to play Amazon Prime Videos I receive the following:

13:47:33.670 T:28416   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
13:47:33.671 T:15280  NOTICE: Creating InputStream
13:47:34.395 T:15280   ERROR: AddOnLog: InputStream Adaptive: Unable to find license;hdcpEnforcementResolutionPixels in JSON string
13:47:34.395 T:15280   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
13:47:34.395 T:15280   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
13:47:34.396 T:15280   ERROR: CVideoPlayer::OpenInputStream - error opening [https://a192avoddashs3us-a.akamaihd.net/d/2$v1VDDa2w8h-KQuKhDPKkqvm-myM/ondemand/8666/f421/b613/40a8-9eab-2fedcc5e1413/e6575bc6-cead-406f-b3a8-74fb5865708f_corrected.mpd]

Can anyone help shed a light on this?

**Comment by Sandmann79** [comment]
Look for solutions at this issues: #90 #62 
Duplicate closing.
